박스오피스 [STEP 1] kaki, harry
yagom-academy/ios-box-office pull request #1
Opened 2023-03-20 08:17 UTC by kak1x

# 박스오피스 [STEP 1] kaki, harry
@lina0322

안녕하세요 엘림~! 박스오피스 기간 동안 잘 부탁드리겠습니다😀😀😀
STEP1 리뷰 잘부탁드립니다 !

## 구현 내용
### 데이터 모델 타입 구현
- 영화진흥위원회의 일별 박스오피스 API 문서를 참고하여 데이터 모델 타입인 BoxOffice 구조체를 구현해주었습니다.

## 고민한 점, 질문사항
### Equatable 채택
```swift
extension DailyBoxOfficeList: Equatable {
    public static func == (lhs: DailyBoxOfficeList, rhs: DailyBoxOfficeList) -> Bool {
        return lhs.number == rhs.number
        && lhs.rank == rhs.rank
        && lhs.rankIncrement == rhs.rankIncrement
        && lhs.rankOldAndNew == rhs.rankOldAndNew
        && lhs.movieCode == rhs.movieCode
        && lhs.movieKoreanName == rhs.movieKoreanName
        && lhs.openDate == rhs.openDate
        && lhs.salesAmount == rhs.salesAmount
        && lhs.salesShare == rhs.salesShare
        && lhs.salesIncrement == rhs.salesIncrement
        && lhs.salesChange == rhs.salesChange
        && lhs.salesAccumulation == rhs.salesAccumulation
        && lhs.audienceCount == rhs.audienceCount
        && lhs.audienceIncrement == rhs.audienceIncrement
        && lhs.audienceChange == rhs.audienceChange
        && lhs.audienceAccumulation == rhs.audienceAccumulation
        && lhs.screenCount == rhs.screenCount
        && lhs.showCount == rhs.showCount
    }
}
```
- 데이터 모델에 Testability를 위해 Equatable 프로토콜을 채택한 후 메서드를 정의해주었습니다.
- 그러나 이 과정에서 비교할 것들이 많은 `DailyBoxOfficeList` 타입 같은 경우, 휴먼에러가 발생할 가능성이 높다고 생각되어 고민했는데 혹시 다른 방식으로 조금 더 안전하게 구현이 가능할까요?
### Equatable 채택을 활용한 Test case 작성
```swift
func test_첫번째_dailyBoxOfficeList_값이_json_데이터와_일치한다() {
    // given
    let result = DailyBoxOfficeList(number: "1", rank: "1", rankIncrement: "0", rankOldAndNew: .new, movieCode: "20199882", movieKoreanName: "경관의 피", openDate: "2022-01-05", salesAmount: "584559330", salesShare: "34.2", salesIncrement: "584559330", salesChange: "100", salesAccumulation: "631402330", audienceCount: "64050", audienceIncrement: "64050", audienceChange: "100", audienceAccumulation: "69228", screenCount: "1171", showCount: "4416")
    // when
    let jsonDecoder = JSONDecoder()
    guard let dataAsset = NSDataAsset(name: "BoxOffice") else {
        XCTFail("DataAsset Error")
        return
    }
    do {
        sut = try jsonDecoder.decode(BoxOffice.self, from: dataAsset.data)
    } catch {
        XCTFail(error.localizedDescription)
    }
    // then
    XCTAssertEqual(result, sut.boxOfficeResult.dailyBoxOfficeList[0])
}
```
- 데이터 모델 타입에 모두 Equatable 채택을 함으로써 decode를 통한 데이터와 임의로 만들어준 모델 타입 객체가 일치하는지 비교할 수 있었습니다.
- 다만 JSON 파일을 직접 열어서 일일이 비교해가며 초기화 파라미터에 직접 작성하고 초기화를 해주어야했습니다. 
- 이렇게 작성하게 되면 휴먼에러 발생의 위험이 있을 것 같아 어떤식으로 테스트 케이스를 작성하면 좋을지 조언해주시면 감사하겠습니다.

2023-03-21 11:11 UTC, lina0322 requested changes
고생하셨습니다~! 조금만 더 다듬어봅시당!!🫡
이해 안가는거 있으면 메세지주세요~~

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +struct BoxOffice: Codable {
Codable은 무엇으로 구성 되어있나요? 전부 필요한상황인가요??👀

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +    let boxOfficeType, showRange: String
showRange는 어떤값인가요?? String이라는 타입과 잘 매칭이 되지 않는 것 같습니다?!
그리고 아래 변수명도 다소 이상해요! List인데 안에 들어있는 객체 이름도 List입니다?!

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +    let screenCount, showCount: String
음.. 되도록 한줄에 하나씩 선언해주는게 나중에 관리하기 편해요~
5개정도마다 줄바꿈 하나씩 해주면서 구분할 수 있도록 해주면 어떨까요?

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +    let screenCount, showCount: String
전부 String 값인가요? date나 count로 네이밍 되어있는데 타입이 String이면 다소 오해의 소지가 있을거같아요. 좋은 방법 없을까요?

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +}
LGTM🫡
enum으로 선언한 부분 좋아요! 근데 더 좋은 네이밍은 없을까요 흠.. 이건 저도 참 고민스럽네요!

2023-03-21 11:11 UTC, lina0322 commented on BoxOffice/BoxOffice.swift
> +}
이게 무슨일이지..ㅎㅎㅎ 여러분도 의아했죠..?ㅎㅎ
엄.. 보통은 id값을 서버에서 내려주거나, id 값을 하나 생성해서 구분하는 것 같아요
이렇게 모든 값이 동일한지 체크하는 경우는.. 잘 없는거같아요ㅠㅠ; 진짜 구분이 될 수 있는 값은 없을까요? 혹은 여러분이 만들어 넣을수도 있을거같은데요!

2023-03-21 11:11 UTC, lina0322 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        // when
줄바꿈이라도 해주세용ㅠㅠ..

2023-03-21 11:11 UTC, lina0322 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        }
디코딩을 담당하는 객체는 따로 없나용?

2023-03-21 11:11 UTC, lina0322 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
어떤 역할을 하는 함수인가요??

2023-03-21 11:11 UTC, lina0322 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
given, when, then 의 의미가 무엇인가요??
좀 더 많은 테스트 케이스가 필요해보여요~

2023-03-22 01:19 UTC, HarryHyeon commented on BoxOffice/BoxOffice.swift
> +struct BoxOffice: Codable {
Codable은 Decodable & Encodable의 별칭입니다.

다시 JSON으로 Encode 할 필요는 없을 것 같아 Decodable로 수정해주었습니다.

2023-03-22 01:30 UTC, kak1x commented on BoxOffice/BoxOffice.swift
> +    let boxOfficeType, showRange: String
조회 일자를 보여주는 값인데, 일별 박스오피스 조회이기에 Range는 어울리지 않다 생각되어 `targetDate`로 바꿔주었습니다.
아래 변수명은 `let dailyBoxOfficeList: [DailyBoxOffice]`로 변경하였습니다!

2023-03-22 01:31 UTC, HarryHyeon commented on BoxOffice/BoxOffice.swift
> +    let screenCount, showCount: String
한 줄에 하나씩 선언하는게 다시 찾아보기에도 편할거 같아서 한 줄에 하나씩 선언하는 것으로 수정했습니다 !

2023-03-22 02:04 UTC, kak1x commented on BoxOfficeTests/BoxOfficeTests.swift
> +        // when
넵! 전부 줄바꿈 처리 해주었습니다

2023-03-22 02:06 UTC, HarryHyeon commented on BoxOffice/BoxOffice.swift
> +    let screenCount, showCount: String
init(from decoder: ) 라는 이니셜라이져를 사용하여 이니셜라이져 안에서 형 변환을 해주는 방법을 찾아보았습니다.
하지만 형변환이 불필요한 프로퍼티들도 모두 이니셜라이져 안에서 작업해주어야 했습니다. 

물론 네이밍만 보았을때 String이 아니지만 이런 방식으로 하는 것이 비효율적이라고 생각이 드는데 엘림은 어떻게 생각하시나요?

2023-03-22 02:07 UTC, kak1x commented on BoxOffice/BoxOffice.swift
> +    let screenCount, showCount: String
그렇다고 변수명을 `dateString`, `countString` 같은 방식으로 네이밍을 수정해주는것도 상당히 어색하다고 느껴지는데 이 부분에 관한 엘림의 의견도 듣고 싶습니다!

2023-03-22 02:09 UTC, kak1x commented on BoxOffice/BoxOffice.swift
> +}
수정할만한 네이밍이 떠오르지 않아 그대로 유지하였습니다...

2023-03-22 02:10 UTC, HarryHyeon commented on BoxOfficeTests/BoxOfficeTests.swift
> +        }
해당 객체는 이번 스텝에서는 구현하지 않았고, 필요하다면 다음 스텝에서 구현해보겠습니다.

2023-03-22 02:12 UTC, kak1x commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
메서드 실행 전에 정의하거나 초기화할 작업을 오버라이드하여 구현할때 사용하는 함수인데, 이번 테스트에서는 따로 실행 전에 정의할 것이 없어 삭제해주었습니다.

2023-03-22 02:25 UTC, kak1x commented on BoxOfficeTests/BoxOfficeTests.swift
> +        // when
더이상 테스트에서 사용하지 않게 되어 삭제해주었습니다🙂

2023-03-22 02:39 UTC, HarryHyeon commented on BoxOffice/BoxOffice.swift
> +}
엘림이 조언해주신대로 몇가지 값을 테스트 케이스로 비교해보는 것으로 수정하고 Equatable 채택한 것을 전부 제거해주었습니다.

2023-03-22 02:40 UTC, kak1x commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
given은 필요한 value들을 세팅해준다는 의미이며 when은 테스트 코드 실행, then은 결과를 확인한다는 의미입니다.
테스트 방식을 변경하며 테스트 케이스를 추가해주었습니다~!

2023-03-22 11:42 UTC, merged