박스오피스 [STEP 3] karen
yagom-academy/ios-box-office pull request #104
Opened 2023-08-14 18:45 UTC by karenyang835

@YebinKim

안녕하세요. 븨븨~

븨븨의 배려로 `Step2`를 무사히(?)마치고 `Step3` 구현을 완료하여 `PR` 보내드립니다.

`TableView`도 아직 능숙하지 않은 상태라 `CollectionView`는 더더욱 많이 헤멨던 것 같습니다.🥹

부족한점이 많지만 이번 `Step3` 피드백도 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ `@available`을 사용하게 되는 이유는?
- `CollectionView`를 생성하려고 하니 자꾸 오류가 발생해서 `@available`를 해줘야되는 상황이라 버전을 높여서 해결해주었습니다.
#### <문제점>
![스크린샷 2023-08-15 오전 2 22 14](https://github.com/yagom-academy/ios-box-office/assets/124643896/43025b26-f2a2-4b13-99c1-ec77448ea4fe)

#### <해결 방법>
![스크린샷 2023-08-15 오전 3 03 27](https://github.com/yagom-academy/ios-box-office/assets/124643896/c6e4a90e-8d50-49a4-9679-c8d3a04495fd)

### 2️⃣ `CollectionView`의 `cell`도 재사용 되는가?
- `TableView`는 `cell`을 재사용한다고 했는데 과연 `CollectionView`도 `Cell`을 재사용하는지 궁금해서 찾아보니,`TableView`와 마찬가지로 `Queue`방식으로 `cell`을 관리하고 재사용한다는 것을 알게 되었습니다.

### 3️⃣ `LodingView`를 어떻게 구현할 것인가?
- `Step3` 미션 내용에 요구하는 사항 중 로드 중인 것을 표시해 주는 걸 어떻게 구현해야될 지 고민해보았습니다. 이미지를 직접 그려서 애니메이션을 해야되는건지 아니면 따로 `swift`에 구현되어져 있는 것을 활용할지 고민하였습니다.
- `LodaingView`를 할 수 있는 제가 알아 낸 방법은 총 세 가지 방법이 있었습니다.
    - `UIActivityIndicatorView`라는 인디케이터를 활용하여 하는 방법
        - 가장 간단하고 빠르게 구현 가능한 방법
    - 로딩 화면을 위한 `ViewController`를 새로 생성해서 활용하는 방법
        - 구현이 복잡하지만 로딩이 길어질 경우 더 나은 화면 전환 가능 
    - `CustomLoadingView`를 활용하는 방법
        - 서브클래싱하여 자체적으로 디자인 가능, 로고 텍스트 표시 가능
- 이번 프로젝트에서는 간단하게 로딩 중인 애니메이션만 구현하면 될 것 같았고 `LodaingView`에 많은 시간을 투자하는건 비효율적일 것 같아`UIActivityIndicatorView`를 활용하여 구현했습니다.

--- 

<br>

2023-08-15 12:37 UTC, YebinKim requested changes
카렌 안녕하세요 😄
빠르게 Step3 까지 진행하느라 고생 많으셨습니다!

고민하신 부분 중 `UICollectionView` 를 커스텀한 `BoxOfficeViewController` 를 호출하려고 할 때마다 버전 오류가 나셨을 것으로 보이는데요 👀
혹시 왜 버전 오류가 발생했을지도 알고 계실까요?

---

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="343" alt="step3" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/d1dd8db0-793a-4c9b-a17b-d3212b641aa2">

목표한대로 UI가 잘 그려지고 있지만, 메서드의 활용과 전반적인 네이밍 방식에 대해 의도된 네이밍이 맞는지 얘기를 나눠보는 게 필요할 거 같아 Request Changes 로 요청드렸습니다 ☺️
혹시 코멘트 내용 및 수정 방향에 대한 추가 설명이 필요하다면 언제든 질문주세요 😄🙌

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice.xcodeproj/project.pbxproj
> +		9C8D70BB2A8A7CBA004E9299 /* DataNamespace.swift in Sources */ = {isa = PBXBuildFile; fileRef = 9C8D70BA2A8A7CBA004E9299 /* DataNamespace.swift */; };
p3;

두 파일은 아무 폴더에도 속하지 않은 것으로 보이네요 🤔
적절한 위치의 폴더로 이동해볼 수 있을까요?

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice.xcodeproj/xcuserdata/karen.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
p4;

`xcuserdata` 파일이 추적되고 있어서 프로젝트를 열 때마다 파일 변경이 발생하는 것으로 보여요 🤔
프로젝트를 작업하는 사람들이 매번 같은 파일에서 변경이 발생하면 Git 충돌이 발생하기 쉬울 거 같은데, 추적되지 않도록 해보면 어떨까요?

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    // MARK: Propertie
p4;

주석에 오타가 있는 거 같아요 👀

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var rankingViewType: BoxOfficeRankingViewType = .list
p3;

무엇을 위해 필요한 프로퍼티일까요? 🤔 현재 쓰임이 없어서 어떤 용도의 프로퍼티인지 짐작이 어려워보여요.
그리고 변동되지 않는 프로퍼티는 상수 처리가 필요해보입니다 👀

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var boxofficeDate = {
p3;

저장 프로퍼티로 선언해야 할 이유가 있었을까요?
변동 가능성이 없는 프로퍼티라면 상수 처리가 필요해보여요 👀

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func handleFetchResult(result: Result<[BoxOfficeMovieInfo], Error>) {
p2;

네이밍이 모호해서 무엇을 하는 메서드인지 떠올리기 어려워보여요 🤔
메서드가 수행하는 동작을 더 구체적으로 명시해볼 수 있을까요?

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +            presentErrorAlert(error: error, title: "박스오피스")
p2;

[Human Interface Guilelines - Alerts](https://developer.apple.com/design/human-interface-guidelines/alerts)에 따르면 title 은 발생한 상황에 대한 명료하게 인지할 수 있는 문구를 담을 것을 권장하고 있어요.
`"박스오피스"` 로는 현재 상황이 잘 전달되지 않을 거 같아 적절한 문구로의 변경이 필요해보입니다. (HIG를 준수하지 않으면 앱 배포 심사에서 리젝당할 수 있이요)

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Extension/String+.swift
> +    func formatDecimal() -> String? {
p4;

Swift API Design Guidelines의 [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)에 따라 반환값이 있는 메서드(side-effects 가 있는 메서드)는 분사구를 활용했을 때 의미를 더 잘 전달할 수 있을 것으로 보여요 👀

> When the operation is naturally described by a verb, use the verb’s imperative for the mutating method and apply the “ed” or “ing” suffix to name its nonmutating counterpart.

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Model/BoxOffice/BoxOfficeMovieInfo.swift
> +    enum RankingStatus: String, Decodable {
enum에 Decodable을 적용한 덕분에 값을 다루기가 쉬워졌네요!! 🤩

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Model/BoxOfficeRankingViewType.swift
> +    var anotherTitl₩e: String {
p2;

오타가 있는 것으로 보여요 👀

또한, `anotherTitle` 이 어떤 용도의 프로퍼티인지 잘 와닿지 않는 거 같아요 🤔

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/NetWork/NetworkManager.swift
> +    func getRequest(request: URLRequest, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) {
p2;

get~ 네이밍과 달리 반환하는 값이 없어서 사용에 혼란이 있을 거 같아요 🤔
메서드의 동작에 맞는 이름으로 변경해볼 수 있을까요?

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/NetWork/NetworkManager.swift
> +            completion(.failure(.invalidType))
p3;

data 가 nil일 때 `invalidType` 에러가 발생하는 것은 문제 상황과 에러의 이름이 잘 매칭되지 않는 거 같아요 🤔
어떤 문제 상황을 표현하고자 하신걸까요?

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/View/MovieRankingListCell.swift
> +    func updateLabelText(for manager: CellUIModel) {
p2;

`manager` 매개변수명은 `CellUIModel` 타입을 적절히 표현하지 못 하고 있는 거 같아요 🤔

---

p5;

메서드의 내용은 셀 내부의 모든 데이터를 업데이트 하고 있는 것으로 보이는데,
 `updateLabelText` 이라는 메서드명은 단일 레이블의 업데이트로 보여서 명확한 의미 전달을 위해 네이밍을 변경해보면 어떨까요? 👀

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/View/MovieRankingListCell.swift
> +    private let audienceLabel = UILabel(fontStyle: .preferredFont(forTextStyle: .body))
p3;

다른 UI 들은 Dynamic Types가 잘 적용되고 있는데 `audienceLabel`만 레이블의 제약조건으로 인해 Dynamic Types가 잘 적용되지 않는 것으로 보여요 👀
의도되지 않은 상황이라면 수정이 필요할 거 같아요!

<img src="https://github.com/yagom-academy/ios-box-office/assets/38066039/117bd2da-d50a-43f5-b3bd-657cff15cb40" width="300">

2023-08-15 12:37 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        dataSource?.apply(snapshot, animatingDifferences: true)
[apply(_:animatingDifferences:completion:)](https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3375811-apply) 메서드는 일관된 작업 큐에서 호출해야 한다는 사실 알고 계셨을까요? 👀
참고차 전달드립니다 😆

<img width="933" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/db4ea276-206a-4c96-b95b-96cbe4c8780b">

2023-08-15 12:52 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var rankingViewType: BoxOfficeRankingViewType = .list
이 변수는 다음 스텝에 관련된 부분이긴 한데요. 

박스오피스 프로젝트를 진행함에 있어 처음에 븨븨께 말씀드렸던 것처럼 숲을 보기 위해서 코드를 작성하는 방향으로 `Step`을 진행하고 있습니다.

`TableView`를 활용하지 않고 `CollectionView`를 활용하는 만큼 추후에 `Grid`방식이라던가 보여지는 레이아웃 자체가 변동이 될 수도 있다는 것을 고려해서 해당 레이아웃별로 변동이 되었을 때를 알려줄 수 있는 값을 넣는 프로퍼티로 구현을 해두었습니다. 

추후에 코드의 수정을 되도록 줄일 수 있는 방향으로 진행하기 위해서 현재로서는 `List`형태만을 구현하기에 `List`라고 입력을 해두고 해당 타입에 맞추어서 코드를 작성해두었습니다.

2023-08-15 13:59 UTC, karenyang835 commented on BoxOffice/NetWork/NetworkManager.swift
> +            completion(.failure(.invalidType))
앗...에러문을 수정하면서 `Data`를 누락시켰습니다.🥹

올바른 데이터 포맷이 들어오지 않는 부분을 에러문으로 표현하고자 했는데 가장 중요했던 `Data`를 누락시키고 네이밍을 했네요. `invalidDataType`로 수정해주었습니다.
이번 프로젝트는 이런 실수가 유독 잦은것 같습니다. 

조금 더 주의해서 꼼꼼하게 보도록 하겠습니다.

2023-08-15 17:57 UTC, karenyang835 commented on BoxOffice.xcodeproj/project.pbxproj
> +		9C8D70BB2A8A7CBA004E9299 /* DataNamespace.swift in Sources */ = {isa = PBXBuildFile; fileRef = 9C8D70BA2A8A7CBA004E9299 /* DataNamespace.swift */; };
`Model`폴더에 넣었는데 해당 폴더에 안들어가고 밖에  있는 상태가 되어버렸네요.🥹
다시 제자리를 찾아서 넣어주었습니다.

2023-08-15 17:59 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    // MARK: Propertie
엇..영어에 약한걸 주석에서까지 티를 냈군요.😅

`Properties`로 수정해주었습니다.

2023-08-15 22:31 UTC, karenyang835 commented on BoxOffice/View/MovieRankingListCell.swift
> +    private let audienceLabel = UILabel(fontStyle: .preferredFont(forTextStyle: .body))
해당 부분은 의도한 부분은 아니고 다이나믹 적용이 누락되었던 것 같습니다.🥲

해당 부분 확인하면서 순위 유지를 표시해주는 '-'부분이 다크모드일때도 검은색으로 표기되어지기에 해당 부분도 다크모드에 맞추어 색상이 변하도록 수정해주었습니다.

2023-08-15 22:41 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        dataSource?.apply(snapshot, animatingDifferences: true)
사실 잘 모르고 있었습니다.🥲
븨븨께서 조언해주셔서 새롭게 알게 된 것 같습니다. 더 공부해보도록 하겠습니다.
챙겨주셔서 감사합니다.🙏🏻

2023-08-15 22:45 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func handleFetchResult(result: Result<[BoxOfficeMovieInfo], Error>) {
역시나 네이밍은 어려운 것 같습니다.😅

박스오피스 영화 정보를 가져온 후에 처리하는 함수이므로 `boxOfficeFetchDataResult`로 네이밍을 변경해주었습니다.

2023-08-15 22:49 UTC, karenyang835 commented on BoxOffice/View/MovieRankingListCell.swift
> +    func updateLabelText(for manager: CellUIModel) {
가장 기본적이면서도 중요한 네이밍 짓는 건 항상 어려운 것 같습니다.🥺
`Text`만을 다루긴 하지만 셀 내부의 데이터를 업데이트하는 것도 맞아 븨븨께서 조언해주신대로 'updateCellData(for cellUIModel: CellUIModel)로 변경해주었습니다.

2023-08-15 22:53 UTC, karenyang835 commented on BoxOffice/NetWork/NetworkManager.swift
> +    func getRequest(request: URLRequest, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) {
`fetchData`로 네이밍 수정해 주었습니다.

2023-08-15 22:56 UTC, karenyang835 commented on BoxOffice/Model/BoxOfficeRankingViewType.swift
> +    var anotherTitl₩e: String {
오타가 들어갔는데 현재 스텝에서는 아직 활용을 하지 않아 동작에는 이상이 없어 미처 확인을 못했었네요.
오타 수정 완료해주었습니다.

그리고 프로퍼티명도 레이아웃타입 설정 부분에 활용 되어질 프로퍼티라 `layoutType`으로 네이밍도 변경해주었습니다.

2023-08-15 23:00 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +            presentErrorAlert(error: error, title: "박스오피스")
조금 더 꼼꼼히 검토하고 생각하면서 코드를 작성했어야 했는데 놓치고 간 부분이 많은것 같습니다.

해당 부분 수정 완료해주었습니다.

그리고 `HIG`를 준수하지 않으면 앱 배포 심사에서 리젝당할 수 있다는 부분도 이번 기회에 다시 한번 상기시키도록 하겠습니다.

항상 꼼꼼하고 놓친 부분이라던가 참고할 수 있는 부분에 대해서 아낌없이 조언해 주셔서 감사합니다. 븨븨~

븨븨 덕분에 정말 많은것을 배웠습니다.😊

2023-08-15 23:04 UTC, karenyang835 commented on BoxOffice/Extension/String+.swift
> +    func formatDecimal() -> String? {
'formattedDecimalString'로 네이밍 변경해주었습니다.

2023-08-16 00:15 UTC, karenyang835 commented
>고민하신 부분 중 UICollectionView 를 커스텀한 BoxOfficeViewController 를 호출하려고 할 때마다 버전 오류가 나셨을 것으로 보이는데요 👀
혹시 왜 버전 오류가 발생했을지도 알고 계실까요?

- `UICollectionLayoutListConfiguration`와 `UICollectionLayoutListConfiguration`이 `iOS 14`에 도입되었기 때문이라고 알고 있습니다.

2023-08-16 00:22 UTC, karenyang835 commented on BoxOffice.xcodeproj/xcuserdata/karen.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
해당 부분 수정 완료했습니다.
체크해주셔서 감사합니다. 븨븨~
이번에 또 하나를 븨븨께 배워 한층 더 깃허브에 가까워진 것 같습니다.☺️

2023-08-16 00:22 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var boxofficeDate = {
`boxofficeDate`는 `createDataManager`에서 수행하는것이 코드도 더 간결해지고 저장프로퍼티에 선언할 필요는 없을 것 같아 수정해주었습니다.

`dataManager`은 기존 `ViewController`에서 수행하는 역활을 따로 분리해 구분해 준 것이기에 저장프로퍼티로 가지고 있는 것이 맞다 생각되어져서 저장프로퍼티로 활용을 해주었습니다.

`rankingViewType`도 추후 레이아웃 타입 적용을 위해서 저장프로퍼티로 가지고 있는게 맞다고 생각되어져서 남겨두었습니다.

2023-08-17 21:39 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var rankingViewType: BoxOfficeRankingViewType = .list
추후 사용 여부를 고려하여 만든 프로퍼티였군요! 👀
미래의 요구사항을 고려해서 당장 쓰지 않는 프로퍼티를 생성하게 되면 추후 용도를 알 수 없는 레거시 코드가 될 수도 있다는 문제점을 함께 생각해보면 좋을 거 같아요 🤔

2023-08-17 21:41 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func handleFetchResult(result: Result<[BoxOfficeMovieInfo], Error>) {
`boxOfficeFetchDataResult` 로 네이밍을 변경하셨군요! 메서드는 동작을 수행하는 코드 블럭이기 때문에 동사로 시작하는 네이밍을 활용하는 것이 더욱 자연스럽게 읽힐 수 있을 거 같아요 👀

2023-08-17 21:45 UTC, YebinKim commented on BoxOffice/Extension/String+.swift
> +    func formatDecimal() -> String? {
`make~` 메서드는 팩토리 메서드를 만들 때 선호하는 이름이기 때문에 의미가 혼동되는 것을 피하려면 지양하는 것이 좋을 거 같아요 🤔
> Swift API Design Guidelines - [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)
> The first argument to initializer and [factory methods](https://en.wikipedia.org/wiki/Factory_method_pattern) calls should not form a phrase starting with the base name, e.g. x.makeWidget(cogCount: 47)

2023-08-17 21:55 UTC, YebinKim approved these changes
카렌 안녕하세요~
Step3 수정까지 고생 많으셨습니다! 👏👏

`BoxOfficeViewController` 를 사용하려고 할 떄 버전 오류가 발생하는 이유를 정확히 알고 계시군요!
PR 코멘트에서는 `UICollectionView` 를 생성한 게 버전 오류의 이유였다고 읽혀서 혹시 해당 부분 어떻게 이해하고 계신지 궁금해서 질문드렸습니다. 각 코멘트에 대해 꼼꼼히 의견 남겨주셔서 감사해요 ☺️

이번 스텝의 핵심 경험은 모두 충족하셨다고 생각되어 Approve 로 리뷰 의견 드렸습니다!
남겨주신 코멘트 중 추가로 의견을 드리고 싶은 부분은 답글을 남겨두었는데, 혹시 추가로 수정하고 싶은 부분이 있으시다면 이번 스텝에서 반영하고 다음 스텝 바로 넘어가고자 하신다면 이대로 머지 진행하겠습니다~

확인 후 머지 의사 한 번 확인 부탁드릴게요 😄

2023-08-17 22:10 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var rankingViewType: BoxOfficeRankingViewType = .list
아하~ 그렇군요. 이 부분도 염두해 두고 코드를 작성해보도록 하겠습니다.
숲을 보려고 하되 굳이 필요 하지 않은 나무까지 심지는 않도록 해보겠습니다. ☺️
조언해주셔서 감사합니다. 븨븨~

2023-08-17 22:18 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func handleFetchResult(result: Result<[BoxOfficeMovieInfo], Error>) {
확인 후 동사로 시작하게 'fetchBoxOfficeDataResult'로 네이밍 변경해주었습니다.

꼼꼼한 조언 감사합니다. 븨븨~

2023-08-17 22:24 UTC, karenyang835 commented on BoxOffice/Extension/String+.swift
> +    func formatDecimal() -> String? {
아하~ 팩토리 메서드라는 것이 있군요?
이 부분은 븨븨가 붙여주신 주소 참고하여 더 공부해보도록 하겠습니다.

`make`를 삭제한 `formattedDecimalString`로 수정완료했습니다.

2023-08-17 22:32 UTC, merged