박스오피스 [STEP 4] Dasan, Whales
yagom-academy/ios-box-office pull request #106
Opened 2023-08-15 17:27 UTC by DasanKim

안녕하세요, 븨븨(@YebinKim)!! 💃🏻
웰다비의 Dasan🌳과 Whales🐬입니다 🙆🏻‍♀️

오토레이아웃에 두들겨맞고 삽질 가득했던 STEP4를
드디어드디어 마무리했습니다 🎉🎉🎉
너무 오래 걸리고 끙끙댔던만큼 이것저것 많이 공부하고 배웠던 시간이었습니다.
(복습의 필요성도 많이 느꼈습니다. 공부 더 화이팅!!)
그럼에도 불구하고 아쉬운 점이 많아 븨븨의 리뷰로 더 배우고싶습니다!!

이번 리뷰도 잘 부탁드립니다 🙇🏻‍♀️

---

## 🤹🏻 고민했던 점

### 🔹 스크롤 뷰 내 오토레이아웃
🚨 **문제점** <br>
- 아래와 같이 코드로 **스크롤 뷰**와 스크롤 뷰의 `content 뷰` 역할을 하는 **스택 뷰**의 오토레이아웃을 설정하여 주었습니다. 실행되는 화면에서는 특별한 문제가 없었는 듯하였으나, debug view hierarchy에서 아래와 같은 오류 메시지를 확인할 수 있었습니다.

  - **코드**
    ```swift 
    // MovieScrollView.swift
    private func configureUI() {
        self.translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(movieStackView)
        movieStackView.addArrangedSubview(movieImageView)

        NSLayoutConstraint.activate([
            movieStackView.topAnchor.constraint(equalTo: self.topAnchor),
            movieStackView.bottomAnchor.constraint(equalTo: self.bottomAnchor),
            movieStackView.centerXAnchor.constraint(equalTo: self.centerXAnchor),
            movieStackView.widthAnchor.constraint(equalTo: self.widthAnchor),
            ...
        ])
        ...
    }
    ```
  - **debug view hierarchy**의 오류 메시지
    <img src ="https://github.com/yagom-academy/ios-box-office/assets/106504779/7be8cce2-dc29-4a4d-8f9d-d9b01078c04d" width = "500">

💡 **해결방법** <br>
- [Working with Scroll Views](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithScrollViews.html#//apple_ref/doc/uid/TP40010853-CH24-SW1)에서 스크롤 뷰의 레이아웃은 `content 뷰`의 크기를 **`완전히`** 정의해야한다고 말해주고 있습니다.
   > to set the width, you must have an unbroken chain of constraints and views from the content view’s leading edge to its trailing edge.
- `content 뷰`인 `movieStackView`의 크기가 완전히 정의되지 않아 생긴 오류이므로, `movieStackView`의 centerX 대신 `leading`, `trailing` edge를 스크롤 뷰의 edge에 고정시켜주었더니 해당 오류 메시지가 사라졌습니다.
- `widthAnchor`는 스크롤 뷰의 가로 스크롤을 막기 위한 constraint입니다.
    ```swift 
    // MovieScrollView.swift
    private func configureUI() {
        self.translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(movieStackView)
        movieStackView.addArrangedSubview(movieImageView)

        NSLayoutConstraint.activate([
            movieStackView.topAnchor.constraint(equalTo: self.topAnchor),
            movieStackView.bottomAnchor.constraint(equalTo: self.bottomAnchor),
            movieStackView.leadingAnchor.constraint(equalTo: self.leadingAnchor),
            movieStackView.trailingAnchor.constraint(equalTo: self.trailingAnchor),
            movieStackView.widthAnchor.constraint(equalTo: self.widthAnchor),
            ...
        ])
        ...
    }
    ```
    
<br>

### 🔹 Custom init을 통한 데이터 전달
- 두번째 화면인 MovieInformationViewController를 인스턴스화하는 방법에는 아래와 같은 방법이 있었는데, 스토리보드 없이 UI를 구현해보는 것에 도전해보았습니다!
   - 스토리보드의 `instantiateViewController(identifier:)` 메서드 활용
   - 스토리보드 없이 MovieInformationViewController의 `생성자` 활용 

- 스토리보드 없이 UI를 구현
    1. 스토리보드가 없으므로 nib파일로 초기화가 필요했습니다.
        - 인터페이스 빌더에서 정의한 요소들(ViewController, 색상, 폰트 등)을 object graph로 만든 파일
        - 인터페이스 빌더에서 구성된 파일: XML형태의 `.xib`를 컴파일 하면 `.nib`파일이 됨
    2. Custom init을 통해 MovieInformationViewController에서 필요한 movieCode를 전달해주었습니다.
        - Custom init에서 `super.init(nibName: nil, bundle: nil)`을 호출해주었습니다.

    ```swift 
    // MovieInformationViewController.swift
    final class MovieInformationViewController: UIViewController {
        init(movieCode: String) {
            super.init(nibName: nil, bundle: nil)
            self.movieCode = movieCode
        }

        required init?(coder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }

    // BoxOfficeViewController.swift
    extension BoxOfficeViewController: UICollectionViewDelegate {
        func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
            let movieCode: String = items[indexPath.item].movieCode
            let movieInformationViewController = MovieInformationViewController(movieCode: movieCode)

            navigationController?.show(movieInformationViewController, sender: self)
        }
    }
    ```

<br>

### 🔹 navigationController.push 와 show의 차이

- 박스오피스 화면에서 영화 상세 정보 화면으로 넘어갈 때, 계층적인 구조로 `BoxOfficeViewController`에서 `MovieInformationViewController`를 직접 호출해서 화면을 표시하기 때문에 네비게이션 컨트롤러를 이용하는 화면전환 방식을 선택했습니다. 그 중에서 적절하다 생각되는 다음 두 가지 방식이 매우 비슷하게 느껴져 고민했습니다.
    - push
        ```swift
        navigationController?.pushViewController(movieInformationViewController, animated: true)
        ```
    - show
        ```swift
        navigationController?.show(movieInformationViewController, sender: self)
        ```
- pushViewController(_ viewController: UIViewController, animated: Bool)
    - viewController 파라미터의 객체는 내비게이션 stack의 최상위 ViewController이 된다.
    - viewController를 누르면 해당 view가 내비게이션 인터페이스에 포함된다.
- show(_ vc: UIViewController, sender: Any?)
    - ViewController를 실제로 화면에 표시하는 프로세스에서 ViewController를 표시해야 하는 필요성을 분리
    - ViewController는 내비게이션 컨트롤러 또는 분할 뷰 컨트롤에 내장되어 있는지 알 필요가 없다.
    - 내비게이션 컨트롤러는 이 메서드를 override하고 내비게이션 stack으로 vc를 push하기 위해 사용한다.
    - custom ViewController에서 vc를 직접 표시하기 위해 override해서 사용할 수 있다.
    - 기본 컨텍스트에서 vc를 표시하기 위해 사용
    
- 결론
    - show 메서드를 사용하면, pushViewController 방식처럼 현재의 네비게이션 stack에 새로운 뷰 컨트롤러를 직접적으로 호출하는 것이 아니라, 시스템이 primary context를 기반으로 뷰 컨트롤러를 present 하는 것을 결정할 수 있도록 하고, show 앞에 현재 뷰에 네비게이션 컨트롤러가 연결되어있는지 확인하는 navigationController?는 생략도 가능합니다.
        이 방법은 이전 방법보다 훨씬 dynamic하고 미래의 변동가능성을 대비한 좋은 방법이라 show로 화면 전환 방식을 택했습니다.

- 참고링크
    - [Apple - show](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621377-show)
    - [Apple - push](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621887-pushviewcontroller)
    - [블로그](https://velog.io/@dev_jane/ViewController을-navigation으로-띄우는-방식-show-와-push)

<br>

## 🎙️ 조언을 얻고 싶은 점
### 🔸 비동기, 그리고 UI 호출 타이밍에 관하여
- 이번 프로젝트를 진행하면서 데이터를 비동기로 받아오는 타이밍 뿐만 아니라 UI 호출 시점까지 함께 고려하는 것이 쉽지 않았습니다ㅠㅠ
  (예시: A뷰가 addSubView된 후에 B뷰가 addSubView되어야 정상적으로 작동하는 등)
  븨븨께서는 이와 같은 상황을 어떻게 풀어나가시는지 여쭤보고싶습니다!
  
(질문을 드리고 싶은데 말로 쓰기가 너무 어렵네요🥺 질문이 이해가 안가신다면 편하실 때 연락주세요🙏🏻)

<br>

2023-08-17 21:31 UTC, YebinKim requested changes
다산🌳, 웨일🐬 안녕하세요~
박스오피스1의 마지막 스텝 진행까지 고생 많으셨습니다!!

회의실에서 PR을 보며 얘기를 많이 나눠서 코멘트 양은 많지 않은데요.
이번 스텝의 핵심 경험 중 SafeArea 가 지켜지지 않은 화면이 있어 Request Changes 로 요청드렸습니다 😄
<img width="500" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/3bd7c428-5649-4bcc-8d94-cc821ee0ee46">

혹시 코멘트 내용 중 궁금한 점이 있다면 오늘 오프라인 모각코에서도 많은 얘기 나눠보아요 😆🙌

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        boxOfficeManager.fetchMovieData(movieCode: movieCode){ result in
p4;

띄어쓰기가 하나 누락된 거 같아요 👀
```suggestion
        boxOfficeManager.fetchMovieData(movieCode: movieCode) { result in
```

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/View/MovieInformationStackView.swift
> +    private var movieInformation: MovieInformation?
p3;

상태를 저장할 프로퍼티와 UI 프로퍼티가 한 눈에 구분될 수 있도록 개행을 추가해보면 어떨까요?

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/Model/BoxOfficeManager.swift
> +                    print(movieInformation)
p4;

로그로서 정보를 확인하고자 한다면 콘솔창에서 정보를 유의미하게 구분할 수 있도록 작성해보면 어떨까요?

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/Utility/NetworkManager.swift
> +    func fetchImage(url: URL?, completionHandler: @escaping ((UIImage?, NetworkError?)) -> Void) {
p2;

`fetchData(url: completionHandler:)` 메서드와 코드가 많이 중복되는 것으로 보여요 🤔
중복 코드를 줄여볼 수 있을까요?

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        activityIndicatorView.center = view.center
질문;

다른 뷰와 달리 `activityIndicatorView` 뷰만 오토레이아웃이 아닌 프레임으로 위치를 정한 이유가 있을까요?
로딩 중 화면을 가로로 전환하면 UI가 깨질 것으로 보여요 🤔

2023-08-17 21:31 UTC, YebinKim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        guard let posterImage = posterImage,
p3;

타입이 상태값을 가질수록 발생할 수 있는 문제점을 줄일 수 있도록 `MovieInformationViewController`이 `posterImage`라는 프로퍼티를 가지기보다는 매개변수를 통해 전달하는 방식으로 작성해보면 어떨까요?

2023-08-18 06:38 UTC, DasanKim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        boxOfficeManager.fetchMovieData(movieCode: movieCode){ result in
수정하였습니다😂

2023-08-18 06:39 UTC, DasanKim commented on BoxOffice/View/MovieInformationStackView.swift
> +    private var movieInformation: MovieInformation?
바로 개행을 추가해주었습니다!🥹

2023-08-18 07:28 UTC, WhalesJin commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        activityIndicatorView.center = view.center
b0add276200a73bcdc4f769fa38a31621a5a7466

오!! 여러 번 시도 끝에 정말 깨지는 걸 확인했습니다!!
center로 맞추는 기능이 있길래 썼는데 가로 화면은 생각도 못했어요ㅠㅠ

```swift
NSLayoutConstraint.activate([
    activityIndicatorView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
    activityIndicatorView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
])
```

이렇게 고쳤습니다!!
감사합니당!!!ㅎㅎ

2023-08-18 07:35 UTC, WhalesJin commented
b871432d22b2c86e948a234072892b830bcee4c9

알려주신대로 양 옆 레이아웃 기준을 SafeArea로 변경했습니다!!

```swift
NSLayoutConstraint.activate([
    movieScrollView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor),
    movieScrollView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor),
])
```

<img width="656" alt="스크린샷 2023-08-18 오후 4 30 53" src="https://github.com/yagom-academy/ios-box-office/assets/124643545/c8879fcf-733c-4c97-9b91-77951e34a86d">

2023-08-18 07:39 UTC, DasanKim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        guard let posterImage = posterImage,
타입이 상태값을 가질수록 문제점이 발생할 수 있다는 것까지 생각하지 못했던 것 같습니다 감사합니다☺️
`posterImage` 프로퍼티를 삭제하고 아래와 같이 매개변수를 통해 전달하도록 수정하였습니다!

```swift
boxOfficeManager.fetchMovieImageData(keyword: keyword) { result in
            switch result {
            case .success(let image):
                DispatchQueue.main.async {
                    self.stopActivityIndicator()
                    self.configureUI(with: image)
                }
            case .failure(let error):
                os_log("%{public}@", type: .default, error.localizedDescription)
            }
        }
    ...
}
```

2023-08-19 03:02 UTC, WhalesJin commented on BoxOffice/Model/BoxOfficeManager.swift
> +                    print(movieInformation)
이 부분은 간단한 확인을 위해 넣었던 부분인데
지우지 않고 남겨뒀네요🥲
어제 말씀드린대로 슬쩍 지웠습니다 감사합니다 🙏🏻

2023-08-19 03:07 UTC, WhalesJin commented on BoxOffice/Utility/NetworkManager.swift
> +    func fetchImage(url: URL?, completionHandler: @escaping ((UIImage?, NetworkError?)) -> Void) {
알려주신대로 메서드 안에서 이미 만들어놓은 fetchData를 호출하는 형태로 수정해보았습니다🫣

```swift
func fetchImage(url: URL?, completion: @escaping (Result<UIImage?, NetworkError>) -> Void) {
  fetchData(url: url) { result in
    switch result {
    case .success(let data):
      guard let data = data,
        let image = UIImage(data: data) else { return }
        completion(.success(image))
    case .failure(let error):
      completion(.failure(error))
    }
  }
}
```

2023-08-25 07:08 UTC, YebinKim approved these changes
웨일, 다산 안녕하세요~
마지막 스텝에서 좀 더 나아가기 🚀 까지 수행하느라 고생 많으셨습니다 😆

| 세로 모드 | 가로모드 |
| :---: | :---: |
| <img width="250" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/ea385eba-a02a-4959-81be-68f1c03fcbc6">   | <img width="600" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/0dd605ae-a4fd-4764-baf3-56b11528b701"> |

현재 화면에서 긴 텍스트들이 개행되지 않고 잘려보이는 점, 가로모드가 고려되지 않은 점이 다소 아쉽긴 하지만 Compositional Layout 을 처음 활용해보았음에도 두 가지 모드의 UI가 이해하기 쉬운 코드로 작성된 점에 의의가 있다고 생각해요 👏👍

Step4에서의 핵심 경험은 아래와 같았는데요.
<img width="344" alt="step4" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/5169d115-7a92-487f-8391-357803bb5f9b">

이번 스텝에서 목표하고자 하는 내용은 잘 구현되었다고 생각해서 바로 머지 진행하겠습니다~

4주간 자주 소통해주신 덕분에 즐거웠습니다 🐬🌳💖
프로젝트 마무리까지 다시 한 번 고생 많으셨어요 👏👏

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/View/BoxOfficeCell.swift
>  final class BoxOfficeCell: UICollectionViewListCell {
p3;

Grid 셀이 따로 존재하게 되었으니 셀의 구분을 위한 리네이밍이 필요해보여요 👀

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/View/BoxOfficeGridCell.swift
> +        rankIntensityLabel.attributedText = rankIntensityText
p3;

82번 라인의 guard 구문에서 빠른 탈출을 해버렸을 때 `audienceCount` 또는 `audienceAccumulate` 값과는 관련 없는 `rankIntensityLabel.attributedText` 에 대한 업데이트가 실패할 것으로 보여요 🤔
의도된 동작이 맞을까요?

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/View/MovieDetailStackView.swift
> +    }
질문;

오버라이딩을 통해 아무 동작을 수행하지 않는 것으로 보이는데 따로 작성해준 이유가 있을까요?

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/View/MovieScrollView.swift
> +        if let movieInformation = movieInformation {
p4;

guard 구문으로의 활용도 생각해보셨을까요?

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                                             heightDimension: .fractionalHeight(1.0))
p4;

정방형 셀의 UI를 만들 때는 `heightDimension` 매개변수로 `.fractionalWidth(0.5)` 등의 width 기준 값을 전달할 수도 있었을 것으로 보여요 👀

2023-08-25 07:08 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                                              heightDimension: .fractionalHeight(0.2))
p5;

소수점의 값 보다는 `1 / 5` 와 같은 분수 형태로 표현하는 게 한 눈에 구조를 파악하기에 좀 더 쉬워보일 수도 있을 거 같아요 ☺️

2023-08-25 07:09 UTC, merged