박스오피스 [STEP2] Toy, Morgan
yagom-academy/ios-box-office pull request #118
Opened 2023-11-30 11:18 UTC by devjoon

@havilog
안녕하세요 하비
step2 PR 드립니다.
이번 스텝도 잘 부탁드립니다 !!👍

고민이 되었던점
- 요구사항중 오늘의 일일 박스오피스를 조회하는 내용이 있었으나 일일 박스오피스 조회는 하루전날 내용까지만 조회가 가능하여 어제로 시간을 설정하여 박스오피스 조회를 진행하였습니다 

- DataDecoder파일에 step1에서는 assetDate가 사용되어서 asset을 디코딩하는 메서드를 남겨두었는데 step2부터는 직접 서버를 통해 받아온 값을 사용하게 되어 받아온 값을 디코딩하는 메서드를 구현하였습니다. 만일 이렇게 두가지 방법으로 디코딩하는 메서드를 만들경우 지금처럼 DataDecoder한곳에 넣어주는게 좋을까요 아니면 따로 분리해주는것이 좋을까요?

- Error를 처리하는 부분에서 `LocalizedError` 프로토콜을 채택하여 에러에 관련된 상세 설명을 구현하였습니다. 
~~~ swift
import Foundation

enum DecodingError: Error {
    case emptyAssetData
}

extension DecodingError: LocalizedError {
    var errorDescription: String? {
        return "에셋 데이터가 없습니다."
    }
}
~~~

- 해당 에러를 처리하는 부분에서 궁금증이 생겼습니다.
  .decode 에서 던져주는 에러는 어떤 에러인지 알수가 없는데 저희가 작성한     코드처럼 error 상수를 타입캐스팅하여 errorDescription을 사용하는게     맞는 방법인지 궁금합니다.

~~~ swift
static func parseJson<T: Decodable>(type: T.Type, data: Data) -> T? {
        let decoder = JSONDecoder()
        do {
            let receivedData = try decoder.decode(type, from: data)
            return receivedData
        } catch let error as DecodingError {
            print(error.errorDescription ?? .empty)
        } catch {
            print(error.localizedDescription)
        }
        return nil
    }
~~~

- 그리고 에러 케이스가 여러개인 경우 아래처럼 구현하면 .decode 처럼 어떤에러가 나오는지 모르는 경우에는 정의한 error케이스 중 어떤게 던져질지 모르는데 어떻게 errorDescription을 원하는 케이스에 맞게 사용할 수 있을지 궁금합니다.

~~~ swift
enum DecodingError: Error {
    case emptyAssetData
    case A // 예시 케이스
    case B // 예시 케이스
}

extension DecodingError: LocalizedError {
    var errorDescription: String? {
        switch self {
            case .emptyAssetData:
                return "에셋 데이터가 없습니다."
            case .A:
                return "A"
            case .B:
                return "B"
        }
        return "에셋 데이터가 없습니다."
    }
}
~~~

`LocalizedError` 프로토콜을 상황에 맞게 적절히 사용하였는지 알고싶습니다.

그외 부족한 부분이 있다면
말씀 주시면 감사드리겠습니다 😀

2023-12-01 14:43 UTC, havilog requested changes
수고하셨어용

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Model/MovieDetail.swift
> +struct Infomation: Decodable {
```suggestion
struct Movie.Infomation: Decodable {
```

```suggestion
struct MovieInfomation: Decodable {
```

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Model/MovieDetail.swift
> +struct Infomation: Decodable {
여기 파일들은 전부 Movie 네임스페이스 안에 넣는게 나을거같네요

2023-12-01 14:43 UTC, havilog commented on BoxOffice/NameSpace/DateFormat.swift
> +}
이런 아이는 앱 전역에서 접근하는게 아닌, 실제로 필요한 곳에 정의되는게 좋을 것 같아요

2023-12-01 14:43 UTC, havilog commented on BoxOffice/NameSpace/MovieURL.swift
> +}
네트워크 엔드포인트를 정의하고 해당 위치에 있어야 할 것 같고,
key같은 경우에는 따로 분리하여 깃에 올리면 안될거 같아요

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +    }
API가 100개 생기면 함수를 100개 만들어야 할 것 같아요.
generic을 활용해보는건 어떨까요?

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Extension/String+.swift
> +}
요거슨 이미 있는 아이 같아요

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +    }
HTTPMethod를 정의하는 부분, 헤더나 파라미터를 정의하는 부분
파라미터를 인코딩 하는 방법(url, json)
네트워크 통신에서 나올 수 있는 에러를 정의하는 부분
위 정의한 아이들을 활용하여 URLRequest를 만드는 부분

 data task를 에서 온 response를 validate 하는 부분
data를 원하는 타입으로 디코딩하는 부분

등이 빠져있어서 해당 부분 공부해보시면 좋을 것 같습니다.

alamofire같은곳에서는 어떻게 구현했는지도 공부해보시면 좋을 것 같아요

2023-12-01 14:43 UTC, havilog commented on BoxOffice/Model/DataDecoder.swift
> +    }
> DataDecoder파일에 step1에서는 assetDate가 사용되어서 asset을 디코딩하는 메서드를 남겨두었는데 step2부터는 직접 서버를 통해 받아온 값을 사용하게 되어 받아온 값을 디코딩하는 메서드를 구현하였습니다. 만일 이렇게 두가지 방법으로 디코딩하는 메서드를 만들경우 지금처럼 DataDecoder한곳에 넣어주는게 좋을까요 아니면 따로 분리해주는것이 좋을까요?

요 함수는 여기 있으면 안될거 같아요
디코드는 fetch해오는 시점에서 하는게 좋을것같습니다

2023-12-03 05:15 UTC, devjoon commented on BoxOffice/Model/MovieDetail.swift
> +struct Infomation: Decodable {
MovieInfomation으로 네이밍 변경하였습니다.

2023-12-03 05:45 UTC, devjoon commented on BoxOffice/Model/MovieDetail.swift
> +struct Infomation: Decodable {
MovieInfomaion(전 MovieDetail)파일 Movie파일에 병합을 진행하였고 DailyBoxOfficeItem 파일 또한 동일한 형태여서 BoxOffice파일에 병합하였습니다.

2023-12-03 05:48 UTC, DevWooHyeon commented on BoxOffice/NameSpace/DateFormat.swift
> +}
NetworkManager 안에서만 사용할 수 있도록 중첩타입으로 변경하였습니다.

2023-12-03 06:06 UTC, DevWooHyeon commented on BoxOffice/NameSpace/MovieURL.swift
> +}
key는 따로 분리해서 깃에 올라가지 않도록 하였습니다.
근데 처음 설명해주신 부분을 저희는 Network 그룹에서 사용하는 부분으로 옮기라는 뜻으로 이해해서 옮겼는데 저희가 이해한게 맞는지 궁금합니다!!

2023-12-03 06:15 UTC, devjoon commented on BoxOffice/Extension/String+.swift
> +}
"" 네임스페이스를 어떻게 처리할까 생각하다가 String에는 empty프로퍼티가 존재하지 않아서 따로 생성을 해 주었는데 ```이미 있다``` 는 말씀은 빈 문자열을 나타낼 방법이 따로 있다는 뜻일까요?

지금은 empty는 이미 존재하는 프로퍼티여서 네이밍이 겹친다는 뜻으로 이해 하고
네이밍 변경을 진행하였습니다

2023-12-03 07:21 UTC, DevWooHyeon commented on BoxOffice/Network/NetworkManager.swift
> +    }
API가 여러개일때도 동일하게 함수를 사용 할 수 있도록 generic을 사용해서 수정하였습니다.

2023-12-03 07:21 UTC, devjoon commented on BoxOffice/Model/DataDecoder.swift
> +    }
fetch해오는 시점에서 디코드 할 수 있도록 변경하였습니다!

2023-12-03 07:25 UTC, DevWooHyeon commented on BoxOffice/Network/NetworkManager.swift
> +    }
아직 네트워킹에 대한 공부가 부족해서 지금 당장 수정하기에는 시간이 조금 부족할 것 같습니다.. 설명해주신 부분을 조금 더 공부해서 다음 스텝에서 수정하도록 하겠습니다!

2023-12-03 08:42 UTC, havilog commented on BoxOffice/NameSpace/DateFormat.swift
> +}
네트워크 매니저 라는 아이는 말 그대로 네트워크 통신을 담당하는 아이여야 할 것 같은데
데이트 포맷은 어떠한 포맷을 가지고 데이트를 포매팅 하는 역할로 보여요
그렇다면 커스텀 데이트 포매터를 만들고 네트워크 매니저가 해당 의존성에 의존하도록 하는건 어떨까요?

2023-12-03 08:51 UTC, havilog reviewed
step 3의 경우 UI구현으로 알고있는데요
사실 제 생각에는 네트워크 레이어에 대한 제대로 된 구현이 없다면 UI를 구현하는 의미는 없다는 생각이 들어요
토이 모건의 의견은 어떠신가요?

2023-12-03 08:51 UTC, havilog commented on BoxOffice/Extension/String+.swift
> +}
아 이미 있다는 코멘트는 잊어주시구 .. ㅎㅎ
사실 요런 extension들은 존재하는지 모르는 사람이 많아지면 레거시가 될 것 같아서요
그냥 ""으로 써도 될 것 같아요!

2023-12-03 08:51 UTC, havilog commented on BoxOffice/Network/Key.swift
> +}
그냥 Key라고 하기보다는 어떤 api의 어떤 key인지 명시적으로 지어주는게 좋아보어요

2023-12-04 06:17 UTC, devjoon commented on BoxOffice/Extension/String+.swift
> +}
넵 코멘트 이후 삭제 하였습니다!

2023-12-04 06:18 UTC, devjoon commented on BoxOffice/Network/Key.swift
> +}
명시적인 네이밍을 위하여 movieDataApiKey로 변경하였습니다.

2023-12-12 08:18 UTC, merged