박스오피스 [STEP 2] Brody, Vetto
yagom-academy/ios-box-office pull request #12
Opened 2023-03-22 07:31 UTC by seunghyunCheon

## STEP2

안녕하세요 태태 @uuu1101
스텝 2-1까지 완료하여서 PR보냅니다.

## 조언받고 싶은 점

### URL 관리방법
네트워크 통신을 위해 사용하는 URL을 상황에 따라 다르게 생성시키기 위해서 다음과 같이 정의했습니다.
```swift
enum BoxOfficeAPI {
    case dailyBoxOffice(date: String)
    case detailMovieInformation(movieCode: String)
    
    static let key: String = "67e99e70400656a77208ca1775261071"
}

extension BoxOfficeAPI {
    var url: URL? {
        switch self {
        case .dailyBoxOffice(let date):
            let path = "boxoffice/searchDailyBoxOfficeList.json?"
            return .makeForEndpoint("\(path)key=\(BoxOfficeAPI.key)&targetDt=\(date)")
        case .detailMovieInformation(let movieCode):
            let path = "movie/searchMovieInfo.json?"
            return .makeForEndpoint("\(path)key=\(BoxOfficeAPI.key)&movieCd=\(movieCode)")
        }
    }
}

private extension URL {
    static let baseURL = "http://kobis.or.kr/kobisopenapi/webservice/rest/"
    
    static func makeForEndpoint(_ endpoint: String) -> URL? {
        guard let url = URL(string: baseURL + endpoint) else {
            return nil
        }
        return url
    }
}
```
하지만 이 방법은 요청하는 url의 열거형타입이 `dailyBoxOffice`인 상태에서 여러가지 쿼리 파라미터를 받고자 한다면 매개변수의 개수만 다른 비슷한 유형의 case를 정의해야 합니다.
```swift
var url: URL? {
    switch self {
    case .dailyBoxOffice(let date):
        let path = "boxoffice/searchDailyBoxOfficeList.json?"
        return .makeForEndpoint("\(path)key=\(BoxOfficeAPI.key)&targetDt=\(date)")
    case .dailyBoxOffice(let date, let itemPerPage):
        let path =  "boxoffice/searchDailyBoxOfficeList.json?"
        return .makeForEndpoint("\(path)key=\(BoxOfficeAPI.key)&targetDt=\(date)&itemPerpage=\(itemPerPage)")
    }
} 
```

이 때문에 쿼리파라미터의 종류가 다양한 서비스의 경우에는 보일러 플레이트 코드가 많이 생겨날 것으로 생각했습니다. 

혹시 태태는 어떤 방식으로 URL Endpoint를 관리하시는지 궁금합니다.

### mimeType

처음에는 httpResponse의 mimeType을 검사하여 json 형식의 데이터만 받아오도록 하려고 하였습니다. 하지만 데스트를 하기 위해 MockURLSession을 만들었고 HTTPURLResponse를 생성할 때 mimeType이 생성되는 생성자가 아닌 statusCode가 생성되는 생성자로 구현하였고 그로인해 api를 통해 받아오고 있던 mimeType이 존재하지 않아(nil값이 나옴) if let 구문에서 실행이 안되어 테스트가 안되었습니다.

따라서 현재는 mimeType을 검사하는 코드를 삭제하였습니다. 혹시 직접 만든 HTTPURLResponse객체에 mimeType을 추가하는 방법이 있을까요?

혹은 다른 자료들을 찾아봤을 때 mimetype까지 검사하지 않고 에러나 상태코드에 의해서만 검사를 진행했는데 이대로 해도 괜찮을까요?

수정 전
```swift
if let mimeType = httpResponse.mimeType, mimeType == "application/json",
    if let data = data {
        do {
            let jsonData = try JSONDecoder().decode(type, from: data)
            completion(.success(jsonData))
        } catch {
            completion(.failure(NetworkError.failToParse))
        }
                
        return
    }
```

수정 후
```swift
if let data = data {
    do {
        let jsonData = try JSONDecoder().decode(type, from: data)
        completion(.success(jsonData))
    } catch {
        completion(.failure(NetworkError.failToParse))
    }
                
    return
}
```

2023-03-23 15:35 UTC, uuu1101 requested changes
안녕하세요 ! @gzzjk159 @seunghyunCheon 
Step2 하시느라 고생하셨습니다 ! 

요즘 퇴근이 자꾸 늦어져서, 해당 피드백 먼저 드리고 바로 주말 지나기전에 피드백 한번 더 드리겠습니다 ㅠㅠ
코멘트 확인하시고, 답글 달아주세요 ! 
토요일전에 꼭 피드백 드리겠습니다

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Error/NetworkError.swift
> +    case failToParse
enum 타입으로 잘 작성하셨네요 👍
에러타입에 대해서 조금 더 구체적으로 명시할수 있을까요?
서버의 어떤에러인지, 클라이언트에서의 어떤 부분이 에러인지 조금 더 명확하면 좋을 것 같아요 !

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeAPI.swift
> +}
BoxOfficeAPI 라고 하니 되게 포괄적인 네이밍 같아요.
오히려 구조체로 작성하여서 API가 가질수있는 부분들을 표현하는 객체로 생성하거나
enum 타입으로 한다면 해당 부분들을 잘 표현할 수 있는 네이밍이 오는게 좋을 것 같습니다.

key도 이렇게 관리하는 방법도 좋지만 따로 빼서 관리해주면 어떨까요?
지금 필요한것은 아니지만, plist 에서 관리해주는 방법도 있답니다. (나중에 시간될때 해보시면 좋을 것 같아요)

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeAPI.swift
> +    }
동일한 코드가 반복되는게 싫으시다면, URL을 생성해주는 객체나 메서드를 통해 생성해주셔도 좋을 것 같네요!

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeAPI.swift
> +private extension URL {
URL을 extension 하신 이유가 궁금해요 :)

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeAPI.swift
> +        guard let url = URL(string: baseURL + endpoint) else {
endPoint는 어떤 것을 나타내나요? 무엇인가요?

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/MovieDetailInformation.swift
> +    let movieOriginalName: String
각자의 코딩 스타일이긴 할텐데, movie에 대한 것을 struct 네이밍으로 알 수 있으니 movie 를 생략 해주셔도 무방할 것 같아요!

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Model/MovieDetailInformation.swift
> +// MARK: - Audit
마크주석을 통해서 잘 관리하셨네요 👍

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/Network/NetworkManager.swift
> +
44, 55라인의 공백은 의도하신건가요?

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        guard let yesterday = makeYesterday() else {
어제를 만든다는 표현이 좀 어색한것 같습니다.

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +    private func showAlert() {
Alert를 보여주는게 있다면, 다른 에러부분에서도 사용자에게 Alert을 통해 알려주면 좋을것 같네요 :)

2023-03-23 15:35 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        let url = BoxOfficeAPI.detailMovieInformation(movieCode: "20124080").url
movieCode를 따로 관리하는것도 좋아보입니다 👍

2023-03-24 01:39 UTC, seunghyunCheon commented on BoxOffice/Error/NetworkError.swift
> +    case failToParse
`clientError` ->  `requestError`로,
`serverError` -> `responseError`로 변경했습니다.

그리고 `LocalizedError`를 채택해서 에러문구를 정의해주었습니다!

2023-03-24 03:05 UTC, seunghyunCheon commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +    private func showAlert() {
사용자 입장에서 보여지는 에러는 STEP2에서는 아직 존재하지않아서요! STEP3하면서 추가하겠습니다!

2023-03-24 03:06 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        guard let yesterday = makeYesterday() else {
makeYesterday 메서드를 삭제하고 yesterday 연산 프로퍼티를 사용하여 어제 날짜를 가져오도록 하였습니다. 022a89f7e4a0e9882e59bcbab56a9c6ca0381251

2023-03-24 03:15 UTC, gzzjk159 commented on BoxOffice/Network/NetworkManager.swift
> +
저희가 정한 컨벤션에 의해 리턴문만 있을 경우를 제외하고 공백을 주기로 하였습니다. 5fa6a1d3be05dd01a517543095987b5d40d7cc28

2023-03-24 03:15 UTC, seunghyunCheon commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        let url = BoxOfficeAPI.detailMovieInformation(movieCode: "20124080").url
현재는 movieCode하나만 존재해서 해당 뷰컨트롤러에서 프로퍼티로 갖도록 했습니다!
추후에 다뤄야할 코드가 많아진다면 다른 방법을 고민해보겠습니다!

2023-03-25 13:24 UTC, uuu1101 commented
조언이 필요한 부분
---
1. EndPoint 관리
먼저 API 와 EndPoint 의 차이점은 무엇일까요?
이 부분을 명확하게 하시면 답을 찾는데 도움이 될 것 같습니다. 

2.따라서 현재는 mimeType을 검사하는 코드를 삭제하였습니다. 혹시 직접 만든 HTTPURLResponse객체에 mimeType을 추가하는 방법이 있을까요?  
> 해당 부분을 전처리 하고 싶으신 이유가 있으실까요? JSON 디코더를 통해서 디코딩을 하고 , 에러 처리도 해주고 있기 때문에 전처리 과정이 필요할까? 라는 의견이 있습니다.

혹은 다른 자료들을 찾아봤을 때 mimetype까지 검사하지 않고 에러나 상태코드에 의해서만 검사를 진행했는데 이대로 해도 괜찮을까요?
> 네 이대로 하셔도 괜찮을것 같아요.

2023-03-27 13:38 UTC, merged