박스오피스 [STEP 2] 레옹아범, Andrew
yagom-academy/ios-box-office pull request #14
Opened 2023-03-22 09:12 UTC by Andrew-0411

@1Consumption 
안녕하세요 레옹아범, Andrew입니다.
박스오피스 STEP 2, 2-1 PR 보내드립니다.
Unit Test는 많이 사용해 봤지만 Test Double은 처음 구현해봐서 많이 어색한거 같습니다. 🤔

## 고민했던점

### 1️⃣ 하나의 네트워크 모델 만들기

#### ❓문제점
* **일일 박스오피스 조회** 및 **영화 개별 상세조회**를 url을 통해 부르는 과정을 기존에는 두가지 타입으로 구현하였습니다.
* 그러나, 여러개를 통신으로 불러와야 하는 경우 계속 타입을 만들어줘야한다는 문제와 겹치는 코드가 있다는 문제 때문에 하나의 타입으로 만들었습니다

#### 📖해결법
```swift
protocol Fetchable: Decodable
```

* `Fetchable` 프로토콜을 만들어 해당 프로토콜을 채택하는 타입을 JSONDecoding 할 수 있도록 구현하였습니다.

```swift
class BoxofficeInfo<T: Fetchable> {
    //.....
    func search(completion: @escaping (Result<T, BoxofficeError>) -> Void) {
        //....
                if let mimeType = httpResponse.mimeType, mimeType == "application/json",
                   let data = data {
                    do {
                        let decodingdata = try JSONDecoder().decode(T.self, from: data)
                        completion(.success(decodingdata))
                    } catch {
                        completion(.failure(.decodingError))
                        return
                    }
                }
            }
    //....
    }
}
```

* 위와 같이 제너릭타입으로 `Fetchable`을 채택하는 타입이라면 `JSONDecoder`를 통해 디코딩 할 수 있도록 만들었습니다.

### 2️⃣ errorDescription을 사용하여 error 내용 설명하기
```swift
var errorDescription: String? {
    switch self {
    case .urlError:
        return "url형식이 잘못되었습니다"
    case .sessionError:
        return "네트워크 연결이 불완전합니다"
    case .responseError:
        return "데이터를 받아오지 못하였습니다"
    case .decodingError:
        return "데이터를 변환하지 못하였습니다"
    }
}
```
- 지금 단계에서는 사용하지 않지만 URLSession 네트워크 통신을 하는 과정에서 에러를 반환값에 사용하거나
- 또는 추후에 에러가 발생하면 Alert창으로 어떤 내용인지 에러를 나타내기 위해서 구현하였습니다

### 3️⃣ @escaping Closure를 통한 에러처리

#### ❓문제점
* 네트워크의 불안정으로 인해 발생한 error
* 서버 혹은 클라이언트로 발생한 400번 혹은 300번대의 response에러 등을 처리해주기 위해 기존에는 함수에서 `throws`를 통해 에러를 반환하도록 구현하였습니다.

#### BoxofficeInfo
```swift
func search() throws
```

* 위와 같이 구현할 경우 `ViewController`에서 `search`메소드에서 발생하는 모든에러를 `do-catch`문을 이용해서 구현해야 된다는 점때문에 `@escaping closure`를 사용하였습니다.

#### 📖해결법

```swift
func search(completion: @escaping (Result<T, BoxofficeError>) -> Void)
```

* `@escaping closure` 및 함수 인자에 `Result`를 사용함으로 올바른 값일 때는 `completion(.success(T))`, 오류가 날 경우 `completion(.failure(.BoxofficeError))`를 사용함으로 `ViewController`내에서 클로저만 구현하여 기존 생각했던 `do-catch`문보다 더 짧게 코드를 구성할 수 있었습니다.

## 조언을 얻고 싶은 점

### 올바른 TestDouble요소인지?

#### 1️⃣ FakeURLSessionDataTask
```swift
class FakeURLSessionDataTask: URLSessionDataTask {
    var resumeDidCall: () -> Void = {}
    
    override func resume() {
        resumeDidCall()
    }
}
```
* 해당 부분은 `URLSessionDataTask`가 기존에 해야하는 `resume`메소드의 역할을 위해 만든것이지만 저희는 `resume`메소드의 정확한 구현을 모르기 때문에 필요한 부분인 클로저를 실행하는 방식만 동작하도록 만들었기 때문에 Fake라고 생각합니다.

#### 2️⃣ StubURLSession
* URLSession과 같이 유사하게 동작하지만 가짜 `HTTPURLResponse`를 전달하면서 나머지 동작을 진행할 수 있도록 만들어주기 때문에 Stub이라고 생각합니다

#### 3️⃣ StubBoxoffice
* 해당 부분은 Stub과 Dummy 둘 중에서 조금 헷갈리는것 같습니다
* 하지만 Dummy의 경우 아무일을 하지 않고 단순히 무언가 객체의 파라미터를 채우는 용도로만 사용한다면
* Stub은 메소드가 동작할 수 있도록 정해진 객체를 주는것이라고 이해했는데
* 해당 `StubBoxoffice`는 `JSONDecoder`의 `decode`메소드가 동작할 수 있도록 만들어주기 때문에 `Stub`이라고 생각합니다

#### 4️⃣ MockBoxofficeInfo
* 해당 객체는 여러 상황에서 메소드가 다 동작하는지에 대한 여부를 확인하기 때문에 `Mock`이 맞다고 생각합니다

* 혹시 이 부분에서 저희가 틀리게 이해하고 있는 부분이 있을까요? TestDouble의 각각 요소가 생각보다 밀접하게 관련이 있고 저희 테스트를 위한 코드들이 모두 중복되는 것들이 있어서 뭐 하나로 지정하기 어려울까요?

2023-03-22 15:29 UTC, 1Consumption requested changes
안녕하세요 @Andrew-0411 @fatherLeon 
고생하셨습니다.

스텝 2-1은 도전 스텝인데, 진행해주신 점 좋습니다👍
다만 아직 정확한 이해를 기반으로 코드를 작성하지 않은듯 하여 많이 아쉽습니다.

아래는 고민한 점, 조언받고싶은 점에 대한 제 생각입니다.

### `@escaping` Closure를 통한 에러처리
이건 `@escaping` 클로저를 활용한게 아니라 `Result` 타입을 활용했다고 보여집니다. 한번 더 생각해보면 좋겠습니다.

### 올바른 TestDouble요소인지?
1️⃣ FakeURLSessionDataTask
```swift
class FakeURLSessionDataTask: URLSessionDataTask {
    var resumeDidCall: () -> Void = {}
    
    override func resume() {
        resumeDidCall()
    }
}
```
* 해당 부분은 `URLSessionDataTask`가 기존에 해야하는 `resume`메소드의 역할을 위해 만든것이지만 저희는 `resume`메소드의 정확한 구현을 모르기 때문에 필요한 부분인 클로저를 실행하는 방식만 동작하도록 만들었기 때문에 Fake라고 생각합니다.

> 네, 이부분은 저도 맞다고 생각합니다.

#### 2️⃣ StubURLSession
* URLSession과 같이 유사하게 동작하지만 가짜 `HTTPURLResponse`를 전달하면서 나머지 동작을 진행할 수 있도록 만들어주기 때문에 Stub이라고 생각합니다

> 아니요, 이부분은 `URLSessionProtocol`을 채택해 내부의 동작을 속이고 있기 때문에 stub이라고 보기 어렵습니다. stub은 프로그래밍 된 응답 이외에는 다른 어떤 일도 하지 않습니다.

#### 3️⃣ StubBoxoffice
* 해당 부분은 Stub과 Dummy 둘 중에서 조금 헷갈리는것 같습니다
* 하지만 Dummy의 경우 아무일을 하지 않고 단순히 무언가 객체의 파라미터를 채우는 용도로만 사용한다면
* Stub은 메소드가 동작할 수 있도록 정해진 객체를 주는것이라고 이해했는데
* 해당 `StubBoxoffice`는 `JSONDecoder`의 `decode`메소드가 동작할 수 있도록 만들어주기 때문에 `Stub`이라고 생각합니다

> 맞다고 생각합니다.

#### 4️⃣ MockBoxofficeInfo
* 해당 객체는 여러 상황에서 메소드가 다 동작하는지에 대한 여부를 확인하기 때문에 `Mock`이 맞다고 생각합니다

> Mock은 메소드가 다 동작하는지가 아니라 행위를 검증하는 객체입니다. 전혀 다른 타입의 객체를 만드는게 아닙니다. 또한 Mock을 이용해 테스트를 하는 것이지, Mock을 테스트 하는게 아닙니다.
https://martinfowler.com/articles/mocksArentStubs.html 이 문서를 참고해보세요.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
get~ 보다는 다른 이름을 고려해보세요. get~ ,set~는 잘 사용하지 않는 네이밍입니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
`interfaceValue`가 정말 모든 url을 가져오는데 필요한 정보일까요? 지금은 그래보입니다만, 만약 `interfaceValue`가 필요하지 않은 url이 생긴다면 어떻게 해야할까요? 필요하지 않은 값이니까 빈 값을 넣어야할까요?

이런 방법보다는 enum의 연관값을 사용해보는게 어떨까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
고민했던 점에 적어주신 것 중에 throws 대신에 Result타입을 사용한 내용이 있었습니다. 여기는 해당되지 않는 내용인가요? 여기는 왜 throws를 사용했나요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +
불필요한 공백 같습니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +            return boxofficeUrl
굳이 에러를 던지지 말고 옵셔널을 리턴해도 될거같습니다. 사용하는 곳에서 판단해도 될거같아요.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +class BoxofficeInfo<T: Fetchable> {
상속되는 객체인가요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +    let apiType: APIType
외부에서 알아야하는 프로퍼티인가요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +class BoxofficeInfo<T: Fetchable> {
구조체가 아니라 클래스로 만든 이유가 궁금합니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
만약 이 dataTask를 취소하고싶다면 어떻게 해야하나요? 지금은 별다른 방법이 없어보이네요.

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
지금은 실제 URLSession 타입의 객체를 항상 호출하는데, 이러면 테스트할때도 네트워킹을 하게되지 않을까요?
우리가 정말 URLSession 타입이 필요한걸까요? 아니면 `특정 역할`을 할 수 있는 객체가 필요한걸까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +                }
if let과 guard let이 혼용되어 사용되고 있네요. 특별한 기준이 있을까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +                   let data = data {
만약 이 if문을 통과하지 못하면 사용자는 콜백을 받을 수 있을까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxOffice/Protocol/Fetchable.swift
> +}
굳이 이 프로토콜을 만들어야만했던 이유가 있을까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    var mockSession = StubURLSession()
외부에서 몰라도 되는 변수 같습니다. 
물론 이 객체를 직접 생성해서 사용할 일은 없습니다. 하지만 이런 습관을 들이는게 중요합니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    var mockSession = StubURLSession()
`mockSession`이 바뀔 일이 있나요? var인 이유가 없어보입니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    }
이 테스트들은 제대로 진행되고 있나요? 검증이 전혀 안되고 있지 않나요? `search` 메소드는 이스케이핑 클로저를 매개변수로 받고 있습니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +        }
30번째가 when절이고 34번째가 then절 같습니다.
given when then 패턴을 다시 한번 공부해보세요.

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +            }
만약 여기로 들어오면 테스트가 실패해야하나요? 아니면 성공해야하나요? 지금은 성공할거같습니다.

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    }
프로젝트 요구 사항에 아래와 같은 내용이 있습니다.

* Test Double을 통해 네트워크 상태와 무관하게 로직을 테스트할 수 있도록 테스트를 구성합니다.
* 네트워크가 연결되지 않은 상황에서, 위에서 작성한 테스트를 실제로 진행해봅시다.

이 테스트는 요구사항을 만족한 테스트인가요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/FakeURLSessionDataTask.swift
> +}
test doubles는 어떤 것이 있나요? 그리고 각각의 정의와 차이점은 어떻게 되나요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/MockBoxofficeInfo.swift
> +}
이건 Mock객체가 아닙니다. `공교롭게도 실제 구현부와 같은 코드를 가지고 있는 전혀 다른 객체`입니다. 
실제 구현부를 테스트해야 테스트의 의미가 있지 않을까요?

그리고 지금 같은 경우, 만약 실제 구현부가 변경되면 여기도 같이 변경을 해줘야할 거 같은데... 과연 적절한 방법일까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/StubURLSession.swift
> +    let sessionDataTask = FakeURLSessionDataTask()
이 멤버 변수가 필요한 이유가 있을까요?

2023-03-22 15:29 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/StubURLSession.swift
> +    }
iOS 13부터 `URLSessionDataTask`의 init이 deprecated 된걸로 알고 있는데, 사용하신 이유가 있을까요? 
테스트를 위함이라면, [URLProtocol](https://developer.apple.com/documentation/foundation/urlprotocol)을 보시면 좋겠습니다.

2023-03-23 05:08 UTC, Andrew-0411 commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
받아오다는 의미로 receiveUrl로 변경하였습니다.

2023-03-23 05:22 UTC, fatherLeon commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
말씀하신대로 열거형의 associated Values를 이용하여 

```swift
enum APIType {
    case movie(String)
    case boxoffice(String)

    func receiveUrl() throws -> URL {
        let key = Bundle.main.apiKey
        
        switch self {
        case .movie(let code):
            guard let movieUrl = URL(string: "http://kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=\(key)&movieCd=\(code)") else {
                throw BoxofficeError.urlError
            }
            return movieUrl
    //......
}
```
* 위와 같이 변경하였습니다.
* 이럴 경우 말씀하신것과 같이 기존에는 요청 인터페이스 값에 1개만 넣을 수 있었지만 이렇게 만들 경우 여러개의 값을 가지는 URL 만드는것도 가능하고 한개도 가지지 않는 상황도 만들 수 있을것 같습니다.

2023-03-23 05:34 UTC, Andrew-0411 commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
APIType에서 receiveUrl 메서드를 사용할 경우 urlError만 던져주기 때문에 위와 같이 사용하였습니다.
네트워크 통신의 경우에 throw를 하게 된다면 에러의 종류가 많아서 `urlError, sessionError, responseError, decodingError` catch문이 많아지기 때문에 Result 타입을 사용하였습니다.

2023-03-23 05:48 UTC, fatherLeon commented on BoxOffice/Model/APIType.swift
> +            return boxofficeUrl
```swift
func receiveUrl() -> URL? 
```
* 말씀해주신대로 옵셔널 타입으로 고치고 

```swift
func search(completion: @escaping (Result<T, BoxofficeError>) -> Void) {
        guard let url = apiType.receiveUrl() else {
            completion(.failure(.urlError))
            return
        }
    //......
}
```
* `search`메소드도 do-catch문에서 guard문으로 변경하였습니다.

* 리뷰주신거 통해 코드 수정하다보니 `do-catch`문이 사라지게 되었는데 이런 부분을 에러 핸들링 통일성 때문에 말씀해주신걸까요?

2023-03-23 05:50 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
> +class BoxofficeInfo<T: Fetchable> {
`final`키워드를 붙여주었습니다!!

2023-03-23 05:54 UTC, Andrew-0411 commented on BoxOffice/Model/BoxofficeInfo.swift
> +    let apiType: APIType
receive 메서드를 수정하면서 interfaceValue 프로퍼티는 필요가 없어져서 삭제하였고 apiType을 private 접근제어자로 변경하였습니다

2023-03-23 06:10 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
> +class BoxofficeInfo<T: Fetchable> {
* 기존 `BoxofficeInfo`에서 `data`프로퍼티가 있어, 해당 프로퍼티를 캡처하여 `JSONDecoding.decode`한 값을 저장해놓는 역할을 가졌었기 때문에 클로저 값 캡처를 위해 클래스로 사용하였었습니다.
* 다만 현재 이 부분은 사용하지 않기 때문에 클래스가 아닌 구조체로 다시 변경하였습니다!!

2023-03-23 07:58 UTC, Chanhhyuk commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
```swift
private var task: URLSessionDataTask?

func cancelTask() {
    self.task?.cancel()
}
```
URLSessionDataTask 타입인 프로퍼티를 생성하여 URLSessionDataTask 타입의 메서드인 cancel()을 호출하여 취소할 수 있는 방법을 만들었습니다

2023-03-23 08:11 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
* 실제로 동작할때는 URLSession타입이 네트워크를 통해 데이터를 받을 수 있도록 만들어주기 때문에 필요하다고 생각합니다.
* 다만 테스트할때는 하나의 테스트케이스 안에 네트워크가 연결된 상황과 연결되지 않은 상황일 때 각각 통과하는 테스트코드가 만들어져야된다고 생각합니다
* 그렇기 때문에 테스트시에 네트워크가 연결되어있지 않은 상태에서도 임의로 만든 객체를 활용하여 테스트를 진행할 수 있도록 `session`을 분리해주었습니다.
```swift
struct BoxofficeInfo<T: Fetchable> {
    private let session: URLSession

    mutating func search(completion: @escaping (Result<T, BoxofficeError>) -> Void) {
        self.task = session.dataTask(with: url) { data, response, error in
            if error != nil {
                completion(.failure(.sessionError))
                return
            }
    //......
```

2023-03-23 08:31 UTC, Andrew-0411 commented on BoxOffice/Model/BoxofficeInfo.swift
> +                }
[Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory) 
공식문서를 참고하여 API 통신을 구현하다보니 명확한 기준없이 혼용해서 사용했던거 같습니다.
guard문으로 통합해서 변경하였습니다

2023-03-23 08:36 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
> +                   let data = data {
```swift
guard let mimeType = httpResponse.mimeType,
          mimeType == "application/json",
          let data = data else {
        completion(.failure(.incorrectDataTypeError))
        return
}
```
* 사용자가 콜백을 받을 수 있도록 `incorrectDataTypeError`를 추가로 넣어주었습니다.

2023-03-23 08:48 UTC, fatherLeon commented on BoxOffice/Protocol/Fetchable.swift
> +}
```swift
struct BoxofficeInfo<T: Fetchable>
```
* 단순히 `Decodable`만을 사용하고 위의 구조체를

```swift
struct BoxofficeInfo<T: Decodable>
```
* 위와 같이 변경하여도 동작은 하겠지만 개발과정에서 실수가 발생할 가능성이 있기 때문에 위 프로토콜을 구현하였습니다.

```swift
var boxoffice = BoxofficeInfo<InfoObject>(apiType: .boxoffice("20230320"), session: URLSession.shared)

var movie = BoxofficeInfo<MovieInfoDescObject>(apiType: .movie("20221230"), session: URLSession.shared)
```
* 위와 같이 다른 `Decodable`을 채택한 DTO를 넣어줄 경우 `.decodingError`가 나오기 때문에 올바른 타입을 넣어주기 위해 `Fetchable`프로토콜을 만들어 현재 DTO의 최상위 객체만 해당 `Fetchable`을 채택하여 구현하였습니다.

2023-03-23 09:36 UTC, Andrew-0411 commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +        }
Given (준비)
- 테스트를 위한 변수나 값등을 정의합니다.
- Mock 객체를 정의하는것도 Given에 포함됩니다.

When (실행)
- 실제로 테스트를 실행하는 부분입니다.

Then (검증)
- 예상한 값과 실제 테스트에서 나온 값을 검증합니다

2023-03-24 07:18 UTC, fatherLeon commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    }
* dataTask는 비동기로 작동되므로 `XCTestExpectation`을 추가로 사용하여 다시 검증하도록 만들었습니다.

```swift
func test_URLResponse가_200번대가_아니라면_responseError를_나타낸다() {
    // given
    MockURLProtocol.requestHandler = { request in
        guard let url = request.url,
              url == APIType.boxoffice("20230322").receiveUrl() else {
            throw BoxofficeError.urlError
        }
        
        let response = HTTPURLResponse(url: url, statusCode: 400, httpVersion: "2.0", headerFields: nil)!
        let data = StubBoxoffice().data
        
        return (response, data)
    }
    
    let asyncTest = XCTestExpectation()
    var result: BoxofficeError = .urlError
    
    // when
    sut.search { event in
        switch event {
        case .success(_):
            XCTFail("잘못된 테스트코드입니다.")
        case .failure(let error):
            result = error
            asyncTest.fulfill()
        }
    }
    
    wait(for: [asyncTest], timeout: 3)
    
    // then
    XCTAssertEqual(result, BoxofficeError.responseError)
}
```

2023-03-24 07:22 UTC, Andrew-0411 commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +            }
```swift
case .failure(_):
    XCTFail("잘못된 테스트코드입니다.")
}
```
- 테스트코드가 잘못되었을 때 테스트 실패를 나타내도록 XCTFail을 사용하였습니다

```swift
XCTAssertEqual(expectation, result)
```
- 그리고 then절에 예상값과 결과값을 비교하는 구문을 추가하였습니다.

2023-03-24 07:23 UTC, fatherLeon commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +    }
* 해당 테스트는 어떤것을 테스트하는지에 대한 생각을 잘 못 한것 같습니다.
* 처음에는 네트워크를 통한 작동이 가능한지?, 네트워크가 끊겨있다면 올바른 에러를 반환하는지에 대한 여부를 생각했었습니다
* 천천히 공부하다보니 `URLSessionDataTask`의 클로저가 제대로 작동하는지 여부에 대한 테스트를 진행해야한다는 것을 알게되고 위 요구사항을 지킬 수 있도록 테스트를 다시 작성하였습니다!!

2023-03-24 07:27 UTC, fatherLeon commented on BoxofficeInfoTests/TestModel/StubURLSession.swift
> +    let sessionDataTask = FakeURLSessionDataTask()
* 실패 `HTTPURLResponse`와 성공 `HTTPURLResponse`를 해당 변수를 통해 반환해주도록 만들기 위해서 필요했다고 생각합니다
* 다만, 지금은 `URLProtocol`을 상속받아 따로 구현을 하여

```swift
MockURLProtocol.requestHandler = { request in
    guard let url = request.url,
          url == APIType.boxoffice("20230322").receiveUrl() else {
        throw BoxofficeError.urlError
    }
    let response = HTTPURLResponse(url: url, mimeType: "application/octet-stream", expectedContentLength: 0, textEncodingName: nil)
    let data = StubBoxoffice().data
    
    return (response, data)
}
```

* 위와 같이 각각 테스트케이스에 맞춰 `HTTPURLResponse`를 주었습니다.

2023-03-24 07:28 UTC, fatherLeon commented on BoxofficeInfoTests/TestModel/MockBoxofficeInfo.swift
> +}
이 부분은 적절하지 않다 판단하여 삭제하고
저희가 앱 내부 모델에서 구현한 `BoxofficeInfo`를 직접 호출하여 사용하도록 변경하였습니다!

2023-03-24 07:35 UTC, Andrew-0411 commented on BoxofficeInfoTests/TestModel/StubURLSession.swift
> +    }
```swift
class MockURLProtocol: URLProtocol {
    
    static var requestHandler: ( (URLRequest) throws -> (HTTPURLResponse, Data) )?
    
    override class func canInit(with request: URLRequest) -> Bool {
        return true
    }
    
    override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        return request
    }
    
    override func startLoading() {
        guard let handler = MockURLProtocol.requestHandler else {
            fatalError("handler를 응답 받지 못하였습니다")
        }
        
        do {
            let (response, data) = try handler(request)
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: data)
            client?.urlProtocolDidFinishLoading(self)
        } catch {
            client?.urlProtocol(self, didFailWithError: error)
        }
        
    }
    
    override func stopLoading() {
        
    }
    
}
```
- URLProtocol을 사용하여 네트워크의 요청 결과에 따른 코드 동작을 테스트를 하였습니다
- MockURLProtocol을 구현하여 네트워크를 수행하는 객체(BoxofficeInfo)에 의존성 주입으로 URLSession을 넣어 구현하였습니다

2023-03-24 08:04 UTC, Andrew-0411 commented on BoxofficeInfoTests/TestModel/FakeURLSessionDataTask.swift
> +}
## Dummy
- 객체를 생성하거나, 함수를 호출할 때 필요하지만 실제로는 사용하지 않는 객체
- 해당 객체는 어떠한 메서드도 프로퍼티도 가지지 않으며 자리만을 차지합니다.
- Stub과 유사한 느낌이지만 값을 가지느냐 가지지 않느냐 / 사용되느냐 사용되지 않느냐의 차이에 따라 Dummy와 Stub이 나뉘어 지는 것 같습니다

## Fake
- 핵심 로직만 작성하고 나머지 불필요한 요소는 제거 된 객체
- 테스트를 할 때는 핵심기능을 제외하고 제거하는것을 Fake라고 한다
- 예를들어 `URLSessionDataTask`의 `resume`역할은 클로저를 실행시키는 것 이외에도 다른 역할을 서버와 연결을 하는 등 다른 역할도 하겠지만 단순히 클로저만 실행할 수 있도록 만들어야한다.

```swift
override func resume() {
    resumeDidCall()
}
```
* 위와 같이 만든다면 해당 객체는 Fake객체라고 볼 수 있을것 같습니다.

## Stub
- 가짜 객체지만 이미 정한 결과 값을 돌려줌으로써 테스트를 진행 할 수 있도록 한다
- 실제로 동작하는것처럼 특정 값을 되돌려주기 위해 만든 가짜 객체

## Mock
- 테스트 할 메소드를 위해 여러 원하는 동작을 할 수 있도록 만들어주는 객체

## Spy
- 구현된 객체에 메소드와 프로퍼티가 얼만큼 호출이 됐는지 등에 대해 기록하는 객체
- Stub과 유사하며 Stub을 통해 해당 객체를 생성할수도 있다.

- 행위 검증: 테스트가 참조하고 있는 객체의 메서드를 제대로 호출하는지에 대한 `행위`를 검증
- 상태 검증: 메서드가 실행될 때 연관되어 있는 객체의 `상태`를 검증함으로써 제대로 기능이 동작하고 있는지를 검증

2023-03-26 12:25 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +    func getUrl(interfaceValue: String) throws -> URL {
정확히 어떤 말인지 잘 이해가 안되네요. 여러가지 에러 타입을 반환하기 때문에 throws가 적절하지 못하다는건가요? 그렇다면 에러를 한번 래핑해서 하나의 타입으로 만들어 던지면 되지 않을까요? 

이부분에 대해서는 적어주신 코멘트만으로는 납득이 가지 않네요.

2023-03-26 12:25 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +            return boxofficeUrl
<img width="757" alt="image" src="https://user-images.githubusercontent.com/37682858/227775473-62341cf0-b1b1-407f-a501-10d31b0aa0fb.png">
`에러 핸들링 통일성`이 정확히 어떤걸 말하는지 잘 모르겠습니다.

2023-03-26 12:29 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
만약 1번 요청이 처리 중에 2번 요청이 와서 task가 바뀐 상황에서 1번 요청을 취소하려면 어떻게 해야하나요?
`URLSessionDataTask`를 리턴하고 사용하는 곳에서 판단하게 하면 어떨까요?

2023-03-26 12:30 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
`실제로 동작할때는 URLSession타입이 네트워크를 통해 데이터를 받을 수 있도록 만들어주기 때문에 필요하다고 생각합니다.` 이 말도 엄연히 따지면 틀린 말입니다.

결국 요청 자체는 네트워크에 하는 꼴이지만, `BoxofficeInfo`는 요청을 실제 네트워크에 하는지, 아니면 Mocking된 session에 하는지 모릅니다. 다만 `URLSession`에게 정보를 전달할 뿐이죠.

2023-03-26 12:36 UTC, 1Consumption commented on BoxOffice/Protocol/Fetchable.swift
> +}
`BoxofficeInfo`가 왜 제네릭 타입을 받아야하나요? 서로 다른 요청에 대한 다른 응답인데요. 역할 분리가 잘 되지 못한듯 합니다. 코드를 재사용할 수 있는 부분은 재사용을 하고, 역할에 의해 분리되어야할 부분은 잘 분리를 해보세요.

2023-03-26 12:38 UTC, 1Consumption commented on BoxofficeInfoTests/BoxofficeInfoTests.swift
> +            }
굳이 result를 저장할 필요 없이 success 내부에서 assert를 해도 좋겠습니다.

2023-03-26 12:39 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/FakeURLSessionDataTask.swift
> +}
그럼 mock과 stub의 차이는 뭔가요? 적어주신 내용만으로는 큰 차이를 못느끼겠습니다. 

> 테스트 할 메소드를 위해 여러 원하는 동작을 할 수 있도록 만들어주는 객체

☝️이 내용이 어떤걸 의미하는지 좀 더 자세히 설명해주시겠어요?

2023-03-26 12:40 UTC, 1Consumption commented on BoxofficeInfoTests/TestModel/StubURLSession.swift
> +    let sessionDataTask = FakeURLSessionDataTask()
프로토콜을 `채택`하는 것과 클래스를 `상속`받는 것은 엄연히 다릅니다. 용어 선택에 주의해주세요.

2023-03-26 12:56 UTC, 1Consumption requested changes
코멘트 확인 부탁드리겠습니다.

2023-03-26 12:56 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +}
이 객체가 너무 많은 역할을 합니다. 네트워킹도하고, 디코딩도 하고 있네요.

`네트워킹을 하는 객체`와 `어떤 요청을 보낼지, 그리고 네트워킹을 담당하는 객체를 사용해 data 타입을 디코딩하는(비즈니스 로직을 담당하는)` 객체로 나눠보세요.

지금 같은 경우는 어디로 요청을 보낼지, 그리고 해당 요청에 대한 응답으로 제네릭으로 받은 `T`를 디코딩 하는(비즈니스 로직을 다루는) 객체가 두개가 되겠네요.

2023-03-26 12:56 UTC, 1Consumption commented on BoxOffice/Model/DTO/BoxofficeDTO/BoxofficeResultObject.swift
> +    let movies: [InfoObject]
`Object`를 붙인 이유가 궁금합니다.

2023-03-26 12:56 UTC, 1Consumption commented on BoxOffice/ViewController.swift
>  }
당장 필요하지 않은 코드 같습니다. 지우는게 좋아보여요.

2023-03-26 12:56 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
> +    }
apiType을 가진 객체가 네트워킹하는 객체를 활용해 네트워킹을 하면 더 좋겠습니다.

2023-03-27 08:49 UTC, Andrew-0411 commented on BoxOffice/Model/DTO/BoxofficeDTO/BoxofficeResultObject.swift
> +    let movies: [InfoObject]
DTO라는걸 명확하게 하기위해서 Object를 뒤에 붙였습니다

2023-03-27 09:14 UTC, fatherLeon commented on BoxofficeInfoTests/TestModel/FakeURLSessionDataTask.swift
> +}
Stub은 객체 혹은 메소드의 동작과는 전혀 무관하게 예상 된 값만 반환합니다.
Mock의 경우 메서드 혹은 객체가 제대로 동작하고 있는지가 중요합니다.

> 테스트 할 메소드를 위해 여러 원하는 동작을 할 수 있도록 만들어주는 객체

입력이 주어진다면 그거에 맞도록 Mock이 예상한대로 동작한다는 의미로 썻습니다.

2023-03-28 12:13 UTC, Andrew-0411 commented on BoxOffice/Model/BoxofficeInfo.swift
> +            let task = URLSession.shared.dataTask(with: url) { data, response, error in
```swift
private var isRunningOnlyOneTask: Bool
func fetchData(handler: @escaping (Result<T, BoxofficeError>) -> Void) {
    if isRunningOnlyOneTask {
         cancelTask()
    }
}
```
- isRunningOnlyOneTask 통해 true이면 이전 Task를 취소하는 if문을 추가하였습니다

2023-03-28 12:20 UTC, fatherLeon commented on BoxOffice/Protocol/Fetchable.swift
> +}
```swift
struct NetworkModel: NetworkingProtocol {
    private let session: URLSession
    
    init(session: URLSession) {
        self.session = session
    }
}
```

* 네트워크 모델은 `URLSessionDataTask`를 생성하고 `resume`메소드를 통해 실행하는 역할 및 `URLSessionDataTask`를 반환하도록 구현하였습니다.

```swift
class BoxofficeInfo<T: Decodable> {
    private let apiType: APIType
    private let model: NetworkingProtocol
    private var task: URLSessionDataTask?
    //...
}
```
* `BoxofficeInfo`는 제너릭 타입을 받아 데이터를 디코딩하고 `NetworkingProtocol`타입을 가져서 `search`메소드를 실행하는 역할을 하도록 구현하였습니다.

2023-03-28 12:23 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
> +}
```swift
struct NetworkModel: NetworkingProtocol {
    private let session: URLSession
    
    init(session: URLSession) {
        self.session = session
    }
}
```

* `NetworkModel`은 네트워킹만 하도록 구현하였습니다.

```swift
class BoxofficeInfo<T: Decodable> {
    private let apiType: APIType
    private let model: NetworkingProtocol
    private var task: URLSessionDataTask?
    //...
}
```
* `BoxofficeInfo`는 제너릭 타입을 받아 데이터를 디코딩하고 네트워크 모델을 실행시켜주는 역할로 구현하였습니다.

2023-03-28 12:26 UTC, Andrew-0411 commented on BoxOffice/Model/BoxofficeInfo.swift
> +    }
APIType가진 BoxofficeInfo가 NetworkingProtocol을 통해 네트워킹을 하도록 하였습니다

2023-03-28 23:49 UTC, 1Consumption approved these changes
고생하셨습니다.
코드 품질이 훨씬 올라갔네요.👍

2023-03-28 23:49 UTC, merged