박스오피스 [STEP 2] 무리, Rowan
yagom-academy/ios-box-office pull request #16
Opened 2023-03-23 07:58 UTC by parkmuri

@junbangg 

🫡안녕하세요 알라딘:) 무리, Rowan 입니다 
STEP2와 도전스텝 진행하고 PR보냅니다~! 

## 고민한 점
### 1️⃣ DataManager 기능 분리
SOLID 단일 책임 원칙을 최대한 지키기 위해 추가적인 객체와 메서드를 정의했습니다.

-  `URLMaker` 객체: Query parameter로 사용할 데이터를 받아 URL을 만드는 객체. <br/> `dataTask()` 메서드를 사용하기 위해서는 요청을 보낼 `url`이 필요했습니다. `DailyBoxOffice`와 `MovieDetails`는 서로 다른 요청 url과 query문(query item)을 갖기 때문에 추후를 생각하여 활용 가능한 `URLMaker`타입을 구현하게 되었습니다.

-  `makeDataTask` 메서드: URLSession의 dataTask 메서드를 호출하는 기능(반복되는 코드를 줄이기 위해 정의하였습니다.)

-  `startLoad` 메서드: 어떤 데이터를 받을 지에 따라 parameter가 달라지기 때문에 2가지로 나누었습니다. 

</br>

### 2️⃣ Unit Test
TestDouble 객체를 처음 사용해보았습니다🤯

* `MockURLSession`
빠른 테스트를 위해 실질적 네트워크 통신 없이 통신이 성공한 경우와 실패한 경우의 동작을 임의로 작성하여 data/error가 잘 전달되는지 확인했습니다.

* `MockURLSessionDataTask`
`resume()`이 호출됐을 때, 실행될 클로저를 `resumeDidCall`이라는 프로퍼티에 담아 실행되도록 했습니다. 주입이 필요한 객체가 아니기 때문에 URLSessionDataTask 클래스를 상속받도록 하였습니다.

</br>

### 3️⃣ Error 타입 추가
테스트진행을 위해 구현하며 dataTask가 실패하는 경우의 수가 몇가지 있다고 판단하여 구현해놓은 error에 `request`, `server` case를 추가해주었습니다. 
- `case decode` : STEP1에서 구현해놓은 케이스로 `decodeFail`에서 리네이밍했습니다. 디코딩 실패 시 사용될 에러입니다.
- `case request` : dataTask에서 요청 실패 시 사용 될 에러입니다. 
- `case server` : dataTask의 Response의 statuscode가 성공이 아닐 시 (200대) 사용 될 에러입니다.

</br>

## 조언받고 싶은 점
### 1️⃣ dataTask()의 completionHandler 클로저 error 파라미터
[dataTask(with:completionHandler:)](https://developer.apple.com/documentation/foundation/urlsession/1407613-datatask)공식문서에는 다음과 같이 나와있습니다.
> **error**
An error object that indicates why the request failed, or nil if the request was successful.
- 저희가 이해한 바로는 request, 요청에 실패했다고 생각하여 에러타입을 `case request`로 정의하여 사용했습니다.
- error라는 파라미터에 담겨있는 Error는 어떤 오류가 담겨있는 것인지 확실하게 알고 싶은데 어떻게 확인할 수 있을까요?

</br>

### 2️⃣ URL 만들기
현재 URLMaker에서 메서드 parameter로 code와 data를 받고 있습니다. Test를 작성하다보니 `KobisAPI`라는 열거형을 만들게되었는데, 이걸 프로젝트에서 사용하는게 더 좋을지 아니면 지금처럼 객체를 통해서 만드는게 좋을지 알라딘은 어떻게 생각하시나요??🤔

2023-03-24 03:56 UTC, junbangg requested changes
수고하셨습니다~!

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/DataManager.swift
> +    private let kobisUrlSession: KobisURLSession
약어는 대문자로 하는게 어떨까요??? 취향차이라 꼭 바꾸실 필요는 없습니다

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/DataManager.swift
> +    func startLoadDailyBoxOffice(date: String, completion: @escaping (Result<DailyBoxOffice, Error>) -> Void) {
밑에것도 그렇게 메서드명을 startLoad 으로 하신 이유를 여쭤봐도 될까요?! 틀렸다는건 아닙니다

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/DataManager.swift
> +
밑에도 그렇고 불필요한 줄바꿈으로 보이긴하는데 의도하신걸까요?!

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let companys: [Company]
companies 가 맞을것 같아요!

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let peopleName, peopleEnglishName, castName, castEnglishName: String
한사람의 이름인거죠?? people 은 복수형이라 personName, 아니면 아예 그냥 name, englishName 로 해도 될것 같아요..! 

앗 뒤에 cast 도 있군요 근데 cast 붙은건 뭐져???🤔

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/URLMaker.swift
> +    }
보니까 enum 으로 케이스별로 잘 나누셨던데 
make 메서드 하나로는 재사용이 안될까요?

'makeURL(for serviceType: Service)'

요런 느낌으로다가

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/URLMaker.swift
> +    private enum Services {
복수형으로 이름을 지어주신 이유가 있을까요??

2023-03-24 03:56 UTC, junbangg commented on BoxOfficeTests/DataManagerTests/DataManagerTests.swift
> +    }
에러를 던지나요 여기서?!

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/DataManager.swift
> +    private let kobisUrlSession: KobisURLSession
흠
DataManager 는 굉장히 일반적인 이름으로 보이는데 (널리 재사용 가능해보이는) 


혹시 추후에 api 가 추가되는 상황을 고려해보셨을까요???

당장 바꾸자고 의견을 드린건 아닙니다!

2023-03-24 03:56 UTC, junbangg commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let staffs: [Staff]
Staffs 는 문법적으로 조금 어색해보여서 
그냥 staff 도 복수형으로 볼 수 있을것 같고 
staffList 도 나쁘지않을것 같아요!

2023-03-24 03:57 UTC, junbangg commented
저는 개인적으로 타입으로 하고 계신 방법 좋은거 같아요! 
Enum 은 테스트 과정에서 나온걸까요?? 테스트에 필요해서?🤔

2023-03-24 07:13 UTC, Kyeongjun2 commented on BoxOffice/Model/DataManager.swift
> +
저희 컨벤션으로 return 위에 같은 depth의 코드가 있을 경우 개행을 하기로 했습니다!

2023-03-24 09:11 UTC, parkmuri commented on BoxOffice/Model/DataManager.swift
> +    private let kobisUrlSession: KobisURLSession
`DataManager`를 `APIProvider`로 변경하며 `KobisURLSession`또한 `DataTaskMakeable`로 변경해주었습니다!
말씀해주신 약어가 `kobis`인지 `url`인지 확신하지못하여... 프로퍼티로 사용하는 url은 소문자로 그대로 사용하고, kobis는 추후에 API가 추가될 수 있는 상황을 생각하여 삭제하였습니다.

3cac0f4f3fb43ef644f5d90d6d627b7452194617

2023-03-24 09:14 UTC, parkmuri commented on BoxOffice/Model/DataManager.swift
> +    func startLoadDailyBoxOffice(date: String, completion: @escaping (Result<DailyBoxOffice, Error>) -> Void) {
- [공식문서](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)에 나와있는 `startLoad()`를 참고하여 같은이름의 메서드로 사용하게 되었습니다!

2023-03-24 14:06 UTC, Tediousday93 commented on BoxOfficeTests/DataManagerTests/DataManagerTests.swift
> +    }
에러를 던지지 않아서 `setUp()`, `tearDown()`으로 변경하였습니다!

2023-03-24 14:09 UTC, Kyeongjun2 commented on BoxOffice/Model/URLMaker.swift
> +    private enum Services {
`kobisService`로 변경하였습니다 ㅎㅎ..😅

2023-03-24 14:11 UTC, parkmuri commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let staffs: [Staff]
다른 프로퍼티 모두 단순한 복수형으로 사용하고있어 `staff`로 사용하기로했습니다!

2023-03-24 14:12 UTC, Kyeongjun2 commented on BoxOffice/Model/URLMaker.swift
> +    }
API 관리 객체를 나누다 보니 URLMaker를 삭제하고 EndPoint라는 객체에서 URLRequest를 만들어주도록 변경되었습니다.. 너무 많이 바뀌어서 확인하기 힘드실 것 같아요... 죄송합니다!!! 🫡

```swift
struct EndPoint {
    func request(for api: API) -> URLRequest? {
        var urlComponents = URLComponents(string: api.baseURL + api.path)
        urlComponents?.queryItems = []
        
        for (key, value) in api.queries {
            let queryItem = URLQueryItem(name: key , value: value)
            
            urlComponents?.queryItems?.append(queryItem)
        }
        
        guard let url = urlComponents?.url else { return nil }
        
        return URLRequest(url: url)
    }
}
```

enum case 로 관리하는 것은 KobisService 종류만 관리하고 있습니다.

2023-03-24 14:17 UTC, parkmuri commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let peopleName, peopleEnglishName, castName, castEnglishName: String
한 사람의 이름이여서 모두 `person~`으로 바꾸어주었습니다🥹...!
cast는 영화나 연극에서의 배역을 뜻하는 단어로, 영화 내 배우가 맡은 배역의 이름으로 사용되고있습니다!

2023-03-27 10:16 UTC, junbangg commented on BoxOffice/Model/URLMaker.swift
> +    }
죄송하긴요..! 고민의 흔적이 아주 느껴지는군요👍👍

2023-03-27 10:21 UTC, junbangg approved these changes
바뀐게 많네요!? 아주 수고많으셨습니다~ 고민의 흔적이 많이 느껴졌습니다~

2023-03-27 10:21 UTC, junbangg commented on BoxOffice/Model/JSONModel/MovieDetails.swift
> +    let nationName: String
이름에서 다소 중복적인 느낌이 있네요! 타입명이미 Nation 이다보니!

2023-03-27 10:21 UTC, junbangg commented on BoxOffice/Network/APIProvider.swift
> +    private let endPoint = EndPoint()
요것은 주입시키는게 어떨까요??
만약에 안하신 특별한 이유가 있다면 설명 한번 부탁드려요!

2023-03-27 10:21 UTC, junbangg commented on BoxOffice/Network/APIProvider.swift
> +    init(urlSession: DataTaskMakeable = URLSession(configuration: .default),
변경된거 좋군요👏👏

2023-03-27 10:22 UTC, merged