박스오피스 [STEP 2] 혜모리, 크리스티
yagom-academy/ios-box-office pull request #20
Opened 2023-03-23 14:32 UTC by christy-hs-lee

@havilog

안녕하세요 하비!
STEP 2 PR 보내드립니다.
URLSession 구현하면서 테스트를 작성해보았는데 굉장히 어려웠습니다...🥲

---
## 고민했던 점
### 1️⃣ Decoder 객체 수정

- Asset의 JSON 파일은 이후 다루지 않기때문에 data라는 매개변수를 받아 디코드 해주는 방식으로 변경하였습니다.
- data에 문제가 있는 경우와 type에 문제가 있는 경우를 구분하기 위하여 `Result` 타입을 이용하여 오류를 던져주는 방식을 채택하였습니다.

``` swift
struct FileDecoder {
    func decodeData<T: Decodable>(_ data: Data?, type: T.Type) -> Result<T, NetworkingError> {
        guard let data = data else { return .failure(.dataNotFound) }
        // 없는 data인 경우 dataNotFound 에러
        
        if let result = try? JSONDecoder().decode(type, from: data) {
            return .success(result)
        } else {
            return .failure(.decodeFailed)
            // 잘못된 타입으로 디코딩에 실패한 경우 decodeFailed 에러
        }
    }
}
```

### 2️⃣ data task 에러처리

- **에러 코드에 대한 오류 처리**

``` swift
guard (200...299).contains(httpResponse.statusCode) else {
    switch httpResponse.statusCode {
    case 400...499:
        completion(.failure(NetworkingError.clientError))
    case 500...599:
        completion(.failure(NetworkingError.serverError))
    default:
        completion(.failure(NetworkingError.unknownError))
    }

    return
}
```

- `HTTPURLResponse`를 통해 응답을 받을 때 발생할 수 있는 에러 타입을 세분화 시켰습니다. `switch`를 사용하여 각 에러 타입에 대한 `case`를 만들어 주었습니다. 

</br>

- **data decoding 실패에 대한 오류 처리**

``` swift
guard let data = data,
      let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
    completion(.failure(NetworkingError.dataNotFound))

    return
}
```

- data가 nil이거나 디코딩에 실패하면 `dataNotFound` 에러를 던져줍니다.

### 3️⃣ protocol 사용
Mock 테스트를 진행하기 위해 `URLSessionProtocol`, `URLSessionDataTaskProtocol`프로토콜을 구현하였습니다. 
프로토콜을 사용하여 의존성을 주입시키고 코드의 범용성을 높여주고, extension으로 
`URLSession`, `URLSessionDataTask`에 각 프로토콜을 채택한 후 기본 구현을 해주었습니다.

```swift
// MARK: - URLSessionProtocol
protocol URLSessionProtocol {
    func dataTask(with url: URL, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol
}

extension URLSession: URLSessionProtocol {
    func dataTask(with url: URL, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
        return dataTask(with: url, completionHandler: completionHandler) as URLSessionDataTask
    }
}

// MARK: - URLSessionDataTaskProtocol
protocol URLSessionDataTaskProtocol {
    func resume()
}

extension URLSessionDataTask: URLSessionDataTaskProtocol {}
```

2023-03-23 16:32 UTC, havilog requested changes
테스트에 대한건 일단 나중에 고민하고 .. ㅎㅎ
네트워크 객체에 집중해서 주말동안 코멘트 남긴 부분 수정해보시면 좋을거 같아요 : )

2023-03-23 16:32 UTC, havilog commented on NetworkMockTests/NetworkManagerTests.swift
> +//
BoxOfficeTest 폴더 안에 생성하지 않고, 밖에 생성하신 이유가 있을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +struct FileDecoder {
이름은 FileDecoder인데, 실제 행동은 네트워크 에러를 뱉는 디코딩을 하고있네요

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +    func decodeData<T: Decodable>(_ data: Data?, type: T.Type) -> Result<T, NetworkingError> {
data가 nil인걸 디코더에서 검증해야할 작업일까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +    func decodeData<T: Decodable>(_ data: Data?, type: T.Type) -> Result<T, NetworkingError> {
```suggestion
    func decode<T: Decodable>(data: Data, type: T.Type) -> Result<T, Error> {
```

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +        }
에러를 throw로 뱉어줄 수도 있을거 같은데, try? 를 활용해서 Result로 반환하신 이유가 뭘까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +import UIKit
Decode하는 로직에 UIKit이 임포트 되어있을 필요가 있을까용?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +class NetworkManager {
이 객체를 상속할 일이 있을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +    let session: URLSessionProtocol
해당 프로퍼티를 외부에서 접근해야할일이있을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
URLSession의 shared객체는 어떤 역할을 하는지 알고계신가요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +        guard let url = url else { return }
에러 안 떤저도 될까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +            }
어떤 에러가 왔는지 검증할 고민은 해보셨을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +            }
여기도 마찬가지로 에러 안떤져도 될까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +            }
다른 객체로 분리할 생각 해보셨을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
링크 보냈던 의존성주입은 생각해보셨을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
decode()의 결과값인 Result에서 받은 error는 어디에서 처리해주고 있는걸까용?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/NetworkingError.swift
> +}
에러를 설명하기 위한 CustomStringConvertible같은 프로포콜을 준수하는 것은 고려해보셨을까용?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/URLMaker.swift
> +    static var baseURL = "https://kobis.or.kr/kobisopenapi/webservice/rest"
여러 개의 도메인
ex. www.naver.com & www.google.com
에 대한 URL을 어떻게 처리하면 좋을 지 고민해보셨을까요?

2023-03-23 16:32 UTC, havilog commented on BoxOffice/Network/URLMaker.swift
> +    }
method를 post로 보내는 API가 생길경우 인코딩을 어떻게 할까요?

2023-03-24 09:03 UTC, christy-hs-lee commented on BoxOffice/Decoder/FileDecoder.swift
> +struct FileDecoder {
네트워크 디코딩의 의미로 `NetworkDecoder`로 수정했습니다!

2023-03-24 09:03 UTC, christy-hs-lee commented on BoxOffice/Decoder/FileDecoder.swift
> +    func decodeData<T: Decodable>(_ data: Data?, type: T.Type) -> Result<T, NetworkingError> {
코멘트 참고하여 수정했습니다! 감사합니다!

2023-03-24 09:04 UTC, hyemory commented on NetworkMockTests/NetworkManagerTests.swift
> +//
BoxOfficeTests는 BoxOffice 타입에 대한 테스트이고, NetworkMockTests는 Network에 대한 통신으로 생각해서 파일을 나누었었는데
말씀을 듣고 폴더 구조를 생각해보니 BoxOfficeTests는 BoxOffice 프로젝트에 대한 테스트라고 생각되어 같은 폴더로 이동하였습니다. 😊

2023-03-24 09:05 UTC, christy-hs-lee commented on BoxOffice/Decoder/FileDecoder.swift
> +import UIKit
`import Foundation`만 사용하도록 수정했습니다!

2023-03-24 09:08 UTC, christy-hs-lee commented on BoxOffice/Network/NetworkManager.swift
> +    let session: URLSessionProtocol
접근제어 수정했습니다!

2023-03-24 09:08 UTC, hyemory commented on BoxOffice/Decoder/FileDecoder.swift
> +    func decodeData<T: Decodable>(_ data: Data?, type: T.Type) -> Result<T, NetworkingError> {
아래 코멘트에서 힌트 주신대로 중복되는 data nil 체크 로직은 제외하였습니다. 👍

2023-03-24 09:13 UTC, christy-hs-lee commented on BoxOffice/Network/NetworkManager.swift
> +        guard let url = url else { return }
URL에 대한 에러 `completion(.failure(NetworkingError.invalidURL))`를 던져주는 방향으로 수정했습니다!

2023-03-24 09:14 UTC, hyemory commented on BoxOffice/Decoder/FileDecoder.swift
> +        }
Data에 대한 검증은 외부에서 하고있고, 실패하게 된다면 대체로 type 문제로 인한 오류라고 생각했습니다.
실행하고 있는 `decode` 메서드가 성공 또는 실패, 2갈래로 나누어도 무방하다는 생각이 들어 `Result`로 반환 시켰습니다.

2023-03-24 09:15 UTC, hyemory commented on BoxOffice/Network/NetworkManager.swift
> +class NetworkManager {
final 키워드를 붙여주었습니다! 👍

2023-03-24 09:18 UTC, christy-hs-lee commented on BoxOffice/Network/NetworkManager.swift
> +            }
해당 부분은 `httpResponse.statusCode`를 통해 에러를 던지는 switch문과 하나로 묶어 에러를 검증할 수 있도록 수정했습니다.

2023-03-24 09:20 UTC, hyemory commented on BoxOffice/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
[shared](https://developer.apple.com/documentation/foundation/urlsession/1409000-shared) URLSession의 task 생성에 대한 기본 싱글톤 객체입니다. 
간단한 로직인 경우 URLSession의 메서드를 간편하게 사용할 수 있게해줍니다.
그러나 delegate나 configuration을 사용하려면 custom URL session을 구현해 주어야 합니다!

2023-03-24 09:23 UTC, hyemory commented on BoxOffice/Network/NetworkManager.swift
> +            }
NetworkingError 타입에 해당 에러를 받을 수 있는 transportError 케이스를 만들어 주었습니다.

``` swift
if let error = error {
    completion(.failure(NetworkingError.transportError(error)))
    
    return
}
```

이후 에러 처리할 때 어떤 오류인지 알 수 있도록 출력 등의 방법으로 노출시킬 계획입니다.

2023-03-24 09:31 UTC, christy-hs-lee commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
decode()의 결과값으로 성공과 실패, 단 두가지 경우만 존재하므로 
`NetworkManager`에서 try?로 받아 실패를 `nil`값으로 처리하도록 했습니다.
추후 decode가 필요한 다른 부분에서 사용할 때 필요시 `failure`에 대한 처리를 위해 현재와 같이 구현했습니다!

2023-03-24 09:32 UTC, hyemory commented on BoxOffice/Network/NetworkingError.swift
> +}
에러의 설명을 description에 담아주었습니다! 감사합니다

``` swift
enum NetworkingError: Error, CustomStringConvertible {
    case decodeFailed
    case dataNotFound
    case clientError
    case serverError
    case unknownError
    case invalidURL
    case transportError(Error)
    
    var description: String {
        switch self {
        case .decodeFailed:
            return "디코딩 실패"
        case .dataNotFound:
            return "찾을 수 없는 데이터"
        case .clientError:
            return "클라이언트 오류 (코드 : 400~499)"
        case .serverError:
            return "서버 오류 (코드 : 500~599)"
        case .unknownError:
            return "알 수 없는 오류"
        case .invalidURL:
            return "잘못된 URL"
        case .transportError(let error):
            return "통신 오류 - \(error)"
        }
    }
}
```

2023-03-24 09:36 UTC, christy-hs-lee commented on BoxOffice/Network/URLMaker.swift
> +    static var baseURL = "https://kobis.or.kr/kobisopenapi/webservice/rest"
도메인이 두개 이상 받는 경우가 생긴다면 `URLMaker`를 인스턴스로 만들어 초기화하고 내부의 메서드를 이용해 URL을 만들 수 있을 것 같습니다!

2023-03-25 02:54 UTC, havilog commented on BoxOffice/Decoder/FileDecoder.swift
> +        }
근본적으로 `NetworkDecoder`라는 아이의 역할에 대한 고민이 필요할 거 같은데요,
네트워크 리퀘스트를 보내서 받은 데이터에 대한 디코딩을 어떠한 로직을 가지고 수행하는 아이라고 생각하는데,
지금은 따로 로직이 있어보이지는 않아요.

뭔가 글로 설명하기 힘든데 ,,,
디코더는 디코딩 해서 어떠한 모델을 넘겨주거나, error를 넘겨주는 행위만 하면 될거 같고,
그 동작은 JSONDecoder에서 try-catch로 이루어져서,
NetworkDecoder의 decode함수도 try-catch로 구현되는게 더 자연스러운 시그니쳐 같아요!

틀렸다는건 아니긴 한데, 굳이 안해도 될 작업인 느낌이랄까요..?
해당 결과를 Result값으로 변환하는건 NetworkDecoder를 사용하는 Networking 객체에서 해도 될거 같아요.

2023-03-25 02:56 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
요 내용은 조금더 깊게 설명할 수 있으시면 면접 때 더 도움될 거 같아요. 

shared의 Limitation이랑,
<img width="764" alt="image" src="https://user-images.githubusercontent.com/57659933/227685513-61d72ade-bfc3-49cb-8f3c-853a5a6e2fee.png">

default, ephemeral, background configuration의 각각 특징이랑 언제 사용해야하는지 등 읽어보시면 좋을 거 같아요.

2023-03-25 02:57 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +            }
외부로 던져서 핸들링하는 방법도 있겠지만,
네트워크 에러나 세션에러 같은 경우에는 네트워킹 객체에서 한 번 핸들링해주는 방법도 있을거 같아요.

2023-03-25 03:01 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +            }
`메서드의 인스턴스를 생성하는 것으로 이해`라는 말을 제가 잘 이해하지 못했는데요,
``` swift
struct NetworkErrorHandler: ErrroHandlable {
func handle(error: Error) -> NetworkError {
// ... do some error handling
}
```

과 같은 역할을 하는 객체를 만들고,
해당 객체를 NetworkManager에서 가지고 있고,
리퀘 찔렀을 때 내려오는 에러에 대한 핸들링을
에러 핸들러 객체에 전담해주는 식으로 코드를 작성하면
NetworkManager의 역할이 분리되서, 각각의 역할이 명확해지고,
request내부의 코드가 짧아져서 읽기 쉬워질거 같아요.

2023-03-25 03:04 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
request함수를 test하려면 FileDecoder의 로직까지 테스트가 같이 진행되어야해요.
만약 디코딩에 대한 로직에 전혀 관계 없이 테스트를 하고 싶더라도(무조건 디코딩은 성공한다는 가정을 하고) request가 FileDecoder에 의존하고 있기 때문에 불가능해요.
따라서 FileDecoder를 init시점에 주입받고, 프로퍼티로 들고 있고 해당 프로퍼티를 들고있으면 될거같아요.
주입 받을 때는 프로토콜 타입으로 주입받아야할거 같구요.

2023-03-25 03:06 UTC, havilog commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
위 코멘트에도 작성했지만,

// data에 대한 존재 유무 확인 -> 없으면 데이터없음 에러
// 디코딩 성공 실패 유무 확인 -> 실패했으면 디코딩 에러

의 형태로 되는게 좋을거 같아요.

위 로직은 두가지 역할이 하나의 가드문에서 이루어지고 있어서요!

2023-03-25 03:06 UTC, havilog commented on BoxOffice/Network/URLMaker.swift
> +    static var baseURL = "https://kobis.or.kr/kobisopenapi/webservice/rest"
해당 부분도 고려되어서 처음 작성할 때 확장성 있는 객체가 되면 더 좋을거 같다고 생각합니다~

2023-03-25 03:09 UTC, havilog commented on BoxOffice/Network/URLMaker.swift
> +    }
get했을 때 parameter encoding만 가능하게 구현되어 있는거 같아서,
post나 다른 method로 보내는 경우를 고려해보셨는지가 궁금했고,

또한 parameter encoding / json encoding에 대한 고민이 있으셨는지 궁금했어요!

위 코멘트와 마찬가지로 처음 객체를 설계할  때부터 해당 기능을 고려해보고 구현하는게 좋을거 같아요

2023-03-27 09:37 UTC, hyemory commented on BoxOffice/Network/NetworkManager.swift
> +                  let dataStructure = try? FileDecoder().decodeData(data, type: type).get() else {
각각 다른 에러를 던지도록 우선 수정하였습니다!

``` swift
guard let data = data else {
    completion(.failure(NetworkingError.dataNotFound))
    
    return
}

guard let dataStructure = NetworkDecoder().decode(data: data, type: type) else {
    completion(.failure(NetworkingError.decodeFailed))
    
    return
}
```

2023-03-28 03:32 UTC, hyemory commented on BoxOffice/Decoder/FileDecoder.swift
> +        }
객체들의 역할을 고민해보고 `NetworkDecoder`는 특별한 역할을 하고있지 않아 삭제했습니다.
그리고 `NetworkManager`의 메서드를 분리해 보았습니다! 
9e4e620fc4e74e2a204f63c866d5cd2d60de3961

2023-03-28 03:32 UTC, hyemory commented on BoxOffice/Network/URLMaker.swift
> +    static var baseURL = "https://kobis.or.kr/kobisopenapi/webservice/rest"
추후 리팩토링 진행해 보겠습니다!

2023-03-29 14:25 UTC, merged