박스오피스 [STEP 3] sehong
yagom-academy/ios-box-office pull request #21
Opened 2023-03-28 04:54 UTC by sehoong0429

#step3
@AppleCEO
안녕하세요 도미닉!
step3 PR올립니다!ㅎㅎ 

collectionView가 아직은 다루기 어려운 것 같습니다..🥲
이번 스텝도 잘 부탁드리겠습니다🙇🏻‍♀️ 

## 고민 및 구현한 내용 

### 1️⃣ 날짜가 제대로 출력되지 않았던 문제 

박스오피스 화면 목록 구성은 `어제`를 기준으로 `targetDt`를 생성해주어야합니다. 오늘 날짜를 기준으로 어제 날짜를 만들어주는 createFormattedData() 함수를 구현해주었는데 해당 함수는 원하는 형식의 dataFormat을 넣어주면 어제날짜로 원하는 형식의 String을 반환해줍니다. 
```swift
private func createFormattedDate(dateFormat: String) -> String? {
        let dateFormatter = DateFormatter()
        let today = Date()
        dateFormatter.dateFormat = dateFormat
        guard let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: today) else { return nil }
        return dateFormatter.string(from: yesterday)
    }
```

위의 함수를 사용해서 navigationBar에 날짜를 표시하거나 데이터를 받아왔는데 
날짜가 이상한 형태로 출력되거나 데이터가 출력되기도 하고 빈배열이 담기기도 하는 문제가 발생했는데(ㅠㅠ)
이건 제가 `createFormattedDate(dateFormat: "yyyyMMdd")` 라고 작성하지 않고 분을 나타내는 `mm`으로 넣어서 발생하는 문제였습니다..🥲

### 2️⃣ createStateLabel 함수

영화의 순위 변동에 따라 상태 레이블을 생성해주는 함수 

영화진흥위원회API에서 확인할 수 있는 rankOldandNew(랭킹에 신규진입여부)와 rankInten(전일대비 순위의 증감분)을 매개변수로 받아주었습니다. 

1. rankOldandNew가 “Old”인 경우에는 아래 세 조건이 들어갑니다.
 
    -  변동 없으면 "-"
    -  순위 상승 : 빨간 화살표 + 등락 편차  ▲
    -  순위 하락 : 파란 화살표 + 등락 편차  ▼

2. rankOldandNew가 “New”인 경우에는 “신작”으로 표시해줍니다.

```swift
private func createStateLabel(rankOldandNew: String, rankInten: Int) -> NSMutableAttributedString {
        let attributedString = NSMutableAttributedString()
        
        if rankOldandNew == "OLD" {
            if rankInten == 0 {
                attributedString.add(string: "-")
            } else if rankInten > 0 {
                attributedString.add(string: "▲", color: .systemRed)
                attributedString.add(string: "\(rankInten)")
            } else {
                attributedString.add(string: "▼", color: .systemBlue)
                attributedString.add(string: "\(-rankInten)")
            }
        } else {
            attributedString.add(string: "신작", color: .systemRed)
        }
        
        return attributedString
        
}
```

또한 새로운 NSAttributedString을 만들어 주어진 속성으로 초기화한 다음, 
기존의 NSMutableAttributedString에 추가하고 반환할 수 있도록 extension을 구현하여 위와 같이 편리하게 원하는 문자열을 추가할 수 있습니다. 

```swift
extension NSMutableAttributedString {
    
    @discardableResult
    func add(
        string: String,
        font: UIFont = .systemFont(ofSize: 12),
        color: UIColor = .label
    ) -> NSMutableAttributedString {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color
        ]
        
        append(NSAttributedString(string: string, attributes: attributes))
        
        return self
    }
    
}
```

### 3️⃣ 새로고침을 위한 configureRefreshControl 메서드

사용자가 리스트를 아래로 잡아끌어서 놓으면 리스트를 새로고침 할 수 있어야합니다. 또한 로드중일때는 로드중임을 알 수 있도록 구현해야하는데, 이는 `UIRefreshControl()`을 이용해 구현해주었습니다.

```swift
private func configureRefreshControl() {
        collectionView.refreshControl = UIRefreshControl()
        collectionView.refreshControl?.addTarget(self, action: #selector(handleRefreshControl), for: .valueChanged)
        collectionView.refreshControl?.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
    }
    
@objc private func handleRefreshControl() {
        fetchBoxOfficeData()
}
```

또한 fetchBoxOfficeData() 함수에서 새로고침 컨트롤을 종료하고 있습니다. 그 이유는 `데이터를 가져오는 작업이 완료되면 새로고침을 멈추고 사용자에게 업데이트된 데이터가 표시되었음`을 알려주기 위해서입니다. 

fetchBoxOfficeData() 함수는 비동기적으로 박스 오피스 데이터를 가져오기 때문에, 데이터 요청이 시작되면 새로고침 컨트롤이 활성화되어 화면에 표시됩니다. 데이터를 성공적으로 가져오거나 요청이 실패한 경우에 멈춰야하기 때문에 함수의 마지막 부분인 메인 스레드에서 새로고침을 종료하는 작업을 수행해주고 있습니다.

```swift
DispatchQueue.main.async {
    self.collectionView.refreshControl?.endRefreshing()
}

```

### 4️⃣ Compositional Layout
`Compositional Layout`을 사용하여 UICollectionView의 레이아웃을 구성해주었습니다. 
이를 사용하면 레이아웃 구성 요소를 계층적으로 구성할 수 있어 다양한 레이아웃을 구현할 수 있습니다! 
저는 `list`형식의 레이아웃으로 구현해보았습니다. 

```swift
 private func createLayout() -> UICollectionViewLayout {
        let config = UICollectionLayoutListConfiguration(appearance: .plain)
        return UICollectionViewCompositionalLayout.list(using: config)
    }
```

2023-03-28 14:58 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@sehoong0429 고생하셨습니다!
이번 스텝도 어려웠을텐데 잘해내셨네요~
몇가지 고민할 점들 남겨봤습니다.
확인해주시고 이해 안가는 것 있으면 편하게 말씀해주세요.

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/Extensions/Int+decimal.swift
> +}
이렇게 extension 으로 구현하는 것과 IntFormatter 와 같은 이름의 구조체를 만들어서 같은 코드의 함수를 만들어서 사용하는 것은 어떤 차이가 있을지 고민해보시겠어요?
그리고 각각 어떤 장단점이 있을까요?

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/Extensions/String+NSMutableAttributed.swift
> +    ) -> NSMutableAttributedString {
한 줄로 작성하도록 수정해보시겠어요? 어떤 것이 보기 좋을까요?

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/MovieListCell.swift
> +        }
로직이 꽤 복잡해보이는데요.
이프와 엘스가 반복되어서 그렇습니다.
더 간단하게 보이게 개선해 볼 수 있을까요?

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                    let myMovielists = boxOfficeItem.boxOfficeResult.dailyBoxOfficeList.map { ListItem(rank: $0.rank, rankInten: $0.rankInten, rankOldandNew: $0.rankOldAndNew.rawValue, movieName: $0.
$0 이 너무 많이 나오네요.
풀어서 써서 누가 읽어도 쉽게 읽을 수 있는 코드가 좋은 코드입니다.

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        guard let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: today) else { return nil }
3줄로 풀어서 쓰는 것이 좋겠습니다.
저는 특별한 경우가 아니면 기본형으로 풀어서 사용합니다.
guard let 구문인 것을 알더라도 빠져나가는 코드를 보려면 바로 밑에 줄을 보는 것보다 오른쪽 끝까지 가서 찾아야하는 것이 힘들기 때문입니다.

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        guard let yesterday = createFormattedDate(dateFormat: "yyyy-MM-dd") else { return }
저는 이런 부분이 다 세줄로 풀어서 쓰면 더 좋아보이네요 ;;
어떻게 생각하실까요? 이런 부분은 스타일의 문제고 저도 가끔은 한 줄로 쓰기는 합니다.

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        collectionView.refreshControl?.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
옵셔널 체이닝보다 어차피 제일 위에 줄에서 가져오니 옵셔널 바인딩을 해서 사용하면 좋겠네요!
예전에 들었는데 당근마켓에서는 두번 반복되더라도 반복을 줄이고자 노력한다고 합니다.
collectionView.refreshControl? 이 반복되어서 옵셔널 바인딩으로 상수에 넣어서 사용하면 어떨까요?

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
>  }
저는 이러한 extension 을 만드는 것을 선호하지는 않습니다.
이 기능이 필요하지 않은 다른 뷰컨트롤러에도 기능이 추가되어서 불필요한 추가가 발생할 수도 있다고 생각해서인데요.
이러한 코드를 필요한 뷰컨트롤러에만 추가하는 것과 extension 으로 모든 뷰컨트롤러에 추가하는 것 어떤 차이와 장단점이 있을까요?

2023-03-28 14:58 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +}
하나의 프로토콜에 필요한 코드를 extension 으로 묵어놓으신 것 좋습니다! 💯 
저는 위 아래 공백이 조금 어색하게 보이네요.
이전에 적었던 것처럼 코드가 떠있는 것처럼도 느껴지기도 합니다~

2023-03-29 00:27 UTC, sehoong0429 commented on BoxOffice/Extensions/Int+decimal.swift
> +}
`extension Int` 로 구현하면 
 
`장점`: Int 타입에 직접 메서드를 추가하는 구조라 사용할때 별도의 인스턴스 생성이나 구조체 호출 없이 코드를 간결하게 유지하고 관련 기능을 타입에 직접 추가하기때문에 코드의 응집도를 높이거나 가독성을 향상 시킬 수 있습니다.

`단점`: 지금과 같이 하나가 아니라 확장이 너무 많아 졌을때는 오히려 코드 관리가 어려워질 수 있을 것 같습니다. 

`IntFormatter`로 구현하면 

`장점`: 독립적인 구조체로 작성되어 있어 코드 관리가 용이하고 의존성이 낮아집니다.
`단점`: 기능을 사용하기 위해 별도의 인스턴스를 생성해야할 수 있으며, 코드가 길어질 수 있습니다. 
하지만 제가 구현한 extension Int의 함수를 그대로 사용한다면 별도의 인스턴스 생성없이도 코드를 작성할 수 있습니다. 

```swift
struct IntFormatter {
    
    static func decimalString(for value: Int) -> String? {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        return numberFormatter.string(for: NSNumber(value: value))
    }
    
}
```

이렇게 찾아보고 구현을 해보니 현재는 구조체를 구현하는 부분과 extentsion Int의 경우에 큰 차이가 없어보이지만, 프로젝트가 커진다면 차이가 생길 것 같습니다. 저같은 경우는 코드의 간결성과 편의성을 유지하고 구현했던 것 같습니다.

2023-03-29 00:35 UTC, sehoong0429 commented on BoxOffice/Extensions/String+NSMutableAttributed.swift
> +    ) -> NSMutableAttributedString {
```swift
func add(string: String, font: UIFont = .systemFont(ofSize: 12), color: UIColor = .label) -> NSMutableAttributedString {
```
한줄로 작성하는 경우 위와 같이 작성할 수 있습니다. 
제가 처음에 작성한 방식은 매개변수가 하나씩 나열되어있고 기본값을 각각 하나씩 확인할 수 있어서 값이 많거나 복잡한 경우에 유용하다고 볼 수 있을 것 같습니다. 코드를 읽을 때 한 줄로 작성하게 되면 깔끔해 보이는 것 같습니다. 

도미닉이 수정해주신 제안처럼 한줄로 작성하는 경우는 받아 올 매개변수가 적고 간단한 경우에 훨씬 좋을 것 같습니다. 해당 부분 참고하여 함수 작성해보도록 하겠습니다!

2023-03-29 00:49 UTC, sehoong0429 commented on BoxOffice/MovieListCell.swift
> +        }
해당 부분 수정해보았습니다..! 
switch문을 사용해보았습니다!
[6c7302c](https://github.com/yagom-academy/ios-box-office/pull/21/commits/6c7302cb51008c1b51d59436b818fe3bc9db6cf4)

2023-03-29 00:56 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                    let myMovielists = boxOfficeItem.boxOfficeResult.dailyBoxOfficeList.map { ListItem(rank: $0.rank, rankInten: $0.rankInten, rankOldandNew: $0.rankOldAndNew.rawValue, movieName: $0.
for 루프를 사용하여 myMovieLists를 생성하는 방식으로 바꾸었습니다.
코드가 길더라도 읽는 사람이 이해할 수 있는 코드를 작성한다고 생각하고 작성해보도록 하겠습니다ㅠㅠ! [3acfffa](https://github.com/yagom-academy/ios-box-office/pull/21/commits/3acfffa5e2d110955410ae11cc81261f0d2331e4)

2023-03-29 01:12 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        guard let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: today) else { return nil }
[f4cbad8](https://github.com/yagom-academy/ios-box-office/pull/21/commits/f4cbad8b41657a71c9638ae79508acccf1f1ec19)
해당 부분 100자가 넘어가서 else { return } 부분을 띄워주는걸로 수정하였습니다.

2023-03-29 01:12 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        guard let yesterday = createFormattedDate(dateFormat: "yyyy-MM-dd") else { return }
조언해주신대로 너무 길어지면 보기 힘들기때문에 100자를 기준으로 세줄로 풀어쓰는 기준을 잡아보았습니다!

2023-03-29 01:17 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        collectionView.refreshControl?.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
[0b39917](https://github.com/yagom-academy/ios-box-office/pull/21/commits/0b39917b7931932a4522afc515d263c1db1a653d)
알려주신방식대로 수정하였더니 반복을 줄이고 코드를 더 깔끔하게 만들 수 있었습니다!

2023-03-29 01:27 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
>  }
저는 해당 extension viewController에서는 필요한 기능을 viewController에 추가하여 DataSource 관련된 기능을 관리하고 있었습니다. 

- 장점 extension을 사용하면 관련된 기능들을 묶어서 관리할 수 있어 코드의 가독성이 높아집니다.
서로 다른 기능들이 섞이지 않고 독립적으로 작성될 수 있어 코드를 이해하고 수정하기 쉬워집니다.

- 단점 extension을 과도하게 사용하면 코드 구조가 복잡해질 수 있습니다.
같은 클래스 내에서 너무 많은 extension이 사용되면, 전체 코드의 흐름을 파악하기 어려워질 수 있습니다.

코드를 관리하는 측면에서는 extension이 더 나을 수도 있지만 
지금은 viewController 내에서는 따로 구분 할 필요가 없을 것 같다고 느껴집니다.
extension의 장점과 단점을 비교하고 [ee38557](https://github.com/yagom-academy/ios-box-office/pull/21/commits/ee38557c72ecd0f2e501bd0d9bf2b537a521d1bc) 해당 부분은 합쳐주었습니다. 조언 감사합니다!

2023-03-29 01:33 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +}
extension 위아래를 공백을 주는 컨벤션을 유지하고 있었습니다! 
컨벤션에 대한 기준을 잡을때 조금 더 생각해서 기준을 잡고 컨벤션을 지켜나가보겠습니다!

2023-03-29 02:13 UTC, AppleCEO approved these changes
코멘트 한 내용들을 많이 바꿔주셨네요!
더 좋은 코드가 된 부분들도 있겠습니다 ㅎㅎ
다음 스텝 진행하면서 몇가지 코멘트 드린거 추가로 고민해보시면 좋겠네요~
머지해드려도 될까요?

2023-03-29 02:13 UTC, AppleCEO commented on BoxOffice/MovieListCell.swift
>              }
이 부분 제가 더 자세하게 적지 않았군요!
저는 switch문도 비슷하게 느껴지는데요.
저는 코드를 작성하면서 else 를 사용하는 것을 지양합니다.

```swift
if a == b {
  c = d
} else {
  d = c
}
```
이러한 코드가 있다고 할 때는 별 차이가 없을 수는 있는데 하나를 끊고 간다는 느낌이 들도록 저는 아래처럼 작성하는 편입니다.

```swift
if a == b {
  c = d
  return
}
d = c
```
지금 상황에서 이러한 방식으로 한번 작성해보실 수 있을까요? 더 자세히 적고 싶지만 한번 시도해보시고 궁금한거 있으시면 물어보셔도 될 것 같습니다!

2023-03-29 02:13 UTC, AppleCEO commented on BoxOffice/MovieListCell.swift
>              }
제가 선호하는 코드에서 어차피 위에서 return이 되기 때문에 아래 d = c 는 else 일 때만 동작하는 것이 위에 코드와 같습니다.
반면 else 를 확인하려면 위에 if가 뭔지 살펴봐야 하고 두번 확인해야 할 것을 return 으로 한 맥락이 끝내는 느낌이 들어서 더 보기 좋다고 생각해요. 이 부분 고민해보시면 좋겠습니다~

2023-03-29 02:13 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                    var myMovieLists: [ListItem] = []
list 라는 이름이 다시 등장했네요. list 와 lists 의 차이는 무엇인지도 애매하네요.
저는 보통 아이템 이름에 s 를 붙이는 것을 배열의 이름으로 많이 결정합니다~

2023-03-29 02:13 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                    var myMovieLists: [ListItem] = []
ex) myMovies =  [myMovie]
dailyBoxOffices = [dailyBoxOffice]

2023-03-29 02:13 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        refreshControl.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
이 99번째 줄과 100번째 줄이 97번째 줄로 위치가 바뀌었을 때 구조체와 클래스의 경우 동작의 차이가 있을텐데 어떤 차이가 있을까요?

2023-03-29 02:40 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                    var myMovieLists: [ListItem] = []
[7ecab84](https://github.com/yagom-academy/ios-box-office/pull/21/commits/7ecab84cb956dd86e8fa0f3643bc1abe7274f76a)

해당 부분 수정해주었습니다.!

2023-03-29 02:50 UTC, sehoong0429 commented on BoxOffice/MovieListCell.swift
>              }
```swift
private func createStateLabel(rankOldandNew: String, rankInten: Int) -> NSMutableAttributedString {
    let attributedString = NSMutableAttributedString()

    if rankOldandNew == "OLD" {
        switch rankInten {
        case 0:
            attributedString.add(string: "-")
            return attributedString
        case let rankInten where rankInten > 0:
            attributedString.add(string: "▲", color: .systemRed)
            attributedString.add(string: "\(rankInten)")
            return attributedString
        case let rankInten where rankInten < 0:
            attributedString.add(string: "▼", color: .systemBlue)
            attributedString.add(string: "\(-rankInten)")
            return attributedString
        default:
            break
        }
    }

    attributedString.add(string: "신작", color: .systemRed)
    return attributedString
}

```

이런식으로 수정하시는 방식 말씀하시는 거 맞으실까요? 
return을 여러번 써야해서 오히려 가독성은 떨어진다고 느껴집니다..! 
아니면 다른 방법으로 알려주신걸까요? 

저는 개인적으로 현재 처음 조언해주신대로 수정 했던 부분이 깔끔하게 느껴진다고 생각합니다!

2023-03-29 02:53 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        refreshControl.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
클래스는 참조타입이라 위치가 변경되었을때 refreshControl 객체를 전달하고 속성을 변경할 경우 전달한 객체를 참조하는 곳에 영향을 줄 수 있다고 생각합니다. 구조체의 경우 값타입이라 복사본이 전달되어 원래 객체에는 영향을 주지 않는 차이가 있다고 할 수 있습니다.

2023-03-29 02:59 UTC, merged

2023-03-29 03:10 UTC, sehoong0429 commented on BoxOffice/MovieListCell.swift
>              }
또한 알려주신 부분에 대해서 어떠한 의도로 말씀하신건지 생각해보면서 아래 자료도 찾아보았습니다. 
https://medium.com/swlh/return-early-pattern-3d18a41bba8

2023-03-29 03:47 UTC, AppleCEO commented on BoxOffice/Extensions/Int+decimal.swift
> +}
차이를 분명하게 알고 계시네요. 추가적인 설명까지 감사합니다~

2023-03-29 03:49 UTC, AppleCEO commented on BoxOffice/MovieListCell.swift
>              }
아 작성해주신 switch 문을 사용하는 방식보다는 if 로 작성하면서 early return 을 하는 방식이었습니다.
네 이 부분은 한번 보신 것으로도 괜찮습니다. 
나중에 이런 방법이 있다 생각해보시면 점점 더 좋은 것으로 이해하실 수 있습니다~

2023-03-29 03:50 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        refreshControl.attributedTitle = NSAttributedString(string: "Fetching Movie Data...")
제가 의도한 것이었습니다! 잘 이해하셨네요~ 고생하셨습니다 ㅎㅎ