박스오피스 [Step03] 무리, Rowan
yagom-academy/ios-box-office pull request #23
Opened 2023-03-28 09:16 UTC by Kyeongjun2

@junbangg 
안녕하세요 알라딘:) 무리, 로완 입니다🥹💧
우여곡절끝에... STEP3 PR 보냅니다...!!
이번 코멘트도 잘 부탁드립니다~!

# 고민한 점
## 1️⃣ Modern Collection View의 범위와 선택
먼저 STEP3 진행 전 요구사항을 살펴보다 **핵심경험** 부분을 읽게되었습니다. 그 중 하나가 `Modern Collection View 활용`이어서 Modern Collection View를 공부하고 사용해보기로 했습니다.
- **Modern Collection View**는 iOS 13.0+으로, 기존 CollectionView에서 사용하던 `DataSource`와 `Delegate`을 사용하지 않고, 새로운 기능인 `DiffableDataSource`, `CompositionalLayout`을 이용하여 CollectionView를 만들어내는 방법이었습니다.
컬렉션 뷰로 테이블 뷰(처럼 생긴 뷰)를 만들어야 했기 때문에, `CompositionalLayout`의 `list`메서드를 이용하여 목록 형태의 View를 만들게 되었습니다. 또한, `list`메서드와 `collectionViewListCell`이 모두 iOS 14.0+을 요구했기 때문에 프로젝트 minimum deployments를 14.0으로 설정하여 구현해보았습니다.

Modern Collection View의 편리함과 코드의 간결함을 느낄 수 있었지만 CollectionView 자체를 처음 사용해보았는데 기존의 형식을 이해하지 못하고 진행하면 아쉬움이 클 것 같아 Modern Collection View로 끝까지 진행하지 않는 것을 선택했습니다. List형태의 collectionView를 화면에 띄우는 것까지 구현한 후 기존의 collection view를 구현하던 방법으로 처음부터 다시 step을 진행했습니다.

### ✓ Modern Collection View를 사용한 브랜치 파일 태그
* [DailyBoxOfficeViewController](https://github.com/Kyeongjun2/ios-box-office/blob/step03/BoxOffice/Controller/DailyBoxOfficeViewController.swift)
* [DailyBoxOfficeCell](https://github.com/Kyeongjun2/ios-box-office/blob/step03/BoxOffice/View/DailyBoxOfficeCell.swift)

</br>

## 2️⃣ `viewDidLoad()` 이후 CollectionView가 나타나지 않던 문제
### 🔍 문제점
DataSource와 Delegate를 통해 CollectionView layout과 Cell 데이터를 채워주었는데도 앱 실행 시 CollectionView가 나타나지 않는 문제점이 있었습니다.

### ⚒️ 해결방안
`loadDailyBoxOffice()` 메서드에서 collectionView의 `reloadData()` 메서드를 호출하여 데이터의 로딩이 완료되면 UI를 업데이트 할 수 있도록 수정하였습니다.
```swift
apiProvider.startLoad(decodingType: DailyBoxOffice.self) { result in
    switch result {
    case .success(let dailyBoxOffice):
        self.dailyBoxOffice = dailyBoxOffice
        
        DispatchQueue.main.async {
            self.collectionView.reloadData()
            LoadingIndicator.hideLoading()
        }
    case .failure(let error):
        DispatchQueue.main.async {
            self.makeAlert(to: error)
            LoadingIndicator.hideLoading()
        }
    }
}
```

</br>

## 3️⃣ UICollectionViewDelegateFlowLayout 사용
Collection View의 Layout 객체 설정을 어떻게 할까 고민했었습니다.

작성 초기에 UICollectionViewFlowLayout 객체를 직접 만들어 layout 객체의 프로퍼티를 설정한 뒤 collectionView의 `collectionViewLayout` 프로퍼티에 할당해주었습니다.

```swift
private func configureCollectionView() {
    let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createListLayout())
    // ...
}

private func createListLayout() -> UICollectionViewFlowLayout {
    let configuration = UICollectionViewFlowLayout()
    configuration.itemSize = CGSize(width: view.bounds.width, height: 100)
    configuration.minimumLineSpacing = 0

    return configuration
}
```

이 방법은 collectionView 인스턴스를 생성할 때 layout을 바로 할당하지 못하는 불편함이 있었기 때문에 delegate를 이용해 flowlayout을 구현할 수 있도록 변경하였습니다.

```swift
extension DailyBoxOfficeViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView,
                        layout collectionViewLayout: UICollectionViewLayout,
                        sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: view.bounds.width, height: view.bounds.height / 10)
    }
    
    func collectionView(_ collectionView: UICollectionView,
                        layout collectionViewLayout: UICollectionViewLayout,
                        minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
}
```

</br>

## 4️⃣ cell 사이 border
Modern Collection View의 `list()`를 사용할 때와는 다르게 FlowLayout을 사용하여 List형식으로 구현하니, cell 사이를 구분짓는 선이 없어 보는데 불편함이 있었습니다.
이를 해결하기 위해 다음과 같은 방법을 사용해보았습니다.
### 1. background color + spacing
```swift
// DailyBoxOfficeViewController.swift
collectionView.backgroundColor = .systemGray5

private func createListLayout() -> UICollectionViewFlowLayout {
    let configuration = UICollectionViewFlowLayout()
// ...
    configuration.minimumLineSpacing = 0
// ...
}
```
- collectionView의 `backgroundColor`를 원하는 border의 색으로 정한 뒤 레이아웃의 `minimumLineSpacing`을 설정해보았지만 의도한대로 적용이 되지않아 이 방법은 사용하지 않았습니다.

### 2. border 직접 그리기 + spacing
CALayer 타입의 extension을 통해 구분선을 그려주는 메서드를 정의하였습니다.
```swift
extension CALayer {
    func addBorder(color: UIColor, width: CGFloat) {
        let border = CALayer()
        border.frame = CGRect.init(x: 0, y: 0, width: frame.width, height: width)
        border.backgroundColor = color.cgColor
        self.addSublayer(border)
    }
}
```
이때, UICollectionViewDelegateFlowLayout 프로토콜 채택 후 cell 사이 간격이 떨어져있는 것을 확인했습니다.

#### a. minimumItemSpacing(vertical scroll 일 때)
- 1번 방법을 시도한 뒤에 DelegateFlowLayout의 `collectionView(_:layout:minimumItemSpacingForSectionAt:)`메서드를 이용하여 기본적으로 주어진 spacing을 지워주려고했습니다... 생각했던대로라면 리스트에 들어있는 cell 하나하가 item이기때문에 적용이 되었어야 했는데 spacing이 적용되지 않아 코드를 다시 살펴보게되었습니다.
`ItemSpacing`은 grid에서 cell 사이, 가로의 spacing을 의미하여 한 섹션에 아이템이 가로로 여러개 놓여있을 때 적용되는 spacing이었습니다. 현재 저희는 한개의 섹션에 아이템이 여러개 들어가있지만 아이템의 가로길이를 view의 크기와 맞춰주었기 때문에 적용되지 않았습니다.

#### b. **minimumLineSpacing**(vertical scroll 일 때)
- 따라서 `collectionView(_:layout:minimumLineSpacingForSectionAt:)`메서드를 사용해주었습니다. 해당 메서드는 grid에서 cell 사이, 세로의 spacing을 의미하고 기본값이 존재하여 0으로 설정 해 준 뒤 border를 그려주어 원하는대로 구현을 할 수 있었습니다.

---
</br>

# 해결되지 않은 점
## 1️⃣ refreshControl시 animate의 적용
요구사항 중 화면을 아래로 스크롤하여 새로고침을 적용하는 부분이 있었습니다. 해당 기능은 `refreshControl` 키워드를 이용하여 구현을 하게되었습니다. 구현 후 시뮬레이터에서 실행하는 과정에서 요구사항과는 다르게 나타나는 부분이 있었고, 이를 해결하지 못해 질문남깁니다😭...!
- 요구사항에서는 다음과 같이 아래로 스크롤하게되면 새로고침되며 인디케이터 아이콘이 도는 중에는 리스트뷰가 올라오지 않습니다.
>요구사항에서 새로고침 시 리스트가 올라오다가 잠시 멈춘 후 indicator가 사라지며 마저 정렬됨
![](https://i.imgur.com/bawBJ7d.png)
- 하지만 저희가 구현한 화면에서는 다음과 같이 인디케이터 아이콘이 리스트와 겹치고, 리스트가 바로 정렬됩니다😭....
![](https://i.imgur.com/CRu2iYi.gif)

---
</br>

## 조언을 얻고싶은 점
### 1️⃣ 특정 layer의 제거
```swift 
// extension+CALayer.swift
func addBorder(edge: UIRectEdge, color: UIColor, width: CGFloat) {
    let border = CALayer()
    switch edge {
        case UIRectEdge.top:
        border.frame = CGRect.init(x: 0, y: 0, 
                                   width: frame.width, 
                                   height: width)
        case UIRectEdge.bottom:
        border.frame = CGRect.init(x: 0, y: frame.height - width, 
                                   width: frame.width, 
                                   height: width)
    }
    border.backgroundColor = color.cgColor
    self.addSublayer(border)
}

// DailyBoxOfficeViewController.swift
func collectionView(_ collectionView: UICollectionView,
                    cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    // ... 
    if let movieList = dailyBoxOffice?.boxOfficeResult.dailyBoxOfficeList,
    indexPath.item == movieList.count - 1 {
        cell.layer.addBorder(edge: .bottom, color: .systemGray4, width: 1)
    }
    
    return cell
}
```
cell의 테두리를 tableViewCell 처럼 위, 아래 모두 그려주기 위하여 if문에서 제일 마지막 item에만 bottom border를 그려주고 있습니다. 이렇게 구현하니 첫 화면에서는 위, 아래 모두 겹치지 않고 border가 그려졌지만, 새로고침하거나 스크롤하는 과정에서 cell이 reuse될 때 테두리가 겹쳐져 진해지는 현상이 보였습니다.
이를 해결하기 위해 `prepareForReuse()` 메서드 내부에서 border를 초기화 해주고 싶었고, addSublayer를 해주었기때문에 `removeFromSuperLayer()`를 호출하게되었습니다. 
```swift!
// 방법 1.
self.layer.sublayers?.forEach {
    $0.removeFromSuperlayer()
}
// 방법 2.
DispatchQueue.main.async {
    self.layer.sublayers?.last?.removeFromSuperlayer()
}
```
이 과정에서 저희가 넣었던 layer만을 해제해주고 싶었지만, 방법 1은 cell에 담겨있는 모든 layer가 해제되었고 BadAccess가 발생하게되었습니다. 

![](https://i.imgur.com/AhJtRke.png)

그래서 사용해본 방법 2로는 마지막 cell의 bottomLayer은 지우지 못해 셀이 재사용되는 과정에서 border가 남아있었습니다.

이 부분에서 border를 그려준 layer를 특정하여 해제하는 방법이 있을지 궁금합니다🥲

또한.. prepareForReuse에서 border를 초기화시키지 않고 있는 상황에서 setBorder메서드가 계속 호출되어도 테두리가 진해지지 않는 점이 이해하기 어렵습니다.. layer는 중복 추가가 되지 않는걸까요? 🤔

2023-03-31 09:16 UTC, junbangg requested changes
문서화 장인들.. 너무 좋습니다👍
수고하셨습니다!

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private func makeAlert(to error: Error) {
makeAlert(for: ) 는 어떠신가요???

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                                  collectionViewLayout: UICollectionViewFlowLayout())
의도된 줄바꿈인가요??

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    private let movieTitleLable = UILabel()
오타욥!

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        LoadingIndicator.showLoading()
여기부터 로딩을 하는 이유가 있을까요??🤔

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Model/NumberFormat.swift
> +}
String 익스텐션 으로 하는것도 혹시 고려해보셨을까용

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    private var isConstraintNeeded = true
요거 동작 설명 한번 부탁드립니다

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    func fillLabels(with data: DailyBoxOfficeMovie) {
Fill 보다는 configure 같은 단어가 좋을것 같은데 어떠신가요?

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +        case Sign.new:
문자열 관리를 신경쓰셨군요👍
그런데 차라리 data.rankOldAndNew 를 enum 으로 바꿔버리고 여기서 케이스로 나눠서 사용하는건 어떨까요??

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        cell.fillLabels(with: movieData)
MovieData 을 전달해주고 fillLabel을 하던 뭘 하던 내부에서 자체적으로 처리 할 수 있도록 하는건 어떨까요??

cell.configure(with: movieData) 이런식으로 메세지만 전달하면 알아서 하게끔 ?

객체는 가끔 좀 이기적으로 일할 필요가 있더라고요:)

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    }()
낄끔하네요!

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/View/LoadingIndicator.swift
> +            guard let window = UIApplication.shared.windows.last else { return }
궁금한게 요거까지 디스패치큐에 있어야하려나요??🤔

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                    LoadingIndicator.hideLoading()
hideLoading 은 밖으로 빼도 되지않으려나요?? Success, failure 에서 두번 보이네요??

2023-03-31 09:16 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                    LoadingIndicator.hideLoading()
그리고 코드 보니까 hideLoading 은 이미 큐 안에서 동작하는거 같더라고요! 확인 부탁드립니당

2023-04-01 06:23 UTC, Kyeongjun2 commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    func fillLabels(with data: DailyBoxOfficeMovie) {
configure로 변경했습니다~

2023-04-01 06:23 UTC, Kyeongjun2 commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    private var isConstraintNeeded = true
셀이 재사용 될 때 다시 constraint를 잡는 일이 없도록 방지해주는 역할이라고 생각해서 추가했습니다

2023-04-01 06:27 UTC, parkmuri commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private func makeAlert(to error: Error) {
코멘트를 반영하여 수정하였습니다!

2023-04-01 06:27 UTC, parkmuri commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                                  collectionViewLayout: UICollectionViewFlowLayout())
넵 의도된 줄바꿈입니다. 붙여서 사용하니 코드가 길어져 가독성이 떨어져 줄바꿈을 해주었습니다.

2023-04-01 06:28 UTC, parkmuri commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +    private let movieTitleLable = UILabel()
휴먼에러가...😂..! 감사합니다! 오타 수정했습니다!

2023-04-01 06:29 UTC, Kyeongjun2 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        cell.fillLabels(with: movieData)
지정 이니셜라이저를 만들어서 인스턴스 생성 시 적용될 수 있도록 수정했습니다!
```swift
override init(frame: CGRect) {
        super.init(frame: frame)
        setBorder()
        configureSubviews()
    }
    
  required init?(coder: NSCoder) {
      fatalError("init(coder:) has not been implemented")
  }
```

2023-04-01 06:30 UTC, parkmuri commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        LoadingIndicator.showLoading()
로딩 인디케이터를 다른 뷰들이 띄워지기 전에 보여주고싶어서 `viewDidLoad`내부에서 호출해주었습니다!

2023-04-01 06:31 UTC, parkmuri commented on BoxOffice/Model/NumberFormat.swift
> +}
조언해주신대로 String Extenstion으로 리팩토링하였습니다!
```swift 
extension String {
    func decimal() -> String? {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        let result = numberFormatter.string(from: Int(self) as? NSNumber ?? 0)
        
        return result
    }
}
```

2023-04-01 07:01 UTC, Kyeongjun2 commented on BoxOffice/View/LoadingIndicator.swift
> +            guard let window = UIApplication.shared.windows.last else { return }
guard let 부분은 디스패치큐에서 빼줬습니다!

2023-04-01 07:01 UTC, parkmuri commented on BoxOffice/View/DailyBoxOfficeCell.swift
> +        case Sign.new:
조언해주신대로 `DailyBoxoffice`의 `rankOldAndNew`를 enum타입으로 지정하고 케이스를 나누어 사용해주었습니다!
이렇게하니 불필요하게 `default`를 지정해주지않아도 되어서 코드가 조금 더 간결해진거같습니다👏

2023-04-01 07:14 UTC, parkmuri commented on BoxOffice/View/LoadingIndicator.swift
> +            guard let window = UIApplication.shared.windows.last else { return }
현재는 `viewDidLoad()`에서 호출해주어 메인스레드에서 동작하지만 추후에 다른 곳에서 호출할 일이 있을 때 메인스레드에서만 동작할수 있다는 보라색 오류가 염려되어 넣어서 사용해주었습니다!

2023-04-01 07:14 UTC, Kyeongjun2 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                    LoadingIndicator.hideLoading()
```swift
case .success(let dailyBoxOffice):
    self.dailyBoxOffice = dailyBoxOffice
    
    DispatchQueue.main.async {
        self.collectionView.reloadData()
    }
case .failure(let error):
    DispatchQueue.main.async {
        self.makeAlert(for: error)
    }
}

LoadingIndicator.hideLoading()
```
hideLoading 메서드 내부도 main.async로 보내고 있어서 switch 문 밖으로 옮겨주었습니다!

2023-04-01 12:08 UTC, junbangg commented on BoxOffice/Model/NumberFormat.swift
> +}
여런건 메서드가 아닌 연산 프로퍼티로도 가능할것 같아요!

2023-04-01 12:11 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        LoadingIndicator.showLoading()
흠 로딩 인디케이터는 리퀘스트를 기다리는 동안만 보여주는게 좋지 않을까요??🤔

2023-04-01 12:14 UTC, merged