박스오피스 [STEP 3] 리지, kokkilE
yagom-academy/ios-box-office pull request #24
Opened 2023-03-28 13:32 UTC by yijiye

# 박스오피스 step3
@July911
줄라이 안녕하세요! 코낄이, 리지 입니다.
step3 PR 완성하여 올립니다!
매번 좋은 피드백 감사합니다. 이번에도 잘 부탁드립니다 ☺️

# 고민했던 점
## 1️⃣ listCell과 customCell
저희는 Mordern Collection View를 구현하는 방법으로 `UICollectionViewListCell`을 사용하는 방법(iOS 14 타겟)을 선택했었습니다.
하지만 줄라이의 조언을 듣고 listCell을 사용하지 않는 구현을 경험해보지 않는 것이 아쉬워서, iOS 13 타겟으로 listCell을 사용하지 않고 다시 구현해보았습니다.
<img src="https://i.imgur.com/sEQJ37Z.png" width=250>

listCell로 구현하는 방식은 [Implementing Modern Collection Views](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views) 에서 제공하는 샘플 코드 일부를 사용하였습니다.

### listCell을 사용한 구현에서 느낀 점
- Layout이 편했습니다.
``` swift
private func createLayout() -> UICollectionViewLayout {
    let config = UICollectionLayoutListConfiguration(appearance: .plain)
    return UICollectionViewCompositionalLayout.list(using: config)
}
```
셀의 레이아웃을 따로 구현할 필요 없이 `UICollectionViewCompositionalLayout.list`만으로 가로 화면, 세로 화면에서 컬렉션뷰의 레이아웃이 리스트 형태로 완벽하게 구성되는 것을 화인할 수 있었습니다.

- 코드를 이해하기가 어려웠습니다.
``` swift
@available(iOS 14.0, *)
extension UIConfigurationStateCustomKey { ... }

@available(iOS 14.0, *)
extension UICellConfigurationState { ... }

@available(iOS 14.0, *)
final class DailyMovieListCell: UICollectionViewListCell {
    override var configurationState: UICellConfigurationState { ... }
    ...
```
`UIConfigurationStateCustomKey`과 `UICellConfigurationState`, `DailyMovieListCell.configurationState`의 관계를 파악하기가 어려웠습니다. 또한 `UICollectionViewListCell`을 상속하는 클래스에서 구현하는
``` swift
override func updateConfiguration(using state: UICellConfigurationState)
```
메서드는 직접 호출되지 않고 `setNeedsUpdateConfiguration()`를 통해 호출 요청을 보내는데, 이러한 부분도 추적하기가 어려웠습니다.
listCell을 사용하기 위해서는 충분히 시간을 가지고 학습해야 할 것 같다고 생각했습니다.

## 2️⃣ snapshot을 찍어주는 주체
`NSDiffableDataSourceSnapshot` 공식문서를 확인해보니 Diffable data source가 snapshot을 사용해 collectionView에게 필요한 데이터를 제공한다는 것을 알 수 있었습니다. 처음엔 `collectionView`에 데이터를 받아서 띄우는 쪽으로 생각해서 `collectionView` 타입에 구현하였는데, 정확한 개념을 이해하니 MVC 관점에서 `collectionView`는 단순히 `View`를 담당하고 이 `View`에 데이터를 전달하는 즉, snapshot을 찍는 역할은 `viewController`에서 하는 것이 맞다고 생각하여 `viewController`에 구현하였습니다.

## 3️⃣ customCell로 구현시 AccessoryType 문제
`ListCell`로 구현했을 때는 `accessoryType`이 있어 쉽게 적용할 수가 있었는데,`customCell`로 구현하니 `accessoryType`을 찾지 못했습니다. 그래서 저희는 직접 imageView로 구현하였습니다.

- **적용한 방법**
`UIImage(systemName: "chevron.right")` 로 > 이미지를 넣은 후 색상을 변경하였고, `widthAnchor`, `heightAnchor`를 `mainStackView`의 배율로 크기를 지정하였습니다.

```swift
private var accessoryImageView = UIImageView()

private func configureAccessoryImageView() {
        accessoryImageView.image = UIImage(systemName: "chevron.right")?.withTintColor(.systemGray2, renderingMode: .alwaysOriginal)
        
        accessoryImageView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            accessoryImageView.trailingAnchor.constraint(equalTo: mainStackView.trailingAnchor),
            accessoryImageView.widthAnchor.constraint(equalTo: mainStackView.widthAnchor, multiplier: 0.025),
            accessoryImageView.heightAnchor.constraint(equalTo: mainStackView.heightAnchor, multiplier: 0.2)
        ])
    }
```

## 조언을 구하고 싶은 점
### 1️⃣ customCell로 구현시 Autolayout 문제

- 줄라이의 피드백을 받고 `customCell`을 활용해보고자 했습니다. cell을 구성하는 UI는 크게 `mainStackView` - `movieRankStackView`, `movieListStackView`,`accessoryImageView` 로 구성하였고, `movieRankStackView`, `movieListStackView` 안에는 `label`을 두개씩 배치하였습니다. 그리고 필요한 제약을 걸어 autolayout을 잡았는데, 아래와 같은 문제가 발생하였습니다.

- customCell로 구현시 문제된 화면
<img src="https://i.imgur.com/8YG5K4q.gif" width=250><img src="https://i.imgur.com/pMio0Mi.gif" width=250>

- 저희가 생각한 문제의 원인은 UICollectionViewLayout을 잡는 곳에서 itemSize와 관련있다고 생각했습니다. 따라서 `.fractionalHeight`,`absolute`, `estimated`로 확인을 해봤는데, 답을 찾지 못하였습니다.
  - **시도한 방법**
    - `.fractionalHeight(x)`: x 값을 0.1 보다 높여주어 회전했을 때 cell크기가 유지되도록 하였으나 세로 화면일 때 cell크기가 예시화면보다 큰 문제가 발생
    - `absolute(44.0)`, `estimated(44.0)` : 첨부한 첫 번째 화면과 같이 아래로 스크롤 했을 때, cell의 크기가 줄어들어 있거나 화면 회전시 화면을 벗어난 cell의 크기가 다른 cell보다 커지는 현상 발생
```swift
func createMovieListLayout() -> UICollectionViewLayout {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                              heightDimension: .fractionalHeight(0.1))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
    }
```
문제의 원인을 저희가 잘못 생각했을까요? 다른 어떤 방법을 시도해볼 수 있을까요? 🫠

## 2️⃣ 동일한 파일 내에서 extension을 하는 기준
`DailyBoxOfficeViewController` 내에서 메서드를 다음과 같이 구현하였습니다.
``` swift
final class DailyBoxOfficeViewController: UIViewController {
    @objc private func refreshData()
    private func updateDateToViewTitle()
    private func updateDateToEndPoint()
// 서버에 데이터를 요청하고 받아온 데이터를 저장하는 기능
    private func fetchDailyBoxOfficeData()
}

// dataSource를 통해 cell에 데이터를 전달하는 기능
extension DailyBoxOfficeViewController {
    private func setupDataSource()
    private func setupSnapshot()
}

// collectionView의 레이아웃을 생성하는 기능 
extension DailyBoxOfficeViewController {
    private func createMovieListLayout()
}
```
뷰컨트롤러가 많은 기능을 가지기 때문에, 유사한 기능을 묶어 가독성을 개선하고자 위와 같이 extension을 사용하였는데, 적절한 기준으로 분류를 했는지 의문이 들었습니다.

`fetchDailyBoxOfficeData`는 서버에 데이터를 요청하는 기능이고, `setupDataSource`과 `setupSnapshot`는 cell에 데이터를 전달하는 기능입니다. 따라서 두 기능을 별개로 분리하였지만, 사실 cell에 데이터를 전달하는 두 메서드는 `fetchDailyBoxOfficeData`내에서 호출됩니다. 이처럼 서로 다른 기능이지만 연관이 되어 있어 기능을 딱잘라 구분하기엔 어려움이 있었습니다. 이럴 때 기능을 구분하는 기준을 정하는 데 도움이 될만한 조언이 있을까요? :thinking:

2023-03-29 07:05 UTC, July911 requested changes

2023-03-29 07:05 UTC, July911 commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieListCell.swift
> +    private var movie: DailyBoxOffice.BoxOfficeResult.Movie? = nil
이게 왜 필요한거죠 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private var movieDataSource: DataSource?
조금의 띄어쓰기가 필요해보이네요.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private var networkManager = NetworkManager()
변하는 값인가요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private typealias DataSource = UICollectionViewDiffableDataSource<Section, DailyBoxOffice.BoxOfficeResult.Movie>
어떤 기준으로 여기에 놓았는지 모호합니다.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
autoresizingMask 이건 무엇을 해주나요  ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        collectionView.register(DailyBoxOfficeCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeCollectionViewCell.reuseIdentifier)
UI 구현부에 셀 등록까지 할 필요가 있나요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        view.addSubview(collectionView)
UI 구현부에 addSubView를 해줘야하나요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let dateFormatter = DateFormatter()
매번 생성해주는게 불필요해보입니다.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let dateFormatter = DateFormatter()
매번 생성해주는게 불필요해보입니다.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                self?.dailyBoxOffice = result
self가 없으면 어떻게 되는지 생각해주세요.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                              heightDimension: .fractionalHeight(0.1))
item size를 건드는게 맞을까요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
NSCollectionLayoutEnvironment 이 무엇인지 설명해주세요.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/Model/JSON/DailyBoxOffice.swift
>      let boxOfficeResult: BoxOfficeResult
JSON파싱하는 모델의 모든 정보를 쓰는지 생각해주세요.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +    private var movie: DailyBoxOffice.BoxOfficeResult.Movie?
삭제부탁드립니다.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +        audienceVarianceLabel.textColor = .black
super콜은 필요없나요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +            guard let variance = Int(movie.rankVariance) else { return }
cell이 많은걸 하고있는 것 같습니다.

2023-03-29 07:05 UTC, July911 commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieViewController.swift
> +        var snapshot = NSDiffableDataSourceSnapshot<Section, DailyBoxOffice.BoxOfficeResult.Movie>()
내부의 행동이 setup 인가요 ?

2023-03-29 07:05 UTC, July911 commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +    private var separatorView = UIView()
(개인적으로) 조금의 띄어쓰기가 필요해보이네요.

2023-03-29 07:13 UTC, July911 commented
기간내에 잘해주셨습니다 :) 여러가지 수정할 부분들이 보여서 코멘트 남겼습니다. 
지금 Cell이 해주어야할 역할과 VC 가 해야할 역할이 조금 모호한 것 같습니다. 
이 부분 위주로 수정 부탁드립니다. :) 고생하셨습니다 ! 

조언을 구하고 싶은 점
1️⃣ customCell로 구현시 Autolayout 문제


https://user-images.githubusercontent.com/90888402/228454069-fc6bbf0b-eb4b-43c1-b6c2-4f33cf2fe60a.mp4

이런식의 동작을 원하시는거면, 다른 값을 바꾸셔야합니다. 
저번에 디스코드에서 말씀드렸던 문서를 한번 더 참고해주세요. 

2️⃣ 동일한 파일 내에서 extension을 하는 기준 

이건 정말 취향차이인 것 같습니다.  UI 요소가 헤더/ 리프레시 컨트롤/ 콜렉션뷰 / 키보드 등등이 붙어있다고 치면 
각각의 하나의 익스텐션으로 관리해주는 편입니다. 또한 콜렉션뷰 데이터소스와 레이아웃 역시 다르게 관리해주고 있습니다. 
//MARK: - 
//FIXME: - 
//TODO: - 
를 통해 관리하면 더욱 간편합니다.

2023-03-29 07:15 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        updateDateToEndPoint()
pull to refresh를 계속 하면 어떻게 되나요 ? 
방어할 수 있는 방법은 무엇이 있을까요 ?

2023-03-29 07:18 UTC, July911 commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieViewController.swift
> +        let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createLayout())
UICollectionView(frame: view.bounds 
 
추후 콜렉션 뷰 위에 커스텀 헤더가 추가된다면 어떻게 대응하실 건가요 ?

2023-03-29 09:03 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
superView의 사이즈가 달라지면 그 안의 subView의 크기를 조정해주는 역할을 합니다. 
현재 저희는 collectionView의 superView가 viewController이기 때문에 크기가 조정될 일이 없다고 생각하여 이 코드는 불필요하다고 생각합니다. 따라서 삭제하였습니다!

2023-03-29 11:56 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private var networkManager = NetworkManager()
아니요..! let으로 변경하였습니다

2023-03-29 12:55 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    private typealias DataSource = UICollectionViewDiffableDataSource<Section, DailyBoxOffice.BoxOfficeResult.Movie>
`typealias`를 클래스 내 최상단으로 이동하였습니다.

2023-03-29 12:57 UTC, yijiye commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieViewController.swift
> +        var snapshot = NSDiffableDataSourceSnapshot<Section, DailyBoxOffice.BoxOfficeResult.Movie>()
내부의 행동은 dataSource에 data를 전달해주는 기능이라 생각하여 `applySnapshotToDataSource()`로 변경하였습니다!

2023-03-29 12:57 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
상위 뷰의 사이즈가 변경되면 `autoresizingMask`가 설정된 하위 뷰도 비율에 따라 자동으로 크기가 리사이징되네요..!

`DailyBoxOfficeCollectionViewCell` 타입의 `separatorView` 프로퍼티에도 `autoresizingMask`을 적용해주었습니다.

2023-03-29 13:00 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        collectionView.register(DailyBoxOfficeCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeCollectionViewCell.reuseIdentifier)
``` swift
lazy private var collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createMovieListLayout())
```
프로퍼티 구현부에서는 UI 관련 요소를 받아 생성자만 호출하도록 수정하였고, `configureCollectionView` 메서드를 구현하여 셀 등록은 해당 메서드에서 하도록 했습니다!

2023-03-29 13:00 UTC, yijiye commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +            guard let variance = Int(movie.rankVariance) else { return }
저희는 cell 타입에서 cell에 들어가는 UI요소들 모두 구현해주어야 한다고 생각하였습니다. 그런데, 조건에 따라 달라지는 위의 같은 경우는 viewController에서 해주는게 적절하다는 의견이신가요? 어떤 부분이 많은걸 하고 있는 건지 저희가 잘 이해하지 못한 것 같습니다 🥲

2023-03-29 13:00 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        view.addSubview(collectionView)
`configureCollectionView` 메서드를 구현하여 addSubview는 해당 메서드에서 하도록 했습니다!

2023-03-29 13:01 UTC, yijiye commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +        audienceVarianceLabel.textColor = .black
필요하여 추가하였습니다!

2023-03-29 13:01 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let dateFormatter = DateFormatter()
함수 호출 시마다 매번 생성되는 대신, 뷰컨이 `DateFormatter` 타입의 프로퍼티를 보유하도록 수정했습니다.

2023-03-29 13:01 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let dateFormatter = DateFormatter()
함수 호출 시마다 매번 생성되는 대신, 뷰컨이 DateFormatter 타입의 프로퍼티를 보유하도록 수정했습니다.

2023-03-29 13:02 UTC, yijiye commented on BoxOffice/View/DailyBoxOfficeCollectionViewCell.swift
> +    private var movie: DailyBoxOffice.BoxOfficeResult.Movie?
삭제 후 필요한 메서드에서 파라미터로 받아주도록 수정하였습니다.
```swift
 func configure(with movie: DailyBoxOffice.BoxOfficeResult.Movie) {
        setupMovieListLabels(with: movie)
        setupMovieRankLabels(with: movie)
    }

2023-03-29 13:03 UTC, yijiye commented on BoxOffice/Model/JSON/DailyBoxOffice.swift
>      let boxOfficeResult: BoxOfficeResult
movie의 정보만 받기 때문에 `Hashable`이 필요하지 않은 곳에서는 삭제하였습니다.

2023-03-29 13:10 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                self?.dailyBoxOffice = result
위 코드는 `URLSession.shared.dataTask`를 통해 비동기로 실행되는 클로저 내부입니다.
`dailyBoxOffice`는 뷰컨트롤러의 프로퍼티인데, 위 클로저가 실행될 때 뷰컨트롤러가 메모리에 남아있다는것이 보장되지 않기 때문에 `self` 키워드 없이 사용할 수 없습니다.
- `self.` 키워드를 사용하면 강한 참조로 뷰컨트롤러의 Reference Count를 증가시켜 뷰컨트롤러가 메모리에서 해제되지 않도록 합니다.
- 저희는 약한 참조로 사용하기 위해 weak self로 `self?.` 키워드를 사용했으므로 Reference Count를 증가시키지 않고, 뷰컨트롤러가 메모리에 남아있지 않다면 해당 구문은 옵셔널 체이닝에 실패하고 실행되지 않습니다.

2023-03-29 13:12 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
NSCollectionLayoutEnvironment가 생소하여 공식문서를 참고하여 개념을 정리해보았습니다.
NSCollectionLayoutEnvironment는 레이아웃의 컨테이너 및 environment trait에 대한 정보를 제공하는 데 사용되는 프로토콜로, 받은 정보를 통해레이아웃 섹션이 렌더링 되는 동안 레이아웃을 어떻게 보여줄지 결정할 수 있습니다.

2023-03-29 13:20 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                              heightDimension: .fractionalHeight(0.1))
``` swift
let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                              heightDimension: .estimated(44))
...
let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                               heightDimension: .estimated(44))
```
item이 하나의 cell의 크기를 지정한다고 생각하기 때문에 item size를 설정해야 한다고 생각했습니다.
item 내부 UI요소의 크기에 따라 자동으로 크기가 설정되도록 `.estimated`를 사용하였습니다.
group은 group을 구성하는 [item]의 크기에 따라 자동으로 크기가 설정되도록 `.estimated`를 사용하였습니다.

화면 회전 시 `collectionView`의 상위 뷰의 크기가 변경됨에 따라 `collectionView`도 크기가 자동으로 변경되도록 autoresizingMask를 설정하였습니다.

2023-03-29 13:23 UTC, July911 commented on BoxOffice/Model/JSON/DailyBoxOffice.swift
>      let boxOfficeResult: BoxOfficeResult
삭제하고 추가된 내용은 없을까요?

2023-03-29 13:24 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                self?.dailyBoxOffice = result
저 클로저가 실행될때 self가 내려간다면 어떻게 될까요?

2023-03-29 13:25 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                              heightDimension: .fractionalHeight(0.1))
item group section에 대한 자세한 설명 부탁드립니다.

2023-03-29 13:25 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
저 프로토콜에 어떻게 접근할까요?

2023-03-29 13:27 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        updateDateToEndPoint()
@yijiye @kokkilE 확인 부탁드립니다.

2023-03-29 13:27 UTC, July911 commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieViewController.swift
> +        let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createLayout())
@yijiye @kokkilE 확인부탁드립니다.

2023-03-30 04:31 UTC, kokkilE commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieListCell.swift
> +    private var movie: DailyBoxOffice.BoxOfficeResult.Movie? = nil
뷰컨트롤러에서 `updateWithItem`을 통해 전달받은 `movie`를 `configurationState`에 저장하는 로직으로 구현되어 있습니다.
``` swift
final class DailyMovieListCell: UICollectionViewListCell {
    private var movie: DailyBoxOffice.BoxOfficeResult.Movie? = nil
    ...
	override var configurationState: UICellConfigurationState {
	    var state = super.configurationState
	    state.movie = self.movie
	    return state
	}
	
	func updateWithItem(_ newItem: DailyBoxOffice.BoxOfficeResult.Movie) {
	    guard movie != newItem else { return }
	    movie = newItem
	    setNeedsUpdateConfiguration()
	}
```

`configurationState`는 `UICollectionViewListCell`을 상속한 연산 프로퍼티인데, get only로 구현되어 있어서 다음과 같이 직접 `movie`를 할당해줄 수 없었습니다. (set을 구현한다고 해도, 연산 프로퍼티이기 때문에 다른 저장 프로퍼티를 통해 셋팅되어야하기 때문에 추가로 저장 프로퍼티를 구현해야 했습니다.)

``` swift
	func updateWithItem(_ newItem: DailyBoxOffice.BoxOfficeResult.Movie) {
	    configurationState.movie = newItem    // error
	    setNeedsUpdateConfiguration()
	}
```
따라서 뷰컨트롤러에서 전달받은 `newItem`을 임시로 저장할 `movie` 프로퍼티가 필요했습니다. 혹시 저희가 놓친 부분이 있을까요?

2023-03-30 05:18 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                                              heightDimension: .fractionalHeight(0.1))
<img src="https://user-images.githubusercontent.com/114971172/228735552-cee43752-9d3f-4778-8e62-54642973bb9a.png" width="200">
item은 화면을  구성하는 가장 작은 데이터 단위이고, 이러한 item들을 묶어 group 이라하고 이 group으로 구성되어 있는 것이 section이라 생각합니다. 그리고 compositionalLayout은 최소 1개 이상의 section으로 구성되어 있습니다!

2023-03-30 05:46 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +                self?.dailyBoxOffice = result
저희가 직접 테스트해본 결과, self 가 nil이 되어도 closure는 실행이 되었습니다. 
클로저가 실행된 이유는 @escaping closure이기 때문에 self가 nil이어도 RC가 남아있었기 때문이라고 생각했습니다. 👀
그러나 아래 메서드들은 실행되지 않아 viewController에 아무것도 나타나지 않았습니다.
```swift
case .success(let result):
        self?.dailyBoxOffice = result
                
        DispatchQueue.main.async {
               self?.setupDataSource()
               self?.applySnapshotToDataSource()
               self?.refreshControl.endRefreshing()
```

2023-03-30 06:14 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
[공식문서](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider)에서 프로토콜에 접근하는 방법을 찾아보았습니다. `UICollectionViewCompositionalLayout`의 init을 통해 프로토콜에 접근이 가능하고, 이 포로토콜을 사용하여 유연한 레이아웃을 잡을 수 있을 것으로 생각됩니다.
하지만 현재 저희가 이 프로토콜과 레이아웃을 이해하고 적용하는데는 어려움이 있어서, 다음에 기회가 있을 때 사용해보도록 하겠습니다. 🙇

2023-03-30 06:36 UTC, yijiye commented on BoxOffice/Model/JSON/DailyBoxOffice.swift
>      let boxOfficeResult: BoxOfficeResult
`Hashable` 프로토콜 채택시 구현해야 하는 메서드를 말씀하시는 걸까요? 
만약 그렇다면, 저희가 구현한 Movie struct의 모든 프로퍼티가 string 타입으로 공식문서에 나와있는 `For a struct, all its stored properties must conform to Hashable.` 조건에 부합하여 따로 메서드를 추가하지 않아도 문제가 없었습니다..!

2023-03-30 07:03 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        updateDateToEndPoint()
1. 방어의 의미가 pull to refresh가 실행중인 상태에서는 pull to refresh가 반복되어 실행되지 않게끔 하는 의미일까요?

그런 의미라면 pull to refresh 중에는 다시 pull to refresh이 작동하지 않는것을 확인했습니다.
`UIRefreshControl.isRefreshing` 을 통해 내부적으로 확인 후 리프레시가 실행되는 것으로 생각됩니다.

2023-03-30 07:12 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        updateDateToEndPoint()
아니면 혹시 방어의 의미가 다른 의미일까요? 👀

2023-03-30 07:26 UTC, yijiye commented on BoxOffice/@iOS 14.0 ListCell/DailyMovieViewController.swift
> +        let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createLayout())
저희가 생각했을 땐, custom header를 추가하는 과정도 collectionViewCell을 추가하듯이 collectionView에 register 될거고 그러면 collectionView안에 포함된다고 생각합니다. 그래서 위 코드처럼 collectionView의 frame을 view.bounds로 잡는건 문제가 없을 것 같습니다. 다만 header를 추가했을 때, 내부 레이아웃을 잡는 걸로 대응하면 된다고 생각합니다. 👀

2023-03-30 07:33 UTC, merged