박스오피스 [STEP 3] vetto, brody
yagom-academy/ios-box-office pull request #27
Opened 2023-03-29 03:48 UTC by gzzjk159

@uuu1101 
안녕하세요 태태!
박스오피스 step3 PR입니다.
여러가지 새로운 API를 적용해보느라 조금 늦었습니다..ㅎㅎ
리뷰 잘 부탁드리겠습니다!

## 고민한 점

### UICollectionViewListCell, ContentConfiguration의 사용
요구사항의 뷰를 보고 테이블 뷰로 구현할 지, 컬렉션 뷰로 구현할 지, CollectionListCell을 이용해서 구현할 지 고민했습니다. 

테이블 뷰와 컬렉션 뷰로 충분히 구현이 가능해보였지만 `ContentConfiguration`의 이점으로 상태에 따른 셀의 외형, 외형, 데이터 주입을 분리할 수 있다는 점에서 `CollectionViewListCell`을 이용했습니다.

하지만 평범한 `UICollectionViewListCell`은 `text`, `secondaryText` 등의 기본적인 프로퍼티만 존재했습니다. 
이번 프로젝트에서는 랭킹이 어제에 비해 얼만큼 증가 혹은 감소하였는가와 같은 레이블이 필요했고 추후 셀의 레이아웃에 무언가 추가가 되었을 때 기존에 존재하는 `text`같은 요소들은 사용하지 않을 수 있기 때문에(다른 무언가 요소로 대체가 되는 경우가 있을 것 같습니다) `UICollectionViewListCell`를 상속받은 커스텀 ListCell을 만들게 되었습니다.

ListCell을 커스텀하게 만들게 되면 셀에 보여지는 데이터(ContentView)또한 만들어야 합니다. 만약 `ContentView`를 직접 만들지 않는다면 `UICollectionViewListCell`을 상속받은 기본 레이아웃에서 원하는 View를 추가하는 경우만 가능할 것이라고 생각했습니다.

이 때문에 `BoxOfficeListCell`, `BoxOfficeContentView`, `BoxOfficeContentConfiguration` 세 개의 커스텀 타입을 정의했습니다.

`BoxOfficeListCell`에서는 데이터를 주입하고, `BoxOfficeContentConfiguration`에서는 현재 상태에 맞는 구성을 제공해줍니다. 그리고 `BoxOfficeContentView`에서는 화면에 보여지는 셀의 요소들을 보여주는 역할을 합니다.

이와 같이 역할을 분리함으로써 상태에 따른 모든 코드를 같은 객체에 정의하는 것을 피했습니다

### DTO 분리
화면의 보여지는 데이터로는 순위, 순위 변동, 영화 제목, 당일/누적 관객수 정도만 보여지는데 실제 저희가 받아오는 데이터는 이보다 더 많았습니다. 따라서 데이터를 가져올 때 사용하지 않은 데이터들을 없앤 데이터 모델을 따로 만들었습니다.

- 기존 데이터 모델
```swift
struct DailyBoxOffice: Decodable {
    let rowNumber: String
    let rank: String
    let rankIncrement: String
    let rankOldAndNew: String
    let movieCode: String
    let movieName: String
    let openDate: String
    let salesAmount: String
    let salesShare: String
    let salesIncrement: String
    let salesChange: String
    let salesAccumulation: String
    let audienceCount: String
    let audienceIncrement: String
    let audienceChange: String
    let audienceAccumulation: String
    let screenCount: String
    let showCount: String
}
```

- 새로운 데이터 모델
```swift
struct BoxOfficeItem: Identifiable {
    let id = UUID()
    let rank: String
    let rankIncrement: String
    let rankOldAndNew: String
    let title: String
    let audienceCount: String
    let audienceAccumulationCount: String
    
    init(){}
}
```

### Identifiable 프로토콜을 통한 DiffableDataSource 성능향상
기존에는 DiffableDataSource의 Item부분 Identifier로 `struct`타입의 구조체를 넣었습니다.

```swift
struct BoxOfficeItem: Hashable {
    let rank: String
    let rankIncrement: String 
    // ...
}
```

하지만 구조체가 `Hashable`프로토콜을 따른다고해서 과연 유일한 값이 되는건지에 대해서 궁금해져서 다음의 자료를 찾아보았습니다. [Apple - Updating Collection Views Using Diffable Data Sources](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/updating_collection_views_using_diffable_data_sources)

위 공식문서에서는 `DiffableDataSource`의 최적화를 위해 `snapshot`을 통해 데이터 전체를 받는 것이 아닌 식별할 수 있는`id`값만 가질 수 있도록 권장하고 있습니다. 

`Identifiable` 프로토콜은 `ID`라는 associatedtype을 가지고 있고,`id`프로퍼티를 가져야 합니다. 그리고 이 `id`프로퍼티의 타입은 `Self.ID`이기 때문에 프로토콜을 채택하고 난 다음에 결정되는 타입입니다.

그래서 다음과 같이 수정해, Diffable DataSource의 성능을 높였습니다.
```swift
struct BoxOfficeItem: Identifiable {
    let id = UUID()
    let rank: String
    let rankIncrement: String
    // ...
}
```

### dequeueConfiguredReusableCell의 문제점
`tableView`와 마찬가지로 `collectionView`에서도 cell을 재사용하여 UI를 그려주게 됩니다. 따라서 스크롤을 움직여서 몇몇의 `cell`이 안보이게 한 후 다시 그려주는 작업을 수행하게 하면 `cell`의 속성 값이 그대로 남아 적용되는 것을 확인하였습니다. 

처음에는 `prepareForReuse`메서드를 사용하려 했지만 저희의 코드 상 cell이 UI적 요소들을 가지고 있는게 아닌 item이라는 프로퍼티를 가지고 있었기에 `prepareForReuse`를 사용하기가 어려웠습니다.
```swift
final class BoxOfficeListCell: UICollectionViewListCell {
    var item: BoxOfficeItem?
    
    override func updateConfiguration(using state: UICellConfigurationState) {}
}

```

따라서 저희가 해결한 방식은 UI를 그리기 전 재사용되던 속성 값들을 초기화 한 후 다시 UI를 그리는 방법으로 해결하였습니다.

```swift
rankIncrementLabel.text = nil
rankIncrementLabel.textColor = .black
```

## 조언 받고 싶은 점
### dequeueConfiguredReusableCell의 문제점
위에서 말했지만 재사용되는 셀의 속성값이 그대로 유지되는 점을 해결하기 위해 cell의 속성 값을 초기화해주고 다시 그리는 과정을 하여 해결하였는데 혹시 다른 방법이 있는지 궁금합니다.

2023-03-30 11:45 UTC, uuu1101 requested changes
Step3 하시느라 고생하셨습니다 ! @gzzjk159 @seunghyunCheon

몇가지 코멘트 남겨 두었습니다 !

조언 받고 싶은 점 
----
먼저, Mordern Collection View를 사용하신 배경이 있을까요?
Configuration의 라이프 사이클은 어떻게 되나요?
Configuration에 관련된 메서드들은 어떤게 있는지 찾아보시면 좋을것 같습니다.
setNeedsUpdateConfiguration() 에 대해서 한번 알아볼까요..?!

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/Extension/Date+.swift
> +//  Date+.swift
+를 붙이신건 컨벤션으로 정하신건가요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/Model/DTO/BoxOfficeDTO.swift
> +struct BoxOfficeDTO: Decodable {
DTO 는 무엇인가요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
해당 메서드는 무엇을 하는 메서드 인가요? 👀

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeContentConfiguration.swift
> +
해당 부분에 개행이 들어가는 컨벤션이 아니라면, 불필요한 개행 같아보이네요.

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeItem.swift
> +
기존 모델과 사용하는 데이터만 가지고 있는 모델을 분리하신 이유가 궁금합니다.
기존 모델을 불필요한 프로퍼티를 삭제하지 않고 새로운 모델로 만드신 특별한 이유가 있으실까요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/View/BoxOfficeContentView.swift
> +        self.apply(configuration: configuration)
해당부분을 개행을 통해서 분리해두신 이유가 있을까요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/View/BoxOfficeContentView.swift
> +    private func apply(configuration: BoxOfficeContentConfiguration) {
하나의 메서드에서 많은 일들을 해주고 있는것 같습니다 🤔

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/View/BoxOfficeContentView.swift
> +    private func apply(configuration: BoxOfficeContentConfiguration) {
메서드로 나눠볼 수 있을까요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
`lazy` 를 사용하신 이유가 궁금합니다 :)
`lazy` 는 어떤 역할을 하나요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        let layout = UICollectionViewCompositionalLayout(section: section)
줄바꿈을 하는 기준이 어떤것인가요? 
파라미터 1개 이상이면 무조건 줄바꿈을 하는것으로 정하신걸까요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        snapshot.deleteAllItems()
`Snapshot`에 대해서 설명해주실수 있을까요?

2023-03-30 11:45 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        boxOfficeProvider.fetchData(.dailyBoxOffice(date: yesterday),
completion이 escaping 클로저인데 self를 강하게 캡쳐하고 있는데 어떻게 해결 할 수 있을까요?
또한 강하게 캡쳐하면 어떤 문제가 있을까요?

2023-03-30 12:07 UTC, seunghyunCheon commented on BoxOffice/Extension/Date+.swift
> +//  Date+.swift
네 Extension에 대한 내용은 타입+로 하기로 했습니다!

2023-03-30 12:22 UTC, seunghyunCheon commented on BoxOffice/Model/DTO/BoxOfficeDTO.swift
> +struct BoxOfficeDTO: Decodable {
DTO는 `Data Transfer Object`의 약자로 계층 간 데이터 전송을 위해 도메인 모델 대신 사용되는객체입니다. 
어떠한 비즈니스 로직을 가져서는 안되는 특징이 있습니다.

2023-03-30 12:25 UTC, seunghyunCheon commented on BoxOffice/Model/BoxOfficeItem.swift
> +
기존 모델의 불필요한 프로퍼티를 삭제한다는 것이 어떤 의미인지 궁금합니다! 서버에서 전달하는 응답형식은 정해져있기에 UI에 쓰이는 프로퍼티들은 몇가지 존재하지 않아 새로운 모델로 정의했습니다! 

그리고 DTO가 존재하지 않는 경우 추후 기능이 추가가 될 때 하나의 모델로 데이터 전송과 비즈니스 로직들을 다뤄야 하기 때문에 요구사항의 변화에 취약할 것이라고 생각해서 분리했습니다!

2023-03-30 12:29 UTC, gzzjk159 commented on BoxOffice/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
makeAndVisible메서드는 keyWindow로 만들어주는 메서드입니다. 이 메서드를 사용하게 되면 이 윈도우가 가장 앞에 보여지게 할 수 있습니다. 

현재 저희는 코드로만 앱을 구현하기 위해 main.storyboard를 삭제하였습니다. 따라서 저희는 처음 앱을 보여주는 화면을 NavigationViewcontroller로 설정하기 위해 window의 rootViewController를 boxOfficeNavigationViewController로 넣어주고 메서드를 실행하였습니다.

2023-03-30 12:44 UTC, seunghyunCheon commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
`lazy`는 지연저장프로퍼티로 해당 프로퍼티에 접근하는 순간 메모리에 올라가는 특징이 있습니다! 보통 처음 인스턴스가 생성될 때 큰 비용이 드는 프로퍼티나 연산이 큰 작업을 할 때 사용을 하는데 이 부분에서는 그러지 않고 있네요. 

`activityIndicator`를 `lazy`로 선언하게 되면 프로퍼티를 클로저로 정의할 때 다른 프로퍼티에 접근할 수 있기에 사용했던 것 같습니다. (lazy는 인스턴스 초기화 당시에 초기화 되지 않기 때문입니다). 하지만 다른 프로퍼티들은 `lazy`를 사용하고 있지않기에 이를 지워서 컨벤션을 통일했습니다!

2023-03-30 12:53 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        boxOfficeProvider.fetchData(.dailyBoxOffice(date: yesterday),
self를 강하게 참조하게 되면 강한 순환참조가 발생할 수 있다고 생각합니다.
따라서 강한 순환 참조가 일어나지 않게 하기 위해선 [weak self] 붙여 약한 참조를 하게 하였습니다. 9dc39d2500bd2a508b5d2e2a710269d782c3e1e8

2023-03-30 12:55 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        let layout = UICollectionViewCompositionalLayout(section: section)
레이아웃이 어떻게 구성하지는 분류하기 위해서 item, group끼리 분류해서 줄바꿈 하고 나머지는 한꺼번에 모아서 줄바꿈을 하였습니다. 
9dc39d2500bd2a508b5d2e2a710269d782c3e1e8

2023-03-30 12:57 UTC, seunghyunCheon commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +        snapshot.deleteAllItems()
특정 시점의 뷰 내부 데이터 상태를 표현한 것입니다. 
`Diffable data source`는 이 `snapshot`을 이용해서 컬렉션 뷰나 테이블 뷰에 데이터를 제공합니다. 

snapshot내부의 데이터는 화면에 보여지는 section과 item으로 구성되며 이들을 추가, 제거, 이동을 할 수 있습니다. 

`Diffable DataSource`는 이전의 상태 `snapshot`과 현재 새롭게 적용되는 `snapshot`의 차이를 계산해서 뷰를 업데이트합니다. [Apple Docs - apply](https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3375811-apply)

2023-03-30 13:05 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
view의 프로퍼티를 이용하여 레이아웃을 잡아주다 보니 나중에 사용될때 호출되는 lazy var를 사용했던거 같습니다. 현재는 let으로 수정하고 setupUI메서드 안에 넣어주었습니다. 9dc39d2500bd2a508b5d2e2a710269d782c3e1e8

2023-03-30 13:05 UTC, gzzjk159 commented on BoxOffice/View/BoxOfficeContentView.swift
> +        self.apply(configuration: configuration)
뭐가 어색하다는 것 같다는 생각이 들어 현재는 줄바꿈을 없애고 붙여주었습니다. 9dc39d2500bd2a508b5d2e2a710269d782c3e1e8

2023-03-30 13:28 UTC, gzzjk159 commented on BoxOffice/Model/BoxOfficeContentConfiguration.swift
> +
guard 부분이 들어가는 부분아래에 한 칸 띄어주는 컨벤션을 적용해서 작성하였습니다.

2023-03-30 14:18 UTC, seunghyunCheon commented
#### 먼저, Mordern Collection View를 사용하신 배경이 있을까요?
- DiffableDataSource은 기존의 DataSource에 비해 UI상태변화를 단순화하고 hashable한 identifier를 가지고 있는 snapshot을 통해 UI를 업데이트하기 때문에 자동적인 애니메이션이 가능한 점에서 사용을했습니다.
- CompositionalLayout은 신기술이기도 하고 애플 공식문서에서 `DiffableDataSource`와 같이 사용하고 있기에 사용해봤습니다!
- ContentConfiguration의 이점으로 상태에 따른 셀의 외형 코드와 데이터를 주입하는 코드를 분리할 수 있다는 점에서 CollectionViewListCell을 이용했습니다.

#### Configuration의 라이프 사이클은 어떻게 되나요?
1. 셀이 dequeue가 되면서 `updateConfiguration(using state)`메서드를 호출합니다.
2. `cell.defaultContentConfiguration()`을 통해 셀의 기본구성을 가져옵니다.
3.  `updated`메서드를 통해 현재 state에 해당하는 구성을 반환합니다.
4.  반환된 구성에 셀을 구성하고 있는 요소들의 스타일을 상태에 따라 정의합니다.
5. 전부 정의된 구성을 현재 셀의 `contentConfiguration`에 할당합니다.

#### Configuration에 관련된 메서드들은 어떤게 있는지 찾아보시면 좋을것 같습니다.
- `defaultContentConfiguration`: 셀 스타일의 기본 구성을 반환합니다.
-  `setNeedsUpdateConfiguration`: 셀에게 현재 상태에 대한 구성을 업데이트하도록 알리는 메서드입니다. 
    - 이 메서드는 셀의 상태가 변할 때마다 자동으로 호출이 됩니다. 하지만 셀의 커스텀 상태를 추가한다면 자동으로 불려지지 않기 때문에 수동으로 호출해야 합니다.

2023-04-03 04:53 UTC, uuu1101 commented
`refactor: 띄어쓰기 컨벤션 수정, fetchData 메서드 강한순환참조 해결, lazy var 제거' `
해당 커밋도 다른 커밋들 처럼 하나씩 나눠서 커밋하시면 추후에 더 관리하기 좋을 것 같습니다

2023-04-03 04:53 UTC, merged