박스오피스 [STEP 3] 혜모리, 크리스티
yagom-academy/ios-box-office pull request #28
Opened 2023-03-30 06:19 UTC by hyemory

안녕하세요 하비(@havilog)! `모리스티`입니다. 🙇🏻‍♀️🙇🏻‍♀️
이번 리뷰도 잘 부탁드리겠습니다.

---

## 고민했던 점
### 1️⃣ Modern Collection View 구현

이번 프로젝트 핵심 경험에 `Modern Collection View`를 활용해 보라는 내용이 있어 [Implementing Modern Collection Views](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views) 글과 코드를 보고 열심히 구현해 보았습니다.

1. 커스텀 셀 생성 (UICollectionViewListCell)

`defaultBoxOfficeConfiguration`이라는 UIListContentConfiguration을 반환하는 메서드를 만들어 
boxOfficeListContentView를 구현해 주었습니다.

2. 셀 state 생성

configurationState 메서드를 재정의하여 configuration state를 받아 dailyBoxOfficeItem 프로퍼티를 
cell configuration state에 추가하였습니다.

3. snapshot

Section과 Item으로 구성 (작성 중입니다...)

### 2️⃣ URLMaker 리팩토링 (-> KobisURLRequest)
초기 URLMaker `URLSession`을 사용해서 구현했으나, `URLRequest`를 사용한 방식으로 변경했습니다.

### 3️⃣ NSMutableAttributedString 사용

작성 중입니다

2023-03-30 07:30 UTC, havilog requested changes
수고하셨어요~

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Extension/Date+extension.swift
> +}
앱 전역에서 접근할 수 있는데, 현재 사용되는 곳은 `extension Date`밖에 없어서,
fileprivate으로 접근을 제어하던가 extension내부에 구현되어도 괜찮을거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Extension/Date+extension.swift
> +    func showYesterdayDate(format: HyphenStatus) -> String {
dateFormatter를 static하게 가지고 있는것보다는,
showYesterdayDate함수에서 포매터를 만들어주던가,
파라미터로 포매터를 받아와도 괜찮을거 같아요.

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Extension/Date+extension.swift
> +            Date.dateFormatter.dateFormat = "yyyy-MM-dd"
이 dateFormat을 HyphenStatus의 property로 가지고 있으면 코드가 더 예뻐질거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Extension/String+extension.swift
> +extension String {
해당 extension들은, 앱에서 전역적으로 사용되기 보다는, 특정 기능에서만 사용하고 있는거 같아요. (dropFirst 같은 로직을 보면)

따라서 현재는 앱이 작아서 괜찮겠지만, 
공통적으로 쓰이는 extension과, 코드를 이쁘게 하기 위해 지역적으로 사용하는 extension의 구분이 필요할거 같아요.

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Network/KobisURLRequest.swift
> +struct KobisURLRequest {
요것도 틀린건 아닌데, 
대체할 단어가 없으면 고유명사로 프리픽스를 박는건 팀원들의 선택이긴 한데요,
만약 모든 개발자가 Kobis를 알고있다면 상관 없지만, 그렇지 않고 특정 도메인의 개발자만 알고있다면 Movie라던가 더 포멀한 이름을 사용하는게 낫지 않을까 싶어요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/View/Base.lproj/LaunchScreen.storyboard
보통 런치스크린은 뷰보다는 리소스 쪽에 포함시키는거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +}
접근제어가 필요해요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, DailyBoxOfficeItem>!
이것도 취향의 부분이긴 한데, 저는 강제캐스팅보단, lazy var를 선호해요

앱이 죽는것 보단 아무것도 안보여주는게 낫다고 생각해서..

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private let networkManager = NetworkManager()
몇 번 말씀드린 의존성 주입이 필요한 부분이지만 ..
해당 프로젝트에서 챙길 리소스가 없다면 .. 패스

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        api.addQuery(name: queryName, value: queryValue)
쿼리를 만드는 부분은 URLRequst를 만들 때 해줘야할거 같아요~

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        networkManager.fetchData(urlRequest: urlRequest, type: BoxOffice.self) { result in
completion이 escaping 클로저인데 self를 강하게 캡쳐하고 있네요~

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                print(error.localizedDescription)
에러에 대한 핸들링은 다음 스탭에서 처리하실 계획이실까요?

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        collectionView = UICollectionView(frame: view.bounds,
오토레이아웃이 아니라, 프레임 기반으로 잡으신 이유가 뭘까요?

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) { [weak self] in
0.7의 의미는 무엇인가요?

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        }
얘는 지금 api를 호출할 때마다 셀을 다시 등록할거 같은데요
요건 좀 크리티컬해서 한 번만 등록하도록 변경해야할 거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
만약 2번째 페이지에서 10개를 더 받아온다고 했을 때 어떻게 구현할지에 대한 고민도 있으면 좋을거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/View/BoxOfficeListCell.swift
> +extension UIConfigurationStateCustomKey {
얘는 처음 보는 아이네요..!
이 친구를 선택하신 이유와, 어떻게 동작하는 지 설명해주실 수 있으실까요?

2023-03-30 07:30 UTC, havilog commented on BoxOffice/View/BoxOfficeListCell.swift
> +        }
enum으로 만들 수는 없었을까요?

2023-03-30 07:30 UTC, havilog commented on BoxOffice/View/BoxOfficeListCell.swift
> +    private let rankStackView = RankStackView()
이 뷰를 분리하신 이유는 뭔가요?

외부에서 RankStackVIew의 프로퍼티에 접근해서 데이터를 바꿀 수 있어서 데이터의 일관성이 잘 보장되지 않을거 같아요

2023-03-30 07:30 UTC, havilog commented on BoxOffice/View/BoxOfficeListCell.swift
> +        setNeedsUpdateConfiguration()
이 코드도 잘 이해가 안되는데 .. self에서 들고 있는 이유는 setNeedsUpdateConfiguration를 활용하기 위함인거 같은데,

setupViewsIfNeeded도 계속 불려서 셀의 데이터가 바뀔 때마다 제약조건도 다시 잡을거 같아요

커스텀 셀을 안 만들고 기본적으로 제공해주는 셀을 사용하려고 하신 의도가 잘 파악되지 않아서 설명해주시면 좋을거 같아요

2023-03-31 05:35 UTC, christy-hs-lee commented on BoxOffice/Extension/Date+extension.swift
> +}
해당 부분 `extension` 내부에 구현하여 수정했습니다!

2023-03-31 05:35 UTC, hyemory commented on BoxOffice/Extension/Date+extension.swift
> +    func showYesterdayDate(format: HyphenStatus) -> String {
DateFormatter를 매개변수로 받도록 수정했습니다!

``` swift
func showYesterdayDate(formatter: DateFormatter, in status: HyphenStatus) -> String {
    let yesterday = Date().addingTimeInterval(3600 * -24)
    
    formatter.dateFormat = status.format
    
    guard let value = formatter.string(for: yesterday) else { return "" }
    
    return value
}
```

2023-03-31 05:36 UTC, christy-hs-lee commented on BoxOffice/Extension/Date+extension.swift
> +            Date.dateFormatter.dateFormat = "yyyy-MM-dd"
HyphenStatus의 property로 가지고 있을 수 있도록 아래와 같이 수정했습니다!

```swift
switch self {
            case .existHyphen:
                return "yyyy-MM-dd"
            case .notHyphen:
                return "yyyyMMdd"
            }
```

2023-03-31 05:37 UTC, hyemory commented on BoxOffice/Extension/String+extension.swift
> +extension String {
특정 기능에서만 사용되는 extension은 기능이 사용되는 파일에 모아두었습니다
4642717cd3d0c4c097b7e47e143142cb729cd5ef

2023-03-31 05:37 UTC, christy-hs-lee commented on BoxOffice/Network/KobisURLRequest.swift
> +struct KobisURLRequest {
`BoxOfficeURLRequest`로 수정했습니다!

2023-03-31 05:38 UTC, hyemory commented on BoxOffice/View/Base.lproj/LaunchScreen.storyboard
Assets, LaunchScreen, Info 파일을 Resource 폴더로 옮겼습니다!

2023-03-31 05:39 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, DailyBoxOfficeItem>!
collectionView에 기본값을 주도록 수정해 보았습니다~!

2023-03-31 05:39 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +}
해당 부분은 `Modern Collection View`를 사용할 때 필요했던 부분으로, 현재는 삭제된 코드입니다!

2023-03-31 05:40 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        networkManager.fetchData(urlRequest: urlRequest, type: BoxOffice.self) { result in
`[weak self]`를 추가하여 수정했습니다!

2023-03-31 05:43 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        collectionView = UICollectionView(frame: view.bounds,
`collectionView`가 view를 가득 채울 수 있도록 프레임 기반으로 설정했었습니다.

2023-03-31 05:47 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        }
`Custom Cell`사용하는 방식으로 변경하며 해당 부분 수정했습니다!

2023-03-31 05:50 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        api.addQuery(name: queryName, value: queryValue)
queries라는 Dictionary에 쿼리를 담아주고 있는데
반드시 한 곳에서 한 번에 모두 담지는 않을수도 있지 않을까해서 분리해 두었습니다
혹시 메서드를 합치면 어떤 점이 좋은 걸까요?

2023-03-31 05:50 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                print(error.localizedDescription)
실패하면 Alert을 띄워주도록 수정하였습니다

2023-03-31 05:53 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) { [weak self] in
refresh 할 때 뷰가 너무 빠르게 올라가 버리는 감이 있어서
드래그 하고 잠깐동안 멈추게 하고 싶어 적용하였습니다.

2023-03-31 06:00 UTC, christy-hs-lee commented on BoxOffice/View/BoxOfficeListCell.swift
> +extension UIConfigurationStateCustomKey {
`configurationState`에 추가할 뷰의 custom state를 정의합니다.
이후 `UIConfigurationState`에서 커스텀한 state를 만들기 위해 사용됩니다! 
`UIConfigurationStateCustomKey`를 사용하여 custom state key를 정의하면 state를 cell configuration state에 추가해줄 수 있습니다.

2023-03-31 06:03 UTC, christy-hs-lee commented on BoxOffice/View/BoxOfficeListCell.swift
> +    private let rankStackView = RankStackView()
일관성을 생각하지 못 하고 분리 했었습니다. 해당 부분 `Custom Cell` 사용하는 방식으로 수정하며 변경되었습니다!

2023-03-31 06:17 UTC, hyemory commented on BoxOffice/View/BoxOfficeListCell.swift
> +        }
enum으로 문구, 폰트 색상 넣어주었습니다!

``` swift
enum RankInfo {
    case new
    case noChange
    case increase(Int)
    case decrease(Int)
    
    var description: String {
        switch self {
        case .new:
            return "신작"
        case .noChange:
            return "-"
        case .increase(let variance):
            return "▲\(variance)"
        case .decrease(let variance):
            return "▼\(variance * -1)"
        }
    }
    
    var fontColor: UIColor {
        switch self {
        case .new:
            return .systemRed
        case .noChange:
            return .black
        case .increase:
            return .systemRed
        case .decrease:
            return .systemBlue
        }
    }
}
```

2023-03-31 06:18 UTC, hyemory commented on BoxOffice/View/BoxOfficeListCell.swift
> +        setNeedsUpdateConfiguration()
커스텀 셀로 코드 수정하였습니다!!!

2023-03-31 06:29 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
어떤 경우인지 잘 이해가 되지 않습니다!

2023-04-02 05:07 UTC, merged