박스오피스 [STEP 3] 레옹아범, Andrew
yagom-academy/ios-box-office pull request #29
Opened 2023-03-30 09:33 UTC by Andrew-0411

@1Consumption 안녕하세요 올라프 레옹아범, Andrew입니다.
박스오피스 STEP 3 PR 보내드립니다.
Mordern Collection View(UICollectionViewDiffableDataSource ,UICollectionViewListCell)를 사용하여 구현을 해봤습니다.
일반 Collection View와는 다르게 처음 접하는 것들이 많아서 힘들었지만 새로운 방식을 배우게 되어서 뜻깊은 시간이었던거 같습니다 😄

## 고민했던점

### 1️⃣ DataSource vs DiffableDataSource 어떤것을 사용할까?

#### ❓문제점
* DiffableDataSource로 꼭 구현할 필요는 없지만
* DataSource와 DiffableDataSource의 차이점과 왜 기존 DataSource외에 추가적으로 DiffableDataSource가 나왔는지에 대해 공부하고 어떤것을 사용할것인지에 대해 고민했습니다.

#### 📖해결법
[wwdc19 - Advances In UI Data Source](https://developer.apple.com/videos/play/wwdc2019/220)

* 위 영상 내용을 참고했습니다.
* DataSource와는 다르게 DiffableDataSource의 경우 아이템의 변화에따라 애니메이션이 추가된다는 점
* IndexPath를 사용하던 DataSource와는 다르게 각각의 섹션과 아이템을 `Hashable`을 채택한 타입으로 서로 구별할 수 있어 이전에 IndexPath의 섹션과 아이템의 수에 따라서 변화를 주던 방식을 탈피할 수 있는 점 등
* 위 이유와 dataSource는 ios6, diffableDataSource는 ios13에서 사용 가능하여 비교적 최근꺼인 diffableDataSource를 사용하였습니다.

```swift
struct InfoObject: Decodable, Hashable {
}

enum APIType: Hashable {
}
```

* 이 외에 각각의 섹션과 아이템을 구별할 수 있도록 `Hashable`프로토콜을 채택해주었으며, 열거형의 경우 기본적으로 `Hashable`을 채택하지 않아도 되지만 저희 `APIType`와 같이 연관값을 가지고 있다면 써줘야하므로 `Hashable`을 채택했습니다.

### 2️⃣ Snapshot 활용

#### ❓문제점
* 새로고침을 할 경우 기존 스냅샷에 있는 데이터와 같은 데이터가 들어와 `snapshot.appendItems(movieItems)`를 해줄 경우

```
Diffable data source detected an attempt to insert or append 10 item identifiers that already exist in the snapshot.......
```

* 위와 같이 동일한 `identifiers`가 들어와 경고문을 보내는 문제가 있었습니다.

#### 📖해결법

* 위와 같이 기존에 덮어쓰기를 할 경우 기존의 항목들이 다시 원래자리로 돌아가는데 이럴 경우 작업비용이 더 많이 든다라는 추가 문구가 있어서 아래와 같이 코드를 작성하였습니다.

```swift
private func applySnapshot() {
    snapshot.deleteItems(movieItems)
        
    snapshot.appendItems(movieItems)
        
    dataSource.apply(snapshot, animatingDifferences: true)
}
```

* 기존 `snapshot`의 아이템을 지운 이후에 데이터를 넣어주는 방식으로 해결하였습니다.

## 조언을 얻고 싶은 점

### 1️⃣ UI를 작성하는 방법
```swift
private var collectionView: UICollectionView!

private func configureCollectionView() {
    let configuration = UICollectionLayoutListConfiguration(appearance: .plain)
    let layout = UICollectionViewCompositionalLayout.list(using: configuration)

    collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
    collectionView.register(MovieRankingCell.self, forCellWithReuseIdentifier: MovieRankingCell.identifier)
}
```

```swift
private let collectionView = {
    let configuration = UICollectionLayoutListConfiguration(appearance: .plain)
    let layout = UICollectionViewCompositionalLayout.list(using: configuration)
    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        
    collectionView.register(MovieRankingCell.self, forCellWithReuseIdentifier: MovieRankingCell.identifier)
        
    return collectionView
}()
```

- 기존 UI이니셜라이저를 하는 방법으로 두가지를 생각했습니다.
- 첫번째 방법의 경우 메소드로 사용할 경우 모든 프로퍼티를 한눈에 보기 편하다는 장점이 있을 것 같고,
- 두번째 방법의 경우 하나의 프로퍼티에 대한 정보를 간략히 볼 수 있다는 장점이 있을것 같습니다.
- **방법의 차이가 있을 뿐 결과는 똑같이 나오는데 올라프가 선호하시는 방법이 무엇인지 궁금합니다**

2023-03-30 12:42 UTC, 1Consumption requested changes
@Andrew-0411 @fatherLeon 고생하셨습니다.
새로운 CollectionView API를 사용한게 인상깊네요. 또한 WWDC를 통해 잘 학습해주신듯 합니다. 👍 

아래는 고민하신 점에 대한 제 생각입니다.

-------------------------------------------------

> 기존 UI이니셜라이저를 하는 방법으로 두가지를 생각했습니다.
첫번째 방법의 경우 메소드로 사용할 경우 모든 프로퍼티를 한눈에 보기 편하다는 장점이 있을 것 같고,
두번째 방법의 경우 하나의 프로퍼티에 대한 정보를 간략히 볼 수 있다는 장점이 있을것 같습니다.
**방법의 차이가 있을 뿐 결과는 똑같이 나오는데 올라프가 선호하시는 방법이 무엇인지 궁금합니다**

저는 우선 프로덕트 코드에서는 강제언래핑을 절대 하지 않습니다. 따라서 첫번째 방법은 애초에 탈락이고요... 
그렇다면 `클로저를 통해 생성과 설정을 한번에 해줄 것이냐`, 아니면 `일단 생성하고 추후 메소드를 통해 설정해줄 것이냐`로 나뉘는데요.
저는 관심사를 한곳에 모을 수 있어서 전자를 선호합니다. 

-----------------------------------------------------------------------------------------------------------------------

코멘트 확인 부탁드리겠습니다!

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/Extension/Date+extension.swift
> +    }
yesterday인데, guard문을 통과하지 못하면 현재가 반환되네요. 이런 경우는 옵셔널을 활용하고, 사용하는 곳에서 에러처리를 하는게 더 정확합니다.

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/Extension/Date+extension.swift
> +    }()
내부에서만 쓰이니 private으로 변경하는게 좋지 않을까요?

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/Extension/Date+extension.swift
> +    }
이 메소드들이 정말 Date의 extension에 들어갈 정도로 자주 쓰이나요? 아니면 특정 부분에서만 쓰이고 있나요?
만약 특정 부분에서만 쓰이고 있다면 그 부분에 들어가는건 어떨까요?

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/Model/DTO/BoxofficeDTO/InfoObject.swift
> +import UIKit
여기는 모델 레이어 같은데 왜 UIKit이 들어갔을까요?

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/Model/DTO/BoxofficeDTO/InfoObject.swift
> +    }
이 로직은 여기가 아니라 `InfoObject`를 관리하는 객체에서(없다면 만들어야겠죠) 담당하면 더 좋겠습니다.

2023-03-30 12:42 UTC, 1Consumption commented on BoxOffice/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 코드는 어떤식으로 동작하나요? 코드를 설명해주시겠어요?

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +                                                   model: NetworkModel(session: .shared))
이 정보는 view에서 몰라도 되는 정보같아요. 하나의 객체에서 관리하면 좋겠습니다.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<APIType, InfoObject>!
강제언래핑을 사용하셨네요. 옵셔널이면 안되나요?

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +    private var snapshot = NSDiffableDataSourceSnapshot<APIType, InfoObject>()
이 스냅샷을 프로퍼티로 들고있어야하는 이유가 있을까요?

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        configureRefreshController()
네트워크 요청은 view가 다 들어가고 나서 해야할듯합니다.
지금은 네트워크 요청을 하고 refreshController를 설정하고 있네요.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        }
현재 viewDidLoad에서만 불리는거같은데, DispatchQueue.main으로 감싸준 이유가 있을까오?

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
1초 딜레이 준 이유가 궁금합니다. 별다른 이유가 없다면 매직넘버는 지양해주세요.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +}
extension으로 나눈 기준이 모호합니다. 제가봤을때는 다 같은 UI에 속하는 extension 같아서요.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +                return
이때는 알러트를 띄워서 사용자에게 오류발생을 알려야하지 않을까요?

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +
그냥 스냅샷을 매번 생성하고 apply하면 안되나요? 어차피 변경점만 업데이트될텐데요.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        snapshot.appendSections([apiType])
appendSections는 applySnapshot 메소드 내부에서 진행되어야할듯 합니다.

2023-03-30 12:42 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        })
UICollectionView.CellRegistration에 대해서도 공부해보세요.

2023-03-30 12:42 UTC, 1Consumption commented on View/MovieRankingCell.swift
> +class MovieRankingCell: UICollectionViewListCell {
상속되지 않는 클래스 같습니다.

2023-03-30 12:42 UTC, 1Consumption commented on View/MovieRankingCell.swift
> +    }
값을 직접 변경하지말고, 인터페이스를 하나 뚫어서 전달하는식으로 변경해보세요.

2023-03-31 05:22 UTC, Andrew-0411 commented on BoxOffice/Extension/Date+extension.swift
> +    }
```swift
static var yesterday: Date? {
    return Calendar.current.date(byAdding: .day, value: -1, to: Date())
}
```
Date를 옵셔널 타입으로 반환하게끔 변경하였습니다

2023-03-31 05:32 UTC, Andrew-0411 commented on BoxOffice/Extension/Date+extension.swift
> +    }
MovieRankingViewController에서 사용하는곳에 직접 넣어주었습니다

2023-03-31 05:34 UTC, Andrew-0411 commented on BoxOffice/Extension/Date+extension.swift
> +    }()
private으로 변경하였으나 MovieRankingViewController에서 사용되므로 다시 접근제한자를 변경하였습니다

2023-03-31 05:38 UTC, fatherLeon commented on BoxOffice/Model/DTO/BoxofficeDTO/InfoObject.swift
> +import UIKit
`var rankStatusTextColor`의 타입인 `UIColor`가 `UIKit`으로 사용할 수 있기 때문에 `UIKit`을 import해줬었는데 아래 리뷰를 토대로 새 타입을 만들면서 해당 부분을 삭제했습니다.

2023-03-31 06:13 UTC, Andrew-0411 commented on BoxOffice/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
- UIWindowScene은 여러 window를 관리하며 App UI의 전반적인 기능을 관리하는 하나의 객체로 하나의 인스턴스만 존재합니다.
- UIWindow는 컨트롤러 함께 작동하며 사용자의 이벤트를 처리하거나 많은 작업을 수행합니다.

<br />
<br />


```swift
guard let windowScene = (scene as? UIWindowScene) else { return }
```
- UIWindowSceneDelegate 프로토콜의 메서드를 이용하여 scene을 다운캐스팅하여 UIwindowScene의 인스턴스를 만듭니다.
        
```swift
window = UIWindow(windowScene: windowScene)
```
- window를 만들고 정의한 windowScene 인스턴스와 연결합니다.

```swift!
window?.rootViewController = UINavigationController(rootViewController: MovieRankingViewController())
```
- Entry Point(시작지점)가 될 rootViewController의 ViewController를 설정합니다.

```swift!
window?.makeKeyAndVisible()
```
- UIWindow 인스턴스의 초기값은 isHidden속성은 true인데 makeKeyAndVisible 메서드를 호출함으로써 isHidden 속성을 false로 설정하고 window 인스턴스를 keyWindow로 설정해줍니다.

2023-03-31 06:28 UTC, Andrew-0411 commented on Controller/MovieRankingViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<APIType, InfoObject>!
```swift
private var dataSource: UICollectionViewDiffableDataSource<APIType, InfoObject>?
```
dataSource 프로퍼티에 옵셔널을 사용하도록 변경하였습니다

2023-03-31 06:32 UTC, Andrew-0411 commented on Controller/MovieRankingViewController.swift
> +    private var snapshot = NSDiffableDataSourceSnapshot<APIType, InfoObject>()
snapshot을 사용하는 메서드에만 넣어주어서 지역변수로 만들어주었습니다

2023-03-31 06:53 UTC, fatherLeon commented on Controller/MovieRankingViewController.swift
> +        }
그런 부분은 크게 생각을 못하고 코드를 작성한것 같습니다
현재 수정하였습니다!!

2023-03-31 07:01 UTC, fatherLeon commented on View/MovieRankingCell.swift
> +    }
```swift
func updateLabelText(for dataManager: DataManager) {
    //.....
    self.rankStatusLabel.attributedText = dataManager?.rankStatusAttributedText
    //.....
}
```

* 위와 같이 메소드를 구현하여 `DataManager`타입을 받아 사용할 수 있도록 만들었습니다

2023-03-31 08:37 UTC, Andrew-0411 commented on Controller/MovieRankingViewController.swift
> +                                                   model: NetworkModel(session: .shared))
MovieRankingViewController 데이터를 관리해 주는 RankingManager 객체를 새로 만들어서 이동하였습니다

2023-03-31 08:37 UTC, fatherLeon commented on BoxOffice/Model/DTO/BoxofficeDTO/InfoObject.swift
> +    }
```swift
struct InfoManager {
    private var data: InfoObject
    //......
}
```

* 위와 같이 타입을 만들어 해당 로직을 추가하였습니다.

```swift
guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MovieRankingCell.identifier, for: indexPath) as? MovieRankingCell else { return UICollectionViewListCell() }
            
    let infoManager = InfoManager(data: itemIdentifier)
            
   cell.updateLabelText(for: infoManager)
            
    return cell
```

* 추가로 DataSource내에서 해당 객체의 인스턴스를 생성하여 cell의 메소드에 넣어 뷰를 업데이트하는 방식으로 변경하였습니다.

2023-03-31 08:41 UTC, fatherLeon commented on Controller/MovieRankingViewController.swift
> +
```swift
    private func applySnapshot() {
        var snapshot = NSDiffableDataSourceSnapshot<APIType, InfoObject>()
        
        snapshot.appendSections([dataManager.apiType])
        snapshot.appendItems(dataManager.movieItems)
        
        dataSource?.apply(snapshot, animatingDifferences: true)
    }
```
* 말씀하신것 처럼 스냅샷 인스턴스를 만들어 섹션과 아이템을 주도록 변경하였습니다

2023-03-31 08:50 UTC, Andrew-0411 commented on Controller/MovieRankingViewController.swift
> +                return
```swift
    private func presentErrorAlert(error: Error) {
        let alert = UIAlertController(title: error.localizedDescription,
                                      message: nil,
                                      preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "확인", style: .default))
        present(alert, animated: true, completion: nil)
    }
```
- alert창을 만들어서 상황에 맞는 오류를 alert창으로 나타나도록 구현하였습니다

2023-03-31 08:57 UTC, fatherLeon commented on Controller/MovieRankingViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
* 처음에는 너무 빠르게 리로딩되었고, UIRefreshControl이 부자연스럽게 동작되어 딜레이를 줬었습니다.

```swift
private func fetchBoxofficeData() {
    dataManager.boxofficeInfo.fetchData { [weak self] result in
        switch result {
        case .success(let data):
            self?.dataManager.movieItems = data.boxOfficeResult.movies
            DispatchQueue.main.async {
                //...
                self?.collectionView.refreshControl?.endRefreshing()
            }
            //....
    }
}
    @objc private func refreshCollectionView() {
        self.fetchBoxofficeData()
    }
```

* `collectionView.refreshControl?.endRefreshing()`을 `fetchBoxofficeData`의 성공케이스에 줌으로 UI를 조금 더 자연스럽게 변경하였고
* 딜레이를 주지 않아 매직넘버를 삭제할 수 있었습니다.

2023-04-03 04:44 UTC, merged