박스오피스 [STEP4] sehong
yagom-academy/ios-box-office pull request #30
Opened 2023-03-31 06:51 UTC by sehoong0429

#step4
@AppleCEO
안녕하세요 도미닉!
드디어 마지막 관문인 step4 PR올립니다!ㅎㅎ 

지금까지 잘 알려주셔서 감사합니다! 
이번 마지막 스텝도 잘 부탁드리겠습니다🙇🏻‍♀️

## 구현한 내용 
이번스텝에서는 영화의 상세내용을 확인할 수 있는 화면을 구현하는게 목적이었습니다. 
영화의 포스터 이미지를 다음 이미지 검색 API를 활용하는 부분은 영화 진흥위원회API를 활용하는 부분과 비슷하게 구현할 수 있어서  
큰 어려움은 없을거라고 생각했지만 사소한 에러들과 열심히 싸운다고 너무 힘들었던 것 같습니다ㅠㅠ 

### 1️⃣ ImageView extension 구현 

이미지를 가져올 때 이미지가 크면 제가 사이즈를 조절해주더라도
줄여준 만큼 여백이 생기는 문제가 있었습니다. 
`scale`을 이용해서 이미지의 크기를 조절할 수 있도록 했습니다.
원본 이미지의 가로 크기와 UIImageView의 가로 크기를 비교하여 이미지의 스케일을 계산하고, 이용해 UIImage를 생성하는 방식입니다.

데이터에서 이미지를 만드는 과정이 메모리를 많이 사용하는데, 
이런 방식으로 구현하면 imageView에 맞게 크기를 지정해서 불필요한 메모리 사용을 줄일 수 있습니다.   

```swift
extension UIImageView {
    
    func load(url: URL, originalWidth: Int = 0) {
        let viewWidth = frame.width
        
        DispatchQueue.global().async { [weak self] in
            guard let self = self, let data = try? Data(contentsOf: url) else { return }
            
            let scale = CGFloat(originalWidth) / CGFloat(viewWidth)
            
            let image = UIImage(data: data, scale: scale)
            
            DispatchQueue.main.async {
                self.image = image
            }
        }
    }
    
}
```

### 2️⃣ Custom log 사용 

커스텀 로그를 사용하면 코드의 실행 흐름을 쉽게 파악할 수 있습니다. 로그를 통해 아래와 같이 함수 호출, 에러 발생 위치 등의 정보를 정확하게 확인 할 수 있어서 사용하게 되었습니다.

![](https://i.imgur.com/p9B5LMu.png)

```swift
func DEBUG_LOG(_ msg: Any, file: String = #file, function: String = #function, line: Int = #line) {
    #if DEBUG
    let filename = file.split(separator: "/").last ?? ""
    let funcName = function.split(separator: "(").first ?? ""
    print("😡[\(filename)] \(funcName) (\(line)): \(msg)")
    #endif
}
```

### 3️⃣ 이미지 로드 Indicator 사용 

이미지 로드를 하는 동안 나타낼 Indicator를 구현해보았습니다. 
해당 코드가 간단할거라고 생각했는데 제약조건을 구현하는 부분에서 어려움을 겪었습니다. Indicator는 크기를 가지고 있어서 이미지뷰 왼쪽 오른쪽 사이즈를 맞춰주면 이미지 사이즈가 Indicator에 맞춰서 작아지는 문제가 발생했습니다. 이부분은 Indicator 제약 조건을 이미지뷰의 X축 Y축을 맞춰서 이미지의 정중앙에 위치할 수 있도록 맞추면서 해결할 수 있었습니다.   

```swift
imageView.addSubview(indicatorView)
NSLayoutConstraint.activate([
    indicatorView.centerXAnchor.constraint(equalTo: imageView.centerXAnchor),
    indicatorView.centerYAnchor.constraint(equalTo: imageView.centerYAnchor),
])

```

2023-03-31 15:40 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
최종 스텝까지 모두 수고하셨습니다.
상세 항목을 눌러서 들어갔다가 나왔을 때 셀이 눌려있는데 수정해보면 좋을 것 같아요!
코멘트들 참고하시면 좋겠습니다~

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }
하나의 객체가 하나의 역할만 맡는 것이 좋습니다!
이 함수를 수행할 다른 객체를 만들어줄 수 있을까요?

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }
그냥 숨기기만 하는 것이 아니라 애니메이션을 멈추는 것까지 확실하네요! 👍

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/Model/ImageAPI.swift
> +        return "add584f521686e2b3defebd44c63cdfb"
이렇게 key 가 깃 상에 노출되면 다른 사람이 이용할 수 있는데요.
비공개로 숨길 수 있는 방법은 어떤게 있을까요?

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/Model/MovieInfoItem.swift
> +        case actorName = "peopleNm"
오 더 명확한 이름으로 변경하셨네요! 🔢 
actor 라는 객체 이름에서 유추할 수 있어서 name 으로만 변경해도 괜찮을 수 있겠네요~

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    private let mainStackview: UIStackView = {
StackView 로 V 를 대문자로 적어주시면 더 좋겠습니다 ㅎㅎ
이런 사소한 소문자, 대문자 차이로 같은 객체로 인식이 안되는 경우도 있어서 앞으로 잘 살피시면 좋습니다!

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +        static let productionYear = "제작년도"
오호 rawValue 가 아닌 static let 으로 값을 저장해보셨군요~
고급진 문법입니다. 🥇 
rawValue 로 케이스들을 처리할 때와 어떤 차이가 있을까요?

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }()
그냥 스크롤뷰라고만 이름 짓기보다 어떤 내용이 들어갈지 이름이 더 명확하고 길어지면 좋겠습니다!
개발을 하다보면 이렇게 scrollView 라고만 하면 iOS의 기본 객체와 이름이 중복되면서 선언이 제대로 안되는 경우도 있어서요~

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }()
아래 이미지 뷰도 마찬가지입니다.

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +                    let movieInfo: MovieInfoItem = try JSONConverter.shared.decodeData(data, T: MovieInfoItem.self)
오~ 디코딩 방식이 말끔하네요! 💯

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +        indicatorView.startAnimating()
이 코드들도 stopIndicator() 처럼 별도 함수로 빼낼 수 있으면 좋겠네요.
그러면 start, stop 이 쌍을 이뤄서 처음 보는 사람도 조금 더 쉽게 알아볼 수 있겠습니다!

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +                        if let imageInfo = imageInfo, let url = URL(string: imageInfo.imageUrl) {
여기는 guard let 보다 if let 이 더 적합한 곳인데 잘 작성하셨네요~
어떤 기준점이 있었을까요?

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +        imageView.addSubview(indicatorView)
ㅎㅎ 이 코드도 152번째 줄에 위치해서 더 정돈할 수 있겠네요!

2023-03-31 15:40 UTC, AppleCEO commented on BoxOffice/Extensions/UIImageview+load.swift
> +            let scale = CGFloat(originalWidth) / CGFloat(viewWidth)
여기 CGFloat(originalWidth) 대신에 originalWidth 을 넣으면 결과가 다를까요?

2023-04-02 15:40 UTC, sehoong0429 commented
> ddbea47

셀이 눌러져 있는 부분은 viewWillAppear 함수를 구현하여 해결해주었습니다..!

2023-04-02 15:41 UTC, sehoong0429 commented
> 상세 항목을 눌러서 들어갔다가 나왔을 때 셀이 눌려있는데 수정해보면 좋을 것 같아요! 코멘트들 참고하시면 좋겠습니다~

해당 부분은 viewWillAppear함수를 사용해서 해결해주었습니다..! 
 [ddbea47](https://github.com/yagom-academy/ios-box-office/pull/30/commits/ddbea471857932f6045233dd7c9ee748c826f5aa)

2023-04-02 15:43 UTC, sehoong0429 commented on BoxOffice/Model/ImageAPI.swift
> +        return "add584f521686e2b3defebd44c63cdfb"
[f130e1a](https://github.com/yagom-academy/ios-box-office/pull/30/commits/f130e1ac3a969791e0dc946f4bc7e1fc4ab01c7d)

해당 부분은 APIKey를 담고 있는 모델을 구현하고, 해당 파일을 ignore파일에 담아서 비공개로 숨겨주었습니다.
movieApi 키 또한 함께 넣어주었습니다. 
Info.plist를 만들어서 이용하는 방법도 있었지만 간단하게 구현해보았습니다.

2023-04-02 15:43 UTC, sehoong0429 commented on BoxOffice/Model/MovieInfoItem.swift
> +        case actorName = "peopleNm"
[a92c27a](https://github.com/yagom-academy/ios-box-office/pull/30/commits/a92c27aac96a8249c1787adb65848196d00a5e79)
해당 부분 수정하였습니다!

2023-04-02 15:43 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +    private let mainStackview: UIStackView = {
[30b422e](https://github.com/yagom-academy/ios-box-office/pull/30/commits/30b422e0e27a8408334be8d2ec5982d52826f630)
해당 부분 수정해주었습니다.

2023-04-02 15:47 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +        static let productionYear = "제작년도"
rawValue를 사용하는 방식은 각 케이스에 대한 초기값을 가질 수 있습니다. 고정된 타입을 선언해주어야하는걸로 알고 있습니다. 
static let을 각 상수에 다양한 타입의 값을 할당할 수 있고, 원시값을 사용하여 인스턴스를 생성할 수 있습니다. 

원시값이 필요하고 각 케이스가 고유한 값을 가져야하는경우에는 rawValue를 사용하고, 
그렇지 않으면 Static let 을 사용하는게 좋을 것 같다고 느껴집니다!

2023-04-02 15:48 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }()
DetailMovieInfoView에는 하나의 스크롤뷰와 하나의 이미지뷰를 사용하고 있어서 ImageView, scrollView라고만 선언을 해주는것도 문제가 없을거라고 생각했습니다. 해당 부분 고려해서 이름을 명확하게 지어보겠습니다..!

2023-04-02 15:49 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +        indicatorView.startAnimating()
[a06e8a2](https://github.com/yagom-academy/ios-box-office/pull/30/commits/a06e8a2ac0a56e11a46d4df37113f66e97fcefb2)
start함수를 만들어 구현해보았습니다.

2023-04-02 15:52 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +                        if let imageInfo = imageInfo, let url = URL(string: imageInfo.imageUrl) {
`if let 사용 기준`
- if let은 옵셔널 바인딩이 성공한 경우에만 실행되는 블록을 정의하고 바인딩에 실패한 경우에는 해당 블록을 건너뛰고 계속 실행됩니다.

위 예제에서는 옵셔널 바인딩이 성공한 경우 이미지를 로드하고 인디케이터를 중지시키는 동작이 이루어집니다. 
만약 옵셔널 바인딩에 실패한다면, 이 부분을 건너뛰고 다음 코드를 계속 실행하게 됩니다.

즉 if let을 사용한다는 기준은 
1. 옵셔널 바인딩이 실패한 경우에도 코드 실행이 계속 진행되어야 할 때
2. 옵셔널 바인딩 결과에 따른 처리가 간단하고 가독성이 좋을때 

`guard let 사용 기준`
- guard let은 옵셔널 바인딩이 실패한 경우에 빠른 종료를 하고자 할 때 사용됩니다

1. 옵셔널 바인딩이 실패한 경우 코드 실행을 중지하고 싶을 때 (보통 에러 처리나 반환)
2. 옵셔널 바인딩 결과를 함수 또는 클로저의 나머지 부분에서 계속 사용하고자 할 때 (범위 확장)

위와 같은 기준을 세워서 이미지 로딩이 실패해도 다른 코드 실행에 큰 영향을 주지 않아 if let을 사용하는 것이 적합한것 같습니다.ㅎㅎ

2023-04-02 15:52 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +        imageView.addSubview(indicatorView)
[f099d37](https://github.com/yagom-academy/ios-box-office/pull/30/commits/f099d372147e6fbcf6f0ca98463c315fc0d8ad47)

해당 부분 코드 위치 수정해보았습니다. ㅎㅎ

2023-04-02 15:54 UTC, sehoong0429 commented on BoxOffice/Extensions/UIImageview+load.swift
> +            let scale = CGFloat(originalWidth) / CGFloat(viewWidth)
scale 변수는 CGFloat 타입이라 컴파일 에러가 발생할 수 있습니다. originalWidth는 Int타입이기때문에 연산이 불가능합니다!

2023-04-02 15:55 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }
```swift 
class DateFormatter {
    
    private let dateFormatter = DateFormatter()

    func formatDate(from dateString: String, inputFormat: String, outputFormat: String) -> String {
        dateFormatter.dateFormat = inputFormat
        if let date = dateFormatter.date(from: dateString) {
            dateFormatter.dateFormat = outputFormat
            return dateFormatter.string(from: date)
        }
        return dateString
    }
}
```
이런식으로 객체를 분리 해볼 수 있을 것 같습니다!

2023-04-03 00:24 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +    }()
아.. 그 의견도 일리있네요. 새홍의 의견이 맞는 상황이네요~

2023-04-03 02:35 UTC, merged

2023-04-03 02:35 UTC, AppleCEO commented
고생하셨습니다!