박스 오피스 [STEP04] Muri, Rowan
yagom-academy/ios-box-office pull request #35
Opened 2023-04-03 07:58 UTC by parkmuri

@junbangg
안녕하세요 알라딘~ 주말은 잘 보내셨나요!
STEP4 PR입니다! 박스오피스2도 리뷰 잘부탁드릴게요~!

## 고민했던 점
### 1️⃣ `LoadingIndicator.showLoading()`메서드의 위치
STEP3에서 주신 코멘트를 반영하여, `DailyBoxOfficeViewController`의 `viewDidLoad()`가 아닌 `loadDailyBoxOffice()`안에서 호출하도록 코드 위치를 수정해보았습니다.
수정 후 아래로 당겨 새로고침 하는 과정에서 `loadDailyBoxOffice()`가 호출되어 화면 중앙에 인디케이터가 나타나게 되었습니다..🥲
![](https://i.imgur.com/ekIq1da.gif)

고민 결과... 다시 `viewDidLoad()`에서 메서드를 호출하도록 코드를 수정해주었습니다...!

### 2️⃣ RefreshControl
refreshControl이 나타내는 indicator가 자리를 잡지 못하고 collection view의 셀과 겹쳐지는 현상을 해결하기 위해 `endRefreshing()` 메서드를 `reloadData()`와 동일한 위치로 옮겨주었습니다.

```swift
private func loadDailyBoxOffice() {
    //...
            DispatchQueue.main.async {
                self.collectionView.reloadData()
                self.collectionView.refreshControl?.endRefreshing()
            }
    //...
}
```
문제는 해결되었으나 `endRefreshing()`이 `loadDailyBoxOffice()` 메서드가 실행될 때마다 호출되는 것이 조금 마음에 걸리네요 🤔

## 해결하지 못한 점
### 1️⃣ 의문의 붉은색 파일...
![](https://i.imgur.com/2VloPSS.png)
git 사용 중 Xcode에 자꾸 붉은색 파일이 생성됩니다.
git ignore도 수정해보고 서로 번갈아가면서 해당 파일을 지운 뒤 커밋을 해도 계속 생기네요. 💦
어떻게 해결해야 할 지 모르겠습니다....
정확히는 STEP3브랜치를 STEP4브랜치에 머지하고 난 후 생긴오류이고, 위의 파일들을 삭제하면 프로젝트 자체에 Modified표시가 뜹니다. 
![](https://i.imgur.com/TTSOJjg.png)

**시도해본 것**
1. git cache 초기화
2. (번갈아가며)해당 파일 삭제 후 커밋

한쪽에서 지운 후 커밋하고 나머지쪽에서 pull받아도 또 생기는상황입니다...😭 어떻게 해결해야할까요..?

2023-04-04 13:36 UTC, junbangg requested changes
수고하셨습니다~

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +              let movieName = dailyBoxOffice?.boxOfficeResult.dailyBoxOfficeList[indexPath.item].movieName else { return }
엄청 중요한건 아닌데요..!
인덱스 접근을할때 잘못하면 바로 크래시가 발생할 수 있기 때문에 특별히 조심을 해야되기 때문에
`dailyBoxOfficeList[safe: indexPath.item]` 
요런식으로 안전하게 접근하는걸 저는 개인적으로 지향하고 있습니다!
여기는 문제가 되지 않아보이는데 알고 계시면 좋을것 같아서 코멘트 남깁니다:) 👍

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +              let movieName = dailyBoxOffice?.boxOfficeResult.dailyBoxOfficeList[indexPath.item].movieName else { return }
그리고 보면서 다시 또 든 생각인데..! 
`.` 이 연속적으로 많이 달려있는것 같네요..!

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +        LoadingIndicator.showLoading(in: posterView)
메서드 안으로 들어온것 좋아요! 하지만 여기 말고 조금 더 밑으로 API 호출 쪽으로 붙여도 괜찮을것 같아요
startLoad 직전으로?

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +            LoadingIndicator.hideLoading(in: self.posterView)
이걸 왜 저번 리뷰에 그냥 넘어갔는지는 모르겠는데.. 
.success, .failure 에 따른 UI 변경 사항을 적용한 뒤에 `hideLoading` 을 시키는게 맞을까요??🤔
전에 해야되지 않을까 라는 생각이 드네요 ..! `switch` 문 직전으로 놓는것에 대해서는 어떻게 생각하시나요???
의견이 궁금합니다

저번에 바로 캐치 못해서 미안합니다~~

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    }
혹시 요 코드를 보면서 느끼신게 있을까요???

틀렸다는건 아닌데..! 혹시 MVVM에 대해서 공부를 하셨다면 관련해서 생각이 드신게 있을까 해서요ㅎㅎ

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Network/Endpoint.swift
> +        }
저쪽 위에서 forEach 를 본것 같은데 여기서는 for 문 사용하신 이유가 있을까요?! 틀렸다는건 아닌데 혹시 기준이 있었나 해서요~

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Utility/AlertController.swift
> +}
요렇게 빼두신 이유가 있을까요?? 뺀건 너무 좋은데 그런 선택을 하시게 된 계기가 뭔지 궁금해서요!

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/View/CategoryStackView.swift
> +    }()
얘네 text 를 밖에서 수정하고 있어서 private 으로 안두신거죠??🤔

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Utility/Extension/extension+DateFormatter.swift
>      }
shared 로 둬서 사용하신 이유가 있나요???

2023-04-04 13:36 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    private let actorView = CategoryStackView()
오 비슷한 특징을 잡아서 타입을 만들어 사용하신건가요??👍

2023-04-04 13:37 UTC, junbangg commented
혹시 Step3 를 Step4 머지한 시점?이 언제죠?? 리뷰 기다리시면서 Step4 를 선행하다가 발생한 일인걸까요???

2023-04-05 03:13 UTC, parkmuri commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +              let movieName = dailyBoxOffice?.boxOfficeResult.dailyBoxOfficeList[indexPath.item].movieName else { return }
리뷰 반영하여 Collection에 subscript를 적용해보았습니다!
`.`이 연속적으로 달린 부분도 guard로 한번만 처리해준 후 사용해주었습니다.
```swift
guard let dailyBoxOfficeMovie = dailyBoxOffice?.boxOfficeResult.dailyBoxOfficeList[safe: indexPath.item]
        else {
            return
        }
        
        let movieCode = dailyBoxOfficeMovie.movieCode
        let movieName = dailyBoxOfficeMovie.movieName
```
`gaurd`절의 `else`는 코드가 100자가 넘어가 컨벤션으로 개행해주었습니다!

2023-04-05 03:17 UTC, Kyeongjun2 commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +        LoadingIndicator.showLoading(in: posterView)
말씀해주신 것이 흐름 상 보기 좋다고 생각되네요!!
startLoad 바로 위로 변경했습니다 😀

첫 번째 화면의 LoadingIndicator.showloading 메서드도 동일한 위치로 변경하였습니다~
```swift
if collectionView.refreshControl?.isRefreshing == false {
    LoadingIndicator.showLoading()
}

apiProvider.startLoad(decodingType: DailyBoxOffice.self) { result in
```
```swift
LoadingIndicator.showLoading(in: posterView)

apiProvider.startLoad(decodingType: DaumSearchResult.self) { result in
    LoadingIndicator.hideLoading(in: self.posterView)
```

2023-04-05 03:18 UTC, parkmuri commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +            LoadingIndicator.hideLoading(in: self.posterView)
리뷰를받고 인디케이터가 숨겨지는 시점에 대해 생각해보게된것같습니다🤔
인디케이터가 사라지는 시점은 데이터가 들어오기 전(혹은 실패알러트 전)이라고 생각되어 코드 수정하였습니다!

b60ec640964cf210e31b53ccf363ff57e429002c

2023-04-05 03:20 UTC, parkmuri commented on BoxOffice/Network/Endpoint.swift
> +        }
딕셔너리에 존재하는 `key`, `value`를 이용하여 반복문을 돌려주었어야 했는데...😅 foreach까지는 생각 못하고 바로 for문을 사용하게되었습니다...!
foreach로 수정하였습니다!
```swift
api.queries.forEach { (key, value) in
    let queryItem = URLQueryItem(name: key , value: value)
    
    urlComponents?.queryItems?.append(queryItem)
}
```

35fe0270b650f000a8bc777221ec5cf5540934fb

2023-04-05 03:22 UTC, Kyeongjun2 commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    }
MVVM을 아직 제대로 공부하지 않아서 확실하지는 않지만... 맛을 한 번 보자는 생각으로 리팩토링을 해봤습니다!
Cell의 ViewModel 구조체를 만들어서 해당 객체를 프로퍼티로 갖도록 해주고 string을 가공하는 코드를 ViewModel 내부에서 실행할 수 있도록 변경되었습니다. 🤔

61966ef727e2d2b923908934d1e14a8033c03304

2023-04-05 03:23 UTC, parkmuri commented on BoxOffice/View/CategoryStackView.swift
> +    }()
넵 맞습니다! 
`MovieDetailViewController`내부의 `configureCategoryLabels`, `configureDetailLabels`메서드에서 text를 수정하고있어서 접근제어를 두지않았습니다.

2023-04-05 03:26 UTC, Kyeongjun2 commented on BoxOffice/Utility/AlertController.swift
> +}
SOLID 원칙 중에서 SRP 단일 책임 원칙이 가장 중요하다고 알고 있는데요,
MVC에서는 컨트롤러가 엄청나게 많은 역할을 하기 때문에 가능한 선에서 최대한 기능 분리를 해보고 싶었습니다.
얼럿 창을 띄워주는 것은 뷰컨트롤러가 하고 얼럿 자체를 만드는 것은 다른 객체가 할 수 있도록 고민했던 것 같아요 🤔

2023-04-05 03:29 UTC, parkmuri commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    private let actorView = CategoryStackView()
넵😊 영화상세정보에 필요한 Label들이 공통된 특징을 가지고있어 `CategoryStackView`를 만들어 추상화를 시켜주었습니다!

2023-04-05 03:34 UTC, Kyeongjun2 commented on BoxOffice/Utility/Extension/extension+DateFormatter.swift
>      }
dateFormatter인스턴스가 메서드를 호출할 때마다 메모리에 올라갔다가 내려가는 것이 좋지 않다고 생각했습니다.

이번 프로젝트에서 꽤 자주 사용될 메서드이기 때문에 인스턴스를 한 번만 생성할 수 있도록 싱글톤을 사용해봤습니다 🙂

2023-04-05 03:43 UTC, Kyeongjun2 commented
> 혹시 Step3 를 Step4 머지한 시점?이 언제죠?? 리뷰 기다리시면서 Step4 를 선행하다가 발생한 일인걸까요???

네 맞습니다. 스텝4 진행을 먼저 하다가 스텝3이 머지된 이후 4월 3일에 스텝4로 머지했습니다! e22a470bd1699e5eb07da4094c28dc4dee04b641

2023-04-05 12:37 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    }
오 아주 좋습니다~ 이렇게 고민을 해보고 바로 적용해보는것 너무 좋아요~ 
MVVM 한번 공부 해보시면 리팩토링 욕심도 더 생기실것 같아요!  
아주 중요한 개념이니까 나중에 꼭 한번 공부해보시고 기존에 하셨던 프로젝트들 한번 리팩토링하면 아주 도움 많이 될것 같습니다:)

2023-04-05 12:38 UTC, junbangg commented on BoxOffice/Network/Endpoint.swift
> +        }
아주 좋습니다~ for 문 vs forEach 
각각 언제 쓰는게 좋은지 한번 고민해보고 마음속으로 기준을 한번 정해보시는것도 좋을것 같아요~!

2023-04-05 12:39 UTC, junbangg commented on BoxOffice/Utility/AlertController.swift
> +}
아주 좋습니다~ 그리고 Alert 가 추가되는 경우도 생길 수 있어서 타입으로 빼고 최대한 유연한 형태로 만드는거 좋은것 같습니다~

2023-04-05 12:41 UTC, junbangg commented on BoxOffice/View/CategoryStackView.swift
> +    }()
뷰들 자체는 `private` 으로 두고, 내부 뷰의 프로퍼티를 변경 시킬 수 있는 `set` 메서드를 제공하는건 어떨까요??
객체지향에서 객체에 접근할때 `.` 을 연속적으로 사용하는 것은 지양하는 것이 좋습니다!

2023-04-05 12:42 UTC, junbangg commented
> > 혹시 Step3 를 Step4 머지한 시점?이 언제죠?? 리뷰 기다리시면서 Step4 를 선행하다가 발생한 일인걸까요???
> 
> 네 맞습니다. 스텝4 진행을 먼저 하다가 스텝3이 머지된 이후 4월 3일에 스텝4로 머지했습니다! [e22a470](https://github.com/yagom-academy/ios-box-office/commit/e22a470bd1699e5eb07da4094c28dc4dee04b641)

혹시 요거 해결 됐을까요?? 원인이 잘 파악이 안되네요🤔

2023-04-05 12:42 UTC, merged