박스오피스II [STEP 1] 리지, kokkilE
yagom-academy/ios-box-office pull request #39
Opened 2023-04-04 01:30 UTC by yijiye

@July911
줄라이 안녕하세요! 코낄이, 리지입니다.
박스오피스 II STEP1 PR입니다.
이번 프로젝트도 잘 부탁드립니다. 😀

## ✅ 이번 스텝에서 구현한 기능
- navigationContoller present로 날짜선택 화면 띄우기
- 날짜선택 달력 화면 구현
   - UICalendarView, UICalendarSelectionSingleDateDelegate 적용
   - 화면간 데이터 전달 방법으로 delegate 구현
- 오늘날짜 선택시 Alert 구현 

## ✅ 고민했던 점

### 달력 뷰 구현
- 달력을 구현하기 위해 iOS 16.0부터 UIKit에 추가된 `UICalendarView`을 사용하여 새로운 뷰컨트롤러 `SelectDateViewController`를 구현하였습니다.

- 달력에서 날짜 선택 시 이벤트 처리를 구현하기 위해 `UICalendarSelectionSingleDateDelegate` 프로토콜을 채택하여 `dateSelection` 메서드를 활용했습니다.
``` swift
func dateSelection(
    _ selection: UICalendarSelectionSingleDate,
    didSelectDate dateComponents: DateComponents?
)
```

### 화면간 데이터 전달
날짜선택 화면에서 날짜를 선택하면 첫 번째 화면에서 선택된 날짜로 변경되어 그 날짜에 대한 정보를 받아야 했습니다. 저희는 delegate 패턴을 활용하여 데이터를 전달받도록 구현하였습니다.

- 전달할 데이터를 담고 있는 `DateUpdatable` protocol을 구현하고, 첫 번째 화면인 `DailyBoxOfficeViewController`가 채택
```swift
protocol DateUpdatable {
    var selectedDate: Date { get set }
    
    func refreshData()
}
```

- 날짜선택 화면인 `SelectDateViewController`에서 선택한 날짜 정보를 넘겨주도록 구현
```swift
extension SelectDateViewController: UICalendarSelectionSingleDateDelegate {
    func dateSelection(_ selection: UICalendarSelectionSingleDate, didSelectDate dateComponents: DateComponents?) {
        guard let selectedDate = dateComponents?.date else { return }
       ...
        
        delegate?.selectedDate = selectedDate
        delegate?.refreshData()
        
        self.dismiss(animated: true)
    }
}
```

### 오늘날짜 선택시 빈 화면 Alert창으로 구현

수행해야하는 내용 중 날짜 선택은 오늘까지로 제한하는 내용이 있었습니다. 그런데, 박스오피스 API에서 제공하는 데이터는 어제까지만 해당되기 때문에 오늘 날짜를 선택하면 빈 화면으로 보여지는 문제가 있었습니다.
이 부분은 저희가 의논하여 Alert 창으로 알림을 띄우도록 구현해보았습니다.

<img src="https://i.imgur.com/qlJTEwx.gif" width="200">

2023-04-04 09:44 UTC, July911 requested changes

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +    var delegate: DateUpdatable?
delegate패턴을 사용할 때 주의해야 할 상황이 무엇인지 적어주세요.

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +            let message = "오늘 날짜는 집계중입니다.\n다시 선택해주세요."
이런 String은 따로 관리해주는게 좋을 것 같습니다.

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    func refreshData()
인터페이스가 이게 최선일까요 ?

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let nextViewController = SelectDateViewController()
다음화면이라는 말은 너무 모호합니다.

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +        calendarView.availableDateRange = DateInterval(start: .distantPast, end: .now)
공식문서를 잘 활용하신 것 같네요 :)

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +            calendarView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
너무 많은 역할을 하는 메서드 같네요.

2023-04-04 09:44 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +            present(alert, animated: true)
self.dismiss(animated: true) 
어떤 컨벤션을 사용하실건가요 ?

2023-04-05 01:58 UTC, July911 requested changes

2023-04-05 01:58 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          refreshControl.addTarget(self, action: #selector(refreshData), for: .valueChanged)
이것만 나와있으니 조금 어색하네요 :)

2023-04-05 01:58 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    var selectedDate: Date = Date(timeIntervalSinceNow: -86400)
바로 밑에 해주신 이유가 무엇인가요 ?

2023-04-05 02:06 UTC, July911 commented
안녕하세요 :) 
오랜만입니다. 두분 일단, 스텝 1 역시 빠르게 끝내주셔서 정말 잘하신  것 같습니다. 
이전보다 그래도 확실히 공식문서에서 보던 패턴들이 보이는 것 같아서 두분의 학습 방향이 좋은 쪽으로 가고 있는 것 같습니다. 
또한 새로운 타입을 만났을때 당황하지 않고 잘 풀어나간 것도 정말 잘하신 것 같습니다. 
워낙 간단한 스텝이라, 빠르게 수정하고 다음 스텝으로 넘어가는게 좋을 것 같습니다. 
또한 물음표 질문은 수정을 굳이 안하셔도 됩니다 ! 

수정하시고 디엠 부탁드릴게요 :)

2023-04-05 04:49 UTC, yijiye commented on BoxOffice/Controller/SelectDateViewController.swift
> +    var delegate: DateUpdatable?
첫 번째 viewController가 nil 되었을 때, 날짜 선택 화면이 첫 번째 viewController를 강한 참조를 하게 되면 메모리 누수가 발생할 위험이 있습니다. 따라서 Updatable protocol에 AnyObject를 채택하여 class 타입만 채택할수 있도록 해주고 delegate에 weak 키워드를 붙였습니다.

2023-04-05 04:50 UTC, yijiye commented on BoxOffice/Controller/SelectDateViewController.swift
> +            let message = "오늘 날짜는 집계중입니다.\n다시 선택해주세요."
enum AlertMessage를 구현하였습니다 :)

2023-04-05 04:50 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    var selectedDate: Date = Date(timeIntervalSinceNow: -86400)
해당 프로퍼티는 저희가 적절하다고 생각하는 위치에 재배치하였습니다. 😄

2023-04-05 04:51 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          refreshControl.addTarget(self, action: #selector(refreshData), for: .valueChanged)
`refreshControl.addTarget()`가 `configureCollectionView()` 메서드 내에서 이루어지도록 수정하였습니다.

2023-04-05 04:54 UTC, kokkilE commented on BoxOffice/Controller/SelectDateViewController.swift
> +            present(alert, animated: true)
`self` 키워드가 불필요한 경우 `self`를 명시하지 않는 컨벤션으로 수정하였습니다.

2023-04-05 04:55 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    func refreshData()
저희가 protocol에 selectedDate 프로퍼티와 func refreshData() 두가지를 넣은 이유는 메인 VC와 날짜 선택 VC에서 데이터를 전달받아야 하는 항목이기 때문에 넣었습니다. selectedDate가 날짜 선택 VC에서 get set이 둘다 되기때문에 따로 메서드를 만들지 않고 프로퍼티 자체를 넘기도록 하였습니다. 👀

2023-04-05 04:55 UTC, kokkilE commented on BoxOffice/Controller/SelectDateViewController.swift
> +            calendarView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
오토레이아웃 제약을 잡는 부분은 `configureConstraintCalendarView()` 메서드로 분리하였습니다.

2023-04-05 04:55 UTC, yijiye commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let nextViewController = SelectDateViewController()
화면이동하는 VC의 네이밍으로 수정하였습니다!

2023-04-05 05:39 UTC, July911 commented on BoxOffice/Controller/SelectDateViewController.swift
> +    var delegate: DateUpdatable?
정확합니다.

2023-04-05 05:39 UTC, merged