박스오피스 [STEP 4] kaki, harry
yagom-academy/ios-box-office pull request #40
Opened 2023-04-04 06:29 UTC by kak1x

# 박스오피스 [STEP 4] kaki, harry
@1Consumption 
안녕하세요 올라프🙂 박스오피스 기간 동안 리뷰 잘 부탁드리겠습니다!!

## 구현 내용

### 영화 정보 상세보기 화면 구성
- 스크롤 뷰로 전체화면을 스크롤 할 수 있도록 해주고 영화 포스터 이미지와 영화의 상세 정보의 위치를 표시할 수 있도록 하였습니다.

### 카카오 이미지 검색 API로 이미지 받아오기
- 먼저 영화진흥위원회에서 제공하는 API로 영화코드를 받은 후에 새로운 뷰로 화면전환을 하도록 했습니다.
- 이전 뷰에서 받은 영화코드를 카카오에서 제공하는 API를 이용해 영화 포스터 url을 얻은 후에 `Data(contentsOf: url)`로 이미지 데이터를 생성해 주었습니다.

### 영화 포스터 이미지와 영화 정보 레이블 동시에 표시하기
- 영화 상세정보(영화진흥위원회 API), 영화 포스터 이미지(카카오 이미지 API) 불러오기 2가지 작업이 각각 비동기로 작업이 진행됩니다.
- 2가지 작업이 모두 끝났을 때, Activity Indicator의 애니메이션을 중지시키고 화면에 이미지와 정보를 표시할 수 있도록 구현하였습니다.

## 고민한 점, 질문사항

### Activity Indicator 사용
- Step3와 동일한 방식으로 Activity Indicator를 사용하려고 했는데 fetch할 데이터가 2개 존재하여 둘 중 하나만 완료되어도 Activity Indicator가 끝나는 문제가 발생하여 이를 해결하는 방법을 고민하는데 많은 시간이 들었습니다 🥲
- Activity Indicator가 두 가지 데이터를 다 받았을때 종료됨과 동시에 ImageView와 Label도 동시에 채워지길 원했기에 다음과 같은 방식을 선택했습니다.
```swift
private var movieInfo: Movie?
private var posterImage: UIImage?

private func checkFetchComplete() {
    guard posterImage != nil && movieInfo != nil,
          let movieInfo = movieInfo else { return }
    
    DispatchQueue.main.async { [weak self] in
        guard let self = self else { return }
        
        self.activityIndicator.stopAnimating()
        self.posterImageView.image = self.posterImage
        self.configureLabels(data: movieInfo)
        self.contentStackView.isHidden = false
    }
}
```
- 혹시 따로 데이터를 저장할 변수(movieInfo, posterImage)를 생성하지 않고 DispatchQueue.main.async에서 실행한 작업들이 모두 끝났을때 Activity Indicator를 종료할 수 있는 좋은 방법이 있을까요?

2023-04-04 15:34 UTC, 1Consumption requested changes
안녕하세요 @kak1x @HarryHyeon 
고생하셨습니다.

질문해주신 점은 코멘트에 같이 남겼습니다.
이해가 잘 안되는 점이 있다면 언제든지 말씀해주세요.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        navigationItem.title = DateFormatter.yesterdayText(format: .hyphen)
view를 설정하는 코드와 indicator를 start하는 코드가 같이 있으니까 조금 어색합니다. 역할에 맞게 분리해보면 어떨까요?

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        networkManager.fetchData(request: endPoint.createRequest(), type: BoxOffice.self) {
`어디로 요청을 보내는지`를 view가 알아야할까요? 여러분이 생각하시는 view의 역할은 어디까지인가요?

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                guard let self = self else { return }
self를 옵셔널 바인딩해준 이유가 궁금합니다.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +    @IBOutlet private weak var contentStackView: UIStackView!
기본 구현은 internal로 되어있지만, 외부에서 몰라도 되는 프로퍼티니까 private을 해준게 좋네요. 좋은 습관입니다 👍 
저는 여기서 한술 더 떠서, 강제 언래핑도 없애는 편입니다.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +        fetchMoviePoster()
위에도 언급을 했는데, 이 메소드는 정말 한가지 역할만 하고있나요?

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +    }
이런 구체적인 정보는 한번 추상화 되면 좋겠습니다. view에서는 클로저만 활용하는거죠.

추가적으로 `UIViewController`를 Controller로 분류해주셨던데, 저는 `UIViewController`를 `View`로 보고있습니다.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +                print(error.localizedDescription)
print는 제거해주세요.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +        return URL(string: urlText)
이런 로직도 view의 역할은 아닌듯해요.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Controller/MovieInfoViewController.swift
> +    }
이 메소드를 두개의 completion에서 부르기보다는 DispatchGroup을 활용해보면 어떨까요?

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +    }
빈 문자열보다는 nil을 반환하는게 더 정확할듯합니다. 빈 문자열은 의미가 모호해요.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +        dateFormatter.dateFormat = format.rawValue
rawValue를 직접 사용하는것은 지양해주세요. rawValue는 언제 변해도 이상하지 않은 값입니다. 차라리 연산프로퍼티를 통해 값을 반환하도록 해보세요.

2023-04-04 15:34 UTC, 1Consumption commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +        guard let date = dateFormatter.date(from: text) else { return "" }
여기도 마찬가지입니다.

2023-04-04 15:34 UTC, 1Consumption commented on UnitTests/NetworkManagerTests/Mocks/MockURLSession.swift
> +    func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
Mock과 Stub의 차이는 뭔가요?

2023-04-05 08:24 UTC, kak1x commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                guard let self = self else { return }
`self?` 대신 `self`를 사용해주고 싶어 모든곳에 바인딩을 해줬었는데, 필요한 작업은 아니라고 생각되어 제거해주었습니다.

2023-04-05 08:25 UTC, HarryHyeon commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        navigationItem.title = DateFormatter.yesterdayText(format: .hyphen)
말씀주신대로 실제로 데이터를 받아오기 위한 작업이 시작되는 부분에 activityindicator가 start하도록 수정했습니다.

2023-04-05 08:27 UTC, HarryHyeon commented on BoxOffice/Controller/MovieInfoViewController.swift
> +        fetchMoviePoster()
해당 부분도 아까 말씀해주신 것처럼 데이터를 받아오는 부분과 뷰를 초기화하는 부분을 분리해 주었습니다.

2023-04-05 08:29 UTC, kak1x commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        networkManager.fetchData(request: endPoint.createRequest(), type: BoxOffice.self) {
view의 역할로 viewController를 본다면 어디로 요청을 보내는지 알 필요도 없고 요청을 보내는 역할도 해서는 안된다고 생각합니다. 기존엔  viewController를 Controller로 생각하여 위의 역할을 포함시켰었는데, viewController의 역할이 너무 많아지는 것 같아 view의 역할만 가지게 해주도록 수정하였습니다.
요청을 보내는 곳을 알고, 실질적으로 요청을 보내는 역할은 Loader 클래스를 따로 정의해주어 분리해 주었습니다.

2023-04-05 08:31 UTC, kak1x commented on BoxOffice/Controller/MovieInfoViewController.swift
> +                print(error.localizedDescription)
제거하고 error를 전달해주는 `showFailAlert`메서드만 사용하도록 변경하였습니다.

2023-04-05 08:32 UTC, HarryHyeon commented on BoxOffice/Controller/MovieInfoViewController.swift
> +    }
말씀주신 것처럼 뷰컨트롤러를 뷰로 간주하기 위해서 BoxOfficeDataLoader, MovieInfoDataLoader, MoviePosterImageLoader 세 가지 타입으로 추상화해서 각각의 네트워크 요청을 처리하는 작업을 분리하였습니다.

뷰컨트롤러에서는 클로저를 통해 뷰를 업데이트하도록 했습니다.

2023-04-05 08:34 UTC, kak1x commented on BoxOffice/Controller/MovieInfoViewController.swift
> +    }
DispatchGroup을 활용하고 해당 메서드를 사용하지 않는 방식으로 변경해 주었습니다.
aecd684ca155ec0c005c0e65d04d7c0a6813063e

2023-04-05 08:35 UTC, kak1x commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +    }
반환 타입을 옵셔널로 변경해주어 nil을 반환할 수 있도록 변경해 주었습니다.
0f9ad6c7c0837e30e115b77709c3e666b691e52c

2023-04-05 08:36 UTC, kak1x commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +        dateFormatter.dateFormat = format.rawValue
`expression` 연산 프로퍼티를 통해 값을 반환하는 방식으로 변경해 주었습니다.
0f9ad6c7c0837e30e115b77709c3e666b691e52c

2023-04-05 08:37 UTC, HarryHyeon commented on BoxOffice/Controller/MovieInfoViewController.swift
> +        return URL(string: urlText)
MoviePosterImageLoader 클래스에서 동작하도록 수정하였습니다.

2023-04-05 08:38 UTC, HarryHyeon commented on BoxOffice/Etc/DateFormmatter+HyphenFormat.swift
> +        guard let date = dateFormatter.date(from: text) else { return "" }
해당 부분도 nil을 반환하도록 수정하였습니다.
0f9ad6c7c0837e30e115b77709c3e666b691e52c

2023-04-05 08:49 UTC, HarryHyeon commented on UnitTests/NetworkManagerTests/Mocks/MockURLSession.swift
> +    func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
`Mock` 은 테스트 작성을 위한 환경 구축이 어려울때, 테스트할때 필요한 객체를 대신하기 위해 만들어진 객체입니다. 실제로 기능 구현이 되어 있어 행위 검증을 하기 위해 사용한다고 이해하고 있습니다.

`Stub` 은 가짜 객체를 이용해 실제로 동작하는 것처럼 보이게 만드는 객체입니다. 테스트에서 호출될 요청에 대해 미리 응답을 준비해 놓고 테스트하고자 하는 객체에서 이 `Stub`을 이용하여 예상되는 결과의 상태를 검증하기 위해 사용한다고 이해하고 있습니다.

2023-04-05 08:53 UTC, kak1x commented on UnitTests/NetworkManagerTests/Mocks/MockURLSession.swift
> +    func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
`Mock` 을 활용한 테스트를 진행하고자 테스트 케이스를 작성하였는데, 결과적으로 보니 내부적으로 미리 결과값을 정해 놓는 `Stub` 도 활용한 테스트가 되어버린 것 같습니다.
`Mock` 객체 안에 `Stub` 이 존재해도 되는지 판단하기 어려운데, 올라프는 어떻게 생각하시는지 여쭤보고 싶습니다!

2023-04-05 23:10 UTC, merged