박스오피스 [STEP 4] 레옹아범, Andrew
yagom-academy/ios-box-office pull request #41
Opened 2023-04-05 02:21 UTC by Andrew-0411

@1Consumption 안녕하세요 올라프! 박스오피스 STEP 4 PR 보내드립니다.
STEP 3보다 네트워크 통신으로 더 많은 값을 받아와서 UI를 그려줘야 했기 때문에 더 많은 생각을 하게 되는 STEP이였던거 같습니다.🤔
추가로 이번 스텝은 조금 더 타입 분리나 메서드 분리에 대해서 고민을 많이했다고 생각하는데 부족한 부분 많은 리뷰 부탁드립니다!!🙇

---

## 고민했던점

### 1️⃣ HTTP Request의 Header에 주어지는 APIKey 숨기기

#### ❓문제점
* 다음이미지 받아오는 API같은 경우 저희가 사용했던 영화진흥위원회와는 다르게 APIKey를 `HTTPHeader`를 통하여 주는 방법으로 응답을 제공하고 있습니다.
* `HTTPHeader`는 웹사이트에 대한 공격을 효과적으로 방어해준다는 장점이 있지만, 카카오 APIKey가 영화진흥위원회의 `Header`로 보내는 것은 보안상의 문제가 발생할 수도 있다라는 생각을 했습니다.

#### 📖해결법

```swift
var header: String {
    switch self {
    case .movie(_), .boxoffice(_):
        return ""
    case .movieImage(_):
        return "KakaoAK \(Bundle.main.kakaoApiKey)"
    }
}
```

* 다음과 같이 코드를 구현하여 이미지를 받아올 경우에만 `HTTPHeader`에 카카오 API를 추가하도록 구현하였습니다.

<br/>

### 2️⃣ 사용해야되는 값이지만 API문서에 값이 없을 때 처리하는 방법

#### ❓문제점
- 애니메이션 영화는 배우가 아닌 성우만 있기 때문에 API문서를 읽어올 때 빈값을 받아왔습니다.
- 때문에 배우 목록에는 아무것도 적혀져 있지 않은 UI가 출력되었습니다

#### 📖해결법
```swift
return actors.isEmpty ? "배우 정보 없음" : actors.joined(separator: ", ")
```
- 삼항연산자를 주어서 빈값을 받아올 경우 정보가 없음을 UI에 출력을 하게 해서 User Experience(사용자 경험)을 높여보았습니다

<br />

### 3️⃣ 사진의 본연의 비율에 맞게끔 표시해주기

#### ❓문제점
- 포스터 이미지를 받아올 경우 어떤 사진은 너비가 높이보다 크거나, 어떤 사진은 높이보다 너비가 크는 등 사진의 형태가 너무 방대했습니다.
- 또한 `UIImageView`의 기본적인 높이나 너비를 지정하고 `contentMode`를 `Aspectfit`으로 줄 때 `UIImageView`의 크기가 그대로여서 영화정보와 사진의 간격이 벌어지는 문제가 있었습니다.

#### 📖해결법
- 다음 이미지 URL을 받아올 경우 너비와 높이를 받아오고 현재 `UIImageView`의 leading과 trailing을 주었기 때문에 높이와 너비를 나눔으로 `UIImageView`의 적절한 높이를 설정해줄 수 있었습니다.

```swift
case .success((let image, let width, let height)):
    DispatchQueue.main.async {
        self?.posterImageView.image = image
        self?.configureImageWidthConstraint(width: width, height: height)
    }

private func configureImageWidthConstraint(width: Int, height: Int) {
    posterImageView.heightAnchor.constraint(equalTo: posterImageView.widthAnchor, multiplier: CGFloat(height) / CGFloat(width)).isActive = true
}

```

2023-04-05 23:38 UTC, 1Consumption requested changes
고생하셨습니다!

코멘트 참고 부탁드리겠습니다~

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/BoxOfficeInfo.plist
> +	<key>KOFICAPIKEY</key>
👍

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Extension/ViewController+extension.swift
> +    func presentErrorAlert(error: Error, title: String ) {
두번째 매개변수에 불필요한 공백이 있네요!

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +    }
옵셔널로 바꿔도 될거같습니다. 빈 문자열을 보내는건 의미가 모호해요.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/APIType.swift
> +            var components = URLComponents(string: "http://kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json")
URL을 직접 넣지 말고, URLCompoents의 scheme, host, path 변수에 적절한 값을 넣어 조합해보세요.
URLComponents.url로 url을 뽑을 수 있습니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/BoxofficeInfo.swift
UIKit을 사용해야하는 이유가 있을까요?

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/DTO/MovieDTO/MovieInfoDescObject.swift
> +    }
private 처리해도 좋겠습니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +        self.movieImageApiType = movieImageApiType
이 두 정보는 굳이 외부에서 받을 필요가 없어보입니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +    }
컴플리션 내부에서 다시 메소드를 호출하는 방식도 있지만, DispatchGroup을 사용하는 방식도 있습니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +            handler(.success((image, width, height)))
width, height를 CGSize로 묶어서 보내도 좋겠습니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/Manager/RankingManager.swift
> +    }
Result<[InfoObject], Error> 타입으로 변경하고 handler에 Result를 담아서 보내주는게 덜 어색하지 않을까요? 성공일 때 nil을 반환하니까 뭔가 어색합니다.

2023-04-05 23:38 UTC, 1Consumption commented on BoxOffice/Model/UIModel/MovieInfoUIModel.swift
> +    }
다른 곳은 예외처리를 해줬는데 여기만 빈 문자열을 리턴하네요.

2023-04-05 23:38 UTC, 1Consumption commented on Controller/MovieDetailViewController.swift
> +                    self?.stopLoading()
stopLoading은 failure에도 있으니까 아예 switch문 밖으로 빼도 좋겠습니다.

2023-04-05 23:38 UTC, 1Consumption commented on Controller/MovieDetailViewController.swift
> +    }
만약 데이터보다 이미지를 먼저 불러오면 텍스트가 다 채워지지 않았는데 hidden이 풀릴거 같은데요. DisaptchGroup을 사용하면 두 리퀘스트 중 어떤게 먼저 도착하는지 상관 없이 그룹에 할당된 태스크가 모두 끝났을 때 기준으로 시점을 잡을 수 있습니다.

2023-04-05 23:38 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        collectionView.delegate = self
이정도는 viewDidLoad 시점에서 하시죠! 저는 꼭 필요한게 아니라면 lazy var를 지양하는 편입니다.

2023-04-05 23:38 UTC, 1Consumption commented on View/UILabel/CategoryLabel.swift
> +}
저는 프로퍼티 변경 정도는 서브클래싱을 하지 않고 그대로 UILabel을 사용하는 편입니다. 새로운 설명이 추가된다고 매번 새로운 클래스를 만들수는 없으니까요.

2023-04-06 05:52 UTC, Andrew-0411 commented on BoxOffice/Model/APIType.swift
> +    }
```swift
        switch self {
        case .movieImage(_):
            return "KakaoAK \(Bundle.main.kakaoApiKey)"
        default:
            return nil
        }
```
- 옵셔널로 반환하도록 변경하였습니다.
```swift
    private func makeRequest(url: URL) -> URLRequest? {
        if isRunningOnlyOneTask {
            cancelTask()
        }
        
        var urlRequest = URLRequest(url: url)
        
        guard let header = apiType.header else {
            return urlRequest
        }
        
        urlRequest.addValue(header, forHTTPHeaderField: "Authorization")
        
        return urlRequest
    }
```
- 사용하는곳에서 에러처리를 하도록 하였습니다.

2023-04-06 06:20 UTC, Andrew-0411 commented on BoxOffice/Model/APIType.swift
> +            var components = URLComponents(string: "http://kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json")
```swift
   private var scheme: String {
        switch self {
        case .movie(_), .boxoffice(_):
            return "http"
        case .movieImage(_):
            return "https"
        }
    }
    
    private var host: String {
        switch self {
        case .movie(_), .boxoffice(_):
            return "kobis.or.kr"
        case .movieImage(_):
            return "dapi.kakao.com"
        }
    }
```
- scheme, host를 공통된 부분을 묶어서 switch로 분리해서 사용하였습니다.

```swift
case .movie(let code):
    urlComponents.path = "/kobisopenapi/webservice/rest/movie/searchMovieInfo.json"
            
    let keyQuery = URLQueryItem(name: "key", value: key)
    let codeQuery = URLQueryItem(name: "movieCd", value: code)
            
    urlComponents.queryItems = [keyQuery, codeQuery]
            
    return urlComponents.url
```
- path는 모두 다르기 때문에 case문 안에서 설정하고 URLComponents.url로 return하였습니다

2023-04-06 06:21 UTC, fatherLeon commented on BoxOffice/Model/BoxofficeInfo.swift
Foundation으로 변경하였습니다!!

2023-04-06 06:36 UTC, fatherLeon commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +        self.movieImageApiType = movieImageApiType
```swift
init(movieCode: String, movieName: String, session: URLSession = URLSession.shared) {
init(movieCode: String, movieName: String, session: URLSession = URLSession.shared) {
    let movieApiType = APIType.movie(movieCode)
    let movieImageApiType = APIType.movieImage(movieName)
    
    self.boxofficeInfo = BoxofficeInfo<MovieInfoObject>(apiType: movieApiType, model: NetworkModel(session: session))
    self.movieImage = BoxofficeInfo<MovieImageObject>(apiType: movieImageApiType, model: NetworkModel(session: session))
}
```

* 기존의 `APIType`타입을 가진 프로퍼티를 삭제하고
* 위와 같이 `movieCode`와 `movieName`을 받아 이니셜라이저에서 APIType을 만들어 `BoxofficeInfo`에 바로 넣도록 만들었습니다.

2023-04-06 08:12 UTC, Andrew-0411 commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +    }
```swift
let dispatchGroup = DispatchGroup()

dispatchGroup.enter()

movieImage.fetchData { [weak self] result in
    switch result {
    case .success(let data):
        guard let document = data.documents.first else {
            return handler(.failure(.imageVaildError))
        }
        self?.imageDocument = document
        dispatchGroup.leave()
    case .failure(let error):
        handler(.failure(error))
    }
}

dispatchGroup.notify(queue: .global()) {
    guard let imageDocument = self.imageDocument else {
        return
    }
    self.fetchImage(imageUrlText: imageDocument.url, width: imageDocument.width, height: imageDocument.height, handler: handler)
}
```
- DispatchGroup의 notify를 사용하여 컴플리션 밖에서 모든 Task가 끝나고나서 메서드를 호출하도록 하였습니다

2023-04-06 08:26 UTC, fatherLeon commented on BoxOffice/Model/Manager/MovieDescManager.swift
> +            handler(.success((image, width, height)))
```swift
handler: @escaping (Result<(UIImage, CGSize), BoxofficeError>) -> Void
```
* 말씀하신대로 `CGSize`로 묶어서 보내도록 하였습니다.

```swift
private func configureImageWidthConstraint(size: CGSize) {
    let width = CGFloat(size.width)
    let height = CGFloat(size.height)
    
    posterImageView.heightAnchor.constraint(equalTo: posterImageView.widthAnchor, multiplier: height / width).isActive = true
}
```

* 추가로 오토레이아웃을 설정해주는 부분에서 `CGSize`를 받아 너비와 높이를 `CGFloat`으로 변환 이후 비율을 계산할 수 있도록 수정하였습니다.

2023-04-06 09:00 UTC, Andrew-0411 commented on BoxOffice/Model/Manager/RankingManager.swift
> +    }
```swift
    func fetchRanking(handler: @escaping (Result<[InfoObject], Error>) -> Void) {
        boxofficeInfo.fetchData { [weak self] result in
            switch result {
            case .success(let data):
                handler(.success(data.boxOfficeResult.movies))
                self?.movieItems = data.boxOfficeResult.movies
            case .failure(let error):
                handler(.failure(error))
            }
        }
    }
```
Result<[InfoObject], Error> 타입으로 변경하여서 성공하는 handler에  Result 타입으로 data.boxOfficeResult.movies 값을 담아서 보내주도록 하였습니다

2023-04-06 09:02 UTC, Chanhhyuk commented on BoxOffice/Model/UIModel/MovieInfoUIModel.swift
> +    }
```swift
        guard let openDate = Date.apiDateFormatter.date(from: data.openDate) else {
            return "개봉일 정보 없음"
        }
```
- 빈 문자열 대신 "개봉일 정보 없음"으로 예외처리를 해주었습니다

2023-04-06 09:08 UTC, Andrew-0411 commented on Controller/MovieDetailViewController.swift
> +                    self?.stopLoading()
```swift
            DispatchQueue.main.async {
                switch result {
                case .success((let image, let imageSize)):
                    self?.posterImageView.image = image
                    self?.configureImageWidthConstraint(size: imageSize)
                case .failure(let error):
                    self?.presentErrorAlert(error: error, title: "영화 포스터 이미지")
                }
                self?.stopLoading()
            }
```

stopLoading을 switch문에서 빼주고 DispatchQueue로 따로 감싸줘야해서 switch문 안에서 동작하는 DispatchQueue를 삭제하고 switch문을 감싸는 DispatchQueue를 작성하였습니다.

2023-04-06 09:18 UTC, fatherLeon commented on Controller/MovieRankingViewController.swift
> +        collectionView.delegate = self
```swift
private var collectionView: UICollectionView?
```

* 옵셔널로 변경하여 viewDidLoad시점에서 레이아웃 및 UICollectionView를 할당해주었습니다.

2023-04-06 09:24 UTC, fatherLeon commented on View/UILabel/CategoryLabel.swift
> +}
```swift
final class ContentStackView: UIStackView {

    private let categoryLabel = {
        let label = UILabel()
        
        label.translatesAutoresizingMaskIntoConstraints = false
        label.textAlignment = .center
        label.numberOfLines = 1
        label.font = .systemFont(ofSize: 12, weight: .bold)
        
        return label
    }()
    
    private let contentLabel = {
        let label = UILabel()
        
        label.translatesAutoresizingMaskIntoConstraints = false
        label.numberOfLines = 0
        label.font = .systemFont(ofSize: 12)
        
        return label
    }()
}
```

* 서브클래싱 한 라벨을 삭제하고 위와 같이 기본 UILabel을 통하여 구현하였습니다.

2023-04-06 09:59 UTC, Andrew-0411 commented on Controller/MovieDetailViewController.swift
> +    }
dispatchGroup을 사용하여 이미지작업과 데이터작업이 끝나고 나서 hidden을 풀어주어서 UI가 출력되도록 하였습니다
Label 업데이트가 늦다보니 이미지가 먼저 나오는 현상이 있어 이미지뷰도 StackView처럼 isHidden으로 숨겨주었다가 풀어주는 방식으로 추가하였습니다

2023-04-06 12:18 UTC, merged