박스오피스 II [STEP 1] vetto, brody
yagom-academy/ios-box-office pull request #42
Opened 2023-04-06 06:07 UTC by gzzjk159

@uuu1101
안녕하세요 태태!
박스오피스 II step1 PR입니다.

어찌저찌 구현이 돼서 PR을 보내게 되었습니다.

리뷰 잘 부탁드리겠습니다!

## 조언 받고 싶은 점

### iOS버전 호환
UICalendarView를 사용하기 위해서는 iOS 16이상의 버전으로 해야 합니다. 그래서 현재 저희 코드에서는 UICalendarView를 ViewController마다 `@available`을 붙여주며 16버전 이상만 가능하게 해주었습니다. 
다른 방법으로는 프로젝트 설정의 TARGETS에 들어가서 Minimum Deployments를 16으로 해주는 것입니다.

둘 중의 어떤 방법이 더 괜찮은지 궁금합니다. 그리고 다른 방법이 있는지 궁금합니다.

### 폴더구조 분리
`CalendarViewController`내에서 `delegate`로 `BoxOfficeViewController`를 사용하기 때문에 어떤 책임을 위임할지를 나타내는 프로토콜을 정의 해야 했습니다.
```swift
protocol DateChangeable: AnyObject {
    func updateSelectedDate(selectedDate: Date?)
}
```

이 프로토콜은 `CalendarViewController`에서 해당 프로토콜 타입의 `delegate`프로퍼티를 갖고 있기 때문에 `CalendarViewController`에 정의하였는데요, 프로토콜은 프로토콜끼리 있는 것도 좋지 않을까? 생각이 들어서 `Protocol`이라는 폴더를 만들까 생각했습니다.

하지만 프로토콜 폴더를 만들게 되면 `CalendarViewController`에서 사용하는 프로토콜인지 무엇인지 확인하기 위해 서로다른 역할을 하는 프로토콜이 모여있는 `Protocol`폴더에서 찾아야만 했습니다. 현재 프로젝트는 작기 때문에 찾기 어렵지 않지만 후에 프로젝트 규모가 커진다면 어려움을 겪을 수 있을 거라고 생각했습니다. 

그래서 `CalendarViewController`에 프로토콜도 같이 정의해주었습니다. 
현재 프로젝트 폴더구조는 `ViewController`라는 폴더 내에 뷰컨트롤러들이 모여있는데요, 이 대신에 `DailyBoxOffice`라는 폴더를 만들고 그 안에 `DailyBoxOffice`화면에 연관된 뷰, 프로토콜, 뷰 컨트롤러를 정의하면 어떨까 생각했습니다. 

태태는 MVC아키텍처에서 폴더관리를 어떻게 하시는지 궁금합니다!

2023-04-07 08:54 UTC, uuu1101 requested changes
STEP1 고생하셨습니다 :)

몇가지 코멘트 남겨두었으니, 고민해보시고 코멘트 남겨주세요.

조언이 필요한 점
--
iOS버전 호환 관련 
> 답이 정해져있는 질문이 일단 아니라는 점과 상황에 따라 다를 것 같아요.
두 가지의 차이점은 무엇일지 한번 고민해보시는 게 더 좋을 것 같습니다. 그러면 어떤 상황에서 어떻게 해야할지 더 명확해 질 것 같네요.
저는 Minimum Deployments를 변경 해주는 것을 선호합니다.
물론 해당 앱의 사용자 타겟을 어떻게 잡을지를 고려해야겠지만요..

디렉토리 구조 관련
> 해당 부분도 팀 내부에서 정해가기 때문에 다 다를것 같은데요.
저는 화면 단위로 분리하는것을 좋아하고 화면 단위에서 사용하는 파일들을 다시 구분하고 있습니다.
물론 이것도 어떤게 더 좋다라고 할수는 없는것 같네요. 
크게 View, ViewController, Protocol, Network, Resource 같이 큰 분류로 나누는 방법도 있습니다.

2023-04-07 08:54 UTC, uuu1101 commented on BoxOffice/ViewController/CalendarViewController.swift
> +protocol DateChangeable: AnyObject {
AnyObject 를 채택하신 이유가 궁금합니다 👀

2023-04-07 08:54 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> -        boxOfficeProvider.fetchData(.dailyBoxOffice(date: yesterday),
date에 yesterday를 할당하셨는데 date 로 네이밍을 수정하신 이유가 궁금합니다.

boxOfficeProvider.fetchData(.dailyBoxOffice(date: date) 의 date는 항상 yesterday 아닌가요?

2023-04-07 08:54 UTC, uuu1101 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +@available(iOS 16.0, *)
해당 코드는 무엇을 의미하나요?

2023-04-07 08:54 UTC, uuu1101 commented on BoxOffice/ViewController/CalendarViewController.swift
> +    }
해당 코드는 왜 존재해야하나요?

2023-04-10 05:12 UTC, seunghyunCheon commented on BoxOffice/ViewController/CalendarViewController.swift
> +protocol DateChangeable: AnyObject {
`CalendarViewController`의 프로퍼티인 `delegate`는 채택하는 타입을 강하게 참조하고 있기 떄문에 강한순환참조의 여지가 있습니다. 
이를 방지하기 위해 delegate프로퍼티를 weak로 선언하게 되었고 weak는 class-bound에서만 선언할 수 있기 때문에 프로토콜에서 AnyObject를 채택해 클래스만 채택할 수 있도록 만들어주었습니다.

2023-04-10 05:37 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> -        boxOfficeProvider.fetchData(.dailyBoxOffice(date: yesterday),
처음에는 요구사항에 맞춰 어제 날짜의 일일 박스오피스를 보여주었지만 박스오피스2의 step1을 진행하면서 날짜를 선택하고 선택된 날짜로 title과 선택한 날짜에 해당하는 박스오피스를 보여줘야하기 때문에 date라는 변수명과 yesterday라는 변수명을 수정하여 fetchDailyBoxOffice에서는 `formattedSelectedDate`라고 변경하였습니다. 현재 refresh메서드에서는 이러한 변수명이 통일되어있지 않아보여 refresh메서드에서도 `formattedYesterdayDate`로 변경하였습니다. fb2ab9f208b4b638833d24a86cde5577e3e46241

2023-04-10 05:45 UTC, gzzjk159 commented on BoxOffice/ViewController/BoxOfficeViewController.swift
> +@available(iOS 16.0, *)
`@available`은 swift에서 소프트웨어 버전 및 호환성을 나타내는 어트리뷰트입니다. 어트리뷰트를 사용하여 사용가능한 버전을 설정할 수 있습니다. 또한 어떠한 버전에서는 실행하지 않도록 도와줄 수 있습니다. 저 코드는 iOS 16.0이상 버전에서만 실행이 가능하게 해주는 코드라고 볼 수 있습니다.

2023-04-10 05:51 UTC, seunghyunCheon commented on BoxOffice/ViewController/CalendarViewController.swift
> +    }
`UIViewController`를 상속받은 뒤 지정 생성자를 직접 구현하게 된다면 부모(UIViewController)의 생성자를 상속받지 않기 때문에 직접 구현해야 하는 필수 생성자입니다. 

스토리보드나 xib로 화면을 그릴 때는 지정 생성자를 따로 생성할 필요가 없기에 필수 생성자를 자동으로 상속받아 서브클래스에서 구현해줄 필요가 없지만, 현재는 코드로 그리고 있고 지정생성자를 직접 구현하고 있기에 `required init?`이 필요해서 정의했습니다!

이 지정 생성자를 fatalError로 둔 이유는 코드로 뷰를 구성할 경우에는 불리지 않을 생성자이기 때문에 fatalError로 두었습니다.

2023-04-10 10:43 UTC, merged