박스오피스 II [STEP 1] 혜모리, 크리스티
yagom-academy/ios-box-office pull request #44
Opened 2023-04-06 07:11 UTC by hyemory

안녕하세요 하비(@havilog)! `모리스티`입니다.
새로운 프로젝트라고 생각하고 다시 한 번 열심히 달려보겠습니다! 💪🏻👁️ㅅ👁️
이번 리뷰도 잘 부탁드리겠습니다.

---
## 고민했던 점

### 1️⃣ 선택 가능한 날짜

`UICalendarView`에는 선택 가능한 날짜의 범위를 설정할 수 있는 `.availableDateRange` 프로퍼티가 있습니다.
선택 가능 날짜 중 시작 날짜를 어떻게 할까 고민하다가 API의 데이터가 시작되는 날짜를 손수 찾아 2003년 11월 11월을 시작 날짜로 설정하였습니다. 😅

``` swift
let startDateComponent = DateComponents(calendar: Calendar(identifier: .gregorian),
                                        year: 2003,
                                        month: 11,
                                        day: 11)
```

### 2️⃣ Delegate의 활용

`UICalendarView`에서 선택한 날짜의 영화 정보를 받기 위해선 뷰간 데이터 전송이 필요했습니다. 이를 구현하기 위해 저희는 delegate 패턴을 사용했습니다. 값을 업데이트하는 프로토콜을 구현하고 이를 `BoxOfficeViewController`를 대리자로 위임하기 위해 프로토콜을 채택하였습니다.

```swift
protocol DateUpdatableDelegate: AnyObject {
    func updateDate(_ date: Date)
}
```

날짜를 선택하면 updateDate 메서드를 통해 `BoxOfficeViewController`의 네비게이션 타이틀과 박스오피스 정보를 업데이트 해주었습니다.

``` swift
extension BoxOfficeViewController: DateUpdatableDelegate {
    func updateDate(_ date: Date) {
        navigationItem.title = date.showSelectedDate(formatter: dateFormatterWithHyphen)
        
        guard let targetDate = navigationItem.title?.removeHyphen() else { return }
        
        fetchBoxOffice(targetDate: targetDate)
    }
}
```

2023-04-06 14:32 UTC, havilog requested changes
<img width="514" alt="image" src="https://user-images.githubusercontent.com/57659933/230407200-d141e276-4a34-49a1-90ac-f47d686f9f8c.png">
2003년 영화가 신작이라고 뜨는게 의도한 동작이실까요?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/57659933/230407512-4e711542-020f-4075-81cb-a779d6680260.png">
선택하고 다시 나왔을 때 select가 안 풀려있어요.


https://user-images.githubusercontent.com/57659933/230409691-ecc96e5f-dc6c-455b-b777-12b34f3fed29.mp4

제목이 긴 영화를 클릭했을 때, 날짜가 보이다가 가려지는게 이상해보여요

2023-04-06 14:32 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var isRun = false
isRun이라는 변수명은 뭐가 실행되고 있는건지 유추하기 힘들어보여요

2023-04-06 14:32 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        calendarViewController.selectedDate = DateComponents(
외부에서 데이터를 만들어서 넣어준 이유가 뭘까요? 
"yyyy-MM-dd"라는 데이트 포맷만 init시점에 넣어주면 자체적으로 만들 수 있을거 같은데 이렇게 생각하신 이유가 궁금해요

2023-04-06 14:32 UTC, havilog commented on BoxOffice/Controller/Protocol/DateUpdatableDelegate.swift
> +    func updateDate(_ date: Date)
```suggestion
    func update(date: Date)
```

2023-04-07 03:26 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var isRun = false
`isFetchingData`로 수정했습니다!

2023-04-07 03:27 UTC, christy-hs-lee commented on BoxOffice/Controller/Protocol/DateUpdatableDelegate.swift
> +    func updateDate(_ date: Date)
수정 완료했습니다!

2023-04-07 03:30 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        calendarViewController.selectedDate = DateComponents(
처음에는 선택한 값을 넘겨줘야 한다고 판단하여 해당 방식으로 구현했습니다.
현재는 init시점에 넣어주는 방식으로 수정했습니다!

2023-04-07 03:37 UTC, hyemory commented
#### 어색한 동작에 대한 피드백 입니다!

> 2003년 영화가 신작이라고 뜨는게 의도한 동작이실까요?

- 네 맞습니다. 타이틀의 날짜를 기준으로 어제 날짜와 비교한 랭크의 변동 정보가 표시되는 것입니다. 
영화의 개봉일이 전부 동일하지는 않으나 2003년 11월 11일에 API를 제공하기 시작했기 때문에 
그 때 당시 비교적 신작이었던 영화가 표시되는 것으로 추측하고 있습니다.

> 선택하고 다시 나왔을 때 select가 안 풀려있어요.

- viewWillAppear 메서드에서 모든 cell의 isSelected를 false로 만들고 + reloadData() 호출하여 해결해 보았습니다.

> 제목이 긴 영화를 클릭했을 때, 날짜가 보이다가 가려지는게 이상해보여요

- 현재 제목이 긴 영화 제목의 경우 적당히 길면 `< Back` 으로 나오고 그보다 더 길면 `<`만 나오게 됩니다. 
이를 해결하기 위해 backButton에 값을 넣어줬는데,  영화 제목이 가려지는 현상이 발생했습니다. 
따라서 제안해 주신 것처럼 뒤로가기의 의미를 가진 `<` 버튼만 보이도록 수정했습니다!

2023-04-07 13:27 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var isRun = false
개인적으로 data도 여러 개일 수 있어서 모델이나 행위를 특정하는게 좋아보여요

2023-04-10 07:59 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var isRun = false
`isReceivingBoxOffice`로 네이밍 변경하였습니다

2023-04-10 13:32 UTC, merged