박스오피스 II [STEP 1] 무리, Rowan
yagom-academy/ios-box-office pull request #45
Opened 2023-04-06 07:30 UTC by Kyeongjun2

@junbangg
안녕하세요 알라딘~ 박스오피스2 STEP1 PR보내드립니다.🫡
이번 프로젝트도 잘부탁드립니다😊!!

## 고민했던 점
### 1️⃣ Modern Collection View의 사용
지난 프로젝트에서 Modern Collection View가 아닌 DataSource, Delegate를 사용하는 CollectionView를 경험해보았습니다. 새로운 프로젝트를 시작하며 Modern Collection View를 적용시켜보자는 이야기를 나누었고, 지난 프로젝트에서 경험해보았던것을 토대로 적용시켜보았습니다!

</br>

### 2️⃣ Minimum Deployments
CalendarView는 iOS 16.0 이후로 사용 가능하여 프로젝트의 Minimum Deployments를 16.0 보다 높게 설정하였습니다.

</br>

### 3️⃣ Selected Date 전달하기
CalendarView에서 선택된 날짜를 `DailyBoxOfficeViewController`에 전달하기 위해 delegate 패턴을 사용하였습니다.
```swift
protocol CalendarViewControllerDelegate: AnyObject {
    func changeTarget(date: Date)
}
```

```swift
extension DailyBoxOfficeViewController: CalendarViewControllerDelegate {
    func changeTarget(date: Date) {
        targetDate = date
        let titleText = DateFormatter.shared.string(from: date, dateFormat: "yyyy-MM-dd")
        navigationItem.title = titleText
        loadDailyBoxOffice(date: date)
    }
}
```

</br>

### 4️⃣ Calendar View의 Selected Date 변경하기
날짜를 변경 한 후 다시 날짜선택을 눌러 modal창을 띄우게 되면 어제의 날짜로 선택이 되는 문제가 있었습니다. 이를 해결하기위해 `targetDate`라는 프로퍼티를 만들어 CalendarViewController에 전달하여 캘린더 뷰 생성시 init으로 `targetDate`를 가질 수 있게 만들었습니다.

```swift
// DailyBoxOfficeViewController.swift

private var targetDate: Date?
// ...
@objc func showCalendar() {
    let calendarViewController = CalendarViewController(targetDate: targetDate ?? yesterday)
    navigationController?.present(calendarViewController, animated: true)
}
```
```swift
// CalendarViewController.swift

private var targetDate: Date?
// ...
init(targetDate: Date) {
    self.currentDate = targetDate
    super.init(nibName: nil, bundle: nil)
}
// ...
private func configureCalendarView() {
    // ... 
    let selectedDateComponent = createDateComponent(with: targetDate)
    // ...
    dateSelection.selectedDate = selectedDateComponent
}
```

2023-04-07 16:12 UTC, junbangg requested changes
수고하셨습니다!~!

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Controller/CalendarViewController.swift
> +    private let calendarView = UICalendarView()
요 두 친구들은 주입을 안시키는 이유가 있었을까요?! 궁금해서요~

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Controller/CalendarViewController.swift
> +    weak var delegate: CalendarViewControllerDelegate?
요건 private 이 불가능한걸까요?!🤔

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    @objc func showCalendar() {
요거슨 private 이 안될까요?!

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Controller/Protocol/CalendarViewControllerDelegate.swift
> +    func changeTarget(date: Date)
흠 요거 메서드명에 대한 설명? 좀 부탁드려도 될까요?? 
날짜를 변경하는게 맞는거죠??

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Model/TextMaker.swift
> +struct TextMaker {
오 요 문자열 관리 타입은 만들어진 계기가 무엇인가요??

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeListCell.swift
> +        let textMaker = TextMaker(data: dailyBoxOfficeData)
오호 위에도 댓글을 남겼지만 요렇게 리팩토링하게된 이유가 궁금하군요..! 틀렸다는것은 절대로 아닙니다~~

2023-04-07 16:12 UTC, junbangg commented on BoxOffice/Model/TextMaker.swift
> +struct TextMaker {
`moveTitle` 나 rank 처럼 DailyBoxOfficeMovie의 문자열이 그대로 나오는 경우도 보이는데 DailyBoxOfficeMovie 에서 문자열을 적절히 변형이 필요할때만 그렇게해서 내보내는 방법도 있었을것 같은데 요렇게 타입을 만드신 이유가 궁금하네요~!

지금이 틀렸다는것은 역시나 아니고, 생각하시게된 과정이 궁금할 뿐입니다~~ :)

2023-04-07 16:16 UTC, junbangg commented on BoxOffice/Controller/CalendarViewController.swift
> +        guard let targetDate = self.targetDate else { return }
저번에 말하는거 까먹었는데 새로운 스위프트의 멋진 문법을 경험해보시는건 어떠신가요!~!
`guard let targetDate else { return }`

2023-04-07 16:17 UTC, junbangg commented on BoxOffice/Controller/CalendarViewController.swift
> +        guard let targetDate = self.targetDate else { return }
말하다보니까 궁금한건데 `self` 를 붙이시는 기준 같은게 있을까요"?

2023-04-10 06:03 UTC, Kyeongjun2 commented on BoxOffice/Controller/CalendarViewController.swift
> +        guard let targetDate = self.targetDate else { return }
self 프로퍼티랑 같은 이름으로 바인딩을 할 필요가 없었군요!! 😮
대박 감사합니다 적용해보았습니다 ~~
```swift
guard let targetDate else { return }
````
정말 편하네요 👍

self는 타입 인스턴스 프로퍼티와 지역 상수/변수, 메서드 파라미터 등의 이름이 똑같을 때 붙여주고 있습니다.

2023-04-10 06:05 UTC, Kyeongjun2 commented on BoxOffice/View/DailyBoxOfficeListCell.swift
> +        let textMaker = TextMaker(data: dailyBoxOfficeData)
처음에 DailyBoxOfficeCellViewModel 이라고 했던 타입인데요...ㅋㅋㅋ
MVVM에 대한 이해도 부족하고 사용 방법이 ViewModel과는 거리가 멀다고 생각해서 이름을 바꾸기만 했었네요.

바꾸게된 이유는 뷰에서 로직을 분리해내기 위함이었습니다!

2023-04-10 06:06 UTC, parkmuri commented on BoxOffice/Controller/CalendarViewController.swift
> +    private let calendarView = UICalendarView()
리뷰 감사합니다! `calendarView`는 다른곳에서도 View를 주입시켜주지 않고있어 `calendar`만 반영하였습니다!
```swift 
    private let calendar: Calendar
    // ....
    
    init(targetDate: Date,
         calendar: Calendar = Calendar(identifier: .gregorian) {
        self.targetDate = targetDate
        self.calendar = calendar
        
        super.init(nibName: nil, bundle: nil)
    }
```

cbcc766cacb45ba50c5a9b992a02ce40e77c0325

2023-04-10 06:09 UTC, Kyeongjun2 commented on BoxOffice/Model/TextMaker.swift
> +struct TextMaker {
Response Model 에서 직접 가공하면 codingKey들과 이름이 혼동이 올 수도 있을 것 같아서 Model에서는 하지 않는게 좋아보였습니다...

뷰에서 로직을 분리하려다 보니 로직이 있는 프로퍼티만 빼면 나중에 Label text를 할당할 때 통일성이 없어보여서 그대로 나오는 문자열도 전부 처리할 수 있도록 타입을 만들어 주었습니다!

2023-04-10 06:10 UTC, parkmuri commented on BoxOffice/Controller/CalendarViewController.swift
> +    weak var delegate: CalendarViewControllerDelegate?
private 접근제어자 설정하며 init 시에 주입받도록 리팩토링하였습니다!
```swift
// DailyBoxOfficeViewController
    @objc
    private func showCalendar() {
        let calendarViewController = CalendarViewController(targetDate: targetDate ?? yesterday, delegate: self)
        navigationController?.present(calendarViewController, animated: true)
    }
```
```swift
// CalendarViewController
    private weak var delegate: CalendarViewControllerDelegate?
    
    init(targetDate: Date,
         calendar: Calendar = Calendar(identifier: .gregorian),
         delegate: CalendarViewControllerDelegate?) {
        self.targetDate = targetDate
        self.calendar = calendar
        self.delegate = delegate
        
        super.init(nibName: nil, bundle: nil)
    }
```

ce1271493031cfef4cdf7c8c2510c9a1ffb12fd9

2023-04-10 06:11 UTC, parkmuri commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    @objc func showCalendar() {
접근제어자 설정해주었습니다:) !

2023-04-10 06:13 UTC, Kyeongjun2 commented on BoxOffice/Controller/Protocol/CalendarViewControllerDelegate.swift
> +    func changeTarget(date: Date)
이름이 불명확한 것 같아서 delegate 메서드들의 네이밍 컨벤션을 좀 더 찾아보고 수정해봤습니다!
```swift
func calendarViewDidSelect(date: Date)
```

2023-04-10 14:23 UTC, junbangg commented on BoxOffice/Controller/CalendarViewController.swift
> +    weak var delegate: CalendarViewControllerDelegate?
넵 set 메서드로 주입시키는 방법도 있습니다.!!👍

2023-04-10 14:24 UTC, merged