박스오피스II [STEP 2] 리지, kokkilE
yagom-academy/ios-box-office pull request #46
Opened 2023-04-06 08:29 UTC by kokkilE

@July911
줄라이 안녕하세요! 코낄이, 리지입니다.
박스오피스 II STEP2 PR입니다.
부족한점이 많지만,,,이번에도 잘 부탁드립니다!

## ✅ 이번 스텝에서 구현한 기능
- 화면모드 전환을 위한 toolBar 구현
- 화면모드에 따른 compositionalLayout 적용
- Dynamic Type 적용

## ✅ 고민했던 점

### 1️⃣ Dynamic Type 적용을 위한 UICollectionViewLayout 레이아웃 구현
두 가지 타입의 셀 레이아웃을 구현하기 위해 `DailyBoxOfficeViewController`에서 다음과 같이 레이아웃을 생성하는 메서드를 두 가지로 분리하였습니다.

**DailyBoxOfficeViewController**
``` swift
extension DailyBoxOfficeViewController {
    private func createMovieIconLayout() -> UICollectionViewLayout { ... }
    private func createMovieListLayout() -> UICollectionViewLayout { ... }
}
```
리스트 타입의 셀에 dynamic type을 적용하는데 어려움이 있었습니다.
사용자의 텍스트 크기 설정에 실시간으로 대응하기 위해 각 셀의 높이를 고정적으로 부여할수가 없었습니다. 다음과 같이 각 셀의 높이가 동적으로 내부 컨텐츠에 따라 설정되게끔 하기 위해 아이템의 높이에 `estimated` 값을 설정했고, 그룹의 높이 또한 아이템의 높이와 동일하게 동적으로 설정되게끔 `estimated` 값을 설정하였습니다.

**DailyBoxOfficeViewController**

``` swift
let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                      heightDimension: .estimated(1))
let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                      heightDimension: .estimated(1))
```

줄라이가 디스코드에서 조언해주신 대로 각 셀의 크기를 절대값으로 받아와서 설정하는 방안도 고려해 보았으나, 사용자 설정이 변경될때마다 실시간으로 `UICollectionViewLayout` 가 새로 생성되어야 한다는 점, VC에서 각 셀의 내부 컨텐츠 크기를 확인하는 로직이 복잡하다는 점을 고려하여 `estimated` 값을 설정하는 방법으로 구현하였습니다.

### 2️⃣ View에 보여지는 Label.text를 넣어주는 역할 VC로 분리
현재 저희가 진행하는 프로젝트는 MVC 패턴으로 구성되어 있습니다. 기존 코드에서는 View에 보여지는 Label의 값을 넣어주는 코드가 View에 있었고, 상황에 따라 변경되는 로직도 View에 구현하였습니다. 그러나 View에서는 화면에 보여지는 것만 담당하기 때문에 로직과 관련된 기능은 View Controller 에서 하는 것이 적절하다고 판단하였습니다. 
따라서 View Controller에서 Label을 구현하고 String을 반환하는 메서드를 만들어 View의 Label을 셋팅하는 메서드에 넣어주도록 리팩토링 하였습니다.

**DailyBoxOfficeListCollectionViewCell**
```swift
// View에서 Label에 입력될 String을 받는 메서드
func setupLabels(name: String, audienceInformation: String, rank: String, rankMark: String, audienceVariance: String, rankMarkColor: MovieRankMarkColor) {
        nameLabel.text = name
        audienceInformationLabel.text = audienceInformation
        rankLabel.text = rank
        rankMarkLabel.text = rankMark
        audienceVarianceLabel.text = audienceVariance
        
        switch rankMarkColor {
        case .red:
            rankMarkLabel.textColor = .systemRed
        case .black:
            rankMarkLabel.textColor = .black
        case .blue:
            rankMarkLabel.textColor = .systemBlue
        }
    }

// VC에서 넘겨주는 코드
private func setupDataSource() {
        movieDataSource = DataSource(collectionView: collectionView) { [weak self] collectionView, indexPath, itemIdentifier in
           ...
                
        guard let movieInformation = self?.setupCellLabels(with: itemIdentifier) else { return UICollectionViewCell() }
        cell.setupLabels(...)
                
```
- 여기서는 조건에 따라 글씨색상이 바뀌어야 하는 로직이 필요하여 상황을 판단하는 `enum rankMarkColor`를 만들어 case 별로 글씨색상을 변경하도록 구현하였습니다.

**MovieInformationScrollView**
```swift
//View에서 Label에 입력될 String을 받는 메서드
func setupDescriptionLabels(...) {
        directorDescriptionLabel.text = director
        productionYearDescriptionLabel.text = productionYear
       ....
}

// VC에서 넘겨주는 코드
 private func fetchMovieInformation() {
        networkManager.request(endPoint: boxOfficeEndPoint, returnType: MovieInformation.self) { [weak self] in
            ...
            DispatchQueue.main.async {
                self?.movieInformationScrollView.setupDescriptionLabels(director: movieInformationItem.directors, productionYear: movieInformationItem.productionYear, openDate: movieInformationItem.openDate, showTime: movieInformationItem.showTime, watchGrade: movieInformationItem.audits, nation: movieInformationItem.nations, genre: movieInformationItem.genres, actor: movieInformationItem.actors)
                }
```

### 3️⃣ 화면모드 전환 로직
화면모드를 리스트와 아이콘 2가지를 만들어 변경하는 로직을 구현하기 위해 `enum screenMode`를 만들어 상태를 체크하고 선택된 화면에 맞는 cell을 띄우도록 구현하였습니다.
- 2가지 cell 구현     
`DailyBoxOfficeListCollectionViewCell`,
`DailyBoxOfficeIconCollectionViewCell`
 하나의 cell을 사용하여 autolayout을 바꿔주려 했으나 Label이 화면에 보여지는 순서가 달라 하나의 cell을 재사용하기 어렵다고 판단하여 2개의 cell을 만들었습니다.
 
- 화면모드변경 버튼 클릭스 case에 따라 register되는 cell을 다르게 적용
```swift
@objc private func changeScreenModeButtonTapped() {
    ...
        
    let listMode = UIAlertAction(title: title, style: .default) { [self] _ in
        screenMode.changeMode()
            
        switch screenMode {
        case .list:
            collectionView.register(DailyBoxOfficeListCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeListCollectionViewCell.reuseIdentifier)
        case .icon:
            collectionView.register(DailyBoxOfficeIconCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeIconCollectionViewCell.reuseIdentifier)
        }

        DispatchQueue.main.async { [self] in
            setupDataSource()
            updateDataSource()
            switch screenMode {
            case .list:
                    collectionView.collectionViewLayout = createMovieListLayout()
            case .icon:
                    collectionView.collectionViewLayout = createMovieIconLayout()
            }
        }
    }
```

- data를 받아 cell에 전달할때 case로 나눠서 처리하도록 구현
```swift
private func setupDataSource() {
        movieDataSource = DataSource(collectionView: collectionView) { [weak self] collectionView, indexPath, itemIdentifier in
           
        switch self?.screenMode {
        case .list:
            guard let cell = collectionView.dequeueReusableCell(
                withReuseIdentifier: DailyBoxOfficeListCollectionViewCell.reuseIdentifier,
                for: indexPath) as? DailyBoxOfficeListCollectionViewCell else { return UICollectionViewCell() }   
            guard let movieInformation = self?.setupCellLabels(with: itemIdentifier) else { return UICollectionViewCell() }
                
                cell.setupLabels(...)
            return cell
        case .icon:
            guard let cell = collectionView.dequeueReusableCell(
                withReuseIdentifier: DailyBoxOfficeIconCollectionViewCell.reuseIdentifier,
                for: indexPath) as? DailyBoxOfficeIconCollectionViewCell else { return UICollectionViewCell() }
            guard let movieInformation = self?.setupCellLabels(with: itemIdentifier) else { return UICollectionViewCell() }
                
            cell.setupLabels(...)
            return cell
```

#### cell을 구현하는 코드 리팩토링
처음엔 cell을 만들고 타입을 확인하는 코드가 중복되는 느낌이라 두개의 cell이 공통으로 가지고 있는 메서드를 갖고 있는 protocol을 만들어 구현하였습니다. 그러나 줄라이가 주신 피드백을 듣고 tableView나 collectionView에서 cell을 구현할 때, 위의 코드 처럼 정형화되어 있는데, 그 부분을 다르게 접근하게 되면 왜 그렇게 했는지 명확한 이유가 있어야 한다고 생각하였습니다.

처음만든 protocol은 두개의 cell이 지켜야하는 약속을 담았다는 느낌보다 위의 코드가 작동하도록 끼워맞춘 느낌이 더 강했다고 생각합니다. 또한 protocol로 타입캐스팅을 하고 return 할때 cell을 UICollectionCell로 한번 더 타입캐스팅 하는 과정 자체가 어색하다고 느껴졌습니다.

따라서 코드를 중복으로 사용하더라도 직관적인 정형화된 형태로 수정하였습니다.

## ✅ 조언을 구하고 싶은 점

### 1️⃣ Dynamic Type 적용을 위한 리스트 셀의 오토레이아웃
리스트 셀에 dynamic type을 적용하기 위해 레이블의 레이아웃을 구성하는 데 `greaterThanOrEqualTo` 파라미터를 사용하였습니다.
현재 저희 코드에서는 '감독', '박성광' 레이블이 하나의 스택뷰에 들어가 있는 구조입니다.

**DailyBoxOfficeListCollectionViewCell**
``` swift
// 아래 실행 화면에서 '감독'을 나타내는 레이블의 레이아웃
    titleLabel.leadingAnchor.constraint(equalTo:
                            movieInformationStackView.leadingAnchor, constant: 10)

// 아래 실행 화면에서 '박성광'을 나타내는 레이블의 레이아웃
    directorDescriptionLabel.leadingAnchor.constraint(greaterThanOrEqualTo:
                            movieInformationStackView.leadingAnchor, constant: 90)
    // 좌측의 '감독' 레이블의 크기가 작을 땐 90의 leading을 적용하되 
    // 커질 경우 그보다 leading이 커지도록 설정
```

<img src="https://i.imgur.com/plpOU5S.gif" width=200>

<br>

`greaterThanOrEqualTo` 레이아웃의 모호함 때문에 xcode에서 경고를 띄우는데, `greaterThanOrEqualTo`를 사용하지 않고 레이아웃을 구현할 방법을 고려해보았으나 적용할만한 방법을 찾지 못했습니다.

- 고려했던 방법: 각 레이블의 title과 상세 내용을 별도의 스택뷰로 구성
    - stackView1: 감독, 제작년도, 개봉일, 상영시간, ...
    - stackView2: 박성광, 2023, 20230322, 97, ...

이 방법의 문제점은 `좌측의 title을 나타내는 레이블`과 `우측의 상세 내용을 나타내는 레이블`의 라인 수가 항상 같지는 않기 때문에, 레이블의 높이가 서로 달라질 수 있다는  [...]

2023-04-06 11:51 UTC, July911 requested changes

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        }
같은 콜렉션뷰를 사용하는데 굳이 셀 등록을 따로 해줘야할까요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +            case .none:
위랑 같은 질문입니다. 굳이 따로 등록해주어야할까요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    @objc private func changeScreenModeButtonTapped() {
메서드 명에 비해 너무나 큰 역할을 하는 것 같습니다.

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          typealias Snapshot = NSDiffableDataSourceSnapshot<Section, DailyBoxOfficeItem>
저번 스텝에서 적절한 위치로 바꾸셨다고 하셨는데 여기가 맞나요  ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let numberFormatter = NumberFormatter()
매번 셀의 데이터를 포메팅 할때마다 2번씩 인스턴스 생성 후 리턴해주는 것 같네요. 
개선 가능할까요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/Enum/AlertMessage.swift
> +enum AlertMessage {
모든 파일에서 접근 가능한 enum일 필요가 있을까요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/Enum/MovieRankMarkColor.swift
> +enum MovieRankMarkColor {
프로젝트 모든 파일에서 접근할 필요가 있나요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/Enum/MovieRankMarkColor.swift
> +    case black
UIColor랑 연관시킬 방법이 있을까요 ?

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +struct DailyBoxOfficeItem: Hashable {
프로젝트 전체에서 접근이 필요할까요 ? 어떤 화면에 종속되었다면, 종속시키는게 맞을 것 같습니다.

2023-04-06 11:51 UTC, July911 commented on BoxOffice/Controller/Enum/Section.swift
> +enum Section: Hashable {
CollectionView Section을 여러 곳에서 사용할 수 있을 것 같네요.

2023-04-06 11:51 UTC, July911 commented on BoxOffice/View/DailyBoxOfficeIconCollectionViewCell.swift
> +    static let reuseIdentifier = "DailyBoxOfficeIconCollectionViewCell"
매번 이렇게 해주는거 말고 다른 방법이 있을 것 같네요.

2023-04-06 13:16 UTC, July911 commented
일단 너무 잘해주셨네요 :) 
빠르게 다음 스텝으로 넘어가시는걸 권장 드립니다. 
또한 처음보다 훨씬 코드도 깔끔해진 모습입니다. 
내일 안으로 수정해서 주말동안은 다음 스텝에 집중할 수 있게 하면 좋겠습니다 :) :) 

### 1️⃣ Dynamic Type 적용을 위한 리스트 셀의 오토레이아웃
아닙니다. 전혀 문제가 없어보입니다. 
Label 이 접근성 지원에 따라 커짐에 따라 3줄이 되는건 너무 당연한 것 같습니다. 

### 2️⃣ ViewController에서 사용하는 enum 파일 분리

파일 안에서만 쓰는건 Nested로 만드는걸 권장드립니다. 
모든 프로젝트 파일에서 접근되는건 굉장히 아이러니 한 것 같습니다. 


-> 2️⃣ View에 보여지는 Label.text를 넣어주는 역할 VC로 분리 
```
func setupLabels(name: String, audienceInformation: String, rank: String, rankMark: String, audienceVariance: String, rankMarkColor: MovieRankMarkColor) {
        nameLabel.text = name
        audienceInformationLabel.text = audienceInformation
        rankLabel.text = rank
        rankMarkLabel.text = rankMark
        audienceVarianceLabel.text = audienceVariance
        
        switch rankMarkColor {
        case .red:
            rankMarkLabel.textColor = .systemRed
        case .black:
            rankMarkLabel.textColor = .black
        case .blue:
            rankMarkLabel.textColor = .systemBlue
        }
```
    
    또한 고민한 점에서 이 부분 조금 더 개선 될 여지가 있을 것 같습니다 :)

2023-04-07 02:53 UTC, yijiye commented on BoxOffice/View/DailyBoxOfficeIconCollectionViewCell.swift
> +    static let reuseIdentifier = "DailyBoxOfficeIconCollectionViewCell"
String(describing) 을 사용하여 해결하였습니다.
의견 주신 protocol을 활용하는 방법도 추후 적용해보도록 하겠습니다 😀🙇‍♂️

2023-04-07 02:55 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        }
저희는 컬렉션뷰에 등록된 셀을 매번 교체해주어야 한다고 생각하여 저렇게 분리처리를 해두었습니다.
하지만 셀 등록은 여러 셀을 등록해놓아도 dequeue할 때 아무 문제가 없는 것을 확인하였습니다.
따라서 두 셀을 모두 `configureCollectionView`내에서 등록하도록 수정하였습니다!

``` swift
private func configureCollectionView() {
        ...
        collectionView.register(DailyBoxOfficeListCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeListCollectionViewCell.reuseIdentifier)
        collectionView.register(DailyBoxOfficeIconCollectionViewCell.self, forCellWithReuseIdentifier: DailyBoxOfficeIconCollectionViewCell.reuseIdentifier)
        ...
    }
```

2023-04-07 02:55 UTC, yijiye commented on BoxOffice/Controller/Enum/Section.swift
> +enum Section: Hashable {
사용되는 곳으로 옮긴 후 fileprivate 접근제어를 걸어주었습니다.
저희가 처음 cell을 구현할 때, iOS 14버전을 테스트용으로 만들어두니 자꾸 그 부분이 걸려서 다음 스텝에서는 삭제하고 진행하도록 하겠습니다. 🥲

2023-04-07 02:55 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +            case .none:
두 셀을 모두 `configureCollectionView`내에서 등록하도록 수정하였습니다!

2023-04-07 02:56 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +    @objc private func changeScreenModeButtonTapped() {
해당 메서드 내에서 셀을 업데이트하는 부분은 `updateCell` 메서드로 분리하였습니다. 😄

2023-04-07 02:56 UTC, yijiye commented on BoxOffice/Controller/Enum/MovieRankMarkColor.swift
> +    case black
연산프로퍼티를 구현해보았습니다.
```swift
enum MovieRankMarkColor {
    case blue
    case red
    case black
    
    var color: UIColor {
        switch self {
        case .blue:
            return UIColor.systemBlue
        case .red:
            return UIColor.systemRed
        case .black:
            return UIColor.black
        }
    }
}
```
이렇게 변경하니 cell에서 따로 case 별로 나누지 않아 좀 더 깔끔한 코드가 된 것 같습니다!

2023-04-07 02:57 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          typealias Snapshot = NSDiffableDataSourceSnapshot<Section, DailyBoxOfficeItem>
타입 내 최상단으로 위치 이동하였습니다. 🙇

2023-04-07 02:59 UTC, kokkilE commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        let numberFormatter = NumberFormatter()
`NumberFormatterManager` 타입을 따로 구현하여 셀의 데이터를 포메팅할 때마다 불필요한 인스턴스 생성 작업이 반복되지 않도록 하였습니다.

2023-04-07 03:01 UTC, yijiye commented on BoxOffice/Controller/Enum/MovieRankMarkColor.swift
> +enum MovieRankMarkColor {
`MovieRankMarkColor` 는 List, Icon cell과 VC에서 사용되어 따로 파일 분리를 하였습니다.

2023-04-07 03:02 UTC, kokkilE commented on BoxOffice/Controller/Enum/AlertMessage.swift
> +enum AlertMessage {
`AlertMessage`는 특정 VC에 종속된 타입이기 때문에 해당 VC 내로 이동하고 `fileprivate` 키워드를 사용하였습니다.

2023-04-07 05:59 UTC, merged