박스오피스 II [STEP 1] kaki, harry
yagom-academy/ios-box-office pull request #47
Opened 2023-04-06 08:39 UTC by HarryHyeon

# 박스오피스 II [STEP 1] kaki, harry
@1Consumption
안녕하세요 올라프! 박스오피스2 Step1의 구현이 완료되어 PR 드립니다~!
이번 스텝 리뷰도 잘 부탁드립니다🙇🏻🙇🏻🙇🏻

## 구현 내용

### UICalendarView 구현
- 프로젝트 핵심경험을 충족시키기 위해 UICalendarView을 구현하였고, 이를 사용하기 위해서 프로젝트 Minimum Deployments를 iOS 16까지 올려주었습니다.
- 프로젝트 요구사항에는 `선택할 수 있는 날짜는 오늘까지로 제한합니다` 라고 되어있지만, 박스오피스 조회는 전날까지만 가능하기 때문에 선택할 수 있는 날짜를 전날까지로 제한하였습니다.

### UpdateDateDelegate로 선택한 날짜 전달하기
- BoxOfficeViewController에 `var selected: Date` 라는 연산 프로퍼티를 만들어 두고 이 프로퍼티의 날짜를 가지고 박스오피스 순위를 조회하도록 하였습니다.
- `selected` 프로퍼티의 값이 설정되면 다시 박스오피스 순위를 불러오도록 didSet에 설정해 주었고, CalendarViewController에서는 delegate를 통해 달력에서 선택하는 날짜를 전달하도록 하였습니다.

## 고민한 점, 질문사항

### CalendarViewController
- 박스오피스 프로젝트에서 레이아웃 관련한 부분들을 코드가 아닌 스토리보드 기반으로 작업하는 방식을 사용하고 있었습니다. 그렇기에 CalendarViewController도 메인 스토리보드에 뷰컨을 추가해주었는데, UICalendarView는 스토리보드에서 작업해주는 것이 불가능하여 코드로 설정해주게 되었습니다.
- 결과적으로 스토리보드 상에는 CalendarViewController가 빈 뷰컨트롤러로 남아있게 되었는데, 이렇게 사용할 바엔 CalendarViewController는 코드로 뷰컨을 생성해주고 사용하는것이 나을 수도 있겠다고 생각했습니다.
- 스토리보드로 작업하는 기준으로, 빈 뷰컨이라도 스토리보드에 보여주는것이 나을지 혹은 스토리보드에서 작업할 수 있는 것이 없다면 이 부분만 스토리보드에서 제외해주는 것이 나은 방식인지 올라프의 조언을 얻고 싶습니다!

### DateComponents.date 의 날짜가 미국 날짜로 반환되는 이유
- UICalendarView에서 날짜 선택을 통해 `UICalendarSelectionSingleDateDelegate`의 `didSelectDate` 메서드에서 dateComponents를 파라미터로 받을 수 있었습니다.
- 직접 값을 확인해보니 선택한 날짜에서 하루 뺀 날짜가 출력되는 것을 확인할 수 있었습니다.

<img src="https://i.imgur.com/qxx0eEI.png">

- DateComponents의 date 프로퍼티가 기본 내장된 캘린더로 날짜가 계산된다는 것을 알게되었습니다.
- 현재 저희 프로젝트에서는 `selected` 프로퍼티를 DateFormatter에서 한번 포맷을 변환한 이후에 박스오피스 순위 조회의 쿼리로 들어가고 있습니다. 따라서 다시 한국 날짜로 **+ 1**일 되어서 박스오피스 순위를 조회한다는 것을 알게되었습니다.
- DateFormatter의 기본 timezone은 시스템 설정에 적용된 지역과 같기 때문에 위와 같은 결과가 나왔다는 것을 알 수 있었습니다.

2023-04-06 12:25 UTC, 1Consumption requested changes
스텝이 작아 별 다른 코멘트는 없습니다.

질문해주신 
> 스토리보드로 작업하는 기준으로, 빈 뷰컨이라도 스토리보드에 보여주는것이 나을지 혹은 스토리보드에서 작업할 수 있는 것이 없다면 이 부분만 스토리보드에서 제외해주는 것이 나은 방식인지

에 대한 제 생각은 다음과 같습니다.

우선 스토리보드를 쓰는 이유가 궁금한데요, View의 흐름을 인터페이스빌더로 한눈에 파악하기 위함이라면 빈 뷰컨이라도 스토리보드에 있는게 맞다고 생각합니다. 
그게 아니라 굳이 스토리보드를 쓰는 이유가 없다면, 쓸 이유가 없겠죠.

2023-04-06 12:25 UTC, 1Consumption commented on BoxOffice/Controller/BoxOfficeDataLoader.swift
> +    func loadDailyBoxOffice(date: Date, completion: @escaping (BoxOffice?, Error?) -> ()) {
Result 타입을 사용해보세요.

2023-04-06 12:25 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +    private var selectedDate = Date(timeIntervalSinceNow: -86400) {
`Date(timeIntervalSinceNow: -86400)` 이 값이 상수로 관리되면 좋겠습니다. 또한 view에서 알 필요가 없는 정보같습니다.

2023-04-06 12:25 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +            guard let self = self else { return UIViewController() }
self 옵셔널 바인딩이 필요한가요?

2023-04-06 12:25 UTC, 1Consumption commented on BoxOffice/View/CalendarViewController.swift
> +    let selectedDate: Date
외부에서 몰라도 되는 값 같네요.

2023-04-07 02:27 UTC, HarryHyeon commented on BoxOffice/Controller/BoxOfficeDataLoader.swift
> +    func loadDailyBoxOffice(date: Date, completion: @escaping (BoxOffice?, Error?) -> ()) {
컴플리션에 두가지 경우를 파라미터로 가지는 메서드들을 모두 Result 타입으로 수정해주었습니다.

2023-04-07 02:28 UTC, kak1x commented on BoxOffice/View/BoxOfficeViewController.swift
> +    private var selectedDate = Date(timeIntervalSinceNow: -86400) {
Date에 extension을 추가하여 `Date().previousDate()` 로 사용하였습니다. 또한 selectedDate에 포함되어 있던 로직을 `UpdateDateDelegate` 쪽으로 넘겨주어 selectedDate 변수가 불필요한 정보를 갖는 것을 수정해주었습니다.

2023-04-07 02:29 UTC, kak1x commented on BoxOffice/View/CalendarViewController.swift
> +    let selectedDate: Date
접근 제어를 private로 변경해주었습니다.

2023-04-07 02:30 UTC, HarryHyeon commented on BoxOffice/View/BoxOfficeViewController.swift
> +            guard let self = self else { return UIViewController() }
CalendarViewController의 이니셜라이저에서 `date`가 옵셔널 값을 허용하지 않아서 옵셔널 바인딩을 해주었습니다.

2023-04-07 17:18 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +            guard let self = self else { return UIViewController() }
흠.. 그렇다면 95번째 라인에서 `let date = selectedDate`를 로컬변수로 추가해서 사용하면 어떨까요? 그러면 self에 대한 옵셔널 바인딩이 없어도 될듯하긴한데요.
☝️ 이게 꼭 맞다는건 아닙니다. 그냥 어떻게 생각하시는지 궁금하네요. 동료가 질문한다 생각하고 편하게 생각해주세요.

2023-04-08 05:44 UTC, kak1x commented on BoxOffice/View/BoxOfficeViewController.swift
> +            guard let self = self else { return UIViewController() }
self를 바인딩 해주는 대신 `self?. selectedDate` 만 바인딩 하는 것으로 변경해주었습니다.
근데 혹시 self 바인딩을 사용하지 않아야하는 이유가 있을까요?? 이전부터 self 바인딩과 관련하여 코멘트를 여러번 주셨는데, 사용하면 안 되는 이유가 있는건지 궁금해서 질문드려요!
7065d74c937092c3d19ec236b3ced7dc6d934451

2023-04-09 14:48 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +            guard let self = self else { return UIViewController() }
`굳이 해야하는가? -> 아니다.` 라는 생각이 들었습니다.
self를 옵셔널 바인딩 해주면 지연 할당 해제가 발생하는데, 사이드 이페트가 발생할 수 있기 때문입니다. 물론 지금은 그런 상황은 아니지만요.

아래 문서를 읽어보세요.
https://medium.com/@almalehdev/you-dont-always-need-weak-self-a778bec505ef

2023-04-09 14:48 UTC, merged