박스오피스II [STEP 2] sehong
yagom-academy/ios-box-office pull request #48
Opened 2023-04-06 13:11 UTC by sehoong0429

# step2
@AppleCEO
안녕하세요 도미닉!
Step2 PR올립니다..! ㅠㅡㅠ 
레이아웃을 구성하는부분이 유독 어려웠던 스텝이었습니다..ㅠㅡㅠ

### 1️⃣ UIToolBar 사용 
UIToolBar를 사용하여 화면모드를 변경해주었습니다.
아래의 함수를 호출하면 toolbar가 화면에 표시되고 사용자가 화면을 변경할 수 있습니다. 
```swift 
private func configureNavigationToolbar() {
        navigationController?.isToolbarHidden = false
        
        let item = UIBarButtonItem(
            barButtonSystemItem: .flexibleSpace,
            target: self,
            action: nil
        )
        let UIBarButton = UIBarButtonItem(
            title: "화면 모드 변경",
            style: .plain,
            target: self,
            action: #selector(changeViewMode)
        )
        
        setToolbarItems([item, UIBarButton, item], animated: true)
    }
```

### 2️⃣ UICollectionViewCompositionalLayout 활용

두 개의 아이템을 수평으로 나열한 그룹을 생성하여 컬렉션 뷰에 적용해주었습니다. 
```swift 
private func createIconLayout() -> UICollectionViewLayout {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.5),
                                              heightDimension: .absolute(180))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 10, bottom: 0, trailing: 5)
        
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                               heightDimension: .estimated(180))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitems: [item])
        
        let section = NSCollectionLayoutSection(group: group)
        section.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 10, bottom: 0, trailing: 10)
        section.interGroupSpacing = 10
        
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout
    }
```

2023-04-07 04:33 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@sehoong0429 이번 스텝 쉽지 않았을텐데 고생 많으셨습니다!
오래도록 가야하니 건강도 잘 챙기시길 바랍니다.
몇가지 코멘트 남겨봤습니다 ㅎㅎ
그리고 SecretKey.swift 파일이 저는 없어서 앱을 실행시킬 수 없는데 DM으로 전달해주시면 앱 돌려보도록 하겠습니다~

2023-04-07 04:33 UTC, AppleCEO commented on BoxOffice/View/MovieIconCell.swift
> +            switch rankInten {
rankInten 은 생소한 단어인데요.
Inten 은 어떤 의미일까요?

2023-04-07 04:33 UTC, AppleCEO commented on BoxOffice/View/MovieInfoView.swift
여기 공백은 어떤 의미일까요? 
titleLabel 과 contentLabel 에 대한 것이 이 공백으로 구분되어 있는데요.
함수 안에 공백이 있다는 것은 함수가 하나의 동작만 하고 있지 않고 여러 동작을 하는 신호일 수 있습니다.
하나의 함수가 하나의 동작만 하도록 나눠볼까요?

2023-04-07 04:33 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
이 주변에 들어간 숫자들을 하드코딩하지 않고 상수 같은 곳에 모아놓을 수 있을까요?

2023-04-07 04:33 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        }
이런 형식의 코드가 반복되는데요. 혹시 데이터 소스를 나눠서 list 는 list 코드만 있는 식으로 구현 가능할까요?

2023-04-07 04:52 UTC, sehoong0429 commented on BoxOffice/View/MovieIconCell.swift
> +            switch rankInten {
rankInten은 영화진흥위원회 API에서 `전일대비 순위의 증감분` 이라는 뜻으로 가지고 오는 모델인데 
Intensity를 줄여서 표현 한 것 같습니다. Intensity를 사용하려고 하다가 Intensity도 자주 쓰는 용어가 아니라서 따로 수정 할 생각을 하지 못했습니다.

2023-04-07 04:57 UTC, sehoong0429 commented on BoxOffice/View/MovieInfoView.swift
[17ece9e](https://github.com/yagom-academy/ios-box-office/pull/48/commits/17ece9e3784167beb18a002b7017031bb271a1dd)
해당 부분은 코드가 길어지면서 정리 할 생각을 못하고 있었습니다ㅠㅠ 
감사합니다. titleLabel, contentLabel 각각 그려줄 수 있도록 만들어주었습니다.

2023-04-07 05:04 UTC, AppleCEO commented on BoxOffice/View/MovieIconCell.swift
> +            switch rankInten {
줄임말이라고 예상은 했습니다. 그런 경우에 아예 풀로 작성하는 것도 좋습니다. Xcode 는 자동완성이 되어서 긴 이름을 작성해도 사용하는데 불편하지 않습니다. 저는 코드 작성 시 줄임을 전혀 사용하지 않습니다.

2023-04-07 05:04 UTC, AppleCEO commented on BoxOffice/View/MovieIconCell.swift
> +            switch rankInten {
Intensity 로 아예 작성이 되었으면 번역기를 돌려서 어떤 의미인지 대충 알아챌 수 있었을 겁니다 ㅎㅎ 🔢

2023-04-07 05:17 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
```swift
private enum iConLayoutConstant {
        
        static let itemFractionWidth: CGFloat = 0.5
        static let itemabsoluteHeight: CGFloat = 180
        static let groupFractionWidth: CGFloat = 1.0
        static let groupAbsoluteHeight: CGFloat = 180
        static let sectionSpacing: CGFloat = 10
}
```
이렇게 사용하라고 하는 말씀 맞으실까요?

2023-04-07 05:21 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
네 맞습니다 ㅎㅎ

2023-04-07 05:29 UTC, sehoong0429 commented on BoxOffice/View/MovieIconCell.swift
> +            switch rankInten {
[3f5af95](https://github.com/yagom-academy/ios-box-office/pull/48/commits/3f5af957dbcf5ecc7427bdf608d281352ea10652)

해당 부분 수정해보았습니다! 
사용하지 않는 모델들도 없애고, 줄임말 사용 지양하도록 하겠습니다 ㅎㅎ

2023-04-07 05:34 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
[0804f3a](https://github.com/yagom-academy/ios-box-office/pull/48/commits/0804f3a4401dd32efbb5928665db5778bbebcf1a)

해당 부분 수정해주었습니다! 위에 다른거 모델명 수정하면서 커밋이 잘못들어갔는데 이부분만 확인해주시면 됩니다. ㅎㅎ 
앞으로 이 방법을 사용하면 좋을 것 같다고 느꼈습니다~ 관련된 코드 하나만 건들면 되니까 편할 것 같습니다!

2023-04-07 05:35 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
아.. 제가 말을 잘못 적었는데 처음에 작성해주신 enum 을 사용하는 방식이 더 좋습니다!
번거롭거나 하면 두번째 말씀드린 상수에 넣어주신 지금 하신 방식도 나쁘지는 않습니다~

2023-04-07 05:40 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
[c2cb253](https://github.com/yagom-academy/ios-box-office/pull/48/commits/c2cb25365d76eb76714d31b79e52d4c372412b0c)

감사합니다! 해당 부분 변경해주었습니다~! 파일을 따로 빼는게 좋을까요? 아니면 그대로 놔두는게 좋을까요 ㅎㅎ ?

2023-04-07 05:41 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
헉.. 반복 작업하게 해서 죄송합니다. 그대로 둬도 좋겠습니다!

2023-04-07 05:46 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +                                               heightDimension: .estimated(180))
전혀 귀찮은 작업이아니라서 완전!! 괜찮습니다 ㅎㅎ 감사합니다!

2023-04-07 07:15 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        }
도미닉 해당 부분을 list랑 icon datasource 함수를 만들어서 나눠서 하라고 하시는 말씀일까요? 
처음에 나눠서 구현해봤는데 공식문서를 보면 데이터소스를 만든뒤에 컬렉션뷰에서 데이터 소스를 변경하지 말라고 하는 말이 있어서요. 
해당부분은 어떤식으로 구현하면 좋을지 조금 구체적인 도움이 필요합니다..! 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/67987230/230560904-0ad97ce4-f027-4b5a-aed7-2ff553c7a7f1.png">

2023-04-07 13:30 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        }
스냅샷을 사용해서 현재 방식에서 바꿀 수는 없는 것으로 보입니다!
changeView() 함수에서 collectionView.reloadData() 를 하고 있어서 모드를 바꾸면 화면이 깜빡거리는데 reloadData 를 하지 않을 수 있는 방법이 있을지 궁금하긴 한데요.
이건 부가적인 것이라 넘어가도 좋습니다!

2023-04-07 14:12 UTC, AppleCEO approved these changes
@sehoong0429  고생하셨어요~
몇가지 코멘트들 남겨봤습니다.
다음 스텝을 하면서 고민해보셔도 되고 이번 스텝에서 정리하고 가셔도 되겠습니다.

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +            top: 0, leading: 10, bottom: 0, trailing: 5)
모든 숫자가 사라지길 바랐는데 남아있네요!

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +            top: 0, leading: 10, bottom: 0, trailing: 10)
이런 식으로 두 줄로 작성된 것을 저는 보기 안좋다고만 생각했는데요. 
실제 코드를 조금 바꿔보면서 테스트해보려고 주석해보니 두 줄을 다 주석 처리하지 않으면 오류가 발생해서 코드가 실행되지 않네요!
조금 길더라도 하나의 동작을 하는 코드는 한 줄로 작성하는 것이 좋겠습니다~

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        let actionTitle: String = currentViewOption == .list ? ViewOption.icon.rawValue : ViewOption.list.rawValue
3항 연산자를 사용해 보셨군요! 👍

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/ViewController.swift
> +        collectionView.reloadData()
reloadData 를 하니 화면이 깜빡 거리네요. 
reloadData 를 지워보니 화면이 깨져서 보이는군요 ㅎㅎ
이거는 나중에 다음 스텝들 진행하시고 시간 남으시면 추가 미션으로 안깜빡거리게 해봐도 좋겠어요. (저도 지금 1시간 정도 찾아봤는데 바로 나오지는 않네요)

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/View/MovieIconCell.swift
> +        stateLabel.attributedText = createStateLabel(rankOldandNew: item.rankOldandNew, rankIntensity: Int(item.rankIntensity)!)
여기 강제 언레핑이 있군요! 지워볼까요?

2023-04-07 14:12 UTC, AppleCEO commented on BoxOffice/Model/MovieRankingItem.swift
> +    let rankIntensity: String
이름이 명확해졌네요~ 🥇

2023-04-09 13:32 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        }
감사합니다! 
레이아웃을 그려줄때 animated가 true로 설정되어 있어서 false로 변경해주었습니다 ㅎㅎ! 
깜빡거리는 현상은 해결되었습니다!!

2023-04-09 13:38 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +            top: 0, leading: 10, bottom: 0, trailing: 5)
[6cb12eb](https://github.com/yagom-academy/ios-box-office/pull/48/commits/6cb12eb62647d8de360c980b19dca898a2428ed7)
해당 부분 수정해주었습니다!

2023-04-09 13:39 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +            top: 0, leading: 10, bottom: 0, trailing: 10)
네!! 
이번에 상수값을 변경하면서 너무 길어지게 되어 하나하나 볼 수 있도록 띄어쓰기하여 값을 넣어주었습니다! 
이건 괜찮을까요? 
[6cb12eb](https://github.com/yagom-academy/ios-box-office/pull/48/commits/6cb12eb62647d8de360c980b19dca898a2428ed7)

2023-04-09 13:40 UTC, sehoong0429 commented on BoxOffice/ViewController.swift
> +        collectionView.reloadData()
저도 찾아봤는데 ㅠ 간단하게 제가 레이아웃을 그려줄때 애니메이션을 true로 설정해두어서 발생하는 문제였습니다..!ㅠㅡㅠ
기존에는 화면 변경할때 흰색화면이 뜨고 변경되었는데 현재는 바로 변경이 됩니다!!

2023-04-09 13:45 UTC, sehoong0429 commented on BoxOffice/View/MovieIconCell.swift
> +        stateLabel.attributedText = createStateLabel(rankOldandNew: item.rankOldandNew, rankIntensity: Int(item.rankIntensity)!)
[fcc50cf](https://github.com/yagom-academy/ios-box-office/pull/48/commits/fcc50cfb831f3938a7f004c81ae8ca13fcf316ab)
해당 부분 수정해주었습니다!

2023-04-09 14:04 UTC, merged