박스오피스 Ⅱ [STEP 1] 레옹아범, Andrew
yagom-academy/ios-box-office pull request #50
Opened 2023-04-07 05:59 UTC by Andrew-0411

@1Consumption 
안녕하세요 올라프! 박스오피스 &#8545; STEP1 PR 보내드립니다.
UICalendarView가 최신기능이라서 Xcode의 버전을 올린 iOS 16으로 변경하여 구현하였습니다. 

---

## 고민했던점

### 1️⃣ 뷰 컨트롤러간의 데이터 전달
#### ❓문제점
* `CalendarViewController`에서 `MovieRankingViewController`로 어떤방식으로 데이터전달을 할지 고민했습니다.
* `NotificationCenter`, `싱글톤`, `Delegate`방식이 있을거 같은데 싱글톤을 쓰게되면 결합도의 문제도 있지만 너무 많은 타입이 생기는것같아 사용하지 않았습니다.
* `NotificationCenter`의 경우 하나의 이벤트에 대해 여러 객체가 다양하게 처리되어야 할 때 사용하는 것이 좋으므로, 하나의 이벤트가 `MovieRankingViewController`만 이벤트처리를 하는 상황에서 `Delegate`를 사용하는 것이 좋다 생각하여 `Delegate`패턴을 사용하였습니다.

#### 📖해결법
```swift
protocol ChangedDateDelegate {
    func changeDate(_ date: Date)
}

func dateSelection(_ selection: UICalendarSelectionSingleDate, didSelectDate dateComponents: DateComponents?) {
    guard let selectedDate = dateComponents?.date else {
        return
    }

    delegate?.changeDate(selectedDate)

    dismiss(animated: true)
}
```
* 위와 같이 `ChangedDateDelegate`프로토콜을 만들어 사용자가 날짜를 선택할 경우 `MovieRankingViewController`에서 `ChangedDateDelegate`메소드를 실행하게끔 구현하였습니다.

<br/>

### 2️⃣ UICalendarView의 배경색

#### ❓문제점
![](https://i.imgur.com/KAYZMti.png)

- [Apple Developer: UICalendarView](https://developer.apple.com/documentation/uikit/uicalendarview)
- [Apple Developer: backgroundColor](https://developer.apple.com/documentation/uikit/uiview/1622591-backgroundcolor)
- UIView는 backgroundColor의 value가 nil인 즉 투명색은 배경을 가지고 있습니다
- UICalendarView는 UIView를 상속받기때문에 UICalendarView 또한 처음 만들어줄때 배경색이 없는 문제점이 있었습니다.

#### 📖해결법

![](https://i.imgur.com/33JFrz4.png)

- 다크모드에서도 대응을 해주기 위해 `CalendarViewController`의 `view.background`를 white가 아닌 .systemBackground로 배경색을 주었습니다

### 3️⃣ CalendarView의 Locale

#### ❓문제점
* [CalendarView](https://developer.apple.com/documentation/uikit/uicalendarview)해당 공식문서를 보다보니 `Locale`이라는 것을 `zh-CN`으로 할당해주는데 `Locale`은 고유 언어에 맞게 주는것으로 확인했습니다.
* 만약 주지 않을 경우 현재 사용자의 지역에 따라 맞춰주는데 저희는 한국 박스오피스와 한글만을 사용하므로 `Locale`을 할당해주었습니다.

#### 📖해결법
* `Locale`의 `init.(identifier:)`의 경우 유니코드의 고유 언어 ID를 따르므로 [Unicode Language Identifier](http://www.i18nguy.com/unicode/language-identifiers.html)를 참고하여 `Locale`을 할당해주었습니다.

```swift
private let calendarView = {
    let calendarView = UICalendarView()
    calendarView.translatesAutoresizingMaskIntoConstraints = false
    calendarView.calendar = Calendar(identifier: .gregorian)
    calendarView.locale = Locale(identifier: "ko_KR")

    return calendarView
}()
```

2023-04-07 17:31 UTC, 1Consumption requested changes
고생하셨습니다.

스탭이 작아 특별한 코멘트는 없습니다.

2023-04-07 17:31 UTC, 1Consumption commented on BoxOffice/Model/Manager/RankingManager.swift
> -
변수 위치를 바꿔준 이유가 있을까요?

2023-04-07 17:31 UTC, 1Consumption commented on Controller/CalendarViewController.swift
> +    var delegate: ChangedDateDelegate?
이 delegate는 weak일 필요가 없나요?

2023-04-07 17:31 UTC, 1Consumption commented on Controller/MovieDetailViewController.swift
> +    }
`make~`는 `~를 반환한다` 라는 의미가 포함되는거 같습니다. 다른 네이밍은 어떨까요?

2023-04-07 17:31 UTC, 1Consumption commented on Controller/MovieDetailViewController.swift
> +    private var dataManager: MovieDescManager?
이렇게 바꿔준 이유가 궁금합니다.

2023-04-07 17:31 UTC, 1Consumption commented on Controller/MovieRankingViewController.swift
> +        navigationItem.title = navigationTitleText
title 변수가 옵셔널이니 굳이 옵셔널 바인딩이 없어도 될듯합니다.

2023-04-10 05:07 UTC, fatherLeon commented on BoxOffice/Model/Manager/RankingManager.swift
> -
연산 프로퍼티 역시 하나의 프로퍼티이기 때문에 프로퍼티끼리 모여있는게 좋다고 생각하여 바꾸어주었습니다.
`MovieInfoUIModel`과 `CellUIModel`도 연산프로퍼티를 프로퍼티끼리 모여있도록 코드를 수정하였습니다.

2023-04-10 05:13 UTC, Andrew-0411 commented on Controller/CalendarViewController.swift
> +    var delegate: ChangedDateDelegate?
weak로 변경하고 ChangedDateDelegate프로토콜의 AnyObject를 채택하였습니다

2023-04-10 05:17 UTC, Andrew-0411 commented on Controller/MovieDetailViewController.swift
> +    }
~를 생성하다 라는 의미를 가진 create로 변경하였습니다

2023-04-10 05:25 UTC, fatherLeon commented on Controller/MovieDetailViewController.swift
> +    private var dataManager: MovieDescManager?
우선 앞선 리뷰에서 lazy를 지양하라고 말씀하셔서 lazy를 제거했고 나름대로의 이유를 생각해보았습니다.
1. lazy의 경우 [lazy 공식문서](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/#Lazy-Stored-Properties)를 참고해보니 여러 쓰레드에서 해당 `lazy var`프로퍼티에 접근할 경우 한번만 초기화 되는 것이 아닌 여러번 초기화 될 가능성이 있습니다. 특히, 지금 사용하고 있는 네트워크 통신의 경우 다른 쓰레드에서 작업을 따로 처리하고 있기 때문에 lazy가 여러번 초기화 되는 상황이 발생할 수도 있다는 생각이 들었습니다.
2. `lazy var`의 경우 프로퍼티가 호출 될 때 초기화가 되므로 그 상황에서 성능저하가 발생할 수도 있을것 같아 지양하는게 좋다고 생각이 듭니다.

2023-04-11 09:20 UTC, merged