박스오피스 II [STEP 2] kaki, harry
yagom-academy/ios-box-office pull request #51
Opened 2023-04-10 11:40 UTC by kak1x

# 박스오피스 II [STEP 2] kaki, harry
@1Consumption
안녕하세요 올라프! 박스오피스2 Step2의 구현이 완료되어 PR 드립니다~!
이번 스텝 리뷰도 잘 부탁드립니다🫡

## 구현 내용

### 화면 모드 변경
- 화면 모드 변경을 통해 화면이 변경될 수 있도록 두 종류의 레이아웃과 두 종류의 셀을 구현해주었습니다.
- 뷰컨트롤러에 각각의 컬렉션뷰를 구현하여 화면 모드 변경 선택 시 필요없는 컬렉션뷰를 감춰주며, 표시되어야할 컬렉션뷰를 애니메이션과 함께 표시해주도록 구현해주었습니다.

### Action Sheet
- 박스오피스 조회 화면에 툴바를 구현하였고 이를 선택할 시 박스오피스 조회 화면의 레이아웃을 선택할 수 있게 Action Sheet가 표시되도록 구현하였습니다.
- Action Sheet의 UIAlertAction은 현재 레이아웃 정보를 이용하여 현재 레이아웃을 제외한 다른 레이아웃만 선택할 수 있게 구현해주었습니다.

### Dynamic Type
|박스오피스 조회 화면(List)|박스오피스 조회 화면(Icon)|영화 상세 정보 페이지|
|:-----:|:-----:|:-----:|
| <img src = "https://i.imgur.com/LULv0AT.png" width = "300">|<img src = "https://i.imgur.com/hgDgOZS.png" width = "300">|<img src = "https://i.imgur.com/jhic0Wf.png" width = "300">|

- 모든 화면에 사용자가 지정한 Font Size에 맞춰 표시할 수 있도록 구현해주었습니다.
- Icon 형태의 박스오피스 조회 화면에서는 기존 셀의 크기를 그대로 유지하며 중요한 정보(순위, 제목)만 표시할 수 있게 일정 수준 이상으로 글자가 커지면 우선 순위가 떨어지는 정보를 안보이게 구현해주었습니다.

## 고민한 점, 질문사항

### 화면 모드 변경시 발생하는 Constraints 에러, 부자연스러운 모드변경

<img src="https://i.imgur.com/6Z4ZB6Y.gif" width="200">

```swift
private func configureCollectionViewLayout() {
    switch layoutMode {
    case .list:
        collectionView.setCollectionViewLayout(createListLayout(), animated: true)
    case .icon:
        collectionView.setCollectionViewLayout(createIconLayout(), animated: true)
    }
    collectionView.reloadData()
}
```

- 액션시트에서 현재 화면 모드에따라 레이아웃 객체를 변경해주는 메서드(`configureCollectionViewLayout()`)를 액션 핸들러로 주었습니다.
- setCollectionViewLayout(_: animated:) 메서드를 사용해 애니메이션을 주면서 동작하도록 하였는데, 모드를 변경할때 바로 원하는 레이아웃으로 동작하는 것이 아닌 잠깐 constraint가 깨진 레이아웃으로 동작하였다가 구현하고자하는 레이아웃으로 변경되는 것을 볼 수 있었습니다.
- 또한, 레이아웃을 바꿔줄때마다 constraint 에러가 콘솔에 출력되었습니다.
- 위의 문제를 나름대로 분석해보았습니다.
    - 현재 커스텀셀의 타입을 2개 사용중입니다. 데이터소스에서 정의한 셀의 타입이 바뀌지않은 상태에서 레이아웃을 바꾸어주었기 때문이라고 생각했습니다.
    - `collectionView.reloadData()` 메서드를 호출하여 현재 셀의 타입을 바꾸어주어도 그 시점의 레이아웃은 셀의 타입에 맞지 않는 레이아웃 객체이기 때문에 마찬가지로 에러가 발생했습니다.
    - 그렇다면 데이터소스에서 셀의 타입을 다시 정해주는 것과 레이아웃의 교체가 동시에 일어나거나 컬렉션뷰 자체가 교체되어야한다고 생각했습니다.

#### 선택한 해결방법
- listCollectionView, iconCollectionView 두 개의 컬렉션뷰를 선언해놓고 화면 모드에 따라 보여줄 필요가 없는 컬렉션뷰를 Hidden 해주었습니다.
- 뚝뚝 끊기는 듯한 화면모드 변경을 투명도 변화로 애니메이션처리 하였습니다.

<img src="https://i.imgur.com/eqytpLH.gif" width="200">

<br>

### Icon 형태의 박스오피스 조회 화면의 Dynamic Type 적용
<img src ="https://i.imgur.com/2bRlqQ2.png" width ="200">

- 기존 레이아웃을 유지하며 Dynamic Type을 적용하면 셀의 크기가 동적이지 않기 때문에 정보를 표시해주는 레이블이 잘리거나 표시되지 않는 문제가 발생하였습니다.
- 셀의 크기를 동적으로 설정해줄 경우 제목이 길거나 짧은 셀들의 크기가 달라지는 문제가 있었기 때문에 중요한 정보를 우선적으로 표현해주는 현재의 방식을 선택하게 되었습니다.
```swift
private func simplifyItems() {
    if traitCollection.preferredContentSizeCategory >= UIContentSizeCategory.extraExtraLarge {
        rankInfoLabel.isHidden = true
        audienceInfoLabel.isHidden = true
    } else {
        rankInfoLabel.isHidden = false
        audienceInfoLabel.isHidden = false
    }
}
```
- 이를 위해 위와 같은 메서드를 작성한 다음 `awakeFromNib` 부분에 NotificationCenter를 등록해주어 사용자 지정 Font Size가 일정 수준 이상으로 커질 경우 위의 메서드가 실행될 수 있게 구현해주었습니다.
- 또한 도중에 글자 크기를 바꾸는 것이 아닌 이미 큰 글자로 설정된 상태에서 앱을 실행시키는 경우를 고려하여 `awakeFromNib`이 불릴때 위의 메서드가 실행되도록 구현해주었습니다.

2023-04-11 14:22 UTC, 1Consumption requested changes
고생하셨습니다.

콜렉션뷰 관련해서 코멘트를 달았는데, 만약 설명이 부족하거나 이해가 잘 안된다면 디코에서 말을 해보도록하죠.

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/Etc/Configurable.swift
> +}
뭐를Configure한다 라는 의미가 이름에 포함되면 좋겠습니다.

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/Etc/UICollectionView+Animate.swift
> +    }
인덴트가 안맞네요.

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/Etc/UICollectionView+Animate.swift
> +                       animations: { self.alpha = 0 })
completion은 escaping 클로저인데 [weak self]를 안해줘도 되나요?

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/Etc/UIViewController+AlertController.swift
> +}
이정도로 extension이 생길거면 UIAlertController를 만들어주는 factory를 생성하는건 어떨까요?

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +class BoxOfficeCollectionViewCell: UICollectionViewCell, Configurable {
상속되는 객체인가요?

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        simplifyItems()
코드의 추상화 수준이 통일되면 좋겠습니다.

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }
폰트를 업데이트하는 메소드인데 정작 폰트는 업데이트를 안하고있네요.

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +fileprivate extension String {
private으로 하면 안되나요? 
fileprivate과 private의 차이는 뭘까요?

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +    }
흠 글쎄요... 데이터가 동일한데 두개의 콜렉션뷰를 쓰는게 어색하다고 생각합니다.
dataSource에서 layoutMode로 분기를 치면 어떨까요?

2023-04-11 14:22 UTC, 1Consumption commented on BoxOffice/View/BoxOfficeViewController.swift
> +                iconCollectionView.register(iconCellNib, forCellWithReuseIdentifier: BoxOfficeCollectionViewCell.identifier)
인덴트가 안맞네요.

2023-04-12 07:07 UTC, kak1x commented on BoxOffice/Etc/Configurable.swift
> +}
`CellConfigurable` 로 네이밍 변경해주었습니다!
9bba2d1c725dfb049cafacd820353f5aa74b6c0b

2023-04-12 07:09 UTC, HarryHyeon commented on BoxOffice/Etc/UICollectionView+Animate.swift
> +    }
넵 수정하였습니다 ~!
a6007c3b9957c5a4a81487568b340656bfa995ea

2023-04-12 07:11 UTC, kak1x commented on BoxOffice/Etc/UIViewController+AlertController.swift
> +}
extension을 삭제해주고 factory-pattern을 사용하여 Alert을 생성할 수 있도록 구현해주었습니다.
a1aa0488e198d9b1548f6b4db55155d16d49e8eb

2023-04-12 07:12 UTC, kak1x commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        simplifyItems()
추상화 수준을 통일해주었습니다.
61cc5cd9464b3243c2d9049ce58535287f946a0d

2023-04-12 07:15 UTC, kak1x commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +fileprivate extension String {
private로 선언해주어도 동일하게 작동합니다.
private 멤버는 같은 선언 내에서만 접근 가능하지만, 같은 파일 내부에서는 모든 선언에 접근할 수 있기 때문입니다.
그렇기에 좀 더 명확하게 이를 표현해주기 위해 private가 아닌 fileprivate 접근제어자를 사용했습니다.

2023-04-12 07:16 UTC, kak1x commented on BoxOffice/View/BoxOfficeViewController.swift
> +                iconCollectionView.register(iconCellNib, forCellWithReuseIdentifier: BoxOfficeCollectionViewCell.identifier)
수정해주었습니다.
a6007c3b9957c5a4a81487568b340656bfa995ea

2023-04-12 07:17 UTC, HarryHyeon commented on BoxOffice/Etc/UICollectionView+Animate.swift
> +                       animations: { self.alpha = 0 })
이전 스텝에서도 말씀하신것처럼 지연할당 해제로 인한 사이드 이펙트 발생이 생길 수 있는 경우 weak self를 캡쳐리스트로 작성해주어야 합니다. 

animate 메서드의 트레일링 클로저는 escaping 클로저이므로 해당 클로저 블록이 수행되기전에 self라는 객체가 메모리 해제가 되면 문제가 발생할 수 있기 때문입니다.

따라서 [weak self]를 추가해주었습니다.

2023-04-12 07:17 UTC, kak1x commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +class BoxOfficeCollectionViewCell: UICollectionViewCell, Configurable {
`final class` 로 변경해주었습니다!
61cc5cd9464b3243c2d9049ce58535287f946a0d

2023-04-12 07:19 UTC, HarryHyeon commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }
`updateFonts` 메서드가 불필요하게 `simplifyItems`를 wrapping 하고 있었습니다.
`updateFonts` 메서드를 삭제해주고 `selector`로 `simplifyItems`를 사용하도록 수정해주었습니다.

2023-04-12 14:04 UTC, 1Consumption commented on BoxOffice/Etc/UICollectionView+Animate.swift
> +                       animations: { self.alpha = 0 })
이 문서를 참고해보세요.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/37682858/231482543-bed07451-e99b-452e-b5d5-2a8a57e6ddd2.png">
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/

2023-04-20 13:19 UTC, closed without merging