박스오피스II [STEP 2] goat, 송준
yagom-academy/ios-box-office pull request #53
Opened 2023-04-11 02:58 UTC by kimseongj

# 🎬박스오피스 II [STEP2] 
@forestjae
안녕하세요 숲재! 
박스오피스 II [STEP2] PR입니다.
UI 작업이 이렇게 힘들다는 것을 또 한번 깨닫는 스텝이였습니다..ㅎ
이번 리뷰도 잘 부탁드리겠습니다!!!

### 구현한 점
- Dynamic Type 적용
- ToolBar를 통해 영화 순위 표현 형태 변경 기능 구현

### 고민한 점

### :fire: icon layer - stackview distribution
* icon layer 모드일때 내부 요소들을  하나의`vertical stackview`로 묶어주게끔 UI를 구성했습니다.
* 내부 `label`들의 간격이나 너비가 일정하지않아 고민하다 `stackView Distribution`옵션을 eqaulSpacing으로 줌으로써 해결했습니다.

```swift!
 private let iconTypeStackView: UIStackView = {
        let stackView = UIStackView()
        stackView.translatesAutoresizingMaskIntoConstraints = false
        stackView.axis = .vertical
        stackView.alignment = .center
        stackView.distribution = .equalSpacing
        stackView.spacing = 6
        return stackView
    }()
```

* distribution 옵션

|fillequally|default|equalspacing|
|:----:|:----:|:----:|
|<img src = "https://i.imgur.com/7WFJvVB.png" width = 200> |<img src = "https://i.imgur.com/UprJZrP.png" width = 200>|<img src = "https://i.imgur.com/SIOCuL7.png" width = 200>|

<br/>

### :fire: Modern CollectionView 구현 방식

|변경 전|변경 후|
|---|---|
|<img src = "https://i.imgur.com/jWGxJJ2.png" width = 300>|<img src = "https://i.imgur.com/huopzpF.png" width = 300>|

- 변경 전
    - 전체적인 Cell(item)의 크기를 잡아주어 Dynamic Type을 사용할 때, Cell의 크기가 변하지 않는 문제점 발생합니다.

```swift
private func setUpCompositionalLayout() -> UICollectionViewLayout {
        let layout = UICollectionViewCompositionalLayout {
            (sectionIndex: Int, layoutEnvironment: NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection? in
            
            let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
            let item = NSCollectionLayoutItem(layoutSize: itemSize)
            
            item.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
            
            let groupHeight =  NSCollectionLayoutDimension.fractionalWidth(1/4)
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: groupHeight)
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
            let section = NSCollectionLayoutSection(group: group)
            
            return section
        }
        return layout
    }
```

- 변경 후
    - ModernCollectionView의 Layout 중에 `list`라는 메서드를 사용하면 테이블뷰 형태로 생성이 가능합니다.
    - Cell들 내부 요소의 크기만큼 Cell의 크기가 정해지기 때문에 Dynamic Type을 사용하여도 문제가 생기지 않습니다.
```swift
private func setUpCompositionalListLayout() -> UICollectionViewLayout {
        let configuration = UICollectionLayoutListConfiguration(appearance: .plain)
        let layout = UICollectionViewCompositionalLayout.list(using: configuration)
        
        return layout
    }
```

<br/>

### :question: 해결하지 못한 부분
### MovieDetailViewController의 Dynamic Type 적용시 label alignment 문제

* movieDetailViewController에서 내부 UI요소들이 큰`vertical Stackview`안에 카테고리별로 `horizontal Stackview`로 담겨있는 형식으로 구성되있습니다. 
* 왼쪽 카테고리 `Title Label`들과 오른쪽 `불러온 Data Label`들이 일정한 간격을 가지고 정렬된상태를 유지하기위해 왼쪽 `Title Label`들은 **일정 너비`greaterThanEqaul, width = 70`을 갖는 방식**으로 정렬을 유지하게끔 설정했습니다.
* 문제는 `Dynamic Type`을 적용시 `width = 70`을 넘어가게되면서 모든 alignment가 무너지고 label들이 오른쪽 사진과같이 붙어버리는 현상이 발생합니다.
* `horizontal Stackview` 간의 `spacing`아니면 `horizontal Stackview`를 사용하지않고 label간 오토레이아웃 잡는 방식 등 여러가지방법을 고민해봤지만 해결책이 떠오르지않아서 해결못한 부분으로 질문드리려고합니다

<img src = "https://i.imgur.com/qccJJjo.jpg" width = 300> <img src = "https://i.imgur.com/p3q0vCW.jpg" width = 300>

### Icon 모드의 Dynamic Type
- Icon 모드에서 Dynamic Type 사용 시
    - Icon 모드에서의 Dynamic Type 표현을 어떻게 하면 좋을지 고민했습니다.
    - Cell 크기를 늘려서 Dynamic Type을 적용시키는 방법이 좋은건지, 아니면 cell의 크기를 늘리지 않고도 Dynamic Type을 적용시킬 수 있는 방법이 있는지 궁금합니다.
<img src = "https://i.imgur.com/AzqAkMS.png" width = 200>

2023-04-11 13:32 UTC, forestjae requested changes

2023-04-11 13:32 UTC, forestjae commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        switch self.isCurrentListLayout {
Bool을 switch문으로 받으니까 조금 어색한 느낌이 드네요!

또한, 지금은 2개의 메서드를 사용하시는데, 한개의 메서드 안에서 분기를 하는 방향이 더 낫지 않을까 생각합니다.
겹치는 로직이 많기 때문입니다.

2023-04-11 13:32 UTC, forestjae commented on BoxOffice/Controller/BoxOfficeViewController.swift
>          let cell = boxOfficeListCollectionView.dequeueReusableCell(withReuseIdentifier: cellId, for: indexPath) as! BoxOfficeListCell
Compositional Layout을 사용하셨는데, Diffable Datasource를 사용하지 않으신 이유가 궁금하네요.

2023-04-11 13:32 UTC, forestjae commented on BoxOffice/Controller/BoxOfficeViewController.swift
>          print(choosenDate)
불필요한 코드 같습니다.

2023-04-11 14:24 UTC, forestjae commented
전체적으로 요구사항을 잘 구현해주셔서 이번에는 코멘트가 많이 없습니다. 

다만 아이콘 View에 진입할 때마다 스크롤이 살짝 아래로 내려간 상태로 시작되는 이슈가 있네요. 이 부분 해결해보시면 좋겠습니다.

> ### ❓ 해결하지 못한 부분
> ### MovieDetailViewController의 Dynamic Type 적용시 label alignment 문제
> * movieDetailViewController에서 내부 UI요소들이 큰`vertical Stackview`안에 카테고리별로 `horizontal Stackview`로 담겨있는 형식으로 구성되있습니다.
> * 왼쪽 카테고리 `Title Label`들과 오른쪽 `불러온 Data Label`들이 일정한 간격을 가지고 정렬된상태를 유지하기위해 왼쪽 `Title Label`들은 **일정 너비`greaterThanEqaul, width = 70`을 갖는 방식**으로 정렬을 유지하게끔 설정했습니다.
> * 문제는 `Dynamic Type`을 적용시 `width = 70`을 넘어가게되면서 모든 alignment가 무너지고 label들이 오른쪽 사진과같이 붙어버리는 현상이 발생합니다.
> * `horizontal Stackview` 간의 `spacing`아니면 `horizontal Stackview`를 사용하지않고 label간 오토레이아웃 잡는 방식 등 여러가지방법을 고민해봤지만 해결책이 떠오르지않아서 해결못한 부분으로 질문드리려고합니다
> 
> <img alt="" width="300" src="https://camo.githubusercontent.com/12cd48ff6ad8a7ea9e067fd80b2d81aa426d2b4fe2d09467143e8568be54a128/68747470733a2f2f692e696d6775722e636f6d2f7163634a4a6a6f2e6a7067"> <img alt="" width="300" src="https://camo.githubusercontent.com/526e55ef5a91e6073700fc7c3338c876a9a08ba325ee78b57fc8fec15d0f053d/68747470733a2f2f692e696d6775722e636f6d2f703371307643572e6a7067">
> 

Title Label끼리의 wdith 제약을 모두 같다로 시도해보시겠어요?

> ### Icon 모드의 Dynamic Type
> * Icon 모드에서 Dynamic Type 사용 시
>   
>   * Icon 모드에서의 Dynamic Type 표현을 어떻게 하면 좋을지 고민했습니다.
>   * Cell 크기를 늘려서 Dynamic Type을 적용시키는 방법이 좋은건지, 아니면 cell의 크기를 늘리지 않고도 Dynamic Type을 적용시킬 수 있는 방법이 있는지 궁금합니다.
> 
> <img alt="" width="200" src="https://camo.githubusercontent.com/e962c35be8373221cfbd81693437c565b355174afd94224f90c8f9270cd70058/68747470733a2f2f692e696d6775722e636f6d2f417a71416b4d532e706e67">

Icon모드에서는 격자의 크기가 요구사항 상 더이상 늘어나지 않는게 맞는것 같구요, 글자가 늘어나면 어쩔수 없이 짤리는게 당연한 것 같습니다. 이런 경우에는 보통 중요한 특정 요소에만 다이나믹 타입을 적용하는 식으로 해결하는 방법이 어떨까 생각이 되네요. 사실 현업에서는 개발자 혼자 정할 수 없는 문제긴 합니다 😢

2023-04-12 01:58 UTC, kimseongj commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        switch self.isCurrentListLayout {
숲재가 코멘트 주신 부분에 대해 메서드를 하나의 메서드로 정의하고, `switch`문 대신 `if문을 활용하여 수정했습니다!
05eb270a6131d421b33198e9f0b9ed9c82d27694

2023-04-12 01:58 UTC, kimseongj commented on BoxOffice/Controller/BoxOfficeViewController.swift
>          print(choosenDate)
수정했습니다!
05eb270a6131d421b33198e9f0b9ed9c82d27694

2023-04-13 12:34 UTC, merged