박스오피스II [STEP 2] vetto, brody
yagom-academy/ios-box-office pull request #54
Opened 2023-04-11 03:19 UTC by seunghyunCheon

@uuu1101
안녕하세요 태태!
박스오피스 II step2 PR입니다.

step2 완성되어 PR보냅니다.

리뷰 잘 부탁드리겠습니다!

## 조언 받고 싶은 점

### 큰 텍스트 크기에 특정 레이블 잘림현상
다이나믹 타입을 적용하기 전에는 문제가 존재하지않았습니다.
하지만 다이나믹 타입 적용 후 텍스트 크기를 최대사이즈로 한다면 어떤 레이블은 잘리고 어떤 레이블은 잘리지 않은 것을 볼 수 있었습니다. 

<img src="https://i.imgur.com/7qyb0d9.png" width="300"/><br/>

위 사진의 화면은 현재 ScrollView -> UIView(ContentView) -> ImageView와 MovieInformationStackView -> MovieInformationStackView내부에 CategoryStackView 여러 개 -> CategoryStackView 내부에 레이블 두 개로 구성되어있습니다. 

CategoryStackView의 오른쪽 레이블에 `numberOfline`을 0으로 주었음에도 불구하고 개봉일 같은 경우 짤리는 것을 볼 수 있었습니다. 

최대 사이즈가 아닌 최대사이즈에서 두단계 아래의 사이즈를 했을때는 관람등급의 오른쪽 레이블이 잘리는 것을 볼 수 있었습니다.

<img src="https://i.imgur.com/FADoTVM.png" width="400"/><br/>

이 상황을 고려해봤을 때 레이블의 width가 현재 화면에 보여지는 것보다 길게 잡힌게 아닐까 생각을 해봤습니다.
하지만 스크롤뷰 내부 contentView의 trailing은 scrollView에 맞춰져있고, MovieInformationStackView의 trailing또한 contentView에 맞춰져있기 때문에 위 상황이 이해되지 않았습니다. 

그리고 CategoryStackView의 오른쪽 레이블의 `CompressionResistancePriority`을 높여서 글자를 잘리지 않게 하려고 했으나 큰 텍스트 사이즈에서는 변화가 없었습니다.

lineBreak의 문제일까 싶어서 lineBreak모드를 `byCharWrapping`로 설정했는데도 잘리는 현상이 발생했습니다.

혹시 스택뷰이기 때문에 레이블의 width크기를 잘 잡지 못하는 걸까요? numberOfLine이 0임에도 불구하고 ...으로 잘리는 현상이 발생하는 이유가 궁금합니다.

### Icon형태로 보여질때 Dynamic type 구현
현재 프로젝트에서는 아이콘으로 보여주는 모드가 있고 리스트로 보여주는 모드가 있습니다.

<img src="https://i.imgur.com/je2ihUM.png" width="300"/><br/>

위에 사진과 같이 리스트일때는 cell들의 높이가 달라져도 잘 나오는 것을 알 수 있습니다.

| 다이나믹 타입 X | 다이나믹 타입 O |
| :--------: | :--------: |
| <img src="https://i.imgur.com/wFzLfLd.png" width="300"/><br/> | <img src="https://i.imgur.com/v4OGtld.png" width="300"/><br/> |

하지만 아이콘 모드에서는 요구사항 이미지에 따라 정사각형 모양의 정해진 틀이 있는 것처럼 보였고 그것을 준수하기 위해서는 아이콘 화면모드일때는 다이나믹 타입을 적용하는 것이 어렵다고 판단되어 적용하지 못하고 남겨두었습니다.

만약 아이콘에서도 다이나믹 타입을 적용한다면 위의 오른쪽 그림과 같이 label의 길이에 따라서 줄바꿈이 되고 그렇게 되면 cell크기가 늘어나게 되어 5,6위가 서로 안 맞는것처럼 나오게 됩니다. 요구사항에 맞게 다이나믹 타입을 구현하게 되면 위에 오른쪽 그림처럼 나오게 되는데 어떻게 하는 것이 좋은지 모르겠습니다.

### 관객수 길이에 따른 label의 크기 조정

<img src="https://i.imgur.com/98t13ta.png" width="300"/><br/>

현재 요구사항 이미지에서는 위와 같이 관객수 label길이에 따라 글씨 크기가 줄어드는 것을 볼 수 있습니다. 따라서 저희도 이미지에 맞게 label의 `adjustsFontSizeToFitWidth`을 `true`로 바꿔주어 label의 폰트가 자동적으로 조정되게 하였습니다. 이렇게 구현하여도 되는 것인지 궁금합니다.

2023-04-12 15:43 UTC, uuu1101 requested changes
STEP2 구현하느라 고생하셨습니다.
주어진 조건을 깔끔하게 잘 구현하셨네요 👍🏻
접근제어자나 final 에 대한 부분도 잘 관리해주셔서 좋았습니다.
extension을 너무 많이 나눠두신것 같다는 생각이 조금 드는 부분이 있습니다.
CollectionView에 대한 부분을 차라리 하나로 두고 UICollectionViewDelegate나 Datasource 부분들만 따로 extension으로 두셔도 될 것 같습니다.
(configureHierarchy 와 createLayout를 하나의 extension에 관리하시는 건 어떠신가요?)
- 큰 텍스트 크기에 특정 레이블 잘림현상
여러가지를 살펴 보았는데, 같은 문구여도 다른 작품에서는 텍스트가 잘리는 현상이 있더라구요.
해당 부분에 대해서 자료를 좀 찾아보려 했는데, 다이나믹타입에 대한 내용은 정말 찾기가 힘드네요.
다이나믹 타입을 custom font를 사용하는 방법도 있겠지만 기본적으로 제공해주는 내부에 정해져 있는 것을 사용하기 때문에 정확히 어떤 부분이 문제여서 해당 부분이 잘리는지 말씀드리기에는 한계점이 있는것 같습니다. UI 제약조건이나 UI에 관련된 문제는 아닌 것 같아요.
- 아이콘 모드 
해당 부분도 5위에 해당하는 부분이 제목이 2줄로 되면서 dynamic하게 제약조건을 뭔가 내부적으로 변경해서 그 cell 만 높이값이 달라져있는걸로 보여지네요.

- label의 text 크기에 대한 질문
네 , 그렇게 구현하셔도 됩니다. 다만 minimumSize를 지정해줄 수 있으니 글자 크기가 너무 작아지는건 방지해주는게 좋을 것 같습니다!

다이나믹 타입에 대해서 자료를 찾다보니 평소보다 늦은 감이 있었네요.
고생하셨습니다 !

2023-04-12 15:43 UTC, uuu1101 commented on BoxOffice/Model/AlertManager.swift
> +        if layout == "아이콘" {
String 값을 바로 넣기보다는 enum 타입등으로 관리해보시는 건 어떨까요?

2023-04-12 15:43 UTC, uuu1101 commented on BoxOffice/View/BoxOfficeGridCell.swift
> +    func configure(boxOfficeItem: BoxOfficeItem) {
~을 configure 하는지 포함되면 좋을것 같아요 !

2023-04-12 15:43 UTC, uuu1101 commented on BoxOffice/View/BoxOfficeGridCell.swift
> +final class BoxOfficeGridCell: UICollectionViewCell {
`final` 👍🏻 좋습니다

2023-04-13 09:16 UTC, seunghyunCheon commented on BoxOffice/View/BoxOfficeGridCell.swift
> +    func configure(boxOfficeItem: BoxOfficeItem) {
`configureInformation`으로 변경했습니다!

2023-04-13 09:19 UTC, gzzjk159 commented on BoxOffice/Model/AlertManager.swift
> +        if layout == "아이콘" {
처음에는 fileprivate로 enum을 선언하여 AlertManager가 알 필요가 없게 만들기 위해 rawValue에 String값을 넣고 rawValue값을 이용하여 다르게 보여주고자 하였습니다. enum타입으로 관리하는 것이 좋다는 리뷰어 말에 동의하여 fileprivate하였던 enum을 새로운 파일로 저장하여 enum을 구현하였고 그 enum을 받아오는 식으로 코드를 수정하였습니다.  6a14366edff90a1e91162a9e0b51875394768fad

2023-04-13 09:37 UTC, merged

2023-04-13 09:45 UTC, uuu1101 commented
잘리는 부분에 대해서는 제약조건에 대한 이슈인것 같아서, 확인해서 피드백드릴게요 !