박스오피스II [STEP 2] 무리, Rowan
yagom-academy/ios-box-office pull request #55
Opened 2023-04-11 06:30 UTC by parkmuri

@junbangg
안녕하세요 알라딘! 박스오피스2 STEP2 PR보냅니다😊
리뷰 기다리고있겠습니다~!

## 고민했던 점
### 1️⃣ CollectionView Mode
CollectionView가 Icon, List 형태에 따라 다르게 그려질 수 있도록 `CollectionViewMode` 열거형 타입과 `CollectionViewModeManager` 구조체 타입을 정의하여 각각의 모드에 맞는 layout을 가질 수 있도록 하였습니다.

CellRegistration도 2가지로 정의하여 DiffableDataSource가 mode에 따라 다른 셀을 dequeue 할 수 있도록 정의하였습니다.

### 2️⃣ CollectionViewCell
List, Icon 두 가지 형태의 Cell을 정의했습니다.
* ListCell
    * 이전 스텝의 DailyBoxOfficeListCell과 동일
* IconCell
    * backgroundConfiguration을 통해 테두리를 그려주었습니다.

### 3️⃣ ActionSheet
이전에 정의해둔 `AlertController`에 static 메서드 `showActionSheet(mode:to:)`를 추가하여 actionSheet를 화면에 띄워줄 수 있도록 하였습니다.

### 4️⃣ Toolbar
NavigationController에 구현되어있는 toolbar를 활용하였습니다.

MovieDetail 화면에서 toolbar가 표시되지 않도록 `viewWillAppear` 메서드를 override하여 `isToolbarHidden` 을 바꿔주었습니다.

## 조언을 얻고싶은 점
### 1️⃣ reloadData()의 호출
`changeCollectionViewMode()`메서드를 통하여 현재 뷰 모드에 따라 새로운 뷰를 호출해주는  setCollectionViewLayout을 설정해주었습니다. 수정 전의 코드는 다음과 같습니다.
#### 수정 전
```swift!
func changeCollectionViewMode() {
    switch collectionViewMode {
    case .icon:
        collectionViewMode = .list
    case .list:
        collectionViewMode = .icon
    }
    
    collectionView.reloadData()
    collectionView.setCollectionViewLayout(collectionViewLayout(), animated: true)
}
```
위의 코드에서 뷰 모드를 바꾸게되면 아래의 사진과 같은 오류가 발생했습니다.
![](https://i.imgur.com/talYUTZ.png)

#### 수정 후
위의 문제를 해결하기 위해 `setCollectionViewLayout()`의 completion을 활용하여 후행클로저에서 `reloadData()`를 다시한번 호출해주는 방법으로 위의 오류를 해결하게되었습니다. 
```swift!
func changeCollectionViewMode() {
    // ...
    collectionView.reloadData()
    collectionView.setCollectionViewLayout(collectionViewLayout(), animated: true) { _ in
        self.collectionView.reloadData()
    }
}
```
이와 같이 수정을 하고 나니 `reloadData()`를 두 번 호출하는 것이 최선의 방법인지 고민되어 **조언을 얻고 싶은 점**에 남깁니다! 알라딘은 어떻게 생각하시나요?

### 2️⃣ Collection View Mode
두 가지 모드를 갖는 collection view를 전환하는 기능이 추가되면서 코드가 많이 복잡해진 것 같습니다.

layout과 cellRegistration을 분기처리 해서 구현하는 방법 외에도 아예 다른 icon collectionView를 만들어서 hidden을 이용해 화면에 띄워주는 방법이 있는 것 같은데 알라딘은 어느 방법이 더 좋다고 생각하시나요? 🤔

2023-04-12 12:14 UTC, junbangg requested changes
수고하셨습니다!

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        Date(timeIntervalSinceNow: 3600 * -24)
오 return 을 빼셨네요.?!

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          }
UICollectionView.CellRegistration 클로져 한번만 쓰도록 수정 할 수는 없으려나요??🤔

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +            }
중복되는 코드들이 조금 보이네요..! 좀 간소화 시킬 수는 없을까요??

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    private lazy var movieInformationStackViews = [
요건 혹시 왜 lazy 인걸까요??

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +            }
오..! 요런 스타일로 UI 구성하는건 처음 보는데 배워 갑니다!

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/Utility/AlertController.swift
> +        }
안에 있는 클로져 상수에 담아서 재사용하는 방법은 어떨까요/???

```
    let 클로져: (UIAlertAction) -> Void = { _ in
        DispatchQueue.main.async {
            viewController.changeCollectionViewMode()
        }
    }

    let icon = UIAlertAction(title: "아이콘", style: .default, handler: 클로져)
    let list = UIAlertAction(title: "리스트", style: .default, handler: 클로져)
```

요런 느낌으루다가

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/View/CategoryStackView.swift
>      }
메서드 네이밍과 내용은 살짝 맞지 않는것 같은데 네이밍에 특별한 이유가 있었을까요?

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeIconCell.swift
> +    let audienceLabel = UILabel()
은닉 시킬 수 있으려나요?!

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeIconCell.swift
> +    private func configureLayoutConstraints() {
`DailyBoxOfficeIconCell` 타입이 좀 큰거 같은데 `private` 메서드들은 `extension` 으로 빼서 정리하는건 어떠신가요?
고런 적당한 정리들이 있으면 나중에 볼때 편하더라고요.!

2023-04-12 12:14 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeListCell.swift
> +    }
큰 문제는 아닌데요..! 
요 메서드를 보다보니까, 데이터를 업데이트 시키는 책임만 하는것이 아니라, 업데이트를 시켜도 되는지 안되는지 체크하는 일까지 하는것 같네요..!

요건 딱히 로직이 커다랗지는 않아서 큰 이슈로 안보일 수는 있겠지만, 관심사 분리를 해주는건 항상 좋다고 생각합니다!~!

2023-04-12 12:15 UTC, junbangg commented
```
func changeCollectionViewMode() {
    // ...
    collectionView.reloadData()
    collectionView.setCollectionViewLayout(collectionViewLayout(), animated: true) { _ in
        self.collectionView.reloadData()
    }
}
```

저도 이렇게 reloadData를 두번 호출하는건 좋지 않은것 같아요..! 첫번째 reloadData 를 없앴을때는 어떤가요?

2023-04-12 12:18 UTC, junbangg commented
> Collection View Mode 질문

히든 처리도 나쁘지 않다고 봐요..! 
아예 부모 뷰컨 하나, 자식 뷰컨 두개를 만들어놓고, 관리하는 방법도 있을것 같습니다🤔

두분은 이번에 어떤어떤 방법들로 고민하신뒤에 지금처럼 구현하시게된걸까요?

2023-04-12 12:36 UTC, junbangg commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +            }
다만 요렇게 했을때 생각나는 아주 조그만한 우려 포인트는 유연성이긴 합니다.!🤔

movieInformationStackViews 에 있는 레이블들을 하나같이 묶어서 요렇게 하면 변경에 그렇게 용이하지는 않을것 같아요

큰 문제는 없어보이긴해서 패쓰 하고싶으시다면 패쓰..!

2023-04-13 05:32 UTC, Kyeongjun2 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +        Date(timeIntervalSinceNow: 3600 * -24)
return을 명시하지 않아도 연산프로퍼티는 프로퍼티 타입과 내부 값이 같으면 해당 값을 반환하기 때문에 생략해보았습니다~!

2023-04-13 07:53 UTC, parkmuri commented
<img src="https://user-images.githubusercontent.com/115514179/231691253-485dd8d7-af80-428a-9234-94b4f24bf3ad.gif" width="250">

위의 화면과 같이 list -> icon 시에는 list의 레이아웃이 iconCell이 만들어지는과정에서 보이게되고 icon -> list에서는 iconCell에 적용시킨 테두리가 listCell이 그려질때 보입니다... 
한마디로 애니메이션이 자연스럽지 않게 보여져서 `reloadData()`를 두번 호출하게되었습니다.

2023-04-13 08:04 UTC, parkmuri commented
> 히든 처리도 나쁘지 않다고 봐요..!
아예 부모 뷰컨 하나, 자식 뷰컨 두개를 만들어놓고, 관리하는 방법도 있을것 같습니다🤔
두분은 이번에 어떤어떤 방법들로 고민하신뒤에 지금처럼 구현하시게된걸까요?

처음에는 CollectionView를 하나로 두고 Cell, Layout, DataSource를 바꿔주어 진행을 하려고 했습니다. 그러다 [공식문서-DiffableDataSource](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource)에서 DiffableDataSource는 변경하지 말라고해서 Cell, Layout으로만 구현하게되었습니다.
위 공식문서의 `important`에 나와있는 내용 중 DataSource를 변경하기보다는 CollectionView를 새로 만들어서 사용하라는 내용을 구현이 거의 끝난시점에 알게되어 적용시키지는 못했습니다🥲
그래서 모드 변경 시 애니메이션이 부자연스러운점을 개선하기 위해서는 CollectionView를 새로 만들어야 하는가에 대해 고민하게되었습니다..!

2023-04-13 08:07 UTC, parkmuri commented on BoxOffice/View/DailyBoxOfficeListCell.swift
> +    }
`movieDataUpdateIfNeeded()`메서드를 만들어 해당 메서드 내에서 데이터가 바뀌었다면 `updateData()`메서드를 실행시키도록 구현하였습니다.

```swift
func movieDataUpdateIfNeeded(newData: DailyBoxOfficeMovie) {
        guard movieData != newData else { return }
        
        updateData(with: newData)
    }
    
    private func updateData(with newMovieData: DailyBoxOfficeMovie) {
        movieData = newMovieData
    }
```

9bec4e9ac7e408e5742c3f7c493f0e85b97b4578

2023-04-13 08:07 UTC, Kyeongjun2 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          }
중복된 코드 사용이라고 생각되어 제네릭 메서드로 분리해주었습니다...!
서로 다른 셀 타입을 넘겨주어야 하기 때문에 추가적인 protocol도 생겼네요. 😂
```swift
protocol MovieDataUpdatable {
    func movieDataUpdateIfNeeded(newData: DailyBoxOfficeMovie)
}
```

```swift
private func createCellRegistration<Cell: MovieDataUpdatable>(cell: Cell.Type) -> UICollectionView.CellRegistration<Cell, DailyBoxOfficeMovie> {
    let cellRegistration = UICollectionView.CellRegistration<Cell, DailyBoxOfficeMovie> { cell, indexPath, item in
        
        cell.movieDataUpdateIfNeeded(newData: item)
    }
    
    return cellRegistration
}
```

이 방법이 괜찮은 방법일까요..? 🤔

2023-04-13 08:10 UTC, parkmuri commented on BoxOffice/View/DailyBoxOfficeIconCell.swift
> +    private func configureLayoutConstraints() {
`DailyBoxOfficeIconCell`, `DailyBoxOfficeListCell`모두 `extenstion`을 사용하여 정리해주었습니다!
알라딘 말대로 한결 더 보기가 수월해진것같습니다🥹,,,!!!

2023-04-13 08:12 UTC, parkmuri commented on BoxOffice/View/DailyBoxOfficeIconCell.swift
> +    let audienceLabel = UILabel()
넵 외부에서 사용하고있지않아 전부 `private`키워드 사용하여 은닉화해주었습니다!

b1f4c04e9de5c3b2f25ca2ba4a4f758915058d5e

2023-04-13 08:14 UTC, parkmuri commented on BoxOffice/View/CategoryStackView.swift
>      }
혹시 추후에 추가될 가능성을 남겨두고 복수형으로 메서드를 만들었습니다🥲..!
기능에 맞게 메서드 리네이밍 해주었습니다!

```swift
    private func configureSpacing() {
        spacing = 15
    }
```

b035eef6bf9fe6543fc9b2a56765b8c7e47c0938

2023-04-13 08:17 UTC, Kyeongjun2 commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
> +            }
```swift
private func cellForDataSource<Cell: MovieDataUpdatable>(
    _ collectionView: UICollectionView,
    cellRegistration: UICollectionView.CellRegistration<Cell, DailyBoxOfficeMovie>,
    indexPath: IndexPath,
    item: DailyBoxOfficeMovie
) -> UICollectionViewCell {
    let cell = collectionView.dequeueConfiguredReusableCell(using: cellRegistration,
                                                            for: indexPath,
                                                            item: item)
    cell.snapshotView(afterScreenUpdates: true)
    
    return cell
}
```

간소화(?)가 된 건지는 잘 모르겠지만 cell.snapshotView(afterScreenUpdates: true) 코드를 dequeue와 묶어서 메서드로 빼줬습니다!

switch 문은 mode에 따라 dequeue하는 cell 타입이 달라지도록 하려면 꼭 필요한 것 같아요... 💦

`CollectionViewMode` enum 내부에 연산프로퍼티로 mode마다 다른 cell을 dequeue할 수 있도록 하려고 시도해봤는데 아무래도 CellRegistration 타입에 제네릭이 있다 보니 또 같은 코드를 두 번 반복하게 될 것 같아 적용하지 않았습니다!

2023-04-13 08:19 UTC, parkmuri commented on BoxOffice/Utility/AlertController.swift
> +        }
알라딘의 조언대로 중복되는 코드를 줄이기 위해 `CollectionViewMode`에  `oppositeString` 연산프로퍼티를 만들어주었습니다. 
모드에 따라 다른 값을 return하게 해주어 코드를 더 간략하게 사용할 수 있었습니다!
```swift
enum CollectionViewMode {
    case list
    case icon

    var oppositeString: String {
        switch self {
        case .icon:
            return "리스트"
        case .list:
            return "아이콘"
        }
    }
}
```
```swift
enum AlertController {
// ...
        let alertAction = UIAlertAction(title: mode.oppositeString, style: .default) { action in
            DispatchQueue.main.async {
                viewController.changeCollectionViewMode()
            }
        }
        
        let cancel = UIAlertAction(title: "취소", style: .cancel)
 
        actionSheet.addAction(alertAction)
        actionSheet.addAction(cancel)
        
        viewController.present(actionSheet, animated: true)
// ...
}
```

c86d7efa1f398705a0220e355690976befd84f6f

2023-04-13 08:23 UTC, Kyeongjun2 commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +    private lazy var movieInformationStackViews = [
1. MovieDetailsViewController가 초기화가 완전히 끝나기 전에 프로퍼티를 사용하게 되면 오류가 발생하기 때문에
2. 이니셜라이저에서 StackView들을 append하는 메서드를 호출해서 해결할 수도 있지만 메서드가 추가되는 것 보다 lazy var로 해결하는게 간결해질 것 같아서

이런 이유로 lazy var로 만들어 주었습니다..!

2023-04-13 08:29 UTC, parkmuri commented on BoxOffice/Controller/MovieDetailsViewController.swift
> +            }
해당 코드를 사용한 이유는 Dynamic Type을 적용시켜주엇을때 아래의 오른쪽 스크린샷과 같이 `categoryLabel`들의(감독, 제작년도, 개봉일 등) 너비를 맞춰주기 위함이었습니다. `categoryLabel`중 가장 긴 네글자의 `productionYearView`의 `categoryLabel`을 기준으로 다른 스택뷰의`categoryLabel`들의 너비를 맞추어 아래의 왼쪽 스크린샷처럼 나타낼 수있었습니다.

<img src="https://user-images.githubusercontent.com/115514179/231699223-00b119e4-8adc-4792-9f42-13c52ff74bc9.png" width="250"> <img src="https://user-images.githubusercontent.com/115514179/231699314-e220753a-8300-426b-8fc2-39bed95cf508.png" width="250">

`categoryLabel`들이 일관성을 띄어야한다고 생각해서 array에 담아 일괄적으로 처리를 해주었습니다...!

2023-04-13 12:41 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          }
오호 저는 타입 체크해서 updateMovieData 하는 방법 정도로 생각하긴 했는데 이런 방법이..?

2023-04-13 12:42 UTC, junbangg commented on BoxOffice/Controller/DailyBoxOfficeViewController.swift
>          }
나쁘지 않은것 같은데요?🤔

2023-04-13 12:45 UTC, junbangg commented on BoxOffice/View/DailyBoxOfficeListCell.swift
> +    }
IfNeeded 붙인거 아주 좋아요!!! 회사 코드에서도 요런 느낌의 네이밍 많이 본것 같아요
다만 update 를 앞에 붙이는게 조금 더 자연스러울것 같네요 !
`updateMovieDataIfNeeded()`

2023-04-13 12:46 UTC, junbangg commented
> 위의 화면과 같이 list -> icon 시에는 list의 레이아웃이 iconCell이 만들어지는과정에서 보이게되고 icon -> list에서는 iconCell에 적용시킨 테두리가 listCell이 그려질때 보입니다... 한마디로 애니메이션이 자연스럽지 않게 보여져서 `reloadData()`를 두번 호출하게되었습니다.

asyncAfter 로 딜레이를 좀 줘보는 방법도 혹시 시도 해보셨을까요??🤔

2023-04-13 12:53 UTC, merged