박스오피스 II [STEP 2] 혜모리, 크리스티
yagom-academy/ios-box-office pull request #56
Opened 2023-04-11 13:25 UTC by christy-hs-lee

안녕하세요 하비(@havilog)! 박살나서 돌아온 `모리스티`입니다.
험난한 STEP2를 진행하며 많이 혼쭐났네요...ㅎ

---
## 고민했던 점 & 해결하지 못한 점
## 1️⃣ View mode
이번 step의 경우 `List View`와 `Icon View`, 총 2가지 모드의 화면을 구현해야 했습니다.
총 2가지 종류의 모드를 처리하기 위해 각 화면을  switch문을 사용하여 분기처리 하는 방식으로 구현했습니다.
```swift
switch currentLayoutMode {
        case .list:
            guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BoxOfficeListCell.identifier, for: indexPath) as? BoxOfficeListCell,
                  let boxOfficeItem = boxOffice?.result.dailyBoxOfficeList[safe: indexPath.item] else { return UICollectionViewCell() }
            
            cell.configure(with: boxOfficeItem)
            
            return cell
        case .icon:
            guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BoxOfficeIconCell.identifier, for: indexPath) as? BoxOfficeIconCell,
                  let boxOfficeItem = boxOffice?.result.dailyBoxOfficeList[safe: indexPath.item] else { return UICollectionViewCell() }
            
            cell.configure(with: boxOfficeItem)
            
            return cell
        }
```

저희는 분기처리 방식으로 구현했는데, 이 외에 하비가 사용하시는 방법이 있는지 궁금합니다!

## 2️⃣ Dynamic Height
하루종일 시도하고 고민해 봤는데 답이 나오지 않았던 문제가 있습니다.
셀의 높이를 동적으로 늘이는 부분입니다.

시도해 본 내용으로는 cellForItemAt 메서드에서 cell을 반환할 때, indexPath와 셀의 높이 사이즈를 전역 변수에 담아놓고 UICollectionViewDelegateFlowLayout의 sizeForItemAt 메서드에서 height 값에 사용해 보려했는데 자꾸 CGSize가 nil 값이 나왔고,

`estimatedItemSize`라는 것을 조사하고 적용해보려 했는데 아무리 이곳저곳에 적용해보려해도 원하는대로 나오지 않아 도움을 요청드리게 되었습니다...

혹시 저희 코드에서 어떤 것을 더 알아보면 적용할 수 있을지 조언을 구하고 싶습니다.

2023-04-11 14:29 UTC, havilog requested changes
1. 레이아웃을 바꾸기 위해 어떤 방법들이 있었고,
2. 그 방법들 중에 이 방법을 선택한 이유가 궁금해요.

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +}
이 enum도 .. 앱에서 전역적으로 접근할 수 있을거 같아요.

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
leading, trailing과 left, right의 차이 알고 계실까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/57659933/231189290-717960c7-1f77-4a67-82f8-ccdc897f7533.png">
레이아웃 에러나는거 알고 계실까요?
왜 나는건지 분석하고 수정해주세요 ~

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                self?.collectionView.register(BoxOfficeIconCell.self, forCellWithReuseIdentifier: BoxOfficeIconCell.identifier)
레지스터는 매번 해줘야하는 아이일까요?
레지스터의 역할은 뭘까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func switchCurrentLayoutMode(_ mode: LayoutMode) {
파라미터로 받아온 모드를 가지고, 그에 맞는 레이아웃을 그려주고, currentMode에 파라미터로 받아온 레이아웃을 추가할 수는 없을까요?
모드가 하나 더 생기면 어떻게 currentMode를 넣어주실 계획이실까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let modeTitle = currentState == .list ? "아이콘" : "리스트"
LayoutMode의 computedProperty로 만들 수는 없을까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let currentState = informCurrentLayoutMode()
이거 지역변수로 할당해주신 이유는 뭘까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                self?.collectionView.reloadData()
304, 305번과 같은 역할을 하는거 같은데 밖으로 빼도 괜찮지 않을까요?

2023-04-11 14:29 UTC, havilog commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
prepareForReuse에서 아무 것도 안해주고 있네요.
해당 함수의 역할과 여기에서 어떤 일을 수행해야하는지 설명해주세요

2023-04-11 14:29 UTC, havilog commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
복붙 객체가 있네요.
하나로 쓰기 위해 어떤 고민을 해보셨을까요?

2023-04-13 08:00 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +}
`BoxOfficeViewController` 타입 내부로 이동하였습니다

2023-04-13 08:05 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
모드 전환 시 레이아웃 제약이 중첩되어 발생하는 문제였습니다.

현재는 변경이 필요한 레이아웃 제약을 전역 변수로 두고, 변경될 Anchor의 제약 초기화 후 새로 제약을 설정하도록 변경하였습니다!

``` swift
private func switchLayout() {
    collectionViewLeadingConstraint?.isActive = false
    collectionViewTrailingConstraint?.isActive = false
    
    switch currentLayoutMode {
    case .list:
        collectionViewLeadingConstraint = collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor)
        collectionViewTrailingConstraint = collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
    case .icon:
        collectionViewLeadingConstraint = collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 10)
        collectionViewTrailingConstraint = collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -10)
    }
    
    collectionViewLeadingConstraint?.isActive = true
    collectionViewTrailingConstraint?.isActive = true
}
```

2023-04-13 08:49 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
leading, trailing과 left, right 모두 뷰의 위치를 지정할 때 사용됩니다.
`leading`과 `trailing`의 경우 국가별 지원 언어의 방식에 따라 자동으로 설정되어 작동됩니다.
반면 `left`와 `right`의 경우 단순하게 뷰의 좌우 위치만 지정하여 설정합니다.

저희 코드의 경우 `leading`,`trailing`,`left`,`right`를 섞어서 사용하였는데, 통일시켜 수정했습니다.

2023-04-13 08:50 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func switchCurrentLayoutMode(_ mode: LayoutMode) {
`switchLayout()`에서 현재 모드에 따라 레이아웃을 그려주도록 수정하였습니다.
모드가 하나 더 생기면 해당 메서드에서 추가적으로 레이아웃을 추가하면 될 것으로 생각합니다.

2023-04-13 08:52 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                self?.collectionView.register(BoxOfficeIconCell.self, forCellWithReuseIdentifier: BoxOfficeIconCell.identifier)
[공식문서](https://developer.apple.com/documentation/uikit/uitableview/1614888-register)를 읽고 사용했는데, 사용법에 대한 부분을 정확히 숙지하지 못 했었습니다😭
해당 부분 초기에 한번만 등록하여 사용하도록 수정했습니다!

2023-04-13 08:53 UTC, hyemory commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let currentState = informCurrentLayoutMode()
그 때 당시 클로저가 있어 옵셔널 바인딩을 피하기 위해 만들었던 것으로 기억하는데
사실 잘 기억이 나지 않습니다 🥲 아래와 같이 수정하였습니다.

``` swift
@objc private func changeLayoutMode() {
        let alert = UIAlertController(title: "화면모드변경", message: nil, preferredStyle: .actionSheet)
        let modeTitle = currentLayoutMode.title
```

2023-04-13 09:02 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let modeTitle = currentState == .list ? "아이콘" : "리스트"
해당 부분 수정했습니다!

2023-04-13 09:03 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                self?.collectionView.reloadData()
초기에는 layoutMode에 따라 별도로 지정해줘야 한다고 생각했는데,
updateCollectionViewLayout 메서드에서 분기처리를 하고 있어 해당 부분 삭제했습니다!

2023-04-13 09:05 UTC, christy-hs-lee commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
해당 부분 복붙되어 사용되고 있는지 미처 발견하지 못 했습니다😭
해당 부분 수정했습니다!

2023-04-13 09:19 UTC, hyemory commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
prepareForReuse는 셀 재사용하는데 필요한 초기설정을 해주는 메서드입니다.
셀을 dequeue하면 해당 메서드가 호출됩니다. 이 곳에 data source 객체가 하는 역할인 `새 데이터를 할당`하는 작업은 하지 말라고 [공식 문서](https://developer.apple.com/documentation/uikit/uicollectionreusableview/1620141-prepareforreuse)에 기재돼있습니다.
현재 저희 코드에서는 prepareForReuse에서 처리해 줄만한 요소가 없다고 판단해서 비워두었습니다.
내부에 구현할만한 요소가 없으니 해당 메서드는 지우는게 나을까요?

2023-04-14 07:48 UTC, havilog commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
레이아웃 제약을 조정하지 않고, 셀에 패딩을 주는 방식이나, 콜렉션뷰의 패딩을 주는게 더 효과적일수도 있겠다는 생각이 드네요!

2023-04-14 07:50 UTC, havilog commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
`처리해 줄만한 요소가 없다고 판단`된 근거에 대해 조금 더 설명해주실 수 있으실까요?
셀이 재사용 되는 조건과 재사용될 때 어떤 행동을 해야하는지도 설명해주세요

2023-04-14 13:30 UTC, christy-hs-lee commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +                collectionView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: 10),
아래와 같이 데이터 소스 메서드를 추가하여 기본값을 적용하는 방식으로 수정했습니다!
```swift
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
    return UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10)
}
```

2023-04-14 13:30 UTC, christy-hs-lee commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
1. 비슷한 tableView의 [prepareForReuse()](https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse)를 보면 셀의 컨텐츠와 관련있는 것들은 잠재적인 퍼포먼스 이슈를 피하기 위해 prepareForReuse()가 아닌 데이터 소스의 `tableView(_:cellForRowAt:)`에서 초기화하라고 기재되어있었습니다.
collection view의 `prepareForReuse()` 메서드에도 위 코멘트에서 말씀드렸듯 비슷한 문구가 있어 뷰와 관련된 옵션 (이미지, 색상, 선택 여부 등등)만 초기화를 시켜주어야 한다고 판단했습니다.
제가 `prepareForReuse()`에서 초기화할 대상에 대해 잘못 이해하고 있다면 `prepareForReuse()` 메서드에서 셀에 불러온 데이터를 지워주는 것이 맞을까요?

2. 셀이 재사용되는 조건은 셀이 필요할때마다 collection view에 요청하여 새로운 셀을 생성하지 않고, Identifier를 가진 셀을 dequeueReusableCell에 등록하고 화면에서 사라졌을 때 재사용 큐에 담아두었다가 다시 셀이 화면에 보일 때 대기하고있는 셀을 꺼내서 보여주는 것으로 이해했습니다.

3. 셀이 재사용될 때 확인해야 할 부분은 재사용한 셀의 데이터가 변경된다면 이전의 데이터를 지우고 다시 업데이트하는 등의 재설정 작업이 필요합니다.
아직 `prepareForReuse()`과 `cellForItemAt`에서 각각 어떤 작업을 해줘야하는지 구분하는 것에 이해가 부족하여 그 부분 더 공부해 보겠습니다.

2023-04-16 14:57 UTC, havilog commented on BoxOffice/View/BoxOfficeIconCell.swift
> +    }
만약 이전에 title, image, description 을 설정해줬는데,
그 셀이 재사용될 때 title, image, description을 기본값으로 바꿔주지 않고,
title만 configure해준다면, 이전의 image, description값이 남아있을 수 있어요.
따라서 prepareForReuse()시점에 설정해주는 모든 값들을 기본값으로 다시 돌려주는 작업이 필요해요

2023-04-18 13:44 UTC, merged