박스오피스II [STEP 3] sehong
yagom-academy/ios-box-office pull request #57
Opened 2023-04-11 15:06 UTC by sehoong0429

@AppleCEO
안녕하세요 도미닉!
Step3 PR올립니다ㅎㅎ 
역시 이미지를 다루는건 쉬운일이 아닌 것 같습니다ㅎㅎ

### 1️⃣ 캐시 정책

1. 캐싱할 데이터의 범위: `이미지`
크기가 큰 이미지를 캐싱 대상으로 설정해주었습니다. 
이미지를 로드하는 시간을 줄여서 사용자 경험을 개선할 수 있습니다.
아래와 같이 `ImageManager`를 만들어서 사용해보았습니다. 
```swift
final class ImageManager {
    
    static let shared = ImageManager()
    ...
}
```

2. 캐시 용량 제한: `메모리, 디스크 각 500MB` 
```swift
static let cache = URLCache(
        memoryCapacity: 500 * 1024 * 1024,
        diskCapacity: 500 * 1024 * 1024,
        directory: cacheDirectory
    )
```
3. 잔존 기한: `.returnCacheDataElseLoad` 
    URLRequest.CachePolicy는 로컬 캐시 데이터가 있으면 사용하고, 없으면 로드할 수 있는 방식을 선택하여 적용해주었습니다. 
```swift
func fetchImage(imageURL: URL, cachePolicy: URLRequest.CachePolicy = .returnCacheDataElseLoad, completionHandler: @escaping (Data) -> Void) {
        let urlRequest = URLRequest(url: imageURL)
        
        loadImageFromCache(request: urlRequest) { [weak self] result in
            guard let self else { return }
            switch result {
            case .success(let imageData):
                completionHandler(imageData)
            case .failure:
                self.downloadImage(request: urlRequest) { imageData in
                    completionHandler(imageData)
                }
            }
        }
    }
```
    

### 2️⃣ NScache vs URLCache 비교 
네트워크 통신을 통해 받아온 데이터를 로컬에 캐시하려면 CoreData, URLCache, NSCache 등의 방법을 사용할 수 있습니다.

먼저 `CoreData`는 앱에서 모델 계층 개체를 관리하는 데 사용하는 프레임워크입니다. 영구 저장소를 사용하여 앱의 데이터를 관리하고, 객체 관계 및 데이터 모델링 기능을 제공하는데 좀 더 복잡한 데이터를 저장하기에 적합하다고 느껴져서 선택하지 않았습니다. 

저는 `URLCache`를 사용하는 방식을 선택했는데, `NSCache`와 비슷한 부분이 있어서 찾아보고 진행하였습니다.

### 🌀NSCache

NSCache는 in-memory 캐시이기 때문에, 시스템의 메모리를 사용하고 이미지의 크기 또는 데이터의 크기에 비례하는 크기를 할당할 것입니다. 

다른 애플리케이션에 메모리가 필요하고 시스템이 이 애플리케이션에 캐시된 개체를 일부 제거하여 메모리 설치 공간을 최소화할 수 있도록 합니다.

하지만 NSCache는 제거 되는 절차가 순서대로 진행 되는 것을 보장하지 않습니다. NSCache의 장점은 생성 비용이 많이 드는 데이터가 있는 개체에 대한 성능 및 자동 삭제 기능입니다.

### 🌀URLCache

네트워크 데이터 관리를 위해서는 데이터를 캐싱하기 위해 NSCache 대신 URLCache를 사용하는게 좋습니다. URLCache는 메모리 내 및 디스크 상의 캐시이며 데이터에 대해 메모리chunk를 할당하지 않기 때문입니다.

더 유연한 in-memory 및 disk 크기를 정의할 수 있습니다. 또한 URLCache는 시스템이 디스크 공간이 부족할 때까지 캐시된 데이터를 유지합니다.

2023-04-12 01:32 UTC, AppleCEO requested changes
안녕하세요. @sehoong0429 
이번 스텝도 고생하셨습니다!
캐시 관련해서는 면접 질문을 저도 받아봤습니다 ㅎㅎ
차이점을 잘 정리해주셨네요~
그리고 참고한 문서의 출처를 밝힌 것도 좋습니다.
몇가지 개선하면 좋겠는 점들 작성해봤습니다.
리뷰 확인해주시고 이해 안 가면 편하게 말씀해주세요.

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice.xcodeproj/project.pbxproj
> +		63DF20F22970E1A0005DF7D1 /* MainViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = MainViewController.swift; sourceTree = "<group>"; };
디테일한 이름으로 변경해준 것 좋습니다! :)

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice.xcodeproj/project.pbxproj
> +		36B59E1F29CAF8C200A4FC11 /* Models */ = {
폴더는 어차피 복수의 파일이 존재하기 때문에 이름에 s를 굳이 붙이지 않아도 되는 것 같아요 ㅎㅎ
스타일의 차이니 이 내용은 알고만 계셔도 좋겠습니다!

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> +        fetchImageforMovie(name: movieName)
어차피 영화라는 이름이 메소드명에 있으니 인자에서 줄여준 것 좋네요! 
영화의 제목이라는 이름으로는 movieTitle 이 더 나을 수도 있겠습니다 ㅎㅎ

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
> -                    DEBUG_LOG(movieInfo)
디버깅 코드를 빼준 것 좋네요~ 👍

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
>                          }
UI를 바꿔주는 부분만 메인 스레드에서 실행해주면 좋죠!
 self.imageView.loadImage 는 이전 코드에서는 메인 스레드에서 실행했었는데 지금은 아니군요.
메소드명으로만 보면 UI 수정하는 코드로 보이는데 빼준 이유가 있을까요? 🔢

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/MainViewController.swift
> +        dataSource.applySnapshotUsingReloadData(dataSource.snapshot())
이게 말씀해주신 다른 메소드이군요! 다시 뜨는 식으로 안 보여서 유저한테 사용성이 좋아졌습니다 ㅎㅎ
스냅샷의 기능인가보군요 ㅎㅎ 
내부 메소드들을 잘 알고 있으면 더 효율적이고 사용성도 좋은 기능을 사용할 수 있네요~

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/Network/Error.swift
> +//  Error.swift
저는 이런 짧은 이름은 선호하지 않습니다 ㅎㅎ
자칫 잘못하면 Swift 의 Error 타입과 혼돈될 수 있어서요.
붙일 단어가 없을 때는 프로젝트 이름을 붙인 이름도 괜찮아요.
예: BoxOfficeError

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/Network/Error.swift
> +enum ImageCacheError: LocalizedError, CustomStringConvertible {
파일명을 여기있는 ImageCacheError 로 할 수도 있겠네요.
보통 열거형, 클래스, 구조체 이름과 같은 파일이름으로 정해놓습니다. 
찾기 좋고 암묵적인 규칙인 것 같아요 ㅎㅎ

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/Network/ImageManager.swift
> +        diskCapacity: 500 * 1024 * 1024,
1024, 500 이라는 숫자가 나오는군요.
500 * 1024 * 1024 곱한 값을 바로 넣는 것보다 이렇게 나눠주셔서 조금 더 이해하기 쉬운데요.
이 숫자의 의미를 아예 상수에 넣어주면 조금 더 보기 좋겠습니다.

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/Extensions/UIImageview+load.swift
>          }
오 원하는 사이즈를 파라미터로 보내서 받을 수 있는 함수군요! 💯

2023-04-12 01:32 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
>                          }
함수 내용을 보니 어차피 안에서 메인 쓰레드로 돌리도록 되어있군요!
이런 경우는 이 함수도 여기 메인 스레드에서 동작하도록 포함해주는게 좋을 수도 있겠네요.
여기서는 main 스레드에서 빠져있어서 함수 안을 찾아보게 되야지 메인 스레드에서 실행되는 것을 알 수 있군요~

2023-04-12 09:16 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
> +        fetchImageforMovie(name: movieName)
[888a2a7](https://github.com/yagom-academy/ios-box-office/pull/57/commits/888a2a72edfdfefa31309a936c3b26d666d23000)
해당 부분 movieTitle로 수정해주었습니다. 사전을 찾아보면 movieTitle을 쓰는 것 같네요 ㅎㅎ

2023-04-12 09:30 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
>                          }
말씀하신 부분은 imageView extension을 삭제하고 DetailMovieInfoViewController로 loadImage함수를 가져와서 메인스레드에서 함께 실행할 수 있도록 아래와 같이 수정해보는 방법이 오히려 가독성이 조금 더 좋아지는 것 같은데 어떻게 생각하시나요? 제가 이해한 부분이 맞는지 확인 부탁드립니다! 

```swift
    private func fetchImageforMovie(name: String) {
        let query = ImageAPI.imageQuery(movieTitle)
        let imageAPI = ImageAPI.imageSearchQuery(query: query)
        
        provider.performImageRequest(api: imageAPI) { [weak self] requestResult in
            guard let self else { return }
            switch requestResult {
            case .success(let data):
                do {
                    let imageSearchResult: ImageSearchResult = try JSONConverter.shared.decodeData(data, ImageSearchResult.self)
                    if let imageInfo = imageSearchResult.documents.first,
                       let url = URL(string: imageInfo.imageUrl) {
                        DispatchQueue.main.async {
                            self.loadImage(url: url, originalWidth: imageInfo.width)
                            self.stopIndicator()
                        }
                    }
                } catch let error as NetworkError {
                    DEBUG_LOG(error.description)
                } catch {
                    DEBUG_LOG("Unexpected error: \(error)")
                }
            case .failure(let error):
                DEBUG_LOG(error)
            }
        }
    }
    
    private func loadImage(url: URL, originalWidth: Int = 0) {
        ImageManager.shared.fetchImage(imageURL: url) { [weak self] data in
            guard let self else { return }
            let viewWidth = self.imageView.frame.width
            let scale = CGFloat(originalWidth) / CGFloat(viewWidth)
            
            let image = UIImage(data: data, scale: scale)
            DispatchQueue.main.async {
                self.imageView.image = image
            }
        }
    }
```

2023-04-12 09:32 UTC, sehoong0429 commented on BoxOffice/MainViewController.swift
> +        dataSource.applySnapshotUsingReloadData(dataSource.snapshot())
흰색 화면이 뜨거나 말거나 기능 구현만 잘되면 된다고 생각하고 ㅠ 신경안쓰고 있었는데 알려주셔서 감사합니다 ㅎㅎ 내부 메소드들을 잘 활용할 수 있도록 좀 더 깊게 알고 공부해야할것같네요ㅠㅠ!!

2023-04-12 09:35 UTC, sehoong0429 commented on BoxOffice/Network/Error.swift
> +//  Error.swift
[e834ea3](https://github.com/yagom-academy/ios-box-office/pull/57/commits/e834ea34371f8fad4a868defba2fcdb96f4b7d92)
에러타입잉 하나 더 추가되면서 파일명을 정하려다가 저렇게 대충 지어놓고 말았네요ㅠㅠ
제 실수입니다! 조언해주신대로 BoxOfficeError가 좋을 것 같아서 해당 부분 수정해주었습니다!

2023-04-12 09:39 UTC, sehoong0429 commented on BoxOffice/Network/ImageManager.swift
> +        diskCapacity: 500 * 1024 * 1024,
[4c9f061](https://github.com/yagom-academy/ios-box-office/pull/57/commits/4c9f061e8157334fea4ba317bbaa33c783e19244)
나중에 용량을 늘리거나 줄일때 훨씬 관리하기 좋아질 것 같습니다! 해당부분 수정해주었습니다.

2023-04-12 13:39 UTC, AppleCEO commented on BoxOffice/DetailMovieInfoViewController.swift
>                          }
아... 이 것도 좋습니다! 저는 extension 을 선호하지는 않아서 지금 것이 더 좋다고 생각이 듭니다~

2023-04-12 14:11 UTC, AppleCEO commented
코드가 말끔하네요~ 추가 미션 혹시 보이시나요? 한번 진행해보셔도 좋겠는데요! 안 보이시면 말씀해주시면 제가 공유드릴게요.

2023-04-13 03:45 UTC, sehoong0429 commented on BoxOffice/DetailMovieInfoViewController.swift
>                          }
91dd9f09d4d41ec6099560b01d6aebcea4b48b72
해당 부분 수정해주었습니다..!!!

2023-04-14 04:07 UTC, AppleCEO commented
수정해주셔서 좋습니다~ 머지 드릴까요?

2023-04-14 04:19 UTC, sehoong0429 commented
> 수정해주셔서 좋습니다~ 머지 드릴까요?

네 좋습니다!!!👍🏻👍🏻👍🏻

2023-04-14 04:20 UTC, merged

2023-04-14 04:21 UTC, AppleCEO commented
머지했습니다! 방학 잘 보내세요~ 한달간 저한테도 특별하고 배울 수 있는 기간이었습니다. 멀리 가야하니 다 잊고 푹 쉬시고 남은 코스도 화이팅입니다.