박스오피스 [STEP 1] vetto, brody
yagom-academy/ios-box-office pull request #6
Opened 2023-03-20 09:39 UTC by gzzjk159

@uuu1101
안녕하세요 태태! 
박스 오피스 step 1 PR 보냅니다. 2주 동안 잘 부탁드립니다.

## 고민했던 점

### 커스텀 JsonDecoder객체 생성
현재는 `parse`하는 부분이 한군데만 존재하지만 프로젝트 추후에 여러군데에서 사용할 가능성과, 객체를 테스트할 것을 고려해 커스텀 클래스로 정의했습니다.

```swift
final class BoxOfficeJsonDecoder: JSONDecoder {
    func loadJsonData<T: Decodable>(name: String, type: T.Type) throws -> T {
        guard let dataAsset = NSDataAsset(name: name) else {
            throw DataAssetError.invalidFileName
        }
        
        return try self.decode(type, from: dataAsset.data)
    }
}
```

### parse한 데이터 unit테스트
정확한 비교를 하기 위해서는 데이터 타입의 인스턴스를 만들어 예상한 데이터들을 넣고 그 인스턴스와 parse한 모든 데이터들이 맞는지 확인하는 방법이 정확하다고 생각합니다만 저희는 일부만 확인해주어도 parse가 됐는지 확인이 된다고 생각합니다. 혹시 태태는 어떻게 생각하시나요?

2023-03-20 14:22 UTC, uuu1101 requested changes
안녕하세요 @gzzjk159 @seunghyunCheon 베토 브로디 :)
첫 PR 빠르게 보내주셨네요 👍
2주간 잘 부탁드립니다.

몇가지 코멘트 남겨두었습니다. 확인 부탁드려요 🙌

2023-03-20 14:22 UTC, uuu1101 commented on BoxOffice/DailyBoxOffice.swift
> +    let openDate: String
다른 값들은 포함하지 않은 이유가 있으신가요?

2023-03-20 14:22 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxOfficeResult: Result
Result 타입과 혼동 되지 않을까요..?
[Result Type](https://developer.apple.com/documentation/swift/result)

2023-03-20 14:22 UTC, uuu1101 commented on BoxOffice/Model/BoxOfficeResult.swift
> +        let showRange: String
API에서 제공해주는 네이밍이지만, 뜻이 더 명확하면 좋을 것 같습니다.

2023-03-20 14:22 UTC, uuu1101 commented on BoxOffice/Model/DailyBoxOffice.swift
> +    let showCount: String
API 문서를 보지 않고 네이밍만 보고 모든 프로퍼티의 정확한 쓰임을 유추할 수 있을까요? 👀

2023-03-21 01:05 UTC, seunghyunCheon commented on BoxOffice/DailyBoxOffice.swift
> +    let openDate: String
다른 값들도 포함시키도록 수정했습니다!

2023-03-21 01:27 UTC, gzzjk159 commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxOfficeResult: Result
result 타입과 혼동될 수 있는 것을 인지하고 BoxOffice로 이름을 변경하고 그 안에 인스턴스 네임을 BoxOfficeResult로 변경하여 혼동을 피해주었습니다. 
```swift
struct BoxOffice: Decodable {
    let boxOfficeResult: BoxOfficeResult
    
    struct BoxOfficeResult: Decodable {
        let boxOfficeType: String
        let showingDuration: String
        let dailyBoxOfficeList: [DailyBoxOffice]
        
        enum CodingKeys: String, CodingKey {
            case boxOfficeType = "boxofficeType"
            case showingDuration = "showRange"
            case dailyBoxOfficeList
        }
    }
}
```

2023-03-21 01:28 UTC, gzzjk159 commented on BoxOffice/Model/BoxOfficeResult.swift
> +        let showRange: String
showRange라는 네임이 뜻이 명확하지 않아 showingDuration이라는 네임으로 바꾸어 뜻을 더 명확하게 하였습니다. 
885595f75df5991ef545de55d6d19e4678120a6f

2023-03-21 01:32 UTC, seunghyunCheon commented on BoxOffice/Model/DailyBoxOffice.swift
> +    let showCount: String
`audienceChange`의 경우 전일 대비 관객수 증감 비율을 알려주는 프로퍼티입니다!
정확한 쓰임을 위해서는  `audienceChangeRatioComparedToPreviousDay`처럼 풀 네임을 사용해야 할 것 같은데 그렇게 되면 너무 길어지는 것 같아서 이렇게 정의했습니다. 

의미를 최대한 명확하게 짓고, 그럼에도 의미가 모호한 것들은 주석이나 문서를 통해 정리해두는 방법은 괜찮은 방법일까요?

2023-03-21 13:55 UTC, uuu1101 commented on BoxOffice/Model/DailyBoxOffice.swift
> +    let showCount: String
네! 말씀하신것 처럼 주석이나 문서를 통해 정리해두는 방법도 좋아보이네요.

2023-03-21 13:55 UTC, uuu1101 commented
STEP 1 고생하셨습니다 !! 👏👏👏👏👏👏

2023-03-21 13:55 UTC, merged