박스오피스 [STEP 1] 혜모리, 크리스티
yagom-academy/ios-box-office pull request #7
Opened 2023-03-20 10:12 UTC by christy-hs-lee

@havilog

안녕하세요 하비! 크리스티, 혜모리 인사드립니다 🙇🏻‍♀️🙇🏻‍♀️
STEP 1 PR 보내드립니다.
이번 박스오피스 프로젝트 리뷰 잘 부탁드리겠습니다. 🙌🏻

---

## 고민했던 점
### 1️⃣ 타입 구성

JSON을 열어보고 어떻게 타입을 구성할지 고민해 보았습니다.

``` swift
{"boxOfficeResult": {
        "boxofficeType": "일별 박스오피스",
        "showRange": "20220105~20220105",
        "dailyBoxOfficeList": [
            {
                "rnum": "1",
                "rank": "1",
                "rankInten": "0",
                "rankOldAndNew": "NEW",
                "movieCd": "20199882",
                "movieNm": "경관의 피",
                "openDt": "2022-01-05",
                "salesAmt": "584559330",
                "salesShare": "34.2",
                "salesInten": "584559330",
                "salesChange": "100",
                "salesAcc": "631402330",
                "audiCnt": "64050",
                "audiInten": "64050",
                "audiChange": "100",
                "audiAcc": "69228",
                "scrnCnt": "1171",
                "showCnt": "4416"
            }, //...
        ]
    }
}
```

고민하던 중 타입은 중괄호를 열고 닫는 기준으로 나누었습니다.

- `BoxOffice` : 가장 큰 범위로 JSON 파일을 디코딩 받을 타입
- `BoxOfficeResult` : `"boxOfficeResult"` 키의 값을 나타내는 검색 결과 타입
- `DailyBoxOfficeItem` : `"dailyBoxOfficeList"` 키의 값을 나타내는 검색된 영화의 목록 타입

</br>

### 2️⃣ Key의 값을 알기 쉽게 변경하기
JSON 파일을 보니 변수명이 컨벤션에 ~않았습니다. `CodingKey`를 사용하여 카멜케이스를 준수하지 않거나 축약된 이름을 저희가 구분할 수 있도록 풀어서 네이밍을 정해보았습니다.

- `rankInten` ➡️ `rankingIntensity`
- `boxofficeType` ➡️ `boxOfficeType` 등 이해하기 쉬운 네이밍으로 변경했습니다.

</br>

### 3️⃣ Unit Test

JSON 데이터가 잘 Parsing 되는지 확인하기 위한 Unit Test이기 때문에 
`sut`의 초기값에 디코딩 결과 값을 저장해 주었습니다.

디코딩을 성공했는지에 대한 테스트는 디코딩 실패 시 코드에서 nil을 반환해 주기 때문에
`test_디코딩할때_nil을반환하지않는다()` 메서드로 확인해 주었습니다.

``` swift
import XCTest
@testable import BoxOffice

final class BoxOfficeTests: XCTestCase {
    var sut: BoxOffice!
    
    override func setUpWithError() throws {
        try super.setUpWithError()
        sut = Decoder().decodeBoxOffice()
    }

    override func tearDownWithError() throws {
        try super.tearDownWithError()
        sut = nil
    }
    
    func test_디코딩할때_nil을반환하지않는다() {
        // then
        XCTAssertNotNil(sut)
    }
    
    // ...
}
```

2023-03-20 14:15 UTC, havilog requested changes
스탭 1 수고하셨어요 ~
이해 안되는 코멘트 있으시면 답코멘트나 디엠 주세요 :)

2023-03-20 14:15 UTC, havilog commented on .DS_Store
.DS_Store 파일이 올라가있네요?

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/BoxOffice.swift
> +struct BoxOffice: Codable {
`Codable` 프로토콜이 어떻게 구현되어있고, 어떤 요구사항을 요구하는지 알고 계실까요?

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/BoxOfficeResult.swift
> +}
`BoxOfficeResult`모델은 `BoxOffice` 내부에 nested하게 존재하면 BoxOffice 프리픽스가 없어질 수 있을거 같은데 이 고려해보셨을까요 🤔

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxOfficeType: String
`boxOfficeType`이라는 네이밍은 enum으로 된 case들이 정의될 수도 있다고 보여지는데 해당 부분은 고려해보셨을까요?

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +        case number = "rnum"
number라는 네이밍은 정확하게 어떤 숫자를 의미하는지 파악이 잘 안되는거 같아요 ㅠㅠ

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +    let showCount: String
크게 문제되지는 않아보이는데,
보통은 프로퍼티 하나하나 다 풀어쓰는게 일반적인 컨벤션이라고 알고있어요 (아닐 수도 있어요 ..!)

그리고, 실제로 뷰를 구현할 때 필요한 프로퍼티가 아닐 경우에는 선언해주지 않을 수도 있을거 같아요.

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/Decoder.swift
> +    }
제네릭을 사용하는 방법은 고민해보셨을까요?
에러가 났을 때 어떻게 처리할지도 고민해보셨는지 궁금해요.

2023-03-20 14:15 UTC, havilog commented on BoxOfficeTests/BoxOfficeTests.swift
> +}
given은 json이 되어야할 거 같고,
when에서 json의 값을 바꾸고 decode했을 때
then에서 expected result를 비교해야

decode가 제대로 되는지, 모델을 제대로 구현했는지가 테스트 될 거 같은데 어떻게 생각하시나요?

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/Decoder.swift
> +        guard let items: NSDataAsset = NSDataAsset(name: "box_office_sample") else { return nil }
가져올 asset name은 파라미터로 받아오면 확장성이 더 좋을거 같아요.

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/Decoder.swift
> +struct Decoder {
네이밍이 너무 범용적인거 같아요.
어떤 것을 디코드 해서 어떤 행동을 하는 디코더인지에 대한 정보를 유추할 수 없을거 같아요.

2023-03-20 14:15 UTC, havilog commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +        case showCount = "showCnt"
LGTM 👍

2023-03-21 05:50 UTC, christy-hs-lee commented on .DS_Store
해당 부분 `.gitignore` 파일을 사전에 확인하지 않고 진행하다 발생한 실수였습니다.
확인 후 삭제 완료했습니다!

2023-03-21 05:57 UTC, christy-hs-lee commented on BoxOffice/Model/BoxOfficeResult.swift
> +}
프리픽스 관련해서 nestedType으로 변경하고 비슷하게 발생할 수 있는 부분도 수정했습니다!

2023-03-21 05:57 UTC, christy-hs-lee commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +        case number = "rnum"
행의 번호라는 의미를 가지고 있어 `rowNumber`로 수정했습니다!

2023-03-21 06:24 UTC, hyemory commented on BoxOffice/Model/BoxOffice.swift
> +struct BoxOffice: Codable {
Codable은 Encodable과 Decodable 프로토콜을 합친 typealias 입니다. 
인코딩 또는 디코딩을 위해 외부 파일 코딩 키의 경로를 선언해 주어야 합니다.
Encodable 프로토콜은 `encode(to:)` 메서드를, Decodable 프로토콜은 `init(from:)` 메서드를 필수로 구현해야 하는데
Swift에서는 두 메서드의 기본 구현을 제공합니다.

2023-03-21 06:25 UTC, christy-hs-lee commented on BoxOffice/Model/Decoder.swift
> +    }
제네릭을 사용하는 부분은 미처 생각하지 못 했습니다.
해당 부분 제네릭을 사용하여 범용성을 고려할 수 있었습니다.
또한 에러타입을 정의하여 별도로 처리할 수 있도록 했습니다!

2023-03-21 06:28 UTC, hyemory commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxOfficeType: String
샘플로 제공된 JSON 파일에 있는 `boxOfficeType`은 종류가 하나밖에 없어 `String` 타입으로 정의하였습니다!
말씀해 주신 내용을 고민해 보다가 `DailyBoxOfficeItem` 타입의 `rankOldAndNew` 는 enum의 case로 정의할 수 있을 것 같아 수정해 보았습니다 😄

``` swift
enum RankOldAndNew: String, Codable {
    case new = "NEW"
    case old = "OLD"
}
```

2023-03-21 06:29 UTC, hyemory commented on BoxOffice/Model/DailyBoxOfficeItem.swift
> +    let showCount: String
하나하나 풀어쓰는 것으로 수정했습니다!
추후 뷰를 구현할 때 필요 없는 내용을 제외해 보겠습니다. 👍

2023-03-21 06:30 UTC, christy-hs-lee commented on BoxOffice/Model/Decoder.swift
> +        guard let items: NSDataAsset = NSDataAsset(name: "box_office_sample") else { return nil }
제네릭으로 변경하며 해당 부분도 함께 수정했습니다!

2023-03-21 06:34 UTC, hyemory commented on BoxOfficeTests/BoxOfficeTests.swift
> +}
테스트 내용을 변경해 보았습니다. 
`AssetDecoder`의 `decode` 메서드를 호출할 때 잘못된 JSON 파일 이름을 넣으면 의도한 에러를 던지는 지 확인했습니다.

``` swift
func test_잘못된JSON파일이름으로_디코딩했을때_decodeFailed에러를던진다() {
    // given
    let invalidJsonFileName = "invalid_name"
    let errorMessage = DecoderError.decodeFailed
    var error: DecoderError?
    
    // when
    XCTAssertThrowsError(try AssetDecoder().decode(name: invalidJsonFileName, type: BoxOffice.self)) {
        errorHandler in
        error = errorHandler as? DecoderError
    }
    
    // then
    XCTAssertEqual(error, errorMessage)
}
```

2023-03-21 06:35 UTC, hyemory commented on BoxOffice/Model/Decoder.swift
> +struct Decoder {
Asset 파일을 디코딩하는 타입이라 `AssetDecoder`로 네이밍을 변경해 보았습니다!

2023-03-21 11:45 UTC, havilog commented on BoxOffice/Model/BoxOffice.swift
> +struct BoxOffice: Codable {
👍
`BoxOffice`모델을 구현하실 때, 해당 모델이 encoding될 여지가 있는지에 대한 고민이 있으셨나 해서 여쭤봤습니다 ㅎㅎ
현재 요구사항만 봤을때에는 decodable 프로토콜만 준수해도 될거 같았어요 ㅎㅎ  
encoding 될 수도 있다고 생각하셨으면 잘 구현하셨어요 :)

2023-03-21 11:52 UTC, havilog approved these changes
수고하셨어요 다음 스탭에서 뵐게요

2023-03-21 11:52 UTC, havilog commented on BoxOffice/Model/AssetDecoder.swift
> +    func decode<T: Decodable>(name: String, type: T.Type) throws -> T? {
Swift에서 some, any에 대한 키워드도 지원해주는데
떱씨 영상 한 번 참고보시면 도움될거 같아요.
https://developer.apple.com/videos/play/wwdc2022/110352/

2023-03-21 11:52 UTC, havilog commented on BoxOffice/Model/AssetDecoder.swift
> +        }
JSONDecoder에서 실패했을 때의 decoding 에러와, 에셋을 못가져왔을 때의 에러가 똑같지 않을거 같아요!
또한 decode에 실패했을 때 에러 또한 외부로 던져줘야할 거 같아요.
해당 부분은 다음 스탭에서 수정하시면 좋을거 같습니다 :)

2023-03-21 11:52 UTC, merged