박스오피스 [STEP 1] Dasan, Whales
yagom-academy/ios-box-office pull request #73
Opened 2023-07-25 09:58 UTC by WhalesJin

안녕하세요, 븨븨(@YebinKim)!! 💃🏻
박스오피스 리뷰를 받게 된 Dasan🌳, Whales🐋 인사드립니다!!
프로젝트들 중 가장 중요하고 여러운 프로젝트라 들어서 걱정도 하고 있지만, 
그만큼 또 새로운 것들을 배우고 공부할 기회가 될 것 같아서
설레기도 합니다!!!

4주동안 잘 부탁드립니다 🙇🏻‍♀️

## 🤹🏻 고민했던 점
### 🔹 BoxOfficeData 타입 네이밍 이유

- 영화 진흥 위원회의 제공 서비스를 보면 `일별 박스오피스` 뿐만 아니라 `주중/주간 박스오피스`의 데이터도 제공하고 있고, 그 데이터를 구성하는 요소들도 같아서 추후의 확장성을 위해 `DailyBoxOfficeData`가 아닌 `BoxOfficeData`로 네이밍 하였습니다.
  <img src = "https://hackmd.io/_uploads/B1qt9GT92.png" width = "150">

### 🔹 Unit Test
- `Data`만 있는 `BoxOffice` 타입을 테스트하기보다 `DecodingManager` 타입의 decodeJSON`메서드`를 테스트하여, **decoding 및 parsing**이 잘 이루어지고 있는지 확인하였습니다.
- 현재로써는 `Error`를 어떻게 처리해야하는지 명확하지 않아 `do-catch`문 등으로 오류 처리하기보다, Tests 내에서 `XCTAssertThrowsError`, `XCTAssertNoThrow` 메서드를 사용하여 상황에 맞게 오류를 잘 던지고 있는지 확인하였습니다.

```swift
//DecodingManagerTests.swfit

func test_일치하는_dataAsset이없을때_notFoundAsset에러를_던진다() {
    //given
    let fileName = "없는파일이름"

    //when, then
    XCTAssertThrowsError(try sut.decodeJSON(fileName: fileName) as BoxOffice) { error in
        XCTAssertEqual(error as! DataError, DataError.notFoundAsset)
    }
}
    
func test_일치하는_dataAsset가있을때_notFoundAsset에러를_던지지않는다() {
    //given
    let fileName = "box_office_sample"

    //when, then
    XCTAssertNoThrow(try sut.decodeJSON(fileName: fileName) as BoxOffice)
}
```

### 🔗 참고문서
- [Apple Docs: XCTAssertThrowsError](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror)

2023-07-25 15:28 UTC, YebinKim requested changes
웨일, 다산 안녕하세요~!!
2주간 박스오피스 프로젝트를 리뷰하게 된 비비입니다 😄

고민했던 점을 굉장히 깔끔하게 적어주셨는데요! 👍
작성하신 내용을 `문제 원인`, `문제 해결` 로 나눠서 README에도 작성할 수 있다면 추후 귀한 문서화 자료가 될 거 같아요 😆🙌

그리고 리뷰 코멘트 확인 전 아래 내용 확인 부탁드릴게요.

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```


---

현재 최신 커밋 97beb44 에서 테스트가 동작하지 않는 문제가 발생하고 있는데요.
DM으로 말씀드렸듯 직전 커밋에서 Test Plan 의 위치를 옮길 때 `BoxOffice`타겟에 대한 경로의 참조가 깨진 문제인 것으로 보이며, 이에 대한 수정이 필요해 리뷰 의견 Request Changes 로 요청드렸습니다 🙌
(문제 상황에 대한 해결 방법을 이미 함께 알아보았기 때문에, 문제에 대해 정확히 이해할 수 있도록 문제 상황을 다시 한 번 의도적으로 발생시키고 해결하는 과정을 겪어보는 것을 추천드려요 ☺️)

<img width="1400" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/fd8d5e5e-5b07-463d-9973-adb448b58138">

또한, 해당 키값이 무엇을 의미하는가에 대한 설명으로 참고하면 좋을 자료 하나 링크드려요!
[Improving code assessment by organizing tests into test plans](https://developer.apple.com/documentation/xcode/organizing-tests-to-improve-feedback)

그 외 코멘트도 확인 부탁드리며, 혹시 코멘트 중 궁금한 점이 있다면 답글 남겨주세요 🙇🚀

2023-07-25 15:28 UTC, YebinKim commented on BoxOffice/Model/DecodingManager.swift
> +    func decodeJSON<T: Decodable>(fileName: String) throws -> T {
p4;

Generic 매개변수 `T` 를 더 적절한 이름으로 변경해보면 어떨까요? 🤔

[Array 구현체](https://github.com/apple/swift/blob/main/stdlib/public/core/Array.swift#L301)의 `요소` 제네릭 타입이 `Element` 라는 이름을 가짐으로써 타입으로서 의미하는 바가 명확히 전달될 수 있듯
<img width="485" alt="스크린샷 2023-07-25 오후 11 34 56" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/b5de481d-3ea4-4b1e-9ff9-58615ae1536c">

단순히 제네릭 매개변수라는 뜻의 `T`를 사용하는 것 보다는 **의미를 담은 이름**으로 작성하는 편이 이해하기 쉬운 코드라고 생각됩니다.

2023-07-25 15:28 UTC, YebinKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    override func setUpWithError() throws {
p3;

override 메서드를 사용하면서 super 메서드를 호출하지 않은 것은 의도된 사용일까요? 👀

2023-07-25 15:28 UTC, YebinKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +            XCTAssertEqual(error as! DataError, DataError.failedDecoding)
```suggestion
            XCTAssertEqual(error as? DataError, DataError.failedDecoding)
```

여기서는 강제 언래핑을 하지 않아도 비교할 수 있습니다!
참고차 말씀드려요 😄

2023-07-25 15:28 UTC, YebinKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    func test_일치하는_dataAsset이없을때_notFoundAsset에러를_던진다() {
Given-When-Then(GWT) 패턴을 활용해 테스트 코드의 가독성을 높이고 흐름을 이해하기 쉽게 작성하셨군요!! 👍

2023-07-25 15:29 UTC, YebinKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    func test_일치하는_dataAsset이없을때_notFoundAsset에러를_던진다() {
Unit Test 에서는 GWT 패턴 뿐만 아니라 다양한 패턴이 존재한다는 점도 함께 언급드려요 🙌
(GWT 패턴과 유사한 패턴으로는 AAA 패턴이 있습니다)

2023-07-26 02:33 UTC, DasanKim commented on BoxOffice/Model/DecodingManager.swift
> +    func decodeJSON<T: Decodable>(fileName: String) throws -> T {
커밋링크 : https://github.com/yagom-academy/ios-box-office/pull/73/commits/19d97c13676cf267e53d3485ba8fe8700a10b903

- `Data`의 의미가 적절하다고 생각되어 `Data`로 바꾸고 싶었지만 기존 타입이 존재했습니다.
- 위 `DecodingManager`의 `decodeJSON` 메서드의 반환값인 `decodedData`는 `decode` 메서드의 반환값으로 로직을 구현했기에, swift에서 제공해주는 `decode` 메서드 반환값 설명을 참고하여 `Value`라는 이름으로 수정하였습니다:)
    > A value of the specified type, if the decoder can parse the data.

2023-07-26 05:21 UTC, WhalesJin commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    override func setUpWithError() throws {
`super class` 메서드가 아무런 동작을 하지 않을 때 `super`를 호출하지 않아도 된다고 알고 있습니다:)
- `XCTestCase` 내의 해당 메서드는 기능이 구현되어 있지 않기 때문에 `super`를 호출하지 않아도 된다고 판단하였습니다.
    - 이 부분에 관하여 언급하고 있는 공식문서는 찾지 못하였지만, [Set Up and Tear Down State in Your Tests](https://developer.apple.com/documentation/xctest/xctestcase/set_up_and_tear_down_state_in_your_tests) 문서의 예제에서도 super를 호출하지 않는 것을 간접적으로 확인할 수 있었습니다.
- 또한 `XCTestCase`를 포함하여 `해당 메서드를 정의하고있는 super class`가 없기에 super를 호출하지 않았습니다.

`super`의 해당 메서드들이 아무런 동작을 하지 않는다는 것을 알고 생략하였지만, 보통 `super class`에 중요한 정의가 있을 수 있으므로 상속 체인을 유지하기 위하여 보통 `super`를 호출하는 것이 바람직하다는 것을 유념하기로 하였습니다!

2023-07-26 05:26 UTC, DasanKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +            XCTAssertEqual(error as! DataError, DataError.failedDecoding)
커밋링크 : https://github.com/yagom-academy/ios-box-office/pull/73/commits/3225abb04dc186f61517ed4af3cb9eaaf6ff1d6c

오 감사합니다!! 알려주신 덕분에 수정하였습니다!!🙏

2023-07-26 06:12 UTC, WhalesJin commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    func test_일치하는_dataAsset이없을때_notFoundAsset에러를_던진다() {
알려주신 AAA패턴을 공부해보았습니다!!

GWT(Given-When-Then)
- Given(준비): 테스트를 수행하기 위해 초기 상태 설정
- When(실행): 실제 테스트 작업을 수행하는 동작 지정
- Then(검증): 테스트 결과를 검증하는 기대 결과 명시

AAA(Arrange-Act-Assert)
- Arrange(준비): 테스트를 실행하기 전에 필요한 것들을 준비
- Act(실행): 테스트해야 하는 작업을 수행
- Assert(단언): 실행한 코드가 예상한대로 동작했는지 확인

두 스타일을 굉장히 비슷하지만 단어 선택에 대해 GWT는 `scenario(시나리오)`에 초점을 맞추고 AAA는 `behavior(행동)`에 초점을 맞추고 있다는 차이점을 공부했습니다.
사실 알아볼수록 두 개의 패턴이 비슷하다는 생각이 들어 더 명확한 차이점이 있는지 여쭤보고싶습니다 🙏🏻

[Arrange-Act-Assert vs Given-When-Then](https://medium.com/plain-and-simple/arrange-act-assert-vs-given-when-then-c22da421bf75)
[AAA 패턴](https://codechacha.com/ko/unittest-aaa-pattern/)

2023-07-26 06:33 UTC, DasanKim commented
> 현재 최신 커밋 https://github.com/yagom-academy/ios-box-office/commit/97beb449776bfb8c1d9f3a2fae0e688bedbc1d2e 에서 테스트가 동작하지 않는 문제가 발생하고 있는데요.
DM으로 말씀드렸듯 직전 커밋에서 Test Plan 의 위치를 옮길 때 BoxOffice타겟에 대한 경로의 참조가 깨진 문제인 것으로 보이며, 이에 대한 수정이 필요해 리뷰 의견 Request Changes 로 요청드렸습니다 🙌

븨븨 안녕하세요!

Test Plan 경로 참조값이 깨진 것에 대하여 `Target for Variable Expansion`을 수정해보았으나, 스키마의 참조경로가 변하지 않았습니다ㅠㅠ
- **Target for Variable Expansion**: Xcode가 빌드 설정을 확장할 때 기준으로 사용할 대상입니다. 

그리하여 아래 첨부한 사진처럼 `Edit scheme`에서 `Test Plans`에 있는 기존 BoxOffice Test Plan을 삭제하고, 다시 add 해주는 방법으로 해결하였습니다😊

<img src = "https://hackmd.io/_uploads/rk52seCc3.png" width = "300">
<img src = "https://hackmd.io/_uploads/rkg6ogR92.png" width = "500">
<img src = "https://hackmd.io/_uploads/SkvTsgRqh.png" width = "500">

2023-07-26 08:58 UTC, YebinKim commented on BoxOfficeTests/DecodingManagerTests/DecodingManagerTests.swift
> +    func test_일치하는_dataAsset이없을때_notFoundAsset에러를_던진다() {
두 패턴 자체가 비슷한 패턴이다보니 뚜렷한 차이점을 찾기가 어려운 거 같아요 👀
GWT 패턴은 BDD(Behavior Driven Development)에서 유래된 패턴이고 AAA 패턴은 TDD(Test Driven Development)에서 유래된 패턴이라는 점으로 인해 용어 차이가 있지만, 실제로 두 패턴을 활용함에 있어서는 큰 차이가 없다고 생각합니다.

2023-07-26 09:18 UTC, YebinKim approved these changes
다산, 웨일 안녕하세요~
코멘트 확인 감사합니다!

Test Plan 경로와 관련해서는 제가 적용했던 방법이 왜 동일하게 되지 않았는가는 의문이지만 🤔
현재 적용하신 방법과 같이 Test Plan 을 삭제하고 다시 추가하는 게 더 확실한 해결방법인 거 같다는 생각이 드네요 😄

---

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="356" alt="step1" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/530d7133-8f01-4b94-9402-84e3a09cdb66">

파싱하고자 하는 모델 데이터가 샘플 데이터를 디코딩하는 데 성공하며, Unit Test 또한 테스트 대상인 `DecodingManager.swift` 의 테스트 커버리지가 100%를 달성하고 있어서 스텝의 핵심 경험을 모두 충족했다고 생각합니다! 🎉

<img width="857" alt="test coverage" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/09826fd8-946d-48af-8143-b993c07539ea">

이번 스텝은 여기서 머지 진행하도록 할게요! Step1 진행 및 수정까지 고생 많으셨습니다 👏👏

2023-07-26 09:18 UTC, merged