박스오피스 [STEP 1] karen
yagom-academy/ios-box-office pull request #74
Opened 2023-07-26 04:48 UTC by karenyang835

@YebinKim

안녕하세요. 븨븨~
이번에 또 한번 좋은 기회가 생겨 븨븨의 리뷰를 받게 된 `karen`입니다.😊

`Step1` `PR`보내드립니다.

만국박람회 때 븨븨에게 많은 배움을 받았던`JSON`을 다시 한번 더 활용하게 되었습니다. 이번에는 `JSON`데이터 디코딩이 수월하게 이루어지는지`Unit Test`를 진행하는 부분이 많이 어려워 시간이 많이 지체된 것 같습니다.🥲

만국박람회때도 `JSON`에 대해서 심도있게 이해를 못했었는데 이번에 또 다시 진행하면서 조금 더 이해하게 된 것 같습니다.

4주 동안의 박스오피스 프로젝트 리뷰도 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ .DS_Store는 무엇인가?
- 평소 프로젝트를 진행할 때 한 번도 안떴던 파일인 것 같은데 이번 프로젝트 진행을 하니 해당 파일이 보였습니다.
#### <오류 상황>
![스크린샷 2023-07-26 오후 12 14 57](https://github.com/yagom-academy/ios-box-office/assets/124643896/c915534b-bdaf-4e26-896d-0a05ffece528)

해당 폴더를 계속 뜨게 놔둬도 되나 생각해봤는데 기존 파일을 수정을 했는지 여부를 알기 위해서는 `git status`에서 검증을 해줘야되는데 저렇게 계속 뜨게 되면 헷갈릴 것 같아서 삭제를 해주었습니다.

#### <삭제방법>
![스크린샷 2023-07-26 오후 12 23 52](https://github.com/yagom-academy/ios-box-office/assets/124643896/caf6141a-7fa1-4d5f-8bbf-01ba699d84df)

### 2️⃣`CodingKeys`의 역할이 무엇인가?
- 만국박람회때는 `CodingKeys`의 사용 목적이 단순히 `JSON`에서 사용하는 스네이크케이스를 카멜케이스로 변환하는 용도로만 사용한다 생각되어졌지만 카멜케이스도 사용하는 `JSON`에서 축약적인 네이밍부분과 명확하지 않은 네이밍 부분도 변경하는 용도로도 활용해야된다고 생각되어졌습니다. 박스오피스에서는 스네이크케이스 뿐 아니라 네이밍이 명확하지 않거나 알아보기 힘든 네이밍 부분도 `swift`에서 추구하는 네이밍으로 변경하는 용도로 작성해보았습니다.

### 3️⃣`UnitTest`를 하는 목적이 무엇이고 어디에 중점을 두어야 할까?
- 아직 `UnitTest`하는 부분은 어색하고 많이 어려운 것 같습니다. 
기존에 제가 생각하고 있던 `UnitTest`를 하는 목적은 현재 스텝으로 비유하면 디코딩에 대한 검증이라고 생각했었고 검증을 하는 대상이 애플에서 이미 검증해서 적용시켜 둔 메서드인 `decode`에 대한 검증을 했던 것 같습니다.
- 실상은 명확하게 `UnitTest`를 왜 해야되고 목적이 무엇인지를 명확하게 알지를 못하다보니 방향을 잘못 잡았던것 같습니다.
- `UnitTest`를 하는 진짜 목적은 제가 작성한 코드가 제대로 자기 역할에 맞게 수행하는지를 검증하는 것이라는걸 알게되었습니다. 그리고 `UnitTest`를 작성할 때 이번 스텝에서는 비록 `API`데이터를 불러와서 연동하지는 않지만 추후에 연동할 것을 고려해서 코드를 작성해두고 그것을 기점으로 원래 들어올 데이터와 테스트용 코드를 각각 구현해서 작성한 코드가 잘 돌아가는지를 확인 할 수 있게 하는것도 중요하다고 생각되어서 되도록이면 어떤 상황에서도 유연하게 대처할 수 있는 코드를 작성하려고 노력했습니다.

--- 

<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣`UnitTest`를 잘할 수 있는 방법을 알고싶습니다.
- 고민한 부분 3️⃣에 적기도했지만 제가 제대로 이해했는지 사실 파악하기가 쉽지 않은 것 같습니다. 이번에 제가 작성한 코드가 원활히 돌아가는지 여부를 확인하는것에 중점을 두고 테스트 코드를 작성해보긴 했지만 사실 작성을 잘한 것인지는 아직 불분명한것 같습니다. 어떤것에 중점을 두고 테스트를 진행하는게 좋을까요?

2023-07-26 18:12 UTC, YebinKim requested changes
카렌 안녕하세요~
또 한 번 리뷰어로 만나게 된 비비입니다 😄
2주간 박스오피스 프로젝트를 진행하며 또 자주 소통해보아요 🙌👀

그리고 이번에도 코멘트 확인 전 아래 내용 확인 부탁드릴게요!

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. UnitTest를 잘할 수 있는 방법을 알고싶습니다.

카렌의 기준에서 `테스트를 잘 한다.` 는 것은 무엇일까요? 👀
이 기준을 스스로 세울 수 있어야 코드의 작성 방향 및 리팩토링 방향을 설정할 수 있다고 생각합니다.

말씀해주신 작성한 코드가 원활히 돌아가는지를 확인하는 것의 관점에서는 `BoxOfficeTests` 에서 작성한 테스트 코드가 실제 구현에서 활용할 코드가 아닌 테스트만을 위한 타입 `TestDataManager` 와 `TestGetDataAPI` 의 동작을 확인하고 있어서 **테스트를 위해 작성한 코드는 원활히 돌아가는 게 맞지만**, **실제 앱 동작이 테스트되고 있는지**는 의문이 듭니다 🤔

### 2. .DS_Store는 무엇인가?

그리고 작성해주신 *고민한 부분*을 보며 궁금한 점이 생겼는데요.
`.DS_Store` 파일을 왜 지금까지 발견할 수 없었는지, `gitignore` 파일이 무엇인지도 생각해보셨을까요?

---

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="356" alt="step1" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/65126d20-812e-45e1-9e22-c44c3d2dd6f4">

Unit Test 를 통한 설계의 검증이 이루어지고 있는가에 대해 좀 더 얘기를 나눠보는 게 필요할 거 같아 Request Changes 로 요청드렸습니다!
코멘트 내용 및 수정 방향에 대한 추가 설명이 필요하다면 말씀해주세요 😄🙌

2023-07-26 18:12 UTC, YebinKim commented on BoxOffice/Model/GetDataAPI.swift
> +final class GetDataAPI: APIProtocol {
p2;

프로토콜을 채택하고 다시 빈 메서드로 구현하고자 한 이유가 무엇일까요?

또한, Swift API Design Guidelines의 [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)에 따르면 타입의 경우 명사형의 이름을 사용하는 것을 권장하고 있습니다.
> The names of other types, properties, variables, and constants should read as nouns.

2023-07-26 18:12 UTC, YebinKim commented on BoxOffice/Protocol/APIProtocol.swift
> +    func callAPIServer(completion: @escaping (Result<[MovieInfo], Error>) -> ())
`Result` 타입을 사용하셨군요!!
앞으로의 활용이 기대됩니다 😆

2023-07-26 18:12 UTC, YebinKim commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
p2;

프로토콜을 채택할 타입이 수행할 역할을 기준으로 더 적절한 이름을 작성해볼 수 있을까요?
Swift API Design Guidelines의 [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)에서도 프로토콜을 통해 특정 기능을 수행할 수 있음을 명시하고자 하는 경우 접미사로 `-able` 등을 활용할 것을 권장하고 있습니다.
> Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).

2023-07-26 18:12 UTC, YebinKim commented on BoxOffice/Protocol/DataManaging.swift
> +    func decodeData<MovieData: Decodable>(_ type: MovieData.Type, from data: Data) -> MovieData?
p3;

`MovieData` 대신 좀 더 범용적인 이름의 제네릭 매개변수를 활용해보면 어떨까요?
`DataManaging` 프로토콜이 영화 관련 데이터에 의존하지 않음을 나타낼 수 있다면 더욱 확장성 좋은 구조가 될 수 있을 거 같아요 👀

2023-07-26 18:12 UTC, YebinKim commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxofficeType: String
```suggestion
    let boxOfficeType: String
```

p3;

다른 변수와 컨벤션이 달라보여요 👀

2023-07-26 18:12 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.setUp()
질문;

setUpWithError() 메서드와 setUp() 메서드는 어떤 차이가 있는지 알고 계실까요?

2023-07-26 18:12 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +    var testData: TestDataManager!
p1;

해당 테스트를 통해 얻고자 하는 검증 결과가 무엇일까요? 🤔
앞서 종합 코멘트에서 말씀드렸듯 작성된 테스트 코드가 실제 구현에서 활용할 코드가 아닌 테스트만을 위한 타입 `TestDataManager` 와 `TestGetDataAPI` 의 동작을 확인하고 있어서 **테스트를 위해 작성한 코드는 원활히 돌아가는 게 맞지만**, **실제 앱 동작이 테스트되고 있는지**는 의문이 듭니다.

카렌이 이번 테스트를 통해 얻고자 하는 검증은 무엇이었으며, 이번 스텝의 핵심 경험인 `설계의 검증`이 이를 통해 확인된 게 맞을까요?

2023-07-26 18:12 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_API서버와의_통신으로_가져온_데이터가_5초안에_불러오고_Decoding이_잘되었는가() {
p1;

현재 테스트 객체를 사용하고 있기 때문에 서버와 실제로 통신을 하고 있지 않긴 하지만, 서버로부터 데이터를 가져오게 될 경우 클라이언트의 네트워크 상황에 따라 테스트가 실패하거나 서버의 상태에 따라 테스트가 실패할 가능성도 있지 않을까요? 🤔
클라이언트 코드가 변경되지 않았음에도 테스트 결과가 달라지게 되는 상황이 생긴다면 테스트로서 어떤 의미를 가지는지 고민이 필요해보여요.

2023-07-27 17:44 UTC, karenyang835 commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
영화 정보를 받아오는 역활을 수행하는 의미로 `MovieDataFetchable`로 변경해줬습니다.

2023-07-27 18:05 UTC, karenyang835 commented on BoxOffice/Model/GetDataAPI.swift
> +final class GetDataAPI: APIProtocol {
- 제가 이번 프로젝트에서 추구하고자 했던 방법은 숲을 보는 방법을 연습해보고자 했습니다. 추후에 진행되어지는 스텝을 예상해서 되도록이면 코드를 수정하거나 추가하지 않고 진행할 수 있게끔 하기 위해서 스텝1에 명시되어져 있듯이 현 스텝에서는 `API`통신을 하지 않지만 추후 스텝에서는 `API`와의 통신을 진행할 것이라는 것을 유추해서 해당 부분에 맞게끔 코드를 작성해두고 싶었습니다. 그래서 생각한 방식이 프로토콜이었고, 프로토콜을 활용해서 테스트 데이터와 진짜로 가져와야 될 데이터를 적절하게 활용을 하고자 했습니다. 현재 스텝에서는 `API`와 통신하고 있지 않기 때문에 빈 메서드로 두었습니다. 그렇지만 추후에 `API`와 통신을 할 것이고 해당 통신을 했을 때 제대로 수행되는지도 파악을 해야되고 테스트를 위해 내부적으로 불러와지는 실제 모델과 테스트 모델만 바꿔 끼워주면 되게끔 코드를 작성하고 싶어서 빈 메서드로 구현해두었습니다. 
- 네이밍도 `GetDataAPI`에서 `MovieDataAPI`로 변경해주었습니다.

2023-07-27 18:09 UTC, karenyang835 commented on BoxOffice/Protocol/DataManaging.swift
> +    func decodeData<MovieData: Decodable>(_ type: MovieData.Type, from data: Data) -> MovieData?
가장 무난할 것 같은 'Element'로 수정해주었습니다.

2023-07-27 18:10 UTC, karenyang835 commented on BoxOffice/Model/BoxOfficeResult.swift
> +    let boxofficeType: String
`boxOfficeType`로 다른 변수들과 동일하게 컨벤션 통일을 해주었습니다.

2023-07-27 18:13 UTC, karenyang835 commented on BoxOffice/Protocol/APIProtocol.swift
> +    func callAPIServer(completion: @escaping (Result<[MovieInfo], Error>) -> ())
앞으로 자주 사용되어질 것 같아 활용해보았습니다.😆

2023-07-27 18:14 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.setUp()
- 븨븨께서 질문 주시기 전에는 `setUp(`)만 알고 있는 상태여서 두 가지에 대해 잘 몰랐었는데 븨븨의 질문을 받고 공부해본 결과 두 메서드는 각 테스트 메서드라 실행되기 호출되며 각 테스트 메서드에서 공통적으로 필요한 초기화 작업을 수행하는 것으로 알고 있습니다. 
- `setUpWithError()`와 `setUp()`의 가장 큰 차이점은 `setUpWithError()`는 초기화 작업중에 발생하는 예외를 처리할 수 있습니다. 만약 이 메서드내에서 예외가 발생되어지면 해당 테스트는 실패합니다.
- 예외처리가 필요해지면 `setUpWithError()`를 활용하는것이 좋겠지만 해당 메서드는 `IOS 14.0`에서 사용이 가능하므로 타겟 `IOS`버전과 사용중인 `XCTest`버전에 따라서 사용 가능한 메서드가 달라질 수 있기 때문에 확인을 하고 진행해야 되기 때문에 현재로서는 예외처리 부분이 없을 것 같고, 모든 버전에서 활용할 수 있는 `setUp()`을 사용하는 것이 더 좋다고 생각되어졌습니다.

2023-07-27 18:30 UTC, karenyang835 commented
### 1. UnitTest를 잘할 수 있는 방법을 알고싶습니다.
>카렌의 기준에서 테스트를 잘 한다. 는 것은 무엇일까요? 👀
이 기준을 스스로 세울 수 있어야 코드의 작성 방향 및 리팩토링 방향을 설정할 수 있다고 생각합니다.

>말씀해주신 작성한 코드가 원활히 돌아가는지를 확인하는 것의 관점에서는 BoxOfficeTests 에서 작성한 테스트 코드가 실제 구현에서 활용할 코드가 아닌 테스트만을 위한 타입 TestDataManager 와 TestGetDataAPI 의 동작을 확인하고 있어서 테스트를 위해 작성한 코드는 원활히 돌아가는 게 맞지만, 실제 앱 동작이 테스트되고 있는지는 의문이 듭니다 🤔
- 사실 아직 테스트를 잘한다는 것에 대한 명확한 기준이 없는 것 같습니다. `UnitTest`에 대한 목적이 무엇인지에 대해서도 명확하게 알지 못하는 것 같습니다. 그렇지만 이번 프로젝트를 진행할 때 한 가지 정해둔 것이 있었는데위에 코멘트에서도 언급을 했지만 코드의 작성 방향을 해당 미션에서 요구하는 사항과 앞으로 벌어질 사항들까지도 미리 생각해두어 혹시 모를 상황에서도 의연하게 대처하는 코드를 작성하고 싶었습니다. 
- 앞으로 벌어질 사항들에 대해서 미리 생각하는 부분을 잘하려면 경험이 많아야 예상이 쉽게 되어질 수 있지만 현재 제 수준에서는 경험이 많이 부족하기에 예상할 수 있는 사항들이 많지 않아 추후에도 많이 수정하고 추가되어져야 할거라고 생각합니다. 그러나 지금부터라도 한 단계 한 단계 진행을 하면서 감을 잡아가는 것도 중요하게 생각되어졌기에 이번 프로젝트에서는 해당 부분에 중점을 두고 생각했습니다.

### 2. .DS_Store는 무엇인가?
>그리고 작성해주신 고민한 부분을 보며 궁금한 점이 생겼는데요.
>.DS_Store 파일을 왜 지금까지 발견할 수 없었는지, gitignore 파일이 무엇인지도 생각해보셨을까요?
다

### 1️⃣ .DS_Store 파일을 왜 지금까지 발견할 수 없었는지
- 기존에도 있었다면 보면서 의문을 품어서 기억에 남았을텐데 프로젝트를 진행하면서는 한 번도 본적이 없었습니다. 그래서 기존 프로젝트들을 다 뒤져보니 해당 프로젝트에서만 `.DS_Store`가 존재하는것을 확인했습니다.
- 그리고 혹시 몰라서 기존에 올려두었던 프로젝트들과 `TIL`을 검색해 보았더니 커리어스타트 캠프 시작하고 첫 주 두번째날  활동학습(4/25일)을 할 때 제꺼에서는 생성이 되고 같이 활동 학습을 진행했던 동기 시온에게서는 발생되지 않아서 해당 파일을 삭제했었던 적이 있었습니다. 그때는 해당 명령어로 삭제를 해줬었습니다.
```swift=
rm-rf .DS_Store
```
- 새벽에 븨븨께서 설명해주셔서 .DS_Store파일은 gitignore가 생기기 전에 이미 추적을 하고 있는 상황이었기 때문에 gitignore에 등록이 되어져 있더라도 추적을 하고 있는 상황이었다는 것을 알게 되었습니다. 삭제를 해주면 추후에는 생격나지 않는다는 것을 새롭게 배웠던 것 같습니다. 감사합니다 븨븨~

### 2️⃣ gitignore 파일이 무엇인지
- `.gitignore` 파일은 `Git` 버전 관리 시스템에서 사용되는 파일입니다. 
프로젝트 디렉토리 내의 특정 파일이나 디렉토리를 `Git`의 추적과 버전 관리에서 제외시키는 데 사용하는 파일로 주로 프로젝트의 설정 파일, 로그 파일, 컴파일된 바이너리 파일 등과 같이 버전 관리에 포함하지 않아도 되는 파일들을 지정하는 데 사용됩니다.

2023-07-27 18:53 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    var testData: TestDataManager!
- 해당 테스트를 통해서 검증하고 싶었던 것은 추후 `API`와 통신으로 데이터를 제대로 가져오는지를 검증하고 데이터를 올바르게 가져와진 상태에서 디코딩이 제대로 되는지 여부를 확인하고 싶었습니다.
아직 많이 부족해서 의도하는 바는 그랬지만 제대로 검증을 한 것인지는 잘 모르겠습니다.🥲
제가 아직 `UnitTest`를 작성하는데 있어서 미숙하고 부족하기에 어떻게 하면 `UnitTest`코드를 잘할 수 있는지에 대해 븨븨께 조언을 구하고자 했던 이유가 이 부분이었습니다. 
혹시 이 부분에 대해서 븨븨께서 도움을 주실 수 있을까요?

2023-07-27 19:00 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_API서버와의_통신으로_가져온_데이터가_5초안에_불러오고_Decoding이_잘되었는가() {
- 클라이언트 코드가 변경되지 않았음에도 테스트 결과가 달라지게 되는 상황이 어떤 상황인지 사실 잘 모르겠습니다. 어떤 부분에 중점을 두고 테스트코드를 작성해야되는지 나름 고민하고 작성을 했지만 의도된 부분이 제대로 된 것인지에 대한 것도 명확하지 않은 것 같습니다.😭

2023-07-27 23:48 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.setUp()
- 해당 부분 새벽에 피드백 해주셔서 왜 이런 질문을 하시게 되신건지 의도를 알게 되었습니다. `setUpWithError()`이 자동 완성으로 되는 부분인데 자동 완성 기능을 아직 수월하게 활용 하지 못해 하드코딩처럼 적어주다보니 `setUp()`메서드만 알고 있는 상황이었기 때문에 븨븨께서 의문이 드셨던 사항이라는걸 이해했습니다.😅

2023-07-27 23:53 UTC, karenyang835 commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
- 이 부분도 제가 공식문서를 꼼꼼하게 확인하지 않아서 `APIProtocol`이라는 프로토콜명이 동일하게 존재한다는것을 인지하지 못하고 네이밍을 해서 해당 프로토콜이 존재하는데 왜 또 명시를 해주게 되었는지 븨븨께서 의아하게 생각되게 해드린 것 같습니다.

2023-07-28 00:31 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    var testData: TestDataManager!
- 새벽에 시간 내주셔서 븨븨께서 설명해주셔서 조금은 `UnitTest`를 왜 해야되는지와 어느 부분에 대해서 테스트를 진행해야 되는지 이해하게 된 것 같습니다. 
감사합니다.🙇🏻‍♀️

2023-07-28 05:47 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_API서버와의_통신으로_가져온_데이터가_5초안에_불러오고_Decoding이_잘되었는가() {
- 새벽에 조언주신대로 클라이언트 상황 즉 내부에서 컨트롤할 수 없는 사항에 대해서 테스트를 진행하는 것이 아닌 현재 코드로 적용한 부분에 대해서 제대로 역할을 수행하고 있는지에 대해서 테스트 하는 코드로 수정하였습니다. 
현재로서 테스트할 수 있는 메서드는 총 3가지였고, 디코딩 관련된 역할이 주였고 해당 메서드가 원활하게 동작하는지 여부를 테스트할 수 있게끔 적용해보았습니다.

2023-07-28 09:29 UTC, YebinKim commented on BoxOffice/Model/GetDataAPI.swift
> +final class GetDataAPI: APIProtocol {
추후 사용할 네트워킹 모델을 설계하셨었군요!
해당 타입의 이름이나 메서드의 빈 내용을 봤을 때 프로토콜의 메서드를 기본구현하고자 사용한 것인지 다른 역할을 부여하고자 한 것인지 의문이 들어 질문드렸습니다 😄 설명 감사해요!

2023-07-28 09:31 UTC, YebinKim commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
앗 저는 `APIProtocol`이 이미 존재하는지는 몰랐습니다!
`APIProtocol`이 어디에 또 존재하고 있을까요?? 🤔

2023-07-28 09:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.setUp()
자동 완성으로 완성되기보다는 파일을 처음 생성했을 때 디폴트로 구현된 메서드가 `setUpWithError()` 라는 뜻이었습니다~
모든 버전에서 활용할 수 있는 메서드가 더 좋다는 점에는 공감하지 못 했지만 현재 예외처리를 활용하지 않기 때문에 `setUp()`을 사용할 수 있다는 점에는 공감했어요!

2023-07-28 10:35 UTC, YebinKim requested changes
카렌 안녕하세요~
Step1 수정까지 고생 많으셨습니다!

UnitTest에 대한 목표보다는 앞으로 벌어질 사항들까지도 미리 생각해두는 코드를 작성해보는 게 목표셨군요 😄
앞으로 벌어질 상황을 예측하고 대비하는 것은 말씀하셨다시피 경험이 많이 필요한 영역일 수도 있고 경험이 많더라도 예측을 잘 하기는 쉽지 않을 거 같아요.
그래서 미래에 생길지 아닐지 모르는 상황에 대비하기 위해서는 **어떤 요구사항이 들어와도 최소한의 수정으로 또는 빠르게 대처할 수 있도록 현재의 코드를 유지보수성 좋게 유지**하는 것이 개발자의 평생 과제인 거 같습니다 ☺️

또한, `.DS_Store` 파일과 `.gitignore` 파일에 대해서는 회의실에서 `Git`의 추적과 버전 관리가 어떻게 이루어지는지, 이번 프로젝트에서 이미 존재하고 있는 `gitignore` 파일이 어떤 역할을 하고 있었는지에 대해 충분히 얘기를 나눠볼 수 있었던 거 같습니다!

질문에 대해 확인하고 꼼꼼히 답글 남겨주셔서 고맙습니다 🙌😆

---

다만, 현재 디코딩 동작이 수행되지 않고 있어서 다시 한 번 Request Changes 를 요청드리게 되었는데요.
현재 데이터를 디코딩하는 테스트 케이스 함수는 모두 `XCTAssert` 메서드를 호출하기 전 guard에 의해 함수의 실행이 종료되고 있어서 테스트 케이스 자체는 성공하는 것 처럼 보이지만 실제로 테스트가 이루어지지는 않고 있는 것으로 보여요 👀

이를 잘 보기 위해 각 코드 라인이 어떻게 호출되었는지를 보여주는 *Code Coverage* 사진을 첨부합니다!
(빨간색 빗금 영역은 한 라인에서 일부 코드만 실행, 빨간색 영역은 해당 라인이 실행되지 않았다는 뜻)
<img width="864" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/15ca51ff-c061-4351-b085-d17ad1bda3b0">

어떤 부분에서 디코딩이 실패하는지를 알아보고 문제를 해결하는 게 필요해보여요 🛠️🔥

2023-07-28 10:35 UTC, YebinKim commented on BoxOffice/Controller/ViewController.swift
> +    var apiProtocol: MovieDataFetchable = MovieDataAPI()
p3;

추후 변경될 가능성이 있는 프로퍼티일까요? 👀
아니라면 `let` 을 사용하는 게 불필요한 변동 가능성을 막기에 좋을 거 같아요!

2023-07-28 10:35 UTC, YebinKim commented on BoxOffice/DataManager/DataManager.swift
> +    }
p3;

decodeData 메서드와 같이 매개변수와 제네릭을 활용하면 여러 타입에 대해서도 디코딩을 수행할 수 있게 되어 더 확장성 좋은 메서드를 만들 수 있지 않을까요? 🤔

2023-07-28 10:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +
p4;

불필요한 개행이 들어간 거 같아요 👀

2023-07-28 10:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.tearDown()
p2;

오버라이딩하는 메서드(`tearDownWithError()`)와 상위 호출하는 메서드(`tearDown()`)가 다른 거 같아요 👀

2023-07-28 10:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies = dataManager.decodeJSON() else { return }
p1;

디코딩이 제대로 수행되지 않아 guard 문에서 return 되기 때문에 테스트가 제대로 수행되지 않는 것으로 보여요 🤔

<img width="864" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/3877c348-623d-4d48-aac5-ced272ef4689">

2023-07-28 10:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies: DailyBoxOffice = dataManager.decodeData(DailyBoxOffice.self, from: itemsData) else { return }
p1;

마찬가지로 디코딩이 제대로 수행되지 않는 것으로 보여요 🤔

<img width="864" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/444b5415-6212-4628-9494-83294af00a49">

2023-07-28 12:48 UTC, karenyang835 commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
엇..제가 착각했네요. 어제 설명해주실 때 해당 프로토콜이 존재한다고 말씀해주신걸로 잘못 기억했습니다.  죄송합니다. 😭

2023-07-28 17:16 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +
불필요한 개행 삭제해주었습니다. 앞으로 조금 더 신경쓰도록 하겠습니다.
븨븨 덕분에 이런 부분도 놓치지 않는 습관을 들일 수 있을 것 같습니다.😊

꼼꼼한 리뷰 감사합니다. 븨븨~

2023-07-28 17:18 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        super.tearDown()
확인 후 수정해주었습니다.

2023-07-28 17:23 UTC, karenyang835 commented on BoxOffice/Controller/ViewController.swift
> +    var apiProtocol: MovieDataFetchable = MovieDataAPI()
추후에 변경될 가능성이 낮아보여 `let`로 변경을 해주고 외부에서 알지 않아도 될 것 같아서 `private`로 선언해주었습니다. 또한 `DataManager`도 프로퍼티로 추가해주고 `private`로 선언해주었습니다.

2023-07-28 17:27 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies = dataManager.decodeJSON() else { return }
해당 부분 수정해주었습니다.
왜 자꾸 `else`문으로 빠져나가는지 무엇이 잘못 된 건지 원인을 알 수가 없어서 한참 헤멨던것 같습니다.🥹

확인해보니 `boxOfficeType`을 다른 변수명들과 맟줘추면서 생겨난 부분으로 해당 부분을 `CodingKey`로 변환하는부분을 추가해서 테스트가 원활하게 되도록 수정하였습니다.

그래도 이번에 하나 하나 찾아보고 검토해보면서 코드작성이나 오류 찾아가는 것과 `UnitTest`부분을 이해하는데 한걸음 성장한 것 같습니다.

2023-07-28 17:28 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies: DailyBoxOffice = dataManager.decodeData(DailyBoxOffice.self, from: itemsData) else { return }
이 부분도 위의 문제점을 해결하자 원활하게 동작하였습니다.😁

2023-07-28 18:39 UTC, karenyang835 commented on BoxOffice/DataManager/DataManager.swift
> +    }
븨븨께서 조언해주신대로 매개변수와 제네릭 타입을 활용해서 `decodeJSON()`수정해 보았습니다. 해당 메서드에는 미처 적용할 생각을 못했는데 이렇게 븨븨꼐서 조언해 주셔서 이번에 많이 배운 것 같습니다. 감사합니다 븨븨~🙇🏻‍♀️

2023-07-30 13:10 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies = dataManager.decodeJSON() else { return }
이럴 때 테스트 케이스가 실패하는 것으로 나왔더라면 훨씬 더 문제를 일찍 발견할 수 있었을 거 같아요!
테스트 케이스에서는 guard 구문으로의 탈출을 활용하지 않는 게 어떨지 생각해보면 어떨까요?

2023-07-30 13:20 UTC, YebinKim commented on BoxOffice/Protocol/APIProtocol.swift
> +protocol APIProtocol {
아하 그렇군요! 수정에 대한 근거는 오직 Swift API Design Guidelines 를 따른 네이밍을 함으로써 프로토콜의 역할을 더 잘 전달하는 것이었습니다 😄
제가 한 번에 여러가지를 전달드리느라 혼선이 있었나보네요 ㅎㅎ

2023-07-30 13:35 UTC, YebinKim approved these changes
카렌 안녕하세요~
Step1 수정까지 다시 한 번 고생 많으셨습니다! 👏👏

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="356" alt="step1" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/2d8da686-2c73-42b0-9fa4-146cf6c74129">

스텝의 핵심 경험이 모두 충분히 경험되었다고 생각되어 이번 스텝은 여기서 머지하겠습니다 😄
코드 커버리지도 각각 100%를 달성하고 있네요!!
<img width="860" alt="스크린샷 2023-07-30 오후 10 23 16" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/757e59d8-8086-43c0-b01c-8e97b4098cdd">


그리고 이전 스텝에서 디코딩이 실패한다는 사실을 테스트 케이스를 통해 빠르게 알아볼 수 있었다면 더욱 테스트를 잘 활용할 수 있는 방법이라는 생각이 드는데요.
코멘트로도 말씀드리긴 했지만 앞으로 **테스트 케이스에서는 메서드가 단순히 리턴되는 상황을 지양**해보면 어떨지 제안드려봅니다!

Step1 고생 많으셨어요 🚀✨

2023-07-30 13:35 UTC, YebinKim commented on BoxOffice.xctestplan
> +{
p4;

테스트플랜 파일을 추가하셨군요!
현재는 테스트와 관련 없는 폴더까지 포함된 최상위 파일 경로에 놓여져있는 걸로 보여서 더 적절한 위치로 옮겨보면 어떨까요? 👀

<img width="262" alt="스크린샷 2023-07-30 오후 10 21 59" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/fe0264c2-52e3-4f89-b07e-f61b527b56ce">

2023-07-30 13:35 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +    override func tearDownWithError() throws {
질문;

`setUp()` 메서드에 대해 얘기를 나눌 때, 오류가 발생할 가능성이 현재 없기 때문에 `setUpWithError()`를 사용하지 않고 `setUp()` 메서드를 사용하는 결정을 했었는데요.
해당 메서드는 오류의 발생 가능성을 염두에 두고 `tearDown()` 이 아닌 `tearDownWithError()` 로 결정하시게 된 걸까요?? 🤔

`setUp()` 메서드를 활용했을 때와 달라진 결정이라 생각되어 질문드려요!

2023-07-30 13:37 UTC, merged

2023-07-30 14:25 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        guard let decodedMovies = dataManager.decodeJSON() else { return }
되도록 `guard`문을 활용하지 않고 테스트할 수 있는 방법을 생각해보도록 하곘습니다.

테스트를 진행했을 테스트완료가 되어서 당연히 테스트가 잘 진행되었다고 생각했는데 븨븨께서 찍어주신 스샷을 보고 `Coverage`를 확인해서 찾아낼 수 있었습니다.

븨븨 덕분에 이번에 `UnitTest`에 대해 많이 알게 된 것 같습니다.
감사합니다 븨븨!

2023-07-30 14:29 UTC, karenyang835 commented on BoxOffice.xctestplan
> +{
`BoxOfficeTests`폴더에 함께 넣어주겠습니다. 감사합니다 븨븨!

2023-07-30 14:50 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    override func tearDownWithError() throws {
이 부분은 제가 깊게 고민하지 않고 코드를 작성해서 발생된 것 같습니다.🥲

자꾸 코드의 방향성이 갈피를 못잡고 가게 된 것 같습니다.
`Step02`를 진행할때는 조금 더 생각하고 구조를 잡아서 진행해보도록 하겠습니다.

이런 부분 짚어주셔서 감사합니다. 븨븨~