박스오피스 [STEP 2] Erick, kyungmin
yagom-academy/ios-box-office pull request #75
Opened 2023-07-27 02:56 UTC by YaRkyungmin

안녕하세요 July!!
리뷰이 Erick🐶, Kyungmin🐼 입니다!
박스오피스 두번째 PR입니다!
이번에도 많은 조언 해주시면 감사하겠습니다🙇‍♂️

## 📚 학습내용
### 1️⃣ URL 의 구조는 어떻게 되는가? 
**URL 구조**
- **Scheme**: 프로토콜
- **Host**: 서버의 호스트 이름
- **Path**: 서버 경로
- **Query**: 추가적인 파라미터

```swift
var url = URL(string: "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?&key=mykey&targetDt=20230725")
url?.scheme // http
url?.host   // kobis.or.kr
url?.path   // /kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json
url?.query  // &key=mykey&targetDt=20230725
```

### 2️⃣ HTTP method의 종류와 쓰임 
- **GET**: 서버로 부터 리소스 받음
- **POST**: 서버에 새로운 리소스를 게시
- **PUT**: 서버 내 리소스의 모든 데이터를 업데이트
- **PATCH**: 서버 내 리소스의 일부를 업데이트
- **DELETE**: 서버 내 리소스 삭제

```swift
var request = URLRequest(url: url)
request.httpMethod = // HTTP method
```
- `url`을 이용해 `URLRequest`를 만들어 `request`에 `httpMethod`를 추가할 수 있습니다.

### 3️⃣ Test Double의 종류인  mock spy stub dummy는 무엇인가 ?
- **mock**: 실제 객체와 비슷하게 구현되어 있으며 `행위 기반 테스트(Behavior Base Test)`를 위해 사용되는 객체, 예상되는 행위에 대한 시나리오를 만들어 그에 따라 테스트를 진행합니다.
- **spy**: `Stub`의 역할을 가지면서 호출된 내용을 기록하는 객체, 호출 여부나 횟수 등을 기록할 수 있습니다.
- **stub**: `Dummy`가 실제로 동작하는 것처럼 만들어 실제 코드를 대신해서 동작해 주는 `상태 기반 테스트(State Base Test)`를 위해 사용되는 객체, 테스트가 어려운 부분의 객체를 대체하여 역할을 최소한으로 구현한 객체입니다.
- **dummy**: 가장 기본적인 테스트 더블로서 실제로 동작하는 기능이 구현되어 있지 않은 객체, 객체를 전달하는 용도로 사용됩니다.

> `상태 기반 테스트`는 메서드를 호출하고 그 결괏값과 예상 값을 비교하는 식으로 동작하는 테스트이고, `행위 기반 테스트`는 예상되는 행위들에 대한 시나리오를 만들어 놓고, 시나리오대로 동작했는지에 대한 여부를 확인하는 테스트입니다.

## 🤔 고민했던 점
### 1️⃣ NetworkManager 타입 설계
요구사항을 확인했을때, 
>- 이번 스텝에서 진행할 네트워킹 요소
>   - 오늘의 일일 박스오피스 조회
>   - 영화 개별 상세 조회

위와 같이 두가지의 다른 데이터를 받아와야 했습니다. 하지만 네트워킹을 하는 객체에서 `loadBoxOffice()`, `loadMovie()`와 같이 데이터를 나눠 가져오는 것은 좋지 않다고 생각하였습니다. 
`url`이 다를때도 네트워킹을 할 수 있는 하나의 객체를 만들었고, 그 객체에 `url`을 나눠 넣어주거나 `decoding`할 타입을 나눠 넣어주는 것은 다른 객체에서 해야하는 작업이라고 생각했습니다.
따라서 `NetworkManager`는 아래와 같이 세가지 기능을 가지고 있게 설계했고, 추후에 NetworkManager가 어떻게 쓰일지를 고민하여 `URLQueryItems`를 만들어 주는 기능을 추가 할 예정입니다. 

✨`func configuredURL(scheme: String, host: String, path: String, queryItems: [URLQueryItem]) -> URL?` 
: ❗️`scheme`, `host`, `path`, `queryItems`를 통해 `URL`을 만들어 주는 기능

✨`func startLoad(_ url: URL, completion: @escaping (Data?) -> Void` :
: ❗️`URL`받아 데이터를 받아와 데이터를 반환해주는 기능

✨`func decodeJSON<T: Decodable>(data: Data) -> T?` :
: ❗️`Data`를 받아 `JSON`으로 디코딩 해주는 기능

### 2️⃣ TestDouble
네트워크가 연결되지 않은 상황에서 `NetworkManager`의 테스트를 하기 위해 `TestDouble` 객체 `StubUserSession`을 만들어주어 데이터를 받아오는 `startLoad`가 정상적으로 작동하는지 테스트 했습니다.

**의존성 주입**
```swift
// 실제 NetworkManager 생성
NetworkManager(urlSession: URLSession.shared)
// 테스트 NetworkManager 생성
NetworkManager(urlSession: StubURLSession())
```
- `URLSessionProtocol`을 만들어 `NetworkManager`가 프로퍼티로 해당 타입을 가지고 있도록 하여 `URLSession`뿐만 아니라 `StubURLSession`을 주입할 수 있도록 하여 테스트했습니다.

**테스트**
```swift
// given
// 받아올 데이터를 임의로 생성
let dummy = DummyData(data: data, response: response, error: nil)
let stubUrlSession = StubURLSession(dummy: dummy)
sut?.urlSession = stubUrlSession

// when
sut?.startLoad(url!, completion: { data in
    // then
    // startLoad로 받아온 데이터는 DummyData의 데이터
    XCTAssertEqual(data, dataAsset.data)
    expectation.fulfill()
})
```
- `StubURLSession`는 `DummyData`를 가지고 `dataTask` 메서드를 실행시 `StubURLSessionDataTask`을 이용해서 `DummyData`만 던져주도록 구현했습니다.
    

## 🙇‍♂️ 조언을 얻고싶은 점

### 🔑 API KEY 관리
`APIKey`는 공용`repository`에 가지고 있으면 안되고, `private`하게 관리 돼야 한다고 생각했습니다. 그래서 `.gitignore`에 `.xcconfig`를 추가 시켜줬습니다. 
하지만 로컬에서 API config 파일을 추가했을때 `project.pbxproj`에 생기는 파일경로를 `commit`해줄 때마다 `unstage`해주어야 했습니다.
이런식으로 `APIKey`를 관리하는 것이 괜찮은지, 주로 어떻게 `APIKey`를 관리하는지 조언을 얻고 싶습니다🙇

---
### 📚 참고 링크
- [🍎Apple: URLSession](https://developer.apple.com/documentation/foundation/urlsession)
- [🍎Apple: URL](https://developer.apple.com/documentation/foundation/url)
- [🍎Apple: Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)
- [🐻야곰닷넷: Unit Test](https://yagom.net/courses/unit-test-작성하기/)

2023-07-27 09:44 UTC, July911 requested changes

2023-07-27 09:44 UTC, July911 commented on .gitignore
> +*.xcconfig
https://medium.com/@nishant.kumbhare4/working-with-the-xcode-configuration-xcconfig-file-75418d1554af

2023-07-27 09:44 UTC, July911 commented on BoxOffice.xcodeproj/project.pbxproj
> +						CreatedOnToolsVersion = 14.3.1;
생성한 버전인데 지금까지는 왜 없었고 왜 생긴건가요 ?

2023-07-27 09:44 UTC, July911 commented on BoxOffice/Model/NetworkManager.swift
> +    func decodeJSON<T: Decodable>(data: Data) -> T? {
네트워크 매니저가 decode도 해주나요  ?

2023-07-27 09:44 UTC, July911 commented on BoxOffice/Model/NetworkManager.swift
> +    var urlSession: URLSessionProtocol
추후에 network 매니저가 교체되나요 ?

2023-07-27 09:44 UTC, July911 commented on BoxOffice/Model/NetworkManager.swift
> +        return urlComponents.url ?? nil
urlComponents.url 은 이미 'URL?' 타입아닌가요 ? 
?? nil의 의도는 무엇인지 설명해주세요.

2023-07-27 09:44 UTC, July911 commented on BoxOffice/Model/NetworkManager.swift
> +                completion(nil)
어떤 에러가 나든  nil을 받는건가요 ?

2023-07-27 09:44 UTC, July911 commented on BoxOffice/Model/TestDouble/StubURLSession.swift
> +    init(dummy: DummyData) {
(dummy: DummyData?) 이렇게가 아니라 
꼭 지금처럼 해야했나요 ?

2023-07-28 02:03 UTC, h-suo commented on BoxOffice.xcodeproj/project.pbxproj
> +						CreatedOnToolsVersion = 14.3.1;
새로운 테스트 파일을 추가하는 과정에서 `14.3.1` 버전의 Xcode로 생성했기 때문에 생기는 코드입니다.

2023-07-30 04:53 UTC, h-suo commented on BoxOffice/Model/NetworkManager.swift
> +    func decodeJSON<T: Decodable>(data: Data) -> T? {
받아온 데이터를 디코딩하거나 처리해주는 `DataManager` 객체를 만들어 `decode`로직을 추가했습니다!

2023-07-30 04:54 UTC, YaRkyungmin commented on BoxOffice/Model/NetworkManager.swift
> +    var urlSession: URLSessionProtocol
`private let` 으로 수정했습니다☺️

2023-07-30 04:54 UTC, YaRkyungmin commented on BoxOffice/Model/NetworkManager.swift
> +        return urlComponents.url ?? nil
빼줬습니다🤣😂

2023-07-30 04:55 UTC, h-suo commented on BoxOffice/Model/NetworkManager.swift
> +                completion(nil)
`NetworkError`와 `DataError`를 만들어 에러 처리를 해줬습니다!

2023-07-30 04:57 UTC, YaRkyungmin commented on BoxOffice/Model/TestDouble/StubURLSession.swift
> +    init(dummy: DummyData) {
꼼꼼하게 체크했었어야 했는데 실수가 많았던것 같습니다😭 수정했습니다🫡

2023-07-31 01:18 UTC, merged