박스오피스 [STEP 2] Yetti, Maxhyunm
yagom-academy/ios-box-office pull request #77
Opened 2023-07-28 04:05 UTC by iOS-Yetti

안녕하세요 델마!(@delmaSong)
step2부터 너무 어려웠네요 ㅠㅠ 
부족하지만 잘 부탁드립니다!!

## 고민했던 점
### 1. `ATS 설정 추가`
영화진흥위원회의 API 요청 URL은 https가 아닌 http로 안내되어 있어서, 해당 URL로 네트워킹을 시도하면 연결 오류가 발생하였습니다. 이에 따라 info.plist에 App Transport Security Settings를 추가하여 kobis.or.kr과 그 하위 도메인들을 모두 Exception Domains로 처리하여 주었습니다.
![](https://hackmd.io/_uploads/Hkj4Tsgjh.png)

### 2. `API KEY의 gitignore 처리`
API Key는 아무나 접근할 수 없게 만들어야하기 때문에 깃허브에 그대로 올리면 안됩니다. 저희는 API Key를 gitignore 처리하기 위하여, git에 추적되지 않을 PrivateData.xcconfig이라는 설정파일을 생성하였습니다. 그 내부에 API_KEY 항목을 생성하여 네트워크 호출에 필요한 키를 입력하였습니다.
![](https://hackmd.io/_uploads/SJDN1hej3.png)

그 후 해당 환경설정 파일을 프로젝트 info의 Configurations 설정에 추가를 해주었습니다.
![](https://hackmd.io/_uploads/rkx6y3xs3.png)

마지막으로 앱 내부에서 해당 값을 딕셔너리 형태로 접근할 수 있도록 info.plist에 API_KEY 항목을 추가하였습니다.
![](https://hackmd.io/_uploads/HJr-ehes2.png)

### 3. `@escaping 클로저 활용`
NetworkingManager의 load 메서드를 호출한 위치에서 dataTask를 통해 받아 온 데이터를 사용하기 위해, 처음에는 두 타입을 델리게이트로 연결하여 전달하는 등의 방법을 생각했습니다. 하지만 @escaping 클로저를 활용하면 훨씬 편하게 처리할 수 있겠다는 생각이 들어, 해당 방식으로 수정하여 진행하였습니다.
@escaping 클로저의 파라미터값으로는 Result타입을 활용하였습니다. Result는 성공/실패 두 가지 가능성에 대한 데이터타입을 따로 지정해줄 수 있어 CompletionHandler에 활용하기에 적절하다고 판단했습니다.
```swift
func load(_ urlString: String, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) {
    guard let url = URL(string: urlString) else {
        return
    }

    let task = session.dataTask(with: url) { data, response, error in
        if error != nil {
            completion(.failure(BoxOfficeError.connectionFailure))
            return
        }
        ...
```

## 조언을 얻고 싶은 점
### 1. `Test Double에 관한 질문`
인터넷 연결이 없는 상태에서 네트워크 통신을 테스트하기 위해 Test Double을 생성하였습니다. 이를 통해 네트워킹이 성공했을 때와 실패했을 때를 테스트했습니다. 테스트 자체를 성공시키긴 했지만, 몇 가지 궁금한 점이 생겨 질문 드리고 싶습니다!
#### 1-1. 두 가지 다른 response에 대한 테스트 진행시 새로운 세션을 생성해야 하는 점
각 테스트에서 다른 점은 성공했을 시에는 데이터를 받아오고 status code가 200이어야했고 실패했을 시에는 받아오는 데이터가 없고 에러를 뱉어야 했습니다. 해당 조건들을 만족시키기 위해 `setUpWithError()`에서는 성공에 대한 테스트만 초기화해주었고 네트워킹 실패 테스트에 대한 초기화는 실패 테스트 내부에서 이루어지고 있었기 때문에 `setUpWithError()`을 거친 후 실패 테스트로 들어가게 되면 한번 더 세션이 생성되어 비효율적으로 느껴졌습니다. `setUpWithError()`에서 성공, 실패 케이스를 모두 테스트할 수 있도록 초기화할 수 있는 방법이 있는지 궁금합니다.

#### 1-2. 테스트를 위한 URLSessionProtocol로 인한 경고 발생
URLSessionProtocol을 생성하여 실제 URLSession과 Test용 Stub 타입이 모두 이를 채택하도록 구현하였습니다. 이때 실제 URLSession에 아래와 같은 경고가 발생하였습니다.
![](https://hackmd.io/_uploads/BJeZG3lin.png)
이에 대한 해결책으로 CompletionHandler typealias에 @Sendable을 채택하여 동시성처리에 문제가 없음을 명시하면 된다는 내용을 확인하여 추가하였는데, 올바른 해결법인지 궁금합니다...!

#### 1-3. 테스트 더블로 만든 StubURLSessionDataTask에서 경고 발생
테스트용으로 dummyResponse 객체를 전달받도록 만든 StubURLSessionDataTask의 init에서 아래와 같은 경고가 발생하였습니다.
![](https://hackmd.io/_uploads/r1oUG3lj2.png)
그런데 찾아보니 NSURLSession은 Objective-C에서 사용되는 클래스인 것으로 보였습니다. 이 부분에 대한 해결법을 찾지 못해 일단 그대로 두었습니다. 혹시 델마께서는 해결 방법을 알고 계실까요😭?

2023-07-29 06:35 UTC, delmaSong requested changes
수고많으셨습니다.
우선적으로 테스트가 제대로 동작하지 않는 부분이 있어, 아래 코멘트 확인 부탁드리겠습니다.

질문 주신 사항에 대한 답변입니다.
1-1.
해당 상황은 setUpWithError() 내에서 수행하고 있는 역할들을 별도의 메서드나 객체로 분리하고, 성공이냐 실패냐를 인자로 받은 후 원하는 값을 반환하도록 하여 처리하는 건 어떨까요?

1-2.
코멘트 확인 부탁드려요.

1-3.
`StubURLSessionDataTask`가 상속받고 있는 `URLSessionDataTask`의 생성자 자체가 deprecated 된 걸로 보여지네요.

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/BoxOfficeError.swift
> +
케이스명을 보니 BoxOffice와 연관은 크게 높은 것 같지 않은데,
좀 더 적절한 이름으로 열거형 이름을 수정하는 게 어떨까요?

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/MovieDetailEntity.swift
> +        let movieInformation: MovieInformation
단순 궁금증인데요,
`MovieInformationResult`에서 Result가 무슨의미인가요?
영화정보결과 라고 했을 때 딱히 와닿거나 머리에 그려지는 게 없어서, 설명을 해주실 수 있을까요?

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/NetworkingManager.swift
> +    func load(_ urlString: String, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) {
제너럴하게 사용 가능한 `NetworkingManager`로 보여지는데, `load` 메서드의 실패 결과로 내뱉는 게 `BoxOfficeError`는 좀 어울리지 않는 것 같네요 ㅎㅎ

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/URLSessionProtocol.swift
> +typealias CompletionHandler = @Sendable (Data?, URLResponse?, Error?) -> Void
무슨 CompletionHandler인지 이름에 쫌 더 표현이 되면 좋을 것 같습니다!

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/URLSessionProtocol.swift
> +typealias CompletionHandler = @Sendable (Data?, URLResponse?, Error?) -> Void
`@Sendable`은 어떤 역할을 하고, 여기서는 어떤 의도로 사용하신건지 설명해주실 수 있을까요?

2023-07-29 06:35 UTC, delmaSong commented on BoxOfficeTests/BoxOfficeNetworkingTest.swift
> +                return
응답이 failure로 반환되었을 때에도 테스트가 의도대로 동작하지 않았다는 걸 바로 알 수 있게 `XCTFail()`을 호출해주는 편이 어떨까요?

2023-07-29 06:35 UTC, delmaSong commented on BoxOfficeTests/BoxOfficeNetworkingTest.swift
> +            switch result {
expectation에 아무런 상관 없는 단어(ex. 가나다라) 같은 걸 입력해도 테스트가 성공하네요.
load 내에서 dataTask까지 호출되지 않고 반환되고 있는데, 이 부분 수정이 필요해보입니다.

2023-07-29 06:35 UTC, delmaSong commented on BoxOffice/Model/URLSessionProtocol.swift
> +typealias CompletionHandler = @Sendable (Data?, URLResponse?, Error?) -> Void
`@Sendable`을 사용하시게 된 건 pr description에 설명해주셨네요, `@Sendable`이 어떤 역할을 하는건지, 왜 이 시점에 해당 키워드를 통해서 문제해결이 된 건지에 대해 좀 더 설명해주실 수 있을까요?

2023-07-31 08:36 UTC, iOS-Yetti commented on BoxOffice/Model/BoxOfficeError.swift
> +
네트워킹에 관한 에러처리만 담당하고 있기 때문에 `NetworkingError`로 네이밍 수정해주었습니다.

2023-07-31 08:36 UTC, iOS-Yetti commented on BoxOffice/Model/MovieDetailEntity.swift
> +        let movieInformation: MovieInformation
이 부분은 사실 단순히 영화진흥위원회 API를 가져올 때 `MovieInfoResult`라는 네이밍의 키를 풀어서 적어준 것입니다😅 조금 더 적절한 네이밍을 고려하다가 `MovieDetailData`라는 이름으로 수정하였습니다!

2023-07-31 08:37 UTC, maxhyunm commented
안녕하세요 델마(@delmaSong)! 주말에도 PR을 확인해주시고, 리뷰 남겨주셔서 너무나 감사드립니다!
델마의 코멘트를 보고 `URLSessionDataTask` 이슈를 해결할 수 있는 방안을 찾다가 `URLProtocol`을 활용하여 테스트를 작성하는 방법을 발견하였습니다! 이 내용을 시도해보고 싶지만, 공부해보지 못한 내용이 포함되어 있어 시간이 다소 소요될 것 같습니다😭! 프로젝트 요구사항에서 테스트 작성은 2-1 도전 과제로, 시간 내에 완료하지 못할 것 같다면 일단 다음 스텝을 진행 후 추후 다시 시도해보라는 코멘트가 달려 있었기 때문에 고민이 됩니다. 지금 테스트를 다시 작성하는 것이 맞을지, 아니면 일단 다음 내용을 진행하고 추후에 테스트 수정을 진행하는 것이 좋을지 델마의 의견을 여쭤보고 싶습니다!

2023-07-31 08:37 UTC, iOS-Yetti commented on BoxOffice/Model/NetworkingManager.swift
> +    func load(_ urlString: String, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) {
`NetworkingError`로 네이밍을 수정함으로 해결해 주었습니다!

2023-07-31 08:37 UTC, iOS-Yetti commented on BoxOffice/Model/URLSessionProtocol.swift
> +typealias CompletionHandler = @Sendable (Data?, URLResponse?, Error?) -> Void
`NetworkingCompletionHandler`로 명칭 변경하였습니다!

2023-07-31 08:37 UTC, iOS-Yetti commented on BoxOffice/Model/URLSessionProtocol.swift
> +typealias CompletionHandler = @Sendable (Data?, URLResponse?, Error?) -> Void
`@Sendable`은 해당 타입이나 메서드가 동시성 처리가 가능함을 명시해주는 것으로 알고 있습니다! 이를 통해 코드를 볼때 바로 동시성 처리가 필요한 부분임을 명확히 보여줄 수 있으며, 동시성/비동기 처리를 진행할 때 안정성을 확보할 수 있습니다.

2023-07-31 08:37 UTC, iOS-Yetti commented on BoxOfficeTests/BoxOfficeNetworkingTest.swift
> +                return
`XCTFail()` 추가하여 테스트 성공 외의 케이스에는 실패를 호출하도록 했습니다!

2023-07-31 08:38 UTC, iOS-Yetti commented on BoxOfficeTests/BoxOfficeNetworkingTest.swift
> +            switch result {
이 부분은 `load()`에서 빈 url을 넘기고 있는 점, `mimeType` 비교시 nil값과 비교가 되는 점 두 가지 이유인 것으로 확인하였습니다! `mimeType`의 경우 테스트용 `HTTPURLResponse`에서 따로 값을 지정해주는 방법을 찾지 못하여 일단 `mimeType` 비교 부분을 제외하였습니다 😭

2023-08-01 14:19 UTC, merged

2023-08-01 14:20 UTC, delmaSong commented
네 말씀해주신대로 해당 구현은 요구사항 자체에서 옵셔널인 부분이라 다음 스텝이 더 우선순위가 높다고 판단됩니다!
수고 많으셨어요, 다음 스텝에서 만나요!