박스오피스 [STEP2] Zion, Hemg
yagom-academy/ios-box-office pull request #78
Opened 2023-07-28 07:33 UTC by LeeZion94

# STEP 2
## 박스오피스

안녕하세요 올라프(@1Consumption)!
박스오피스 STEP2 구현을 진행했습니다.
부족하지만 잘부탁드립니다.

## 고민했던 점
### 범용적으로 사용될 수 있는 Network 로직만들기
- BoxOffice에서도 여러가지의 API들을 호출할 수 있도록 혹은 다른 BaseURL이 호출되더라도 정보를 받아올 수 있도록(GET) 네트워크로직을 설계했습니다.
    
    현재 NetworkKey, BaseURL, BoxOfficeURLPath, API~등 여러가지 타입들을 둬서 앞으로의 여러가지 종류에 API 호출에 대응하고 decoding해 올바르게 ResponseData를 받아 올 수 있도록 만들었습니다.
    
### 네트워크 요청 실패를 알리기 위한 방법
- 인터넷 연결이 불안정한 상태에서 사용자에게 네트워크 요청이 실패했다는 것을 알려주는 팝업을 노출시키기로 했습니다.

    네트워크 로직의 특성상 인터넷 연결이 불안정하다면 사용자가 원하는 데이터를 일정 시간내에 전달받지 못하는 경우가 존재합니다. 그렇게 되는 경우 사용자로 하여금 네트워크 요청이 실패했다는 것을 알려주는 팝업을 노출시키고 네트워킹을 재시도 할 수 있는 선택지를 두어 네트워크 연결을 재시도할 수 있게 설계했습니다.

----

### 코드 재사용성 늘리기
```swift
    let url = "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"
    let apiKey = "f5eef3421c602c6cb7ea2241047958"
    let targetDate = "20230722"
        
    let currentURL = testURL(url: url, apiKey: apiKey, targetTitle: "targetDt", target: targetDate)        
officeURL.dailyBoxOfficeSession(target: currentURL!)

    func testURL(url: String, apiKey: String, targetTitle: String, target: String) -> URL?
```

```swift
let queryItems: [String: Any] = [
            "key": NetworkKey.boxOffice,
            "movieCd": "20218541"
        ]
        
let request = APIRequest(baseURL: BaseURL.boxOffice, path: BoxOfficeURLPath.movieDetail, queryItems: queryItems)
   
struct APIRequest {
    let baseURL: String
    let path: String?
    let queryItems: [String: Any]?
}    
```
- 데이터를 요청을 진행할때에 함수내에서 URL, Key, TargetData 등 요청인터페이스를 그때마다 설정하여 요청을 진행했는데 반복되는 코드가 생기는점이 있어 반복되는점을 수정하여 고정된 값은 재사용하며, 변경되어야할 값만 변경하여 요청할수있게 범용적으로 진행했습니다.

2023-07-30 15:41 UTC, 1Consumption requested changes
고생하셨습니다. 코멘트를 참고해주세요.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.0;
왜 타겟을 올리셨나요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice.xcodeproj/xcuserdata/hyungminlee.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +               </Location>
이 변경사항들은 무엇을 의미하나요? 의도된 변경사항이 맞을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/App/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
스토리보드를 사용하지 않은 이유는 무엇인가요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Info.plist
> +	</dict>
이 key value를 추가해준 이유는 무엇인가요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
프로토콜로 빼준 이유가 무엇인가요? 프로퍼티 이름이 `우연히` 중복되는 것 외에는 별다른 이유를 찾지 못하겠는데요.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
네스티드 타입도 좋긴한데, 이렇게 하나의 타입이 너무 길어지니까 읽기 힘드네요. 굳이 네스티드타입을 사용해야하는 이유가 있을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +            let actors: [Actor]
이건 개인적인 생각인데, swift에서는 이미 `actor`라는 이름을 선점하고 있습니다. 그러니 다른 이름을 고려해보는 것도 좋겠습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/API.swift
> +}
이건 그냥 `Result`타입을 사용하면 되지 않을까요? 굳이 따로 만들어준 이유가 있을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/API.swift
> +    }
`description` 이라는 프로퍼티 이름은 [`CustomStringConvertible`](https://developer.apple.com/documentation/swift/customstringconvertible)에서 선점한 이름입니다. 다른 이름을 고려해보는건 어떨까요? 또한 이런 경우에는 [`localizedError`](https://developer.apple.com/documentation/foundation/localizederror) 채택을 고려해봐도 좋겠습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/BaseURL.swift
> +}
네임스페이스가 필요하다면 enum을 고려해도 좋겠습니다. 또한 `/kobisopenapi/webservice/rest` 까지는 중복이니까 BaseURL에 들어가는게 맞아보여요.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/BaseURL.swift
> +    static let boxOffice = "a38f2bee3ae1dc5696060047ce83c935"
key를 이렇게 막 올려도 될까요? 만약 제가 이 key를 가지고 허용된 응답 횟수를 초과해서 보내면 여러분들이 이 key를 사용할 수 있을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +final class URLSessionProvider {
class로 만들어준 이유가 있을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +    static func requestData<T: Decodable>(_ request: APIRequest, _ completionHandler: @escaping (APIResult<T>) -> Void) {
static인 이유가 있을까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +        }
`String`을 `URL`로 만들어주는 역할도 `setUpRequestURL(_:_:)`메소드의 역할 같습니다. 굳이 여기서 두번 처리할 필요는 없어보여요.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +            }
contians로 값 포함 여부를 알 수도 있는데, ~= 오퍼레이터를 통해 알 수도 있습니다.
``` swift
guard let (200..<300) ~= httpResponse.statusCode else {
    return
}
```

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +            decodeResponseData(data, completionHandler)
데이터를 decode 해주는 것도 `URLSessionProvider`의 역할일까요? 혹시 한번에 두개의 역할을 하고 있는건 아닐까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +        dataTask.resume()
이 `dataTask`를 취소하려면 어떻게 해야할까요?

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +    }
이미 `URLComponents`를 사용하고 있는데, 굳이 `APIRequest`라는 타입을 만들어준 이유를 잘 모르겠습니다. 하는 역할도 다르지않고요. 매번 새로운 타입을 만들려고 하지말고, apple에서 제공해주는 타입을 먼저 사용하는 것을 지향하면 좋겠습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/Protocol/CanShowNetworkRequestFailureAlert.swift
> +}
그냥 `UIViewController`의 extension으로 만들어도 되지 않을까요? 따로 프로토콜로 분리한 이유가 궁금합니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        button.addTarget(self, action: #selector(didTappedRequestMovieDetailInformationButton), for: .touchUpInside)
`addTarget` 대신 [`addAction(_:for:)`](https://developer.apple.com/documentation/uikit/uicontrol/3600490-addaction) 메소드를 사용하면 `@objc` 어노테이션을 없앨 수 있습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        button.addTarget(self, action: #selector(didTappedRequestMovieDetailInformationButton), for: .touchUpInside)
touchUpInside는 어떤 경우에 발생하는 이벤트인가요? 이 외에 다른 이벤트들도 더 알아보면 좋겠습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +}
이런 자세한 로직 정보를 ViewController에서 알아야할까요? 저는 view는 멍청해야한다고 생각하는 편입니다. 따라서 이런 정보를 알고있는 객체를 따로 분리하고, ViewController는 해당 객체의 인터페이스를 호출하는 식으로 진행되면 좋겠습니다.

2023-07-30 15:41 UTC, 1Consumption commented on BoxOfficeTests/BoxOfficeTests.swift
>  }
이 변경사항은 뭔가요? 항상 확인하고 커밋하는 습관을 들여주세요.

2023-07-31 08:38 UTC, LeeZion94 commented on BoxOffice.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.0;
```swift
'init()' was deprecated in iOS 13.0: Please use -[NSURLSession dataTaskWithRequest:] or other NSURLSession methods to create instances
```
URLSessionDataTask를 상속받은 TestDouble 객체를 만드는 과정에서 이미 deprecated된 init의 버전을 확인하고 다시 돌리는 과정에서 Test Code가 반영되었습니다. 의도된 수정사항은 아니므로 다시 바꿔두겠습니다.

2023-07-31 08:41 UTC, LeeZion94 commented on BoxOffice.xcodeproj/xcuserdata/hyungminlee.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +               </Location>
<img width="431" alt="image" src="https://github.com/yagom-academy/ios-box-office/assets/24710439/dd794021-a984-40aa-831a-599362bbf40e">

xcode 상에서 사용했던 디버깅포인트가 가지고 있던 정보들이 추가되었습니다. 의도된 변경사항이 아닙니다.
주의하겠습니다.

2023-07-31 08:44 UTC, LeeZion94 commented on BoxOffice/App/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
스토리보드로 진행하더라도 순서에 맞게 진행하는 페어프로그래밍 특성상 문제가 되지않았을 것이라 생각했지만,
UI구현을 코드로만 구현해야했던 은행창구 매니저 프로젝트 이후 프로젝트에서도 코드베이스 UI를 조금 더 활용해보고 싶어서 스토리보드를 사용하지 않고 구현했습니다.

2023-07-31 08:46 UTC, LeeZion94 commented on BoxOffice/Info.plist
> +	</dict>
애플에서는 ATS 정책을 통해 기본적으로 https 통신을 하도록 유도하지만,
이번 과제에서는 http 통신을 하기위해서 plist에서 해당부분을 추가해줬습니다.

2023-07-31 08:51 UTC, LeeZion94 commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
올라프께서 말씀해주신대로 중복되는 부분들을 하나의 특성(People)으로 묶고싶었고,
또한 해당 Protocol을 사용하므로써 Director, Actor, Staff는 People의 특성을 가지고 있음 명시하고 싶었습니다.

2023-07-31 08:54 UTC, LeeZion94 commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
코드 작성의 의도는 현재까지의 과제의 요구사항에서는 중첩타입으로 설계된 모델들이 정의된 타입 외부에서 사용되는 부분이 없었기 때문에
중첩타입으로 구현했습니다.
가독성을 위해서 중첩 타입의 모델들을 분리해두겠습니다.

2023-07-31 09:06 UTC, LeeZion94 commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +            let actors: [Actor]
넵 이미 선점하고 있는 이름대신 좀 더 명확한 네이밍인 MovieActor로 수정하겠습니다.

2023-07-31 09:15 UTC, LeeZion94 commented on BoxOffice/Networking/API.swift
> +}
이번기회에 Result Type에 대해 공부하고 활용해보게 되었습니다. 감사합니다.

<참고자료>
https://developer.apple.com/documentation/swift/result

2023-07-31 09:18 UTC, LeeZion94 commented on BoxOffice/Networking/API.swift
> +    }
error임을 명시적으로 나타내고 errorDescription을 준수함으로써 에러메세지임을 분명하게 표현할 수 있도록 수정하겠습니다.

2023-07-31 09:26 UTC, LeeZion94 commented on BoxOffice/Networking/BaseURL.swift
> +}
Namespace로써만 사용하고 있으므로 Enum(case-less)으로 수정하도록하겠습니다.

<참고자료>
https://sujinnaljin.medium.com/namespace-%EC%A7%80%EC%A0%95%ED%95%98%EA%B8%B0-struct-vs-enum-ce86d5717d95
https://onelife2live.tistory.com/15

2023-07-31 10:29 UTC, LeeZion94 commented on BoxOffice/Networking/BaseURL.swift
> +    static let boxOffice = "a38f2bee3ae1dc5696060047ce83c935"
해당 key 값을 가지고 허용된 응답회수를 초과한다면 해당 키는 더이상 사용할 수 없을 것 같습니다.

따라서 해당 APIkey를 막 올리기 보다는 해당 키들을 추가적으로 관리할 수 있는 Keys.plist를 만들어서 관리할 수 있도록 변경했습니다.
올라프가 말씀해주신 방법이 이 방법이 맞을까요?

2023-07-31 10:38 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +final class URLSessionProvider {
애초에 URLSessionProvider 처럼 네트워크를 담당하는 타입을 하나의 객체로 만들어서 할당될 때마다 새롭게 만들어지는 것이 아닌 하나의 객체를 공유참조하는 형태로 설계했습니다. 하지만 URLSessionProvider의 requestData를 구현하면서 URLSessionProvider 타입내부에서 따로 변수를 가지고 있을 필요가 없었고, URLSessionProvider 타입 인스턴스를 굳이 생성해서 해당 메서드를 실행시킬 필요는 없다고 판단되어 static키워드를 사용하게 되었습니다.
이렇게 작업이 진행되다보니 URLSessionProvider를 class로 만들어준 의미가 많이 퇴색되었다고 생각합니다.

해당 타입은 인스턴스화 되거나 상속을 받는 등 class로 사용되어져야할 이유가 없으므로 NameSpace 처럼 사용하기위해 enum으로 변경하도록하겠습니다.

2023-07-31 10:40 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +    static func requestData<T: Decodable>(_ request: APIRequest, _ completionHandler: @escaping (APIResult<T>) -> Void) {
URLSessionProvider 타입 내부에 사용하고 있는 내부 변수가 따로 없고, URLSessionProvider 타입을 인스턴스화 하지 않고 NameSpace에서 가져다가 쓰는 것 처럼 편하게 사용하기 위해 static 키워드를 사용했습니다.

2023-07-31 10:43 UTC, hemg2 commented on BoxOffice/Networking/URLSessionProvider.swift
> +        }
변환을 2번을 걸친부분은 수정하여 진행했습니다.

2023-07-31 10:45 UTC, hemg2 commented on BoxOffice/Networking/URLSessionProvider.swift
> +            }
조언 감사합니다 올라프!
수정 진행했습니다.

2023-07-31 10:50 UTC, hemg2 commented on BoxOffice/Networking/URLSessionProvider.swift
> +        dataTask.resume()
현재로선, 불가능합니다.
 dataTask를 취소하려면 URLSessionProvider 내에 URlSessionDataTask를 변수로 가지고 있고,
이를 외부에서 dataTask.cancel()을 메서드를 호출해서 취소할 수 있을꺼같습니다.
이와 같이 대응할 수 있도록 수정하겠습니다.

2023-07-31 11:13 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +    }
올라프가 아래에서 말씀해주신 것 처럼 ViewController가 불필요하게 방대해지는 부분을 방지하기 위해서 해당 로직을 만들었습니다.
ViewController가 불필요하게 알필요가 없는 부분을 알고 있을 필요가 없으므로 해당 역할을 대신해줄 수 있는 타입을 만들어서 수정하도록 하겠습니다.

2023-07-31 11:15 UTC, LeeZion94 commented on BoxOffice/Protocol/CanShowNetworkRequestFailureAlert.swift
> +}
올라프께서 말씀해주신 것 처럼 UIViewController의 extension으로 만들어도 동일한 기능을 사용할 수 있습니다.

하지만  protocol로 해당 기능을 빼고, MainViewController에서 채택함으로써 해당 ViewController는 네트워크 요청실패시 Alert를 띄울 수 있는 기능을 가진 ViewController 임을 명시하려고 protocol로 만들고 채택, 준수하도록 했습니다.

2023-07-31 11:28 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +        button.addTarget(self, action: #selector(didTappedRequestMovieDetailInformationButton), for: .touchUpInside)
@objc 어노테이션을 없앨 수 있다니.... 감사합니다 올라프.

해당 프로젝트에서는 앱의 최소 iOS 지원 범위가 13 부터이므로 iOS 14 부터 지원가능한 addAction은 따로 적용하지 않았습니다.
(Available Keyword를 따로 사용하지 않았습니다!)
하지만 알려주셔서 감사합니다 올라프 !

2023-07-31 11:31 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +        button.addTarget(self, action: #selector(didTappedRequestMovieDetailInformationButton), for: .touchUpInside)
해당 Control 개체 내(여기서는 UIButton) 에서 touch up(손가락을 떼는) 동작이 일어났을 때 발생하는 이벤트입니다.
UIControl.Event에 존재하는 다른 여러가지 이벤트들도 살펴보겠습니다.

[참고자료](https://developer.apple.com/documentation/uikit/uicontrol/event)

2023-07-31 14:09 UTC, hemg2 commented on BoxOfficeTests/BoxOfficeTests.swift
>  }
수정 진행했습니다. 놓친부분 알려주셔서 감사합니다!

2023-07-31 14:12 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +}
ViewController가 필요한 데이터를 요청하고 최대한 필요한 데이터(dto)만 받아 뷰를 갱신시켜주는 역할만을 할 수 있도록 UseCase로 구현했습니다.

ViewController에서는 유저의 행동 및 동작에 대응할 수 있는 UseCase를 주입받고 UseCase는 전달받은 에벤트에 의해 data를 Fetch 하기 위해 URLSessionProvider를 주입받아 data를 fetch해 올 수 있도록 설계했습니다.

2023-07-31 15:14 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +            decodeResponseData(data, completionHandler)
Decoding해주는 로직을 URLSessionProviderImpl에서 들고 있는 것이 아니라 JSONDecoder의 extension으로 기능을 분리했습니다!

2023-08-01 10:47 UTC, 1Consumption commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
`People`이라는 프로토콜을 사용하면 모르겠는데, 지금은 사용하고 있지 않은 것 같습니다. 현재 불필요한데, 불확실한 미래를 위해 만들어 놓는 것은 불필요하다고 생각해요.

2023-08-01 10:51 UTC, 1Consumption commented on BoxOffice/Networking/BaseURL.swift
> +}
Base URL의 정확한 정의는 무엇인가요? domain을 의도하신걸까요?

2023-08-01 10:52 UTC, 1Consumption commented on BoxOffice/Networking/BaseURL.swift
> +    static let boxOffice = "a38f2bee3ae1dc5696060047ce83c935"
git ignore에 올리는 방법도 있겠죠. 완벽한 보안은 없습니다. 다만 신경을 쓰지 않는 것과는 전혀 다른 얘기여서 드린 코멘트였습니다.

2023-08-01 10:55 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +    static func requestData<T: Decodable>(_ request: APIRequest, _ completionHandler: @escaping (APIResult<T>) -> Void) {
`편하게 사용하기 위해` 라는 말은 반만 맞은 대답 같습니다. 지금은 배우는 단계니까 `편하게`보다는 조금 더 `불편하게` 정석적인 설계에 집중해보는게 좋겠습니다.

2023-08-01 10:57 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +final class URLSessionProvider {
> 인스턴스를 굳이 생성해서 해당 메서드를 실행시킬 필요는 없다고 판단되어
해당 타입은 인스턴스화 되거나

여기에 해당하는 이유가 궁금합니다.

2023-08-01 11:04 UTC, 1Consumption requested changes
클린 아키텍쳐를 적용하려고 하신 것 같은데, 맞을까요? 
그렇다면 어떤 점이 좋아서 클린아키텍쳐를 채택하게 되었는지 궁금합니다.

2023-08-01 11:04 UTC, 1Consumption commented on BoxOffice/Networking/URLSessionProvider.swift
> +}
제가 드린 코멘트의 의도는 `네트워크 레이어는 네트워킹만 진행해야한다` 였습니다. 지금은 네트워킹 레이어에서 `어떤 정보로 디코딩할지`도 알고 있기 때문에 이 부분 자체가 분리되면 좋겠습니다.

2023-08-01 11:04 UTC, 1Consumption commented on BoxOffice/Repository/BoxOfficeRepository.swift
> +final class BoxOfficeRepositoryImpl: BoxOfficeRepository {
Impl은 약어네요. 약어를 지양해주세요.

2023-08-01 11:04 UTC, 1Consumption commented on BoxOffice/Repository/BoxOfficeRepository.swift
> +final class BoxOfficeRepositoryImpl: BoxOfficeRepository {
Repository의 역할은 무엇인가요?

2023-08-01 11:04 UTC, 1Consumption commented on BoxOffice/UseCase/MainViewControllerUseCase.swift
> +    }
escaping 클로저인데, weak self를 붙여주지 않은 이유가 궁금합니다.

2023-08-01 11:04 UTC, 1Consumption commented on BoxOffice/UseCase/MainViewControllerUseCase.swift
> +        return movieInformationDTOList
map을 사용해 바꿔보세요.

2023-08-02 06:05 UTC, LeeZion94 commented on BoxOffice/UseCase/MainViewControllerUseCase.swift
> +    }
escaping 클로저라고 해서 반드시 순환참조가 일어나는 것은 아니라고 알고있습니다!

위의 escaping 클로저의 경우 클로저 내부에서 self를 통해 BoxOfficeRepository를 참조하고 있으나
BoxOfficeRepository는 해당 클로저를 직접적으로 참조하고 있지 않으므로 순환참조가 발생하지 않습니다.
따라서 weak self 키워드를 사용하지 않았습니다.

2023-08-02 06:22 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +}
넵 올라프 네트워크 레이어에서는 네트워킹 만 진행할 수 있도록 수정하고, 
레포지토리에서 data를 넘겨 받아 Decoding해 UseCase에 넘겨 줄 수 있도록 수정했습니다.

2023-08-02 06:27 UTC, LeeZion94 commented on BoxOffice/Repository/BoxOfficeRepository.swift
> +final class BoxOfficeRepositoryImpl: BoxOfficeRepository {
넵 Implementation으로 변경하겠습니다!

2023-08-02 06:29 UTC, hemg2 commented on BoxOffice/UseCase/MainViewControllerUseCase.swift
> +        return movieInformationDTOList
네 `map`으로 변경 진행했습니다. 
감사합니다!

2023-08-02 06:35 UTC, hemg2 commented on BoxOffice/Repository/BoxOfficeRepository.swift
> +final class BoxOfficeRepositoryImpl: BoxOfficeRepository {
`BoxOffice`와 연관되어 네트워킹을 통해 데이터를 패치해주는 로직들을 모아놓고 관리 하기 위한 타입 입니다.
`MainViewController` 가 아닌 다른곳에서도 `BoxOfficeRepository`를 통해  `BoxOffice`와 연관된 데이터를  패치해 올수있도록 재사용 하기 위해 만들었습니다.

2023-08-02 06:36 UTC, hemg2 commented on BoxOffice/Model/Entity/MovieDetailInformation.swift
> +}
넵 삭제 하도록 하겠습니다!

2023-08-02 06:49 UTC, hemg2 commented on BoxOffice/Networking/BaseURL.swift
> +}
저희가 domain과 baseURL를 혼동해서 사용했습니다.
path이전까지의 URL이 baseURL로 알고 있었으나 이는 domain의 개념이였고, domain을 포함한 공통적인 URL(일관된 부분)이 baseURL임을 알게 되었습니다.

2023-08-02 06:49 UTC, hemg2 commented on BoxOffice/Networking/BaseURL.swift
> +    static let boxOffice = "a38f2bee3ae1dc5696060047ce83c935"
조언해주셔서 감사합니다!

2023-08-02 06:51 UTC, hemg2 commented on BoxOffice/Networking/URLSessionProvider.swift
> +    static func requestData<T: Decodable>(_ request: APIRequest, _ completionHandler: @escaping (APIResult<T>) -> Void) {
조금더 정석으로 설계 해보겠습니다.

2023-08-02 07:00 UTC, LeeZion94 commented on BoxOffice/Networking/URLSessionProvider.swift
> +final class URLSessionProvider {
이 또한 아래의 이유와 같이 어디서든 접근하여 편하게 사용하기 위함이였습니다.

하지만 올라프께서 말씀해주신대로 정석적인 설계에 집중하여 수정하도록하겠습니다.

2023-08-02 07:13 UTC, LeeZion94 commented
넵 맞습니다.

사실 처음 부터 클린 아키텍처를 적용하려고 햇던 것은 아닙니다.
ViewController의 역할이 많아졌기 때문에 ViewController의 역할을 오직 뷰의 갱신처리만 담당하도록 기능을 분리했었고
UseCase를 사용하여 해당 기능을 UseCase로 분리할 수 있었습니다.

하지만 UseCase에 BoxOffice API 호출을 통해 data를 fetch하는 로직이 존재하게 되었기 때문에
BoxOffice와 연관된 data를 Fetch하는 로직을 다른 곳에서 재사용할 수 없었고 이를 재사용하기 위해 Repository를 만들어주게 되었습니다.

이와 같은 순서로 Clean Architecture를 적용하게 되었습니다.

2023-08-02 11:50 UTC, merged