박스 오피스 [STEP 2] Serena, BMO
yagom-academy/ios-box-office pull request #81
Opened 2023-07-28 09:02 UTC by bubblecocoa

@GREENOVER 
안녕하세요! 그린🌳
BMO🤖 & Serena🐷팀입니다!
은행창구 매니저 프로젝트 Step2 PR 보냅니다.
항상 꼼꼼한 리뷰 감사합니다!😆

-----

## 구현한 내용
- 영화진흥위위원회 오픈 API를 참고하여 `오늘의 일일 박스오피스 데이터`와  `영화 개별 상세 데이터` Model를 구현하였습니다.
- 위 Model을 활용하여 URLSession을 생성하여 JSON 파일을 Fetch하였습니다.
> 주요 내용 : 오픈 API / URLSession / JSON Decoding

-----

## 고민한 부분
### 🔥 @escaping + Closure Capture
- `ViewController`의 요청으로 `URLSessionTask`를 통해 데이터를 수신해 왔으나 `task` 밖으로 데이터를 반환시켜줄 수 없었습니다. 
- 저희는 수신된 데이터를 `ViewController`의 프로퍼티에 반환시켜주기 위해 `task` 요청 메서드에 프로퍼티에 값을 담아주는 메서드를 전달해 주었습니다.
- 이때 `URLSession`은 비동기로 로직이 처리되고, 해당 메서드는 `task`가 끝난 이후에 수행되어야 하는 것으로, `@escaping` 키워드가 추가되었습니다.

<br>

### 🔥 HTTP 통신
- `URLSessionTask`를 이용하여 데이터를 받아오려고 했는데, 다음과 같은 에러가 출력되었습니다.
    > Use HTTPS instead or add Exception Domains to your app's Info.plist
- 해당 에러는 저희가 데이터를 요청한 `URL`이 `HTTP`를 통해 통신되기 때문이었습니다.
- `xcode`에서 프로젝트를 생성시 기본 설정이 `HTTPS`만 허용되어있기 때문에 `HTTP`를 사용하기 위해서는 추가적인 설정이 필요합니다.
- 설정 내용은 `info.plist`의 `Information Property List`에 `App Transport Security Settings` - `Allow Arbitary Loads`를 추가하는 것입니다.
- 이 설정을 통해 문제없이 `HTTP`통신을 할 수 있게 되었습니다.
 ![](https://hackmd.io/_uploads/Byiyd1-jh.png)

<br>

## 조언을 얻고 싶은 부분

### ⭐️ Session shared / default의 차이점
- 데이터를 `fetch`할 때 `NetWorkManager`에서 어떤 종류의 `URLSession`을 사용할지 고민하였습니다. 기본 통신에 사용 가능한 `URLSession`으로 어떤 것을 활용할지 고민하였습니다.
- Apple 공식문서에 따르면 `Session` 별 차이는 아래와 같이 정리할 수 있습니다.
    > **shared session** : 기본 요청에 대한 공통 session 구성 객체
    >    - `customizable session`과 달리 사용자 정의 불가능
    >    - 간단하게 사용 가능하지만 `delegate`, `configuration`을 제공하지 않기 때문에 제약이 있음
    >    - 점진적 데이터 수신 불가능, 인증이 있는 경우 사용 불가능, `background` 사용 불가능
    >    - `Util`처럼 사용할 수 있도록 싱글톤 구조의 `shared session`을 기본 제공해준다.

    > **customizable configure session** : `Default`, `Ephemeral`, `Background` 세가지 형태로 `URLSession`을 생성
    >    - **Default** : 기본 통신. 캐싱을 지원. `shared Session`과 유사하지만 사용자가 구성 가능.
    >    - **Ephemeral** : 쿠키나 캐시를 저장하지 않는 정책을 가져올 때 사용 ex. Safari 개인정보보호 모드
    >    - **Background** : 앱이 백그라운드에 있는 상황에서 컨텐츠 다운로드, 업로드에 사용. 앱 종료되도 통신을 지원하는 세션

위의 차이점을 바탕으로 현재 스텝에는 `sharedSession`과 `defaultConfigurationSession` 두가지를 놓고 고민하였습니다. 고민을 해보았지만 해결되지 않은 의문이 있어서 그린에게 조언을 구하고 싶습니다.
1. 두 `Session`의 차이로 언급되어 있는 문서 상 기재되어 있는 '점진적 데이터 수신'의 개념이 어떤 것을 말하는지 모호하여 질문드립니다.
 점진적 데이터 수신이란, 데이터가 한쪽에서 다른쪽으로 수신될 때의 패킷 단위 기준으로 순차적으로 데이터가 넘어가는 것을 말하는 것일까요? 
 그런 경우 `shared`는 데이터의 크기 단위가 작기 때문에 점진적 데이터 수신일 불가능 한 것인지 궁금합니다.
2. Step2 기준으로 수신할 데이터의 크기도 크지 않고, 사용자가 `Session`을 구성하여 사용할 일이 없었습니다. 하지만 앞으로 확장 가능성 때문에 현재 Step2 기준으로 `defaultSession`을 사용하였습니다.
만약 그린이라면 현재와 같이 수신할 데이터가 많지 않은 경우 두가지 `Session`중 어떤 것을 사용하실지 조언을 얻고 싶습니다!

> shared 참고링크 [🍎 shared](https://developer.apple.com/documentation/foundation/urlsession/1409000-shared)
> default 참고링크 [🍎 default](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411560-default)

### ⭐️ URLSession dataTask에서 에러 처리
`ViewController`에서 요청한 `dataTask`에서 작업 도중 에러가 발생하는 경우, 발생한 에러를 `ViewController`에서 전달받아 처리하고 싶었습니다. 하지만 `dataTask` 클로저 내부에서 밖으로 값을 리턴시킬수 없는것처럼, 에러도 밖으로 던질 수 없었습니다.
> Invalid conversion from throwing function of type '@Sendable (Data?, URLResponse?, (any Error)?) throws -> Void' to non-throwing function type '@Sendable (Data?, URLResponse?, (any Error)?) -> Void'

위 에러를 확인하였고 코드 이곳저곳에 `throw`, `throws` 키워드를 붙였으나 결국 해결하지 못했습니다 😭
어떻게 하면 `ViewController`에서 `dataTask`에서 발생한 에러를 `catch`할 수 있을까요?

-----

## 참고자료
- [🍎 Developer Apple - Escaping Closures](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/#Escaping-Closures)
- [🍎 Developer Apple - URLSession](https://developer.apple.com/documentation/foundation/urlsession)
- [🍎 Developer Apple - Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)
- [📒 Blog: SwiftUI : @escaping](https://seons-dev.tistory.com/entry/SwiftUI-escaping)
- [📒 Blog: Xcode13에서 HTTP 통신 사용하는 방법](https://jerry-bakery.tistory.com/entry/iOS-Xcode13에서-HTTP-통신-사용하는-방법Use-HTTPS-instead-or-add-Exception-Domains-to-your-apps-Infoplist)

2023-07-29 06:05 UTC, GREENOVER requested changes
@bubblecocoa @serena0720 
두분 스텝 2도 고생 많으셨어요!
이번에는 특히 네트워킹을 잘 구성하셔서 크게 코멘트 드릴건 없을것 같아요ㅎㅎ
좀 더 VC에서 로직 보완과 같은 부분만 남겨봤습니다!
***
### 칭찬 드리고 싶은 부분
- 생겨날 에러 타입에 대해 만드는 습관 너무 좋네요 💯
- 네임 스페이스 활용 너무 잘하시네요 💯
- 클로저의 적극 활용도 능숙하신것 같아요! 💯
***
### 궁금하신 부분에 대한 저의 의견
1. Session shared / default의 차이점
- 우선 정리를 너무 잘해주셔서 크게 첨언할건 없고 조금 궁금하신 부분에 대해 제가 알고 있는 지식을 전달드려볼께요!
말씀하신 `점진적 데이터 수신`이라는건 알고 계신것처럼 쉽게 말하면 데이터를 일부씩 전송받는거까지는 이해를 하고 계실거에요.
그러니까 큰 용량 데이터를 받거나 뭐 가장 일반적인건 스트리밍 서비스 시 계속 들어오는 데이터를 처리할때 많이 사용됩니다.
즉, 점진적 데이터 수신을 사용하고 싶다면 URLSession Delegate 메서드를 구현해야 하는데요. 
shared session은 커스텀한 delegate를 구성할 수 없기에 점진적 데이터 수신을 구현할 수 없죠.
그렇기에 custom URLSession으로 구성해야 하는 차이가 있습니다 🙋🏻
꼭 제 말이 일리가 있는지 등 검증해보세요ㅎㅎ

그리고 두번째로 말씀하신 저라면 어떤것을 사용할지에 대해 여쭤보신 부분은 저도 확장성을 고려해서 여러분들처럼 갈것 같아요!

2. URLSession dataTask에서 에러 처리
- 요건 Result라는 타입을 보통 많이 사용하고 현재 겪고 계신걸 쉽게 해결할 수 있습니다~!ㅎㅎ
혹시 처음 접하신다면 꼭 학습해두시면 유용하실거라 먼저 해결 방안을 드리는것보다 학습해보실 시간을 드려볼께요!
하시다가 헷갈리시거나 하면 말씀해주세요ㅎㅎ
***
코멘트 외 크게 보완해야할 부분은 없다고 보입니다~
우선 코멘트 남긴게 있어서 스텝 1처럼 요구사항은 만족하지만 Request Changes로 드릴께요!
언제든 편하게 머지나 재리뷰 요청을 해주세요 😉
좋은 주말 되세요 🎉🎉🎉

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/DTO/Movie/People.swift
> +    let peopleEnglishNm: String?
다른곳들은 Name으로 컨벤션 가져간것 같은데 여기만 Nm인 이유가 있는건가요~? 🤔

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/Model/NetworkManager.swift
> +extension NetworkManager {
extension으로 private한것들 역할에 맞게 구분해둔거 너무 좋네요 👍👍

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/NameSpace/KobisNameSpace.swift
> +enum KobisNameSpace {
네임스페이스 관리 아주 갓벽하네요!

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/Model/NetworkManager.swift
> +struct NetworkManager {
그룹핑 이름을 Model로 하신 이유가 궁금합니다 🙋🏻
네트워크 매니저의 역할은 네트워킹하는 역할인것 같아서 Service나 Network 느낌이 강해서요..!
뭔가 Model은 DTO와 같은 친구들이 아닐까 싶은데 여러분들 의견은 어떠신가요~?

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/ViewController/ViewController.swift
> +        func fetchBoxOffice(_ boxOffice: BoxOffice) {
추후 아래 fetchMovie도 그렇고 viewDidLoad 외에 리프레쉬로 다시 데이터를 불러오거나 하는 기능들도 고려하여 확장성 있게 ViewDidLoad 내부 메서드에서 분리시키는건 어떨까요?

2023-07-29 06:05 UTC, GREENOVER commented on BoxOffice/ViewController/ViewController.swift
> +        let networkManager = NetworkManager()
추후 현재 프로젝트 요구사항이 아니더라도 일반적으로 networkManager가 viewDidLoad외의 메서드에서도 사용될 여지가 많을것 같은데 전역적으로 빼보는건 어떨까요~? 🙋🏻

2023-07-29 06:05 UTC, GREENOVER commented on README.md
> +# 🎥 박스오피스🍿
리드미 작성 최고 👍👍

2023-07-31 08:11 UTC, bubblecocoa commented on BoxOffice/DTO/Movie/People.swift
> +    let peopleEnglishNm: String?
누락된 부분입니다 😱
해당 부분 수정하였습니다

2023-07-31 08:11 UTC, serena0720 commented on BoxOffice/ViewController/ViewController.swift
> +        let networkManager = NetworkManager()
꼼꼼한 리뷰 감사합니다~! 코멘트 참고하여 수정하였습니다

2023-07-31 08:12 UTC, serena0720 commented on BoxOffice/ViewController/ViewController.swift
> +        func fetchBoxOffice(_ boxOffice: BoxOffice) {
기존 viewDidLoad의 내부 메소드 모두 외부로 분리하였습니다! 😆

2023-07-31 08:13 UTC, bubblecocoa commented on BoxOffice/Model/NetworkManager.swift
> +struct NetworkManager {
그린이 주신 의견에 동의합니다!
현재까지 야곰 커리큘럼에 따라 `MVC`안에서만 분리하려고 하다보니 `Service`적인 부분이 `Model`이 되었네요
기존 `DTO`는 `Model`로 이동하였고, `Model - NetworkManager` 안에 작성되어 있던 코드는 `Service - BoxOfficeService`와 `Util - NetworkManager`로 분리하였습니다.

2023-07-31 08:51 UTC, GREENOVER approved these changes
두분 Result 타입 아주 맛있게 잘쓰셨네요!!
고생 많으셨어요 ㅎㅎ
훨씬 더 보완되고 가독성 좋은 코드가 된것 같아요 👍
스텝 2는 충분함으로 스텝 3로 넘어가보시죠! 🕺🏻🕺🏻
화이팅입니다 🎉

2023-07-31 08:51 UTC, merged