박스오피스 [STEP 2] Kobe, yyss99
yagom-academy/ios-box-office pull request #83
Opened 2023-08-01 06:35 UTC by yy-ss99

안녕하세요 웨더!(@SungPyo) 드디어 두번쨰 PR을 보내게 된 코비와 와이 입니다! 😆

이번에도 잘 부탁드립니다🙇

## 고민되었던 점

- `API Key`를 `Github`에서 안보이도록 숨기는 방법.
    - `github`은 개인적이거나 조직 내부적인 비공개 프로젝트뿐만 아니라 공개적으로 접근 가능한 오픈 소스 코드 저장소도 제공합니다. 
    따라서 `API key`와 같이 민감한 정보는 `github` 레포지토리에 공개적으로 올리는 것은 적절하지 않다고 판단했습니다.
    그에 따라서 `API key`를 `github`에서 추적할 수 없도록 하는 방법에 대하여 고민하였습니다. 
    방법 중에 `.gitignore`에 `Infoplist`를 추가하는 방법을 선택하여서 사용하였습니다.
- `Protocol`을 `extension`하여 사용하는 방법.
    - `POP`를 사용해 보고 싶었습니다.
    그 이유 다음과 같습니다.
    첫째, 프로토콜을 채택하여 구현, 작성하여 유연성을 높이고 싶었습니다.
    둘째, 동일한 프로토콜을 채택하여 여러 유형에서 동일한 동작을 사용할 수 있게하여 재사용성 있는 코드를 작성하고 싶었습니다.
    마지막으로 프로토콜은 인터페이스를 제공합니다. 따라서 추상화를 통해 코드간의 결합도를 낮추고 유지보수성을 높일 수 있기 때문입니다.
    따라서 `POP`에 대한 많은 고민이 있었으며 프로토콜을 직접 구현해보고 확장시켜보고 그 내부에 메서드를 구현해봄으로서 POP를 간접적으로나마 느껴봤습니다.

## 🙏 조언을 얻고 싶은 부분

- 에러를 나누는 기준은 어떤 건가요?
    - `NetworkConfigurable` 에 해당하는 오류타입을 만들려고 했습니다.
     `NetworkConfigurable`이라는 **프로토콜을 기준으로 만들 것인가** 아니면 `NetworkConfigurable`안에 있는 **메서드를 기준으로 각각 여러 개의 오류타입**을 만들 것인가 고민을 했습니다. 
    저희는 굳이 여러개의 오류타입을 만들 필요가 없어 보여서 프로토콜을 기준으로 그 안에서 일어날 수 있는 오류를 담은 타입을 하나만 만들어 주었습니다.
    - 이런 식으로 에러타입을 만들어 줄 때 고려하는 기준이 있나요? 있다면 어떤 것들을 고려하여 만드는지 조언 부탁드립니다!
- 현재 코드에서 `SOLID`를 적용한다면 어디에 어떻게 적용할 수 있을까요?
- 프로젝트 초반에 코드를 설계시 `SOLID`, `OOP`, `POP`를 모두 고려하고 코드를 구현해야하는지 궁금합니다.
    - 그렇지 않다면 리팩토링시에 해야하나요?

## 📚 참고 링크

- [Bundle](https://developer.apple.com/documentation/foundation/bundle)
- [API 키 숨기기](https://velog.io/@leedool3003/iOS-API-Key-%EC%88%A8%EA%B8%B0%EA%B8%B0)
- [URLSession](https://developer.apple.com/documentation/foundation/urlsession)
- [Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)
- [URLSessionConfiguration](https://developer.apple.com/documentation/foundation/urlsessionconfiguration)
- [야곰 활동학습 영상 SOLID](https://camp.yagom-academy.kr/camp/640e8879324ce85b6f358a24/boards/640eb8ea324ce85b6f358a73/articles/6471c086324ce85b6f35c208)
- [야곰 활동학습 영상 POP](https://camp.yagom-academy.kr/camp/640e8879324ce85b6f358a24/boards/640eb8ea324ce85b6f358a73/articles/64a3c150324ce85b6f35d63f)

2023-08-02 08:38 UTC, SungPyo commented on BoxOffice/Model/NetworkConfigurable.swift
> +        }
가드렛과 이프렛의 기준은 어떻게 가지고 계신가요?

2023-08-02 08:40 UTC, SungPyo commented on BoxOffice/Controller/ViewController.swift
> +                ]
굳이 extension으로 나누신 이유가 있을까요?

2023-08-02 08:41 UTC, SungPyo commented on BoxOffice/Controller/ViewController.swift
> +            )
paths의 의도를 잘 모르겠습니다.

2023-08-02 08:41 UTC, SungPyo commented on BoxOffice/Controller/ViewController.swift
> +    func printBoxOfficeData() {
printBoxOfficeData 에 대한 테스트코드를 작성할 수 있나요?

2023-08-02 08:42 UTC, SungPyo commented on BoxOffice/Extension/Bundle+.swift
> +        guard let file = self.path(forResource: "API_KEY", ofType: "plist") else { return "" }
plist로 저장하셨군요.
혹시 plist 는 외부에서 들여볼 수 있다는거 알고 계셨나요?

2023-08-02 08:43 UTC, SungPyo commented on BoxOffice/Model/NetworkManager.swift
> +        task.resume()
이 부분들에 대한 에러는 처리하지 않은 이유가 있나요?

2023-08-03 04:10 UTC, SungPyo commented
> 안녕하세요 웨더!(@SungPyo) 드디어 두번쨰 PR을 보내게 된 코비와 와이 입니다! 😆
> 
> 이번에도 잘 부탁드립니다🙇
> 
> ## 고민되었던 점
> * `API Key`를 `Github`에서 안보이도록 숨기는 방법.
>   
>   * `github`은 개인적이거나 조직 내부적인 비공개 프로젝트뿐만 아니라 공개적으로 접근 가능한 오픈 소스 코드 저장소도 제공합니다.
>     따라서 `API key`와 같이 민감한 정보는 `github` 레포지토리에 공개적으로 올리는 것은 적절하지 않다고 판단했습니다.
>     그에 따라서 `API key`를 `github`에서 추적할 수 없도록 하는 방법에 대하여 고민하였습니다.
>     방법 중에 `.gitignore`에 `Infoplist`를 추가하는 방법을 선택하여서 사용하였습니다.
> * `Protocol`을 `extension`하여 사용하는 방법.
>   
>   * `POP`를 사용해 보고 싶었습니다.
>     그 이유 다음과 같습니다.
>     첫째, 프로토콜을 채택하여 구현, 작성하여 유연성을 높이고 싶었습니다.
>     둘째, 동일한 프로토콜을 채택하여 여러 유형에서 동일한 동작을 사용할 수 있게하여 재사용성 있는 코드를 작성하고 싶었습니다.
>     마지막으로 프로토콜은 인터페이스를 제공합니다. 따라서 추상화를 통해 코드간의 결합도를 낮추고 유지보수성을 높일 수 있기 때문입니다.
>     따라서 `POP`에 대한 많은 고민이 있었으며 프로토콜을 직접 구현해보고 확장시켜보고 그 내부에 메서드를 구현해봄으로서 POP를 간접적으로나마 느껴봤습니다.
> 
> ## 🙏 조언을 얻고 싶은 부분
> * 에러를 나누는 기준은 어떤 건가요?
>   
>   * `NetworkConfigurable` 에 해당하는 오류타입을 만들려고 했습니다.
>     `NetworkConfigurable`이라는 **프로토콜을 기준으로 만들 것인가** 아니면 `NetworkConfigurable`안에 있는 **메서드를 기준으로 각각 여러 개의 오류타입**을 만들 것인가 고민을 했습니다.
>     저희는 굳이 여러개의 오류타입을 만들 필요가 없어 보여서 프로토콜을 기준으로 그 안에서 일어날 수 있는 오류를 담은 타입을 하나만 만들어 주었습니다.
>   * 이런 식으로 에러타입을 만들어 줄 때 고려하는 기준이 있나요? 있다면 어떤 것들을 고려하여 만드는지 조언 부탁드립니다!

ㄴ`에러가 발생했을때 동작에 문제가 있다거나 별도의 트래킹을 해야하는 경우등을 고려하여 만듭니다. 일반적인 에러처리와 크게 다르지 않습니다.`

> * 현재 코드에서 `SOLID`를 적용한다면 어디에 어떻게 적용할 수 있을까요?

ㄴ `이것은 설계의 영역이기때문에 어디에 어떻게 적용해야 한다.. 라고 답변하기 좀 어렵네요. 개인적인 생각입니다만 디자인 패턴과 마찬가지로 코드를 작성하고 추후 유지보수 또는 추가기능을 작성할때, 불편함을 겪으면 그때서야 깨달을 수 있다고 생각합니다.`

> * 프로젝트 초반에 코드를 설계시 `SOLID`, `OOP`, `POP`를 모두 고려하고 코드를 구현해야하는지 궁금합니다.
>   * 그렇지 않다면 리팩토링시에 해야하나요?

ㄴ `모두 고려하고 코드를 구현하면 당연히 좋습니다. 그렇지 못하는 경우가 많을뿐이죠. 그런걸 완벽하게 할 수 있다면 유지보수가 거의 필요없는 프로그램이 되겠죠?``

> 
> ## 📚 참고 링크
> * [Bundle](https://developer.apple.com/documentation/foundation/bundle)
> * [API 키 숨기기](https://velog.io/@leedool3003/iOS-API-Key-%EC%88%A8%EA%B8%B0%EA%B8%B0)
> * [URLSession](https://developer.apple.com/documentation/foundation/urlsession)
> * [Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)
> * [URLSessionConfiguration](https://developer.apple.com/documentation/foundation/urlsessionconfiguration)
> * [야곰 활동학습 영상 SOLID](https://camp.yagom-academy.kr/camp/640e8879324ce85b6f358a24/boards/640eb8ea324ce85b6f358a73/articles/6471c086324ce85b6f35c208)
> * [야곰 활동학습 영상 POP](https://camp.yagom-academy.kr/camp/640e8879324ce85b6f358a24/boards/640eb8ea324ce85b6f358a73/articles/64a3c150324ce85b6f35d63f)

와이, 코비 안녕하세요.

두번째 PR 잘 부탁드립니다.

코멘트 확인 부탁드려요!

2023-08-03 04:16 UTC, SungPyo requested changes
Error 타입의 enum을 추가로 정의하고 에러가 발생했을때 print로 출력하도록 추가되었으면 좋겠습니다.
필수로 필요한 부분은 아닙니다만 현재 작업하고 있는 브랜치와 기존 PR 브랜치를 옮겨다니면서 수정하는 추가적인 경험을 위해서요!

2023-08-03 09:15 UTC, devKobe24 commented on BoxOffice/Model/NetworkConfigurable.swift
> +        }
- 🙋‍♀️🙋‍♂️ 답변
    - 1. 가드렛: 전역적으로 사용할 경우.
    - 2. 이프렛: 이프렛 블럭 내부에서 사용할 경우.

2023-08-03 09:16 UTC, devKobe24 commented on BoxOffice/Controller/ViewController.swift
> +                ]
- 🙋‍♀️🙋‍♂️ 답변
    - 가독성을 위하여 extension을 활용하여 나누었습니다.

2023-08-03 09:48 UTC, devKobe24 commented on BoxOffice/Controller/ViewController.swift
> +            )
- 🙋‍♀️🙋‍♂️ 답변
    - `URL`의 구조가 바뀌거나 새로운 `URL path`가 들어올 경우를 생각, 확장성을 고려했습니다.</br>두 가지의 경우의 예를 들어보겠습니다.</br>첫번째, `path`의 `/searchDailyBoxOfficeList.json` 뒤에 새로운 `path`인 `/hollywood`가 들어가게 될 경우를 생각하여 만들었습니다.</br>두번째, 완전히 새로운 `URL path`이 들어오는 경우를 생각했습니다.</br>그리하여 `paths`를 만들게 되었습니다.</br>

2023-08-03 09:50 UTC, devKobe24 commented on BoxOffice/Controller/ViewController.swift
> +    func printBoxOfficeData() {
- 🙋‍♀️🙋‍♂️ 답변
    - 스텝 2-1에 해당된다고 생각해서 아직 진행하지 않았으나, 안내 사항과 같이 프로젝트를 마치고 해볼 계획입니다!
```
Step 2-1은 도전 스텝입니다.
    Step 2의 첫 PR 목표기한까지 구현이 어려운경우 도전스텝은 건너뛰세요.
    Step 2-1을 건너뛰는 경우, 프로젝트를 모두 마친 후 돌아와서 도전해보세요.
Test Double을 통해 네트워크 상태와 무관하게 로직을 테스트할 수 있도록 테스트를 구성합니다.
    반드시 Test Double의 모든 요소(Dummy, Fake, Stub, Mock, Spy 등)를 모두 적용할 필요는 없습니다.
    URLSession 역할을 대신할 타입을 만들고, 테스트 중 기존의 로직에서 URLSession을 대체할 수 있도록 구현합니다.
네트워크가 연결되지 않은 상황에서, 위에서 작성한 테스트를 실제로 진행해봅시다.
```

2023-08-03 09:51 UTC, devKobe24 commented on BoxOffice/Extension/Bundle+.swift
> +        guard let file = self.path(forResource: "API_KEY", ofType: "plist") else { return "" }
- 🙋‍♀️🙋‍♂️ 답변
    - key 값 노출을 방지하기 위해서 .gitIgnore에 해당 파일을 등록했습니다. 현재 plist파일 자체는 존재하는게 보이지만 실제 key 값은 들어있지 않습니다.

2023-08-03 09:51 UTC, devKobe24 commented on BoxOffice/Model/NetworkManager.swift
> +        task.resume()
- 🙋‍♀️🙋‍♂️ 답변
    - Error 타입의 enum을 추가로 정의하고 에러가 발생했을 때 print로 출력하도록 추후에 스탭3를 진행하면서 수정하도록 하겠습니다.

2023-08-04 05:31 UTC, SungPyo commented on BoxOffice/Extension/Bundle+.swift
> +        guard let file = self.path(forResource: "API_KEY", ofType: "plist") else { return "" }
앱을 실제로 배포한다고 했을때, 해당 파일이 없다면 API가 동작하지 않을겁니다.
이런 부분도 혹시 생각을 해보셧을까요?

2023-08-04 05:32 UTC, SungPyo commented on BoxOffice/Model/NetworkManager.swift
> +        task.resume()
Step2에 추가시켜 주실 수 있나요?

2023-08-15 16:30 UTC, SungPyo approved these changes

2023-08-15 16:30 UTC, merged