박스오피스 [STEP 3]  Erick, kyungmin
yagom-academy/ios-box-office pull request #85
Opened 2023-08-03 04:08 UTC by YaRkyungmin

@July911 
안녕하세요 July!! 
리뷰이 Erick🐶, Kyungmin🐼 입니다!
박스오피스 세번째 PR입니다!
항상 많은 조언 해주셔서 감사했습니다🙇‍♂️
이번에도 잘 부탁드립니다 July~

<br>

## 📚 학습내용

### Closure Capture Strong Reference Cycle
`Closure`는 `Reference Capture`를 하기 때문에 참조 타입을 `Capture`한다면 `RC`가 증가하며 이는 `Strong Reference Cycle`을 발생 시킬 수 있습니다.
따라서 순환 참조가 발생할 수 있는 참조타입을 캡쳐할 경우 `[weak self]`를 사용하여 이를 방지할 수 있습니다.

```swift
boxOfficeManager.fetchBoxOffice { [weak self] error in
                                 
    // ...
    DispatchQueue.main.async {
        self?.collectionView.reloadData()
        self?.collectionView.refreshControl?.endRefreshing()
        self?.activityIndicator.stopAnimating()
    }
}
```
<br>

## 🤔 고민했던 점
### 1️⃣ `UICollectionViewDiffableDataSource`, `UICollectionViewCompositionalLayout`
`UICollectionViewDiffableDataSource`와 `UICollectionViewCompositionalLayout`를 학습하고 적용해 보았지만 필요성을 느끼지 못해 기존의 `UICollectionViewDataSource`, `UICollectionViewDelegateFlowLayout`만을 사용하여 구현하였습니다.

🔗 [**적용코드**](https://github.com/h-suo/ios-box-office/blob/step3_2nd/BoxOffice/Controller/BoxOfficeViewController.swift)

**이유**
- 현재 프로젝트에서는 테이블뷰와 같이 한 줄의 아이템 열만 가지고 있어 `layout`을 그룹별이나 섹션별로 복잡하게 나눠줄 필요가 없어 `UICollectionViewCompositionalLayout`의 필요성을 느끼지 못했습니다. 
- UI업데이트를 하는 상황도 처음 화면을 열거나 `refreshControl`로 데이터를 리로드 할 경우에만 한번에 `CollectionView`를 업데이트 시켜주기 때문에 `UICollectionViewDiffableDataSource`를 사용했을 때의 아이템을 추가 및 삭제 했을 때 사용자에게 애니메이션을 보여주는 반응형 API로서의 이점을 가져가지 못하기 때문에 필요성을 느끼지 못했습니다.

### 2️⃣ 객체 분리
- `Entity` : 서버로부터 받은 `Data`를 `Decode`할때 쓰는 타입
- `DTO` : 실제 `App`에서 사용할 `Data` 타입 
- `NetworkManager` : 서버로부터 `Data`를 받아오는 역할
- `BoxOfficeManager` : `VC`와 연결된 타입, 
- `DataManager` : `Entity`를 `DTO`로 변환해주는 역활
- `Extension`
    - `URL` : `URL`을 생성하는 `makeKobisURL`메서드 추가
    - `UILabel` : `attributedText`의 부분 색을 변경해주는 `asColor`메서드 추가
    - `UIAlertController` : 하나의 액션을 가진 기본적인 `alert`을 반환하는 `makedBasicAlert` 메서드 추가
    - `DateFormatter` : 오늘로부터 원하는 만큼 떨어진 날짜를 원하는 포멧으로 반환하는 `bringDateString` 메서드 추가
    - `NumberFormatter` : 숫자로 이루어진 `String`을 받아 `Decimal`스타일로 포멧해주는 `bringDecimalString` 메서드 추가

<br>

## 🙇‍♂️ 조언을 얻고싶은 점
### ⭐️ private extension
`extension`을 해준 곳안의 메서드들에 `private`을 모두 붙여 줄 경우 `extension`에 `private`을 해야하는지 메서드별로 모두 `private`을 붙여주는것이 나을지에 대한 고민을 했습니다. 보통 어떤식의 방법을 많이 쓰는지 조언 부탁드립니다🙏🏻

**Before**
```swift
private extension BoxOfficeViewController {
    func configureUI() {
        ...
    }
    
    func setupConstraint() {
        ...
    }
}
```

**After**
```swift
extension BoxOfficeViewController {
    private func configureUI() {
        ...
    }
    
    private func setupConstraint() {
        ...
    }
}
```

## 😅 해결하지 못한 점
### ⛔️ stopAnimating
초기화면에서 데이터 로드에 실패하고 `refreshControl`를 이용해서 다시 `loadBoxOfficeData`를 호출했을때 `refreshControl?.endRefreshing()`이 정상적으로 작동하지 않는 것 같습니다.
하지만 `present(alert, animated: true)`를 하지 않으면 `refreshControl?.endRefreshing()` 정상적으로 작동합니다.

---
### 📚 참고 링크
- [🍎Apple: Capturing Values](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/#Capturing-Values)
- [🍎Apple: UICollectionViewDiffableDataSource](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource)
- [🍎Apple: UICollectionViewCompositionalLayout](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayout)
- [🍎Apple: attributedText](https://developer.apple.com/documentation/uikit/uilabel/1620542-attributedtext)

2023-08-03 06:08 UTC, July911 requested changes

2023-08-03 06:08 UTC, July911 commented on BoxOffice/Model/BoxOfficeManager.swift
> +                    self?.dailyBoxOfficeDatas = DataManager.boxOfficeTransferDailyBoxOfficeData(boxOffice: boxOffice)
self? 가 nil이면 어떻게 되나요  ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/Model/BoxOfficeManager.swift
> +                    self?.movie = movie
self? 가 nil이면 어떻게 되나요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    static let identifier = "BoxOfficeCollectionViewCellID"
String(describing:) 을 활용해보시는건 어떨까요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +
alignment, distribution, spacing 은 필요없나요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        rankChangeLabel.attributedText = nil
tableView -
 If you override this method, you must be sure to invoke the superclass implementation.
collectionView - 
The default implementation of this method does nothing. Subclasses such as [UICollectionViewCell] override this method and use it to perform relevant actions. So, if your subclass descends from UICollectionViewCell or another intermediate class, call super to ensure that your class gets the parent’s behavior. 

읽어보셨을까요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/Model/BoxOfficeManager.swift
> +    func fetchBoxOffice(completion: @escaping (Error?) -> Void) {
어떤 생각인지는 유추가 되는 것 같습니다. 
BoxOfficeManager 를 viewModel의 개념으로 두고, 여기서 정보를 받고 저장하자는 의도신것 같은데, 
: @escaping (Error?) -> Void 이 부분이 조금 어색한 것 같습니다. 
차라리 bool이면 어떨까 싶기도 하구요. 
print문도 vc 에 있던데, 어떤 에러가 났는지 구체적인것까지 알아야할까요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let dailyBoxOfficeData = boxOfficeManager.dailyBoxOfficeDatas[indexPath.item]
배열을 안전하게 조회하려면 어떻게 해야할까요 ?

2023-08-03 06:08 UTC, July911 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicator.startAnimating()
뷰 선언부에서 바로 실행해주나요 ?

2023-08-03 08:35 UTC, YaRkyungmin commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicator.startAnimating()
`viewDidLoad()`에서 `loadBoxOfficeData()` 메서드 실행 전으로 옮겨줬습니다🥹

2023-08-03 08:43 UTC, YaRkyungmin commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let dailyBoxOfficeData = boxOfficeManager.dailyBoxOfficeDatas[indexPath.item]
`dailyBoxOfficeDatas`가 비어있을때 `numberOfItemsInSection`이 `dailyBoxOfficeDatas.count`를 0으로 반환하기 때문에 `cellForItemAt`메서드는 실행되지 않았습니다. `dailyBoxOfficeDatas`에 데이터가 있을때만 접근해서 안전하게 조회하는 것 같은데 저희가 이해한 부부인 맞을까요?☺️

2023-08-03 08:50 UTC, h-suo commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        rankChangeLabel.attributedText = nil
넵! 놓친 부분인 것 같습니다! `super.prepareForReuse()` 호출해주었습니다!! 조언 감사합니다 July!!

2023-08-04 01:23 UTC, h-suo commented on BoxOffice/Model/BoxOfficeManager.swift
> +    func fetchBoxOffice(completion: @escaping (Error?) -> Void) {
VC에서는 `fetchBoxOffice`의 성공 유무만 알 수 있도록 `completion`이 `Bool` 타입을 반환하도록 수정하였습니다!
조언 감사합니다 July👍

2023-08-04 01:24 UTC, h-suo commented on BoxOffice/Model/BoxOfficeManager.swift
> +                    self?.dailyBoxOfficeDatas = DataManager.boxOfficeTransferDailyBoxOfficeData(boxOffice: boxOffice)
`bad access`가 날 수 있어서 `guard`문으로 `self`를 옵셔널 바인딩해주었습니다!

2023-08-04 01:34 UTC, YaRkyungmin commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +
`default` 가 `.fill`이고`spacing`도 필요하지 않아서 설정해주지 않았습니다. 명시해주는것이 가독성이 더 좋다고 판단하여 명시해줬습니다☺️

2023-08-04 07:13 UTC, merged