박스오피스 [STEP3] Zion, Hemg
yagom-academy/ios-box-office pull request #89
Opened 2023-08-04 08:48 UTC by LeeZion94

안녕하세요 올라프(@1Consumption)!
박스오피스 STEP3 구현을 진행했습니다.
상세한 리뷰 항상 감사드립니다.
이번에도 잘 부탁드립니다.

## 고민했던 점
### global function에서의 순환참조
global function에서의 타입에 대한 참조는 reference Count를 증가시키지 않습니다.

> Global functions are closures that have a name and don’t capture any values.

왜냐하면 `global function`에서는 어떠한 값도 `capture`하지 않기 때문입니다.
`global capture`에서 값을 캡쳐하지 않아도 되는 이유는 클로저에서 값을 캡처하는 이유는 상수와 변수를 정의한 원래 범위가 더이상 존재하지 않더라도 클로저 내에서 해당 상수와 변수의 값을 참조하고 수정하기 위해서 캡처가 필요하지만, 전역에서 정의된 클로저의 경우 상수와 변수가 정의된 범위가 존재하지 않을 수 없습니다 따라서 `capture`가 필요하지 않습니다.

일반적으로 순환참조가 발생하는 경우는 해당 클로저를 특정 타입에서 참조하고 있고 그 클로저에서 타입을 캡쳐해서 참조하기 때문에 순환참조가 발생합니다. 캡쳐하는 순간 `Strong Reference`로 참조하기 때문입니다. 하지만 `global function`는 어떠한 값도 `capture`하지 않는 클로저 이므로 `reference count` 또한 증가시키지 않기 때문에 `[weak self]` 키워드를 붙이지 않아도 순환참조가 발생하지 않습니다.

<참고 자료>
[Closure docs](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/)
[StackOverFlow](https://stackoverflow.com/questions/49239990/why-swift-global-functions-as-a-special-case-of-closures-capture-global-variable)

### 날짜 표시
```swift
private let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "ko_kr")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()
    
    private var dateString: String {
        let dataString = dateFormatter.string(from: Date())
        let removeString = dataString.components(separatedBy: ["-"]).joined()
        let change = String((Int(removeString) ?? 0) - 1)
        return change
    }
```  
-  위와 같은 코드로 진행하여 Formatter를 생성후 변환을 하여 `NavigationBar`의 날짜와 `어제`의 박스오피스 순위를 가져오게 진행 하게끔했습니다. 이렇게하면 2개의 프로퍼티 생성을 진행하게 되어 좋지않을꺼라는 생각을 하게 되었으며 다른 방법을 생각 하게 되었습니다.
```swift
 private let yesterdayDate: String = {
        let yesterday = Date() - (24 * 60 * 60)
        let formatter = DateFormatter()
        
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: yesterday)
    }()

    lldb po Date() 
    2023-08-04 07:01:02 +0000
  - timeIntervalSinceReferenceDate : 712825262.9015
```    
- `Date()`에는 timeIntervalSinceReferenceDate값을 알게되었고  이값으로 날짜 조정이 가능한점을 알게 되어 간단하게 1개의 프로퍼티 생성으로 날짜 표현을 진행했습니다.
    
## 조언을 얻고 싶은 부분
### DiffableDataSource 사용시 메모리 누수
| deleteAllItems를 하고 새로 추가하는 경우 | SnapShot을 새롭게 만들어 apply 하는 경우 |
| :-: | :-: |
| <img src="https://cdn.discordapp.com/attachments/1136463230886215751/1136926200422465616/deleteDiffable.gif" width="500"/> | <img src="https://cdn.discordapp.com/attachments/1136463230886215751/1136926200820932619/newDataDiffable.gif" width="500"/> |

- `DailyBoxOffice`의 정보를 가져와서 `diffableDataSource`의 `snapShot`을 생성할 때 `NSDiffableDataSource`에서 `SnapShot`을 생성하는 2가지 방법중 `snapShot`을 새로 만들어서 `diffableDataSource`에 `apply`해주는 방법을 적용했습니다. 기존의 스냅샷을 삭제 및 추가 변경하는 것이 아닌 새롭게 데이터를 받아 `reload` 해줘야했기 때문입니다. 따라서 새롭게 `sanpShot`을 만들어 `section`과 `item`을 추가 하고 `apply`할 때 마다 메모리가 누수되지 않는지 고민하게 되었고 디버깅 툴을 사용해 확인해본 결과 `reload`를 할 때마다 사용하고 있는 메모리가 점점 상승해서 해제되지 않는 현상을 발견하게 되었습니다. 이러한 현상은 기존의 `snapShot`을 받아온뒤 `deleteAllItems`을 하고 다시 `item`을 추가해주는 방식을 사용해도 동일한 현상이 발생하고 있었습니다.

    위와 같은 메모리 누수 현상을 해결할 수 있는 방법을 알고 싶습니다. 

<참고 자료>
[NSDiffableSnaptShot docs](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot)

### Animation도중 Animation이 끼어드는 경우
<img src="https://hackmd.io/_uploads/ry2oBI5oh.gif" width="500"/> 

targetDate를 임의로 빈문자열("")로 부여하여 의도적으로 오류를 발생시켜 팝업을 노출시킨 상황에서 RrefreshControl을 사용하여 CollectionView를 Refresh하게 되는 경우 종종 endRefreshing이 호출되었음에도 위의 예시화면처럼 endRefreshing동작을 하지 않는 다는 것을 발견했습니다.

저는 해당 이슈의 원인을 여러가지 애니메이션 메서드가 동시에 호출되어서 endRefreshing 애니메이션 메서드가 호출되어 실행되는 도중에 다른 애니메이션 메서드가 끼어들어서 endRefreshing 동작을 제대로 수행하지 못했다고 생각합니다. 따라서 도중에 여러가지 애니메이션 메서드가 호출되는 것을 방지하기위해 이에따른 예외처리를 구현했습니다. (96199c0f2bfe3ea6ca6eabb38d3ddcbf0a45d3b0)

하지만 이와 같은 커밋의 수정은 근본적인 해결책이 될 수 없다고 생각합니다. 또한 앞으로 코드를 작성하면서 반드시 겪을 상황이라고 생각합니다.

위와 같은 이슈의 근본적인 원인과 이를 해결할 수 있는 방법에 대해 조언을 구하고 싶습니다.

----

2023-08-05 08:30 UTC, 1Consumption requested changes
고생하셨습니다.

고민하신 점이 두가지인데, 이 두가지 모두 저한테는 재현되지 않습니다.
또한 원인이라고 생각하신 점이 정말로 원인일지도 의문입니다.

1. 스냅샷 메모리 누수
   메모리 디버거를 찍어보면 따로 메모리 누수가 발생하는 과정을 확인할 수 없었습니다.

2. refreshControl 애니메이션
> 저는 해당 이슈의 원인을 여러가지 애니메이션 메서드가 동시에 호출되어서 endRefreshing 애니메이션 메서드가 호출되어 실행되는 도중에 다른 애니메이션 메서드가 끼어들어서 endRefreshing 동작을 제대로 수행하지 못했다고 생각합니다.

메인큐는 시리얼큐인데, 동시에 호출된다해도 어차피 순차적으로 처리가 될텐데 어째서 위와같은 추론을 하셨는지 궁금합니다.

------------------------------------------------------------------------
추론을 하는 것은 좋은데, 결과에 과정을 끼워맞추는 식의 추론은 지양하면 좋겠습니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +struct MovieInformationDTO: Hashable {
Hashable은 무엇이고, 이를 채택한 이유는 무엇인가요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +        if OldAndNew == "NEW" {
왜 앞글자가 대문자인가요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +}
여기는 테스트코드를 작성하지 않았는데, 어떻게 잘 나온다고 보장할 수 있나요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/View/MainCollectionViewCell.swift
> +}
view를 계층에 포함시키는 코드와 레이아웃을 잡는 코드가 떨어져있어 가독성이 떨어지는 것 같습니다. view 별로 계층에 포함시키는 코드, 레이아웃 하는 코드를 합치는건 어떨까요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/View/MainCollectionViewCell.swift
> +        [rankStackView, movieDescriptionStackView].forEach { addSubview($0) }
저는 오히려 이런 것들이 가독성을 해친다고 생각합니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +    }()
이게 view에 있어야하는건가요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +}
만약 다른 뷰에서도 디퍼블데이터소스를 사용하면 그땐 어떻게 해야하나요? Section은 view에 종속적인 정보 같은데, 이렇게 밖에 있는게 어색합니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
>      }()
lazy var여야 하나요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +    private lazy var activityIndicatorView: UIActivityIndicatorView = {
https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped 이 프로퍼티도 한번 보면 좋겠습니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        refreshControl.addTarget(self, action: #selector(setUpViewControllerContents), for: .valueChanged)
addAction으로 바꿔주세요. 타겟을 올렸으면 그에 해당하는 기능을 사용하는게 좋습니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        collectionView.dataSource = diffableDataSource
혹시 DiffableDataSource의 공식문서를 제대로 읽어보셨나요? 제가 생각했을때는 대충 읽어본 것 같은데요. 다시 한번 더 읽어보시고 어떤게 잘못된건지 알려주세요.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        collectionView.register(MainCollectionViewCell.self, forCellWithReuseIdentifier: MainCollectionViewCell.reuseIdentifier)
iOS 14부터는 [`UICollectionView.CellRegistration`](https://developer.apple.com/documentation/uikit/uicollectionview/cellregistration)을 활용하는게 좋습니다.

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +            self.diffableDataSource?.apply(snapShot)
apply를 메인쓰레드에서 해줘야하나요?

2023-08-05 08:30 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +            if self.activityIndicatorView.isAnimating { self.activityIndicatorView.stopAnimating() }
이런꼴의 코드가 자주 쓰이는데 메소드로 분리하면 좋겠습니다.

2023-08-07 08:11 UTC, LeeZion94 commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +struct MovieInformationDTO: Hashable {
해당 protocol을 채택한 타입은 Hash Value로 Hash 될 수 있음을 나타내기 위한 Protocol입니다.

각각의 item을 구분하기 위한 key값으로 해당 타입을 사용하기 위해 채택했습니다.

2023-08-07 08:16 UTC, LeeZion94 commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +        if OldAndNew == "NEW" {
DTO 생성시 오타로 보입니다. 수정하도록 하겠습니다. (5a2edb9a71aa8db1bab451d65eb64a273fafa279)

2023-08-07 08:26 UTC, LeeZion94 commented on BoxOffice/View/MainCollectionViewCell.swift
> +}
넵 가독성을 위해서 해당 로직의 코드를 계층 + 레이아웃으로 합쳐보겠습니다. (db901c215ed43fe7992ff1cfa24b1287436fe6c5)

2023-08-07 08:29 UTC, LeeZion94 commented on BoxOffice/View/MainCollectionViewCell.swift
> +        [rankStackView, movieDescriptionStackView].forEach { addSubview($0) }
뷰를 subview로 넣어주는 로직이라 간단히 표현해보고싶었습니다만, 유지 보수 적인 측면에서 보았을 때 혹은 다른 사람이 제가 작성한 코드를 수정해야할 때를 생각해서 해당부분을 수정했습니다. (위의 댓글과 같은 수정사항이므로 해당 커밋기록은 생략하겠습니다.)

2023-08-07 08:32 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +    }()
usecase로 옮겨서 ViewController에서 받아서 쓸 수 있도록 수정했습니다.(698811b37e508157c1afe5f4e11d33c5cccf7090)

2023-08-07 08:35 UTC, hemg2 commented on BoxOffice/ViewController/MainViewController.swift
> +}
중첩타입으로 변경 진행했습니다.
(https://github.com/yagom-academy/ios-box-office/pull/89/commits/7d497134dfe846cd1487bc44d4795e2d16ed1587)

2023-08-07 08:40 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
>      }()
현재 생성된 뷰(self.view)의 center좌료를 activityIndicatorView의 center 좌표로 잡아주기 위해 사용했습니다.

self를 통해 view에 접근 하기위해서는 self에서 초기화 되어야하는 모든 값이 초기화되고 self가 생성된 이후의 시점이어야 하므로lazy var keyword를 사용하여 view에 접근 할 수 있도록 했습니다.

2023-08-07 08:47 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +    private lazy var activityIndicatorView: UIActivityIndicatorView = {
`hidesWhenStopped` 해당 프로퍼티에 대해서 저희가 이해한 부분은 다음과 같습니다.
hidesWhenStopped 해당 property가 true일 경우 (default는 true) animation을 stop하면 해당 개체를 hidden시켜주는 property에 해당합니다. 따라서 따로 hidden을 시켜줄 필요가 없습니다.

알려주셔서 감사합니다 올라프! 추가적인 수정사항은 다음과 같습니다.(현재 조건에서 불필요한 코드 삭제 - https://github.com/yagom-academy/ios-box-office/pull/89/commits/cfb7e3dc2e86ea5793b115f6e10cd737182f6501)

2023-08-07 09:07 UTC, hemg2 commented on BoxOffice/ViewController/MainViewController.swift
> +        refreshControl.addTarget(self, action: #selector(setUpViewControllerContents), for: .valueChanged)
넵 적용 시켜봤습니다!(https://github.com/yagom-academy/ios-box-office/pull/89/commits/66eb6a4967f45bcb05ab55f08dc0c3fb66c6d722)

2023-08-07 09:12 UTC, hemg2 commented on BoxOffice/ViewController/MainViewController.swift
> +            self.diffableDataSource?.apply(snapShot)
이동 진행했습니다! 
(https://github.com/yagom-academy/ios-box-office/pull/89/commits/c280664c3c31a966a7f8c17329f677fbb04fc62a)

2023-08-07 09:18 UTC, hemg2 commented on BoxOffice/ViewController/MainViewController.swift
> +            if self.activityIndicatorView.isAnimating { self.activityIndicatorView.stopAnimating() }
메서드 구현하여 로직 수정 진행했습니다.
(https://github.com/yagom-academy/ios-box-office/pull/89/commits/97c156ba6983e7f8de66c5204fdf0f8c99a62c2e)

2023-08-07 09:25 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +        collectionView.dataSource = diffableDataSource
> To connect a diffable data source to a collection view, you create the diffable data source using its [init(collectionView:cellProvider:)](doc://com.apple.documentation/documentation/uikit/uicollectionviewdiffabledatasource/3255138-init?language=swift) initializer, passing in the collection view you want to associate with that data source.

diffableDatasource를 collectionview와 연결짓기 위해서 해당 diffableDataSource의 init에서 datasource와 collectionview를 연결시켜준 점을 간과 한 것 같습니다. 불필요 코드를 삭제했습니다.(https://github.com/yagom-academy/ios-box-office/pull/89/commits/7b21165abda2d7a39478bd8f115da8af563959dd)

2023-08-07 09:26 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +        collectionView.register(MainCollectionViewCell.self, forCellWithReuseIdentifier: MainCollectionViewCell.reuseIdentifier)
넵 올파르 CellRegistration을 사용해서 불필요한 register 코드를 삭제하겠습니다. (https://github.com/yagom-academy/ios-box-office/pull/89/commits/7b21165abda2d7a39478bd8f115da8af563959dd)

2023-08-07 10:06 UTC, hemg2 commented on BoxOffice/Model/DTO/MovieInformationDTO.swift
> +}
테스트 코드 작성 진행했습니다!
(https://github.com/yagom-academy/ios-box-office/pull/89/commits/86539d3b74969f94fa798a21f440401188ccaea8)
(https://github.com/yagom-academy/ios-box-office/pull/89/commits/cbf1baabbfac009be5fe1c3f10ede89eaf57f8cd)

2023-08-07 13:19 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +            self.diffableDataSource?.apply(snapShot)
그러면 왜 메인쓰레드에서 안해줘도 되나요?

2023-08-07 13:20 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        refreshControl.addTarget(self, action: #selector(setUpViewControllerContents), for: .valueChanged)
여기는 [weak self]를 안해도 되는 부분인가요?

2023-08-08 09:26 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +            self.diffableDataSource?.apply(snapShot)
데이터의 갱신은 현재 비동기적으로 진행되고 있지만, 현재 state와 바뀌어질 state의 diff 계산이 모두 완료 되었다면 UI갱신은 시스템 내부에서 Main Thread로 진행시키는 것으로 이해했습니다.

<참고자료>
[wwdc - diffableDatasource](https://developer.apple.com/videos/play/wwdc2019/220/) - 31분 26초

2023-08-08 09:38 UTC, LeeZion94 commented on BoxOffice/ViewController/MainViewController.swift
> +        refreshControl.addTarget(self, action: #selector(setUpViewControllerContents), for: .valueChanged)
ActionHandler 또한 escaping 클로저이긴하지만 해당 클로저를 MainViewController에서 직접적으로 참조하고 있지않으므로 순환참조가 발생하지 않습니다.

따라서 [weak self] 키워드 또한 사용하지 않아도 된다고 생각합니다.

2023-08-08 10:38 UTC, merged

2023-08-08 10:42 UTC, 1Consumption commented on BoxOffice/ViewController/MainViewController.swift
> +        refreshControl.addTarget(self, action: #selector(setUpViewControllerContents), for: .valueChanged)
[8e10d22](https://github.com/yagom-academy/ios-box-office/pull/89/commits/8e10d22ad02916a22adb775a88a5e1565e02088f)