박스오피스 [STEP 2] karen
yagom-academy/ios-box-office pull request #91
Opened 2023-08-06 11:51 UTC by karenyang835

@YebinKim

안녕하세요. 븨븨

엄청 늦어버린 `Step2 PR`보내드립니다.
네트워크와 웹 개념이 전무하다보니 시간이 많이 늦어진 것 같습니다.

`URLSession`과 마찬가지로 조금 더 공부를 해봐야되는 영역인 것 같습니다.

부족한점이 많지만 이번 `Step` 피드백도 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ `Key`를 외부에 노출되지 않고 코드에도 노출되지 않게 할 수 있는 방법은 없을까?
- `Key`라는것이 개인정보라서 코드나 외부에 드러나지 않게 숨길 수 있는 방법은 없을지 고민해보았습니다. 그러다가 `plist`파일로 생성을 하면 코드에도 잘 보이지 않고 구태여 찾아보지 않으면 쉽게 노출되지 않을 수 있다는 것을 알게 되어서 해당 방법으로 숨겨 주었습니다.

### 2️⃣ `App Transport Security`란 무엇인가?
- `http`로 `request`를 시도하려고 하자 보라색 문구가 뜨면서 접속이 안되었습니다. 그래서 해당 내용을 검색해보니 `http`는 `https`보다 상대적으로 보안이 취약하기 때문에 발생하는 에러로 `App Transport Security(ATS)`를 활용하여 `http`를 통한 접속의 차단을 해제해 주었습니다.
#### <오류 사진>
![스크린샷 2023-08-06 오후 8 22 21](https://github.com/yagom-academy/ios-box-office/assets/124643896/f7acee9b-642d-4292-9ef9-17b3f065050c)

#### <오류 해결>
![스크린샷 2023-08-06 오후 8 27 33](https://github.com/yagom-academy/ios-box-office/assets/124643896/33d0a4ff-f885-4f81-8518-c2decc9405f8)

--- 
<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣ `UnitTest TestDouble`를 진행할 때 어떤 걸 선택해야될까요? 그리고 해당 종류별로 다 이해하고 제대로 구현할 수 있어야 되는걸까요??😢
- `UnitTest`는 여전히 많이 어려운 것 같습니다. 이번에 처음으로 `Mock`을 활용한 `TestDouble`까지 적용시켜보려고 시도해보았는데 제대로 구현한지는 아직 자신이 없습니다. 
- `Test Double`의 종류는 여러가지가 있다고 알고 있습니다.
    - `Dummy` : 아무것도 하지 않고 자리만 채워줄 뿐인 역할
    - `fake` : 실제 객체와 핵심 로직은 동일하게 작성
    - `Stub` : 상태 검증, 실제 객체 대신 가짜 객체를 넣어야 하는데 실제 로직은 필요없음.
    - `Mock` : 행위 검증, 해당 메소드가 잘 호출되었는지, 얼마나 호출되었는지가 중요할 때 쓰는 것
- 차이점도 명확하게 인지가 되지 않을 뿐 아니라 어떻게 구현해야되는지도 감이 안 옵니다. 현재 프로젝트에서는 행위 검증을 해야될 것 같아서 `Mock`를 선택하기도 했고, 그나마 `Mock`에 대한 샘플 코드가 있는 것 같아서 선택하게 된 것도 있습니다. 
- `testDouble`를 조금 더 배우고 싶다면 종류별로 명확하게 기준을 잡고 공부를 하는 것이 좋을까요? 아니면 한 가지만이라도 제대로 파악한 후에 익숙해지면 나머지 것들도 하는게 좋을까요?

2023-08-10 17:33 UTC, YebinKim requested changes
카렌 안녕하세요~
Step2 진행까지 고생 많으셨습니다!
도전 스텝의 테스트 더블까지 수행하느라 더 고민을 많이 하셨을 거 같아요 👏👏

그런데 고민하신 부분 중 API Key 를 외부에 노출시키지 않기 위해 plist 파일로 생성했다고 하셨는데 현재는 결국 서버에 노출되어 있어 누구나 접근 가능한 형태이지 않을까요? 🤔
안전하게 숨겨진 상태가 맞는지 의문이 듭니다.

또한, 질문 주신 Test Double 의 경우 매번 모든 종류의 객체를 구현해야 하는 것은 아니며, 여러 종류의 객체(Dummy, Fake 등)를 필요에 따라 선택적으로 구현하면 충분하다고 생각합니다.
각 객체의 활용 목적이 다르며 테스트 또한 검증하고자 하는 대상이 매번 다르기 때문에 각 상황에 맞춰 적절한 객체를 사용할 수 있도록 모든 객체를 공부하는 것이 필요하지 않을까 싶은데.. 개인적으로는 현재 테스트 더블의 각 객체를 모두 깊이 이해하는 것 보다는 더 다양한 요구사항을 구현해본 후 공부하는 게 좋지 않을까 싶습니다 😄

---

Step2 핵심 경험은 아래와 같았는데요.
<img width="315" alt="step2" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/1453215d-28e5-46ed-a779-22ef10d326a9">

네트워킹 타입의 활용과 관련해 p2 코멘트가 몇 가지 있어 Request Changes 로 요청드렸습니다!

리뷰 코멘트가 늦어지는 상황에 대해 양해해주셔서 감사하고 혹시 궁금하신 점 있으면 언제든 질문 남겨주세요~ 🙌☺️

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let yesterday = Date.yesterday else {
p3;

어제 날짜를 기준으로 계산하는 이유는 무엇일까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Error/BoxOfficeError.swift
> +    case APIKeyError
p4;

Error 를 어미에 다시 붙일 필요가 있을까요? 🤔
`failureRequest` 와 같이 어떤 종류의 에러인지를 좀 더 구체적으로 쓰는 편이 더 명확하게 의미 전달이 될 것으로 보여요.

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Extension/Bundle+.swift
> +              let key = resource["KobisAPIKey"] as? String else { fatalError("\(BoxOfficeError.APIKeyError)") }
p4;

다른 guard 구문과 달리 이 구문에서만 else 블럭이 개행되지 않고 작성된 것으로 보이네요 👀

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Model/NetworkManager.swift
> +    func getRequest(url: URL, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) -> URLSessionDataTask {
p2;

`URLSessionDataTask` 를 반환하는 이유가 무엇일까요?
의도를 알 수 없는 반환값으로 보여요 🤔

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/NetWork/NetworkManager.swift
> +//  NetworkManager.swift
p2;

중복된 파일이 존재하는 거 같아요 👀
삭제가 필요해보입니다.

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/NetWork/BoxOfficeDecoder.swift
> +    func fetchData(handler: @escaping (Result<Element, BoxOfficeError>) -> Void) {
p2;

`Decoder` 는 무언가 해독하는 역할(디코딩하는 역할)을 할 것으로 예상되는 객체인데, `fetchData(handler:)` 메서드를 통해 데이터를 가져오는 것은 디코더의 역할로는 잘 생각되지 않는 거 같아요 🤔
`fetchData(handler:)` 메서드를 `BoxOfficeDecoder`가 갖도록 구현한 이유가 있을까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/NetWork/BoxOfficeDecoder.swift
> +    private var task: URLSessionDataTask?
p2;

마찬가지로 `Decoder` 객체가 `URLSessionDataTask` 프로퍼티를 가지는 이유는 무엇일까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/NetWork/KobisAPIType.swift
> +            return "/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"
p4;

`/kobisopenapi/webservice/rest` 내용이 일부 중복되는 것으로 보여요 👀

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Protocol/NetworkingProtocol.swift
> +protocol NetworkingProtocol {
p3;

이전 스텝에서도 비슷한 코멘트를 드렸었는데, Swift API Design Guidelines 에서 권장하는 방식의 프로토콜 네이밍을 적용해볼 수 있을까요?
> https://github.com/yagom-academy/ios-box-office/pull/74#discussion_r1275280921

2023-08-10 17:33 UTC, YebinKim commented on BoxOfficeTests/BoxOfficeTests.swift
> +    private var url = URL(apiType: KobisAPIType.boxOffice("20230804"))
p4;

변경되지 않는 프로퍼티는 상수로 선언이 필요해보여요 👀
또한, 메서드 내부에서 선언한 `url`을 사용하는 경우가 있고 15번 줄에서 선언한 `url`을 사용하는 경우가 있어서 통일이 필요해보여요.

2023-08-10 17:33 UTC, YebinKim commented on BoxOfficeTests/MockURLProtocol.swift
> +final class MockURLProtocol: URLProtocol {
`URLProtocol`을 채택하는 Mock 객체를 만들고자 하셨군요! 🤩👍

2023-08-10 17:33 UTC, YebinKim commented on BoxOfficeTests/MockURLSession.swift
> +final class MockNetworkModel: NetworkingProtocol {
질문;

`MockNetworkModel` 는 어떤 역할을 하기 위해 필요한걸까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +//  ViewController.swift
p5;

실제 파일명과 주석이 일치하지 않는 것으로 보여요 👀
검색 시 쉽게 찾을 수 있도록 통일해주면 어떨까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Extension/Bundle+.swift
> +//  Bundle.swift
p5;

마찬가지로 실제 파일명과 주석이 일치하지 않는 것으로 보여요 👀
검색 시 쉽게 찾을 수 있도록 통일해주면 어떨까요?

2023-08-10 17:33 UTC, YebinKim commented on BoxOffice/Model/NetworkManager.swift
> +//  GetDataAPI.swift
p5;

마찬가지로 실제 파일명과 주석이 일치하지 않는 것으로 보여요 👀
검색 시 쉽게 찾을 수 있도록 통일해주면 어떨까요?

2023-08-10 17:34 UTC, YebinKim commented
그리고 지금 머지하고자 하는 브랜치가 main 으로 설정된 거 같아요! 👀
개인 브랜치로 수정이 필요해보입니다.

<img width="529" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/adff46b4-94c0-43b5-aec6-83364d6004e7">

2023-08-10 18:09 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let yesterday = Date.yesterday else {
가져오는 데이터의 정보 중 `targetDt`를 임의의 날짜(`String`)로 지정해주기보다 `Date`를 활용해서 해당 날짜의 데이터를 가져오는 코드로 작성을 하고 싶었습니다.
현재 스텝에서는 날짜를 지정하지는 않았지만 추후에 날짜별로 검색을 할 수도 있을것 같아서 `Date`로 구현을 했고 날짜를 어제 날짜로 지정을 해준 이유는 실행하는 당일의 데이터를 가져오도록 하고 싶었는데 영화진흥위원회에서 당일의 데이터는 제공되어지지 않고 있어서 최근의 날짜인 어제로 지정을 해주었습니다.

2023-08-11 17:00 UTC, karenyang835 commented on BoxOffice/Error/BoxOfficeError.swift
> +    case APIKeyError
븨븨께서 추천해주신대로 구체적인 네이밍으로 변경해주었습니다.

2023-08-11 17:01 UTC, karenyang835 commented on BoxOffice/Extension/Bundle+.swift
> +              let key = resource["KobisAPIKey"] as? String else { fatalError("\(BoxOfficeError.APIKeyError)") }
아직까지도 이런 부분이 미숙하네요.🥲
앞으로도 조금 더 컨벤션이나 네이밍 부분 신경써서 코드 작성하도록 하겠습니다.
꼼꼼하게 체크해주셔서 감사합니다. 븨븨~🥰

2023-08-11 17:07 UTC, karenyang835 commented on BoxOffice/Model/NetworkManager.swift
> +    func getRequest(url: URL, completion: @escaping (Result<Data, BoxOfficeError>) -> Void) -> URLSessionDataTask {
`URLSessionDataTask`의 반환을 통해 비동기 작업의 상태와 진행을 추적해서 작업을 취소하거나 일시 중단할 수 있게끔 코드를 작성해서 관리하고 제어할 수 있을 것이라 생각되어져서 반환값을 활용하려고 했는데 현재 제가 작성한 코드에서는 제대로 활용을 못한 것 같아 삭제해주었습니다.
아무래도 이 부분은 조금 더 공부를 해보아야 될 것 같습니다.🥹

2023-08-11 17:08 UTC, karenyang835 commented on BoxOffice/NetWork/NetworkManager.swift
> +//  NetworkManager.swift
삭제 완료했습니다.

2023-08-11 17:14 UTC, karenyang835 commented on BoxOffice/NetWork/BoxOfficeDecoder.swift
> +    func fetchData(handler: @escaping (Result<Element, BoxOfficeError>) -> Void) {
븨븨 말씀대로 `Decoder`은 `decoding`만 하는 것이 맞는것 같아 해당 `decoder`를 따로 분리해주고 해당 구조체의 네이밍을 `BoxOfficeManager`로 변경해주었습니다.

2023-08-11 17:20 UTC, karenyang835 commented on BoxOffice/NetWork/BoxOfficeDecoder.swift
> +    private var task: URLSessionDataTask?
코드를 작성하고 수정하다가 제가 놓친 부분 같습니다. 
불필요한 프로퍼티라 삭제해주었습니다.

꼼꼼하게 체크해 주셔서 감사합니다.🙏🏻

2023-08-11 17:22 UTC, karenyang835 commented on BoxOffice/NetWork/KobisAPIType.swift
> +            return "/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"
중복 되어진 부분을 `basePath`라는 상수에 할당 후 합쳐서 리턴하도록 코드 수정해주었습니다.

2023-08-11 17:23 UTC, karenyang835 commented on BoxOffice/Protocol/NetworkingProtocol.swift
> +protocol NetworkingProtocol {
아직까지 네이밍 부분은 많이 어려운 것 같습니다.🥲
저번 만국박람회에도 븨븨께서 챙겨주셨는데 또 습관처럼 네이밍을 해버린것 같습니다.

앞으로 조금 더 꼼꼼하게 신경써서 하는 습관을 드려야겠습니다.
놓치지 않고 체크해주셔서 감사합니다.

2023-08-11 17:24 UTC, karenyang835 commented on BoxOfficeTests/MockURLProtocol.swift
> +final class MockURLProtocol: URLProtocol {
칭찬 감사합니다. 
검색하고 공부해서 적용해보려고 했습니당.🙆🏻‍♀️

2023-08-11 17:29 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +//  ViewController.swift
`Rename`명령이 오류가 발생해서 수기로 수정을 해주다 보니 놓친 것 같습니다.
수정해 주었습니다.

2023-08-11 17:29 UTC, karenyang835 commented on BoxOffice/Extension/Bundle+.swift
> +//  Bundle.swift
수정완료하였습니다.

2023-08-11 17:30 UTC, karenyang835 commented on BoxOffice/Model/NetworkManager.swift
> +//  GetDataAPI.swift
수정 완료 하였습니다.

꼼꼼하게 체크해주셔서 감사합니다~

2023-08-11 17:31 UTC, karenyang835 commented
이번에 무슨 정신이었는지 꼼꼼하게 체크했어야했는데 코드 스타터때도 안한 실수를 했네요.🥹
븨븨 덕분에 대참사(?)는 막을 수 있었습니다. 븨븨께서 언급해주시지 않으셨다면 모르고 지나갈 뻔 했습니다.

수정 완료했습니다.

2023-08-11 17:39 UTC, karenyang835 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    private var url = URL(apiType: KobisAPIType.boxOffice("20230804"))
`url`을 프로퍼티 `url`활용하는 것으로 통일시켜주었습니다.
그리고 `url`은 변동되지 않기 때문에 `let`로 선언해주었습니다.

2023-08-11 18:00 UTC, karenyang835 commented on BoxOfficeTests/MockURLSession.swift
> +final class MockNetworkModel: NetworkingProtocol {
네트워크 서비스를 모방하여 테스트 시에 실제 네트워크 호출을 대체하는 역할을 합니다.  실제 네트워크 호출을 수행하지는 않지만 네트워크 요청 및 응답을 모방하여 가짜 데이터를 제공하는 역할을 수행합니다.

2023-08-13 11:23 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let yesterday = Date.yesterday else {
아하 왜 필요한지 이해되었어요!
변수명을 `targetDate` 등으로 변경해주면 특정 날짜를 기준으로 정보를 가져오고자 함을 더 명확히 전달할 수 있을 거 같은데 어떻게 생각하실까요??

2023-08-13 13:36 UTC, YebinKim commented on BoxOfficeTests/MockURLSession.swift
> +final class MockNetworkModel: NetworkingProtocol {
가짜 데이터를 제공하는 역할을 제공하기 위한 모델이었군요!

현재는 `MockNetworkModel` 의 last~ 프로퍼티들을 테스트 중 사용하고 있지 않기도 하고,
세션을 통해 넘겨주고자 하는 데이터를 매번 테스트 코드를 작성할 때 선언하고 있다보니 데이터를 제공하는 역할을 잘 수행하고 있는지는 의문이 듭니다 🤔

실제로 `MockNetworkModel` 자리를 `NetworkManager` 로 대체해도 잘 동작하기도 하구요.

의도에 맞게 동작하고 있는지 좀 더 고민이 필요해보여요.

2023-08-13 13:48 UTC, YebinKim commented on BoxOfficeTests/MockURLSession.swift
> +final class MockNetworkModel: NetworkingProtocol {
가짜 데이터를 제공하는 역할을 제공하기 위한 모델이었군요!

현재는 `MockNetworkModel` 의 last~ 프로퍼티들을 테스트 중 사용하고 있지 않기도 하고,
`MockNetworkModel` 내부에서 이미 `URLSession`을 활용한 네트워크 통신을 수행하고 있기 때문에 실제로 진행되는 테스트는 네트워크 상태와 무관한 데이터(`box_office_sample.json`)가 아닌 실제 데이터 통신 결과를 바탕으로 수행되는 것으로 보여요.

이로 인해 `MockNetworkModel` 자리를 `NetworkManager` 로 대체해도 잘 동작하기도 하구요.

Step2-1의 **네트워크 상태와 무관하게 로직을 테스트**하는 의도에 맞게 동작하고 있는지 좀 더 고민이 필요해보여요.

2023-08-13 13:56 UTC, YebinKim approved these changes
카렌 안녕하세요 😄
Step2 수정하신 내용 확인했습니다!
꼼꼼히 코멘트 확인 후 의견 남겨주셔서 감사해요.

코멘트로 드렸던 부분들 뿐만 아니라 Step2 의 목표인 `URLSession` 의 활용과 `CondingKeys` 의 활용에 대해서는 충분히 경험했다는 생각이 듭니다 👏👏
다만, 테스트 더블에 대해서는 현재로서는 네트워크 상황과 무관한 테스트를 진행하고 있지 않기 때문에 테스트를 의도에 맞게 수행하고 있다고 보기는 어려울 거 같아요 😅

테스트 더블과 관련한 내용은 도전 스텝으로서 Step2 에서 필수적으로 완료해야 하는 경험은 아니라고 생각해 Approve 로 리뷰 의견 드렸어요.
테스트와 관련해 좀 더 경험해보고자 하신다면 Mock 객체들을 수정하는 시간을 가져보고, 다음 스텝으로 나아가고자 하신다면 바로 머지 진행해볼게요~

관련해서 얘기 나눠보아요! 수정까지 고생 많으셨습니다 🙌

2023-08-13 14:08 UTC, karenyang835 commented on BoxOfficeTests/MockURLSession.swift
> +final class MockNetworkModel: NetworkingProtocol {
오늘 회의실에서 구두로 븨븨께서 설명해주신대로 해당 부분은 도전미션이었던만큼 아직 제가 완벽히 숙지가 되지 않은 것 같아 조금 더 공부해보고 진행해야 될 것 같습니다.

이 부분은 추후에 더 공부해서 진행헤보도록 하겠습니다.

2023-08-13 14:12 UTC, karenyang835 commented
븨븨~ 회의실에서 구두로 서로 상의한것처럼 테스트 더블 부분은 제가 조금 더 공부해보도록 하겠습니다.

븨븨께서 설명해주신대로 네트워크 통신과 무관한 상태에서 테스트를 진행할 수 있도록 코드를 수정하는 방향으로 해서 해보도록 하겠습니다.

이번 Step에서 제가 조금 욕심을 냈던 부분인지라 해당 프로젝트의 다음 스텝을 먼저 진행 후 추후에 스스로 공부하여 검토하고 진행해보도록 하겠습니다.

2023-08-13 14:12 UTC, merged

2023-08-13 14:17 UTC, karenyang835 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let yesterday = Date.yesterday else {
오! 생각해보니 저도 모르게 또 축약으로 네이밍을 지었군요.🥹
해당 부분은 풀어서 네이밍 변경하도록 하겠습니다.