박스오피스 [STEP 3] Dasan, Whales
yagom-academy/ios-box-office pull request #92
Opened 2023-08-07 18:03 UTC by WhalesJin

안녕하세요, 븨븨(@YebinKim)!! 💃🏻
웰다비의 Dasan🌳, Whales🐬 인사드립니다 🙆🏻‍♀️
Step3 PR이 너무 늦어졌네요ㅠㅠ
늦어진만큼 꼼꼼히 챙겨가고 싶었는데, 보시기에 잘 되었을지 모르겠습니다 🥺

이번 스텝에서는 다양한 고민을 많이 해보았습니다.
`@available(iOS 14.0, *)` 키워드를 계속 붙여주는 대신 `Minimum Deployments`를 수정하는
비교적 간단한 고민부터,
메서드나 타입 기능분리나 텍스트에 `Dynamic Type`을 적용하는 부분까지!
정말 여러가지 고민들도 많이 해보고 해결도 해보는 유익한 Step3였습니다!!

보시고 부족한 부분을 알려주신다면 또 열심히 공부해보겠습니다 💪🏻🔥
이번 리뷰도 잘 부탁드립니다 🙇🏻‍♀️

## 🤹🏻 고민했던 점

### 🔹 역할 분리
🚨 **문제점** <br>
- 프로젝트를 진행하면서 아래와 같이 `ViewController`가 비대해졌고, 이는 `ViewController`가 많은 책임을 가지게 하였습니다.(또한 본래의 책임과는 동떨어진 기능들도 가지고 있었습니다.)

    <details>
        <summary> 코드 </summary>
    
    ```swift
    // BoxOfficeViewController.swift
    class BoxOfficeViewController: UIViewController {
        (...)

        override func viewDidLoad(){
            let networkManager = NetworkManager()

            networkManager.fetchData(url: KobisOpenAPI.boxOffice(targetDate: targetDate.formatNoSeparator()).url) { result in
                switch result {
                case .success(let data):
                    do {
                        let decodedData = try DecodingManager.decodeJSON(type: BoxOffice.self, data: data)
                        print(decodedData)

                        let boxOfficeItems = decodedData.boxOfficeResult.dailyBoxOfficeList

                        boxOfficeItems.forEach { item in
                            self.items.append(item)
                        }

                        (...)
                        self.dataSource.apply(snapshot, animatingDifferences: true)
                        self.stopActivityIndicator()
                    } catch DataError.notFoundAsset {
                        os_log("%{public}@", type: .default, DataError.notFoundAsset.localizedDescription)
                    } catch DataError.failedDecoding {
                        os_log("%{public}@", type: .default, DataError.failedDecoding.localizedDescription)
                    } catch {
                        os_log("알 수 없는 오류입니다.", type: .default)
                    }
                case .failure(let error):
                    os_log("%{public}@", type: .default, error.localizedDescription)
                }
            }
        }
        (...)
    }
    ```
    </details>
    
</br>

💡 **해결방법** <br>

- `ViewController`가 본래의 책임만을 다할 수 있도록 `BoxOfficeManager`라는 타입을 만들었습니다.
    > 본래 `ViewController`의 주요 책임
    > - 일반적으로 기초 데이터의 변경에 대한 응답으로 `뷰의 콘텐츠를 업데이트`
    > - 뷰에 대한 `사용자 상호 작용에 응답`
    > - 뷰 `크기 조정` 및 전체 인터페이스의 `레이아웃 관리`
    > - 앱에서 다른 객체(다른 뷰 컨트롤러 포함)와 조정

- `BoxOfficeManager`에서는 `API`를 통해 얻어온 `Data`를 `Swift`에서 사용할 수 있도록 `Data`를 디코딩하고, 그 결과를 `Result` 타입으로 반환합니다.
- `ViewController`에서는 `API`와의 통신을 몰라도 되며, `BoxOfficeManager`를 통해 받은 `Data`를 가지고 `View`에 전달하는 역할에 집중할 수 있도록 하였습니다.
    
    <details>
        <summary> 코드 </summary>
    
    ```swift
    // BoxOfficeManager.swift
    final class BoxOfficeManager {
        (...)
        func fetchBoxOfficeData(completionHandler: @escaping (Result[BoxOfficeData]?, Error) -> Void) {
            let networkManager = NetworkManager()

            networkManager.fetchData(url: KobisOpenAPI.boxOffice(targetDate: targetDate.formatNoSeparator()).url) { (data, error) in
                do {
                    if let error = error {
                        completionHandler(.failure(error))

                        return
                    }

                    if let data = data {
                        let decodedData = try DecodingManager.decodeJSON(type: BoxOffice.self, data: data)
                        let boxOfficeItems = decodedData.boxOfficeResult.dailyBoxOfficeList
                        completionHandler(.success(boxOfficeItems))
                    }
                } catch {
                    completionHandler(.failure(error))
                }
            }
        }
    }
    
    // BoxOfficeViewController.swift
    extension BoxOfficeViewController {
        private func loadData() {
            let boxOfficeManager = BoxOfficeManager(targetDate: yesterday)

            boxOfficeManager.fetchBoxOfficeData { result in
                switch result {
                case .success(let items):
                    guard let items = items else { return }
                    self.items = items
                    self.applySnapshot()
                    self.stopActivityIndicator()
                case .failure(let error):
                    os_log("%{public}@", type: .default, error.localizedDescription)
                }
            }
        }
    }
    ```
    </details>

### 🔹 Namespace
🚨 **문제점** <br>
- 셀의 구성 요소들의 크기와 간격을 조정하면서 제약사항 중 `constant`나 `multiplier`를 넣어주는 부분들을 구현하였는데 숫자를 직접 넣게 되면 나중에 유지/보수 시에 일일히 찾으러 가야해서 좋지 않다고 생각했습니다.
    <details>
        <summary> 코드 </summary>

    ```swift
    NSLayoutConstraint.activate([
        rankStackView.widthAnchor.constraint(equalTo: self.widthAnchor, multiplier: 0.23),
        stackView.leadingAnchor.constraint(equalTo: self.leadingAnchor),
        stackView.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -(self.frame.width * 0.12)),
        stackView.topAnchor.constraint(equalTo: self.topAnchor, constant: 14),
        stackView.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -14),
        titleStackView.topAnchor.constraint(equalTo: stackView.topAnchor, constant: 5),
        titleStackView.bottomAnchor.constraint(equalTo: stackView.bottomAnchor, constant: -5)
    ])
    ```
    </details>

</br>

💡 **해결방법** <br>
- `Namespace` 열거형을 만들어서 직접적인 숫자는 파일 한 군데에서 다 수정할 수 있도록 구현하였습니다.
    <details>
        <summary> 코드 </summary>

    ```swift
    enum ConstraintsNamespace {
        static let rankStackViewFromCellWidth: CGFloat = 0.23
        static let stackViewFromCellTrailing: CGFloat = 0.12
        static let stackViewFromCellTop: CGFloat = 14
        static let stackViewFromCellBottom: CGFloat = -14
        static let titleViewFromCellTop: CGFloat = 5
        static let titleViewFromCellBottom: CGFloat = -5  
    }
    ```
    ```swift
    NSLayoutConstraint.activate([
        rankStackView.widthAnchor.constraint(
            equalTo: self.widthAnchor,
            multiplier: ConstraintsNamespace.rankStackViewFromCellWidth
        ),
        stackView.leadingAnchor.constraint(
            equalTo: self.leadingAnchor
        ),
        stackView.trailingAnchor.constraint(
            equalTo: self.trailingAnchor,
            constant: -(self.frame.width * ConstraintsNamespace.stackViewFromCellTrailing)
        ),
        stackView.topAnchor.constraint(
            equalTo: self.topAnchor,
            constant: ConstraintsNamespace.stackViewFromCellTop
        ),
        stackView.bottomAnchor.constraint(
            equalTo: self.bottomAnchor,
            constant: ConstraintsNamespace.stackViewFromCellBottom
        ),
        titleStackView.topAnchor.constraint(
            equalTo: stackView.topAnchor,
            constant: ConstraintsNamespace.titleViewFromCellTop
        ),
        titleStackView.bottomAnchor.constraint(
            equalTo: stackView.bottomAnchor,
            constant: ConstraintsNamespace.titleViewFromCellBottom
        )
    ])
    ```
    </details>

### 🔹 셀 재사용
🚨 **문제점** <br>
- 새로고침 시 `rankIntensityLabel`의 `text` 색상이 바뀌는 문제가 있었습니다.
    <img src = "https://github.com/WhalesJin/FireSaturdayStudyClassC/assets/124643545/04a41bb7-cde0-4203-a56c-6e5219280fed" width = "200">

</br>

💡 **해결방법** <br>
- 셀이 **재사용**이 되면서 벌어지는 문제여서 재사용 시 초기화를 해주는 코드로 해결하였습니다.

    ```swift
    //BoxOfficeCell
    override func prepareForReuse() {
        super.prepareForReuse()
        rankIntensityLabel.textColor = .black
    }
    ```

### 🔹 refreshControl 호출 시점
🚨 **문제점** <br>
- `configureRefreshControl` 메서드에서 `refreshControl`은 `collectionView`가 없으면 코드가 성립하지 않기에, **collectionView가 생성되기 전** 해당 메서드를 호출하면 `Fatal Error`가 발생합니다.
 
💡 **해결방법** <br>
- 호출 시점이 매우 중요하다는 것을 알게된 후, 기존에 `viewDidLoad`에서 호출해주었던 메서드를 `configureHierarchy` 메서드 내에서 호출해주었습니다.
- 그 이유는 **collectionView가 생성된 것이 보장된 이후**에 호출하는 것이 가장 안전하다고 판단하였기 때문입 [...]

2023-08-10 20:04 UTC, YebinKim requested changes
웨일🐬, 다산🌳 안녕하세요~
Step3 진행까지 고생 많으셨습니다!

객체의 역할 분리부터 구현 중 발생한 세세한 이슈들까지 모두 신경써서 고민하신 덕분에 완성도 높게 코드가 작성된 거 같습니다 👏👏

조언을 얻고 싶은 점 중 `Dynamic Type Error` 에 대해서는 저도 시뮬레이터에서 재현을 확인했지만 특별히 코드 상에서 원인을 찾을 수 없고 실기기에서는 재현되지 않는 것으로 보아 시뮬레이터 에러로 생각됩니다 😅

또한, 날짜를 표시하는 메서드의 네이밍에 관해서는 라인별 코멘트에 의견 남겨두었습니다~

---

Step3 핵심 경험은 아래와 같았는데요.
<img width="334" alt="step3" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/785f24f9-ef5f-4cf5-b632-ec3551323139">

핵심 경험은 모두 충분히 경험되었다고 생각하지만, 오토레이아웃이 깨지는 일부 상황과 관련해 수정이 필요할 거 같아 Request Changes 로 요청드렸습니다!

리뷰 코멘트가 늦어지는 상황에 대해 양해해주셔서 감사하고 혹시 궁금하신 점 있으면 언제든 질문 남겨주세요~ 🚀🙌

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, BoxOfficeData>! = nil
DiffableDataSource 를 활용하셨군요! 🤩
콜렉션뷰의 데이터를 관리하는 세련된 방법이라고 생각합니다 👍

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Utility/TargetDate.swift
> +struct TargetDate {
`TargetDate` 타입을 선언해준 덕분에 기준이 되는 시간을 별도로 설정할 수 있다는 인터페이스가 잘 와닿네요! 👍👏

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        dataSource.apply(snapshot, animatingDifferences: true)
p3;

[apply(_:animatingDifferences:completion:)](https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3375811-apply) 메서드는 일관된 작업 큐에서 호출해야 한다는 사실 알고 계셨을까요? 👀

<img width="933" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/db4ea276-206a-4c96-b95b-96cbe4c8780b">

호출 시 어느 큐에 작업을 맡길 것인지 명시가 필요해보여요.

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicatorView.stopAnimating()
p3;

UI 작업은 메인 스레드에서의 실행이 보장될 필요가 있어보여요 👀

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicatorView.startAnimating()
p3;

한 메서드에서 UI를 생성하는 것과 애니메이션을 동작시키는 것 두 가지 역할을 하고 있는 것으로 보여요 🤔
필요 시 `activityIndicatorView` 를 다시 애니메이팅 시킬 수 있도록 `startAnimating()` 동작은 분리시키는 게 어떨까요?

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Utility/NetworkManager.swift
> +            DispatchQueue.main.async {
p4;

completionHandler 는 반드시 메인 스레드에서 실행되어야 할까요? 그렇다면 16번, 23번 라인에도 GCD 블럭 처리가 필요하지 않을까요?

해당 메서드 내부에서는 completionHandler 호출 후 어떤 동작이 이어질지 알 수 없으니, 비동기 블럭을 실행하는 시점에서 (필요 시) GCD 작업을 수행해주는 게 어떨까 싶어요 🤔

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/View/BoxOfficeCell.swift
> +        setUpStackViewConstraints()
p2;

해당 코드는 셀을 생성할 때 한 번만 호출되면 되지 않을까요? 🤔
현재는 데이터를 로드할 때마다 `configureCell`이 호출되어 오토레이아웃이 깨지는 경우가 발생하는 것으로 보여요.

(실행 -> 화면 당겨서 새로고침 -> 재현)
```
BoxOffice[88237:5063340] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003b0dae0 UIStackView:0x142d69da0.trailing == _UICollectionViewListCellContentView:0x142d6a1c0.trailing - 47.16   (active)>",
    "<NSLayoutConstraint:0x600003b1cd70 UIStackView:0x142d69da0.trailing == _UICollectionViewListCellContentView:0x142d6a1c0.trailing - 42.4   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003b1cd70 UIStackView:0x142d69da0.trailing == _UICollectionViewListCellContentView:0x142d6a1c0.trailing - 42.4   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/View/BoxOfficeCell.swift
> +                constant: -(self.frame.width * ConstraintsNamespace.stackViewFromCellTrailing)
p4;

오토레이아웃 계산 방식이 다소 복잡해보이는데, 현재 프레임의 가로 값을 기준으로 계산한 이유가 있을까요?

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/View/BoxOfficeCell.swift
> +        self.addSubview(stackView)
p2;

[UICollectionViewCell](https://developer.apple.com/documentation/uikit/uicollectionviewcell)의 문서에 따르면 셀에 표시하고자 하는 콘텐츠는 `contentView` 프로퍼티 내부에 생성할 것을 권장하고 있습니다 👀

<img width="933" alt="" src="https://github.com/yagom-academy/ios-box-office/assets/38066039/b779402c-738c-466e-8f81-841d54b01e6c">

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Utility/TargetDate.swift
> +    func formatByHyphen() -> String {
p4;

Swift API Design Guidelines 에 따르면 nonmutating 메서드의 경우 적절한 분사구(`-ed`, `-ing`)를 활용할 것을 권장하고 있습니다.
현재 네이밍도 나쁘지 않지만, 더 명확한 의미 전달을 위해 분사구를 활용해보면 어떨까요?

> When the operation is naturally described by a verb, use the verb’s imperative for the mutating method and apply the “ed” or “ing” suffix to name its nonmutating counterpart.

2023-08-10 20:04 UTC, YebinKim commented on BoxOffice/Utility/TargetDate.swift
> +    func formatNoSeparator() -> String {
p3;

위와 같이 전치사구를 활용한다면 더 명확한 의미 전달이 될 거 같아요 👀
또한, `By` 로도 의미 전달은 충분히 되지만 `With` 가 개인적으로 더 적절한 전치사구라 생각됩니다 😄

2023-08-11 01:50 UTC, WhalesJin commented on BoxOffice/Utility/TargetDate.swift
> +    func formatNoSeparator() -> String {
관련커밋: 4350095c00213e1fabc0f66228ed94648c60d5ca

오!! 그렇네요!! 위에 있는 친구를 `with` 로 바꾸면서 이 친구는 `without`으로 수정하였습니다!!
좋은 네이밍 추천 감사드려요 🤩

2023-08-11 01:58 UTC, DasanKim commented on BoxOffice/Utility/TargetDate.swift
> +    func formatByHyphen() -> String {
4350095c00213e1fabc0f66228ed94648c60d5ca

`nonmutating` 메서드의 경우 분사구 활용을 권장하고 있었군요! 알려주셔서 감사합니다ㅠㅠ
`formatByHyphen`에서 `formattedWithHyphen`으로 수정하였습니다:)

2023-08-11 11:26 UTC, DasanKim commented on BoxOffice/View/BoxOfficeCell.swift
> +        setUpStackViewConstraints()
1. `configureCell` 메서드를 BoxOfficeCell `init`에서 한번만 호출되도록 수정하였습니다. 
    -> 하지만 디바이스 방향 전환 시, 레이아웃이 원하는 것처럼 나오지 않는 다는 것을 알게되었습니다🥲
2. 최상위 `stackView`를 cell에 add하는 것이 아니라, cell의 `contentView`에 add함으로써 **디바이스 방향 전환** 및 **다이나믹 타입**의 크기가 변경되더라도 오토레이 아웃이 깨지지 않도록 수정하였습니다:)
(오토레이아웃 기준 또한 contentView로 변경해주었습니다.)

```swift
    private func configureCell() {
        (중략)
        
        contentView.addSubview(stackView)
        self.accessories = [.disclosureIndicator()]
        setUpStackViewConstraints()
    }
```

2023-08-11 11:38 UTC, WhalesJin commented on BoxOffice/View/BoxOfficeCell.swift
> +                constant: -(self.frame.width * ConstraintsNamespace.stackViewFromCellTrailing)
셀 안에 `contenView`가 들어있는 것을 모르고 셀에 직접 `stackView` 등을 넣고
길이를 조정하기 위해 `accessary의 leading`만을 찾다 실패해서
적당한 영역을 지정해주기위한 전체 셀에 대한 가로 비율을 수작업으로 찾았습니다 😰

알려주신 덕분에!! `contenView`에 대해서 더 공부하고 훨씬 깔끔하고 완벽한!! `constraint`를 만들 수 있었습니다🥹

```swift
NSLayoutConstraint.activate([
  rankStackView.widthAnchor.constraint(
      equalTo: contentView.widthAnchor,
      multiplier: ConstraintsNamespace.rankStackViewFromContentViewWidth
  ),
  stackView.leadingAnchor.constraint(
      equalTo: contentView.leadingAnchor
  ),
  stackView.trailingAnchor.constraint(
      equalTo: contentView.trailingAnchor,
      constant: ConstraintsNamespace.stackViewFromContentViewTrailing
  ),
  stackView.topAnchor.constraint(
      equalTo: contentView.topAnchor,
      constant: ConstraintsNamespace.stackViewFromContentViewTop
  ),
  stackView.bottomAnchor.constraint(
      equalTo: contentView.bottomAnchor,
      constant: ConstraintsNamespace.stackViewFromContentViewBottom
  ),
  (...)
])
```

2023-08-11 12:07 UTC, WhalesJin commented on BoxOffice/View/BoxOfficeCell.swift
> +        self.addSubview(stackView)
어이쿠 🫢
쓰지말라고 한 걸 떡하니 써버렸네요 ... 🫣
공식문서를 좀 더 꼼꼼히 읽도록 신경써야겠습니다!! 근본을 알려주셔서 감사합니다 븨븨 🤩👍🏻

2023-08-11 12:10 UTC, WhalesJin commented on BoxOffice/Utility/TargetDate.swift
> +struct TargetDate {
항상 저희의 의도를 파악해주시고 딱! 골라서 칭찬해주셔서
정말정말 기분이 좋아요 ㅎㅎ 감사합니다 센스쟁이 븨븨 🙇🏻‍♀️🥰

2023-08-11 12:10 UTC, WhalesJin commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, BoxOfficeData>! = nil
꺄하!!! 감싸합니당!! 🤩

2023-08-11 12:18 UTC, DasanKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        dataSource.apply(snapshot, animatingDifferences: true)
알지 못했습니다...🥲
공식문서대로 `메인 큐` 또는 `백그라운드 큐`에서 메서드를 호출하기 위하여 아래와 같이 수정하였습니다:) (저희는 `메인 큐`를 선택하였습니다!)

```swift
private func applySnapshot() {
    var snapshot = NSDiffableDataSourceSnapshot<Section, BoxOfficeData>()
    snapshot.appendSections([.main])
    snapshot.appendItems(items)
        
    DispatchQueue.main.async {
        self.dataSource.apply(snapshot, animatingDifferences: true)
    }
}
```

2023-08-11 12:32 UTC, DasanKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicatorView.stopAnimating()
ec438f22e2fd5fcae93b9f607bdbf2f044822c51

`stopAnimating()`을 메인 큐에서 호출하도록 수정하였습니다:)

```swift
private func stopActivityIndicator() {
    DispatchQueue.main.async {
        self.activityIndicatorView.stopAnimating()
    }
}
```

2023-08-11 12:37 UTC, DasanKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        activityIndicatorView.startAnimating()
`UI 생성`과 `애니메이션 동작`을 아래와 같이 나누어주고, startAnimating 메서드 또한 메인 스레드에서 실행이 보장되도록 수정해주었습니다:)

```swift
private func configureActivityIndicatorView() {
    view.addSubview(activityIndicatorView)
    
    activityIndicatorView.center = view.center
    activityIndicatorView.style = .large
    
    startActivityIndicator()
}

private func startActivityIndicator() {
    DispatchQueue.main.async {
        self.activityIndicatorView.startAnimating()
    }
}
```

2023-08-11 13:09 UTC, WhalesJin commented on BoxOffice/Utility/NetworkManager.swift
> +            DispatchQueue.main.async {
관련 커밋 : 1f8c48802b5a84968abba18c1ad9311b03212989

븨븨의 조언대로 비동기 블럭을 실행하는 시점에서 GCD 작업을 수행해주기 위해서
`NetworkManager`의 GCD 블럭을 삭제하고
`ViewController`의 필요한 곳에서 GCD 작업을 수행하도록 수정하였습니다.

2023-08-11 14:24 UTC, YebinKim commented on BoxOffice/Utility/TargetDate.swift
> +    func formatNoSeparator() -> String {
더욱 센스있는 네이밍이 되었네요! 👍

2023-08-11 14:29 UTC, YebinKim approved these changes
다산, 웨일 안녕하세요~
Step3 수정까지 고생 많으셨습니다! 👍🙌

코멘트 꼼꼼히 확인해주셔서 감사하고, 이번 스텝은 충분히 얘기를 나눈 거 같아 이대로 Approve 및 머지 진행할게요 😄

다음 스텝 진행도 화이팅입니다!! 💪💪

2023-08-11 14:29 UTC, YebinKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        if rankOldOrNew == "OLD" {
p4;

`rankOldOrNew` 프로퍼티는 정해진 상태값만 갖는 프로퍼티일까요?
그렇다면 enum으로 더욱 쉽게 사용할 수 있을 것으로 보여요!

2023-08-11 14:30 UTC, merged

2023-08-12 06:18 UTC, DasanKim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        if rankOldOrNew == "OLD" {
말씀해주신대로 정해진 상태값만 갖는 프로퍼티여서 아래와 같이 enum을 사용하는 것으로 수정하였습니다😁

```swift
enum RankOldOrNew {
    static let old: String = "OLD"
    static let new: String = "NEW"
}
```