박스오피스II [step1] Erick, kyungmin
yagom-academy/ios-box-office pull request #95
Opened 2023-08-09 04:50 UTC by YaRkyungmin

@July911 
안녕하세요 July!!
리뷰이 Erick🐶, Kyungmin🐼 입니다!
박스오피스II의 첫 스탭입니다!
박스오피스 1-4 같이 포함된 코드입니다
이번에도 많은 조언 해주시면 깊게 새겨듣겠습니다🙇
잘 부탁드립니다🙏🏻

## 🤔 고민했던 점
### 1️⃣ VC의 기능 분리
#### 🔺extension 하지 않은 부분
- stored property
- initializer
- viewDidLoad
#### 🔺extension-setupComponents
- component관련 세팅
#### 🔺extension-configureUI
- 각각의 UI객체의 addSubview
#### 🔺extension-setupConstraint
- 각각의 UI객체의 constraint
#### 🔺extension-buttonAction
- 버튼 메서드
#### 🔺그 외 기능
- 델리게이트, 데이터소스 등..

### 2️⃣ Hashable
July의 조언으로 `CompositionalLayout`와 `DiffableDataSource`를 적용해보았습니다.
`DiffableDataSource`는 `DiffableDataSourceSnapshot`을 이용해 UI를 업데이트 하는데 그때 저희가 `Item`을 구성하는데 사용하는 `DailyBoxOffice` 객체가 `Hashable`을 채택해야 했습니다.

`Hashalbe`을 채택할 때 `struct`는 모든 프로퍼티는 `Hashable`을 준수해야 한다고 나와있습니다.
> For a struct, all its stored properties must conform to Hashable.

그러나 `rankStateColor`는 `rankState property`를 통해서 만들어지는 `property`이기 때문에
`hash value`를 비교할때 필요하지 않는 값이라고 생각해서 `hash`함수에서 빼줬습니다.

```swift
typealias RankStateColor = (targetString: String, color: UIColor)

struct DailyBoxOffice: Hashable {
    let movieCode: String
    let rank: String
    let rankState: String
    let movieTitle: String
    let dailyAndTotalAudience: String
    let rankStateColor: RankStateColor
    
    static func == (lhs: DailyBoxOffice, rhs: DailyBoxOffice) -> Bool {
        return lhs.movieCode == rhs.movieCode
            && lhs.rank == rhs.rank
            && lhs.rankState == rhs.rankState
            && lhs.movieTitle == rhs.movieTitle
            && lhs.dailyAndTotalAudience == rhs.dailyAndTotalAudience
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(movieCode)
        hasher.combine(rank)
        hasher.combine(rankState)
        hasher.combine(movieTitle)
        hasher.combine(dailyAndTotalAudience)
    }
}
```

### 3️⃣ URLRequest
영화 포스터 이미지를 가져올 때 [다음 이미지 검색 API](https://developers.kakao.com/docs/latest/ko/daum-search/dev-guide#search-image) 이용해야 했습니다.
기존 `API`는 `URLRequest`를 설정할 필요 없이 `URL`의 `QureyItem`만을 설정하여 데이터를 요청할 수 있었지만 `다음 이미지 검색 API`는 `Request Header`에 `Key`를 담아서 보내야 했습니다.
따라서 `NetworkManager`에 `URLRequest`를 받을 수 있는 `requestData`를 추가하였습니다.

```swift
func requestData(from urlRequest: URLRequest, completion: @escaping (Result<Data, NetworkError>) -> Void) {
    let task = urlSession.dataTask(with: urlRequest) { data, response, error in
        // ...
    }
    // ...
}
```

### 4️⃣ NSCache
데이터가 큰 이미지는 한번 받아온 후 재사용할 수 있도록 `CacheManager`를 만들어 관리해주었습니다.

```swift
final class CacheManager {
    static let shared = NSCache<NSString, UIImage>()
    
    private init() {}
}
```
- `NSString`을 키값으로 `UIImage`를 저장하는 `NSCache`를 싱글톤 패턴을 이용하여 구현했습니다.

```swift
func fetchPosterImage(_ movieName: String, completion: @escaping (Bool) -> Void) {
    if let cacheImage = CacheManager.shared.object(forKey: movieName as NSString) {
        posterImage = cacheImage
        completion(true)
        return
    }
    
    // ...
    networkManager.requestData(from: urlRequest) { [weak self] result in
        // ...
        switch result {
        case .success(let data):
            do {
                // ...
                CacheManager.shared.setObject(image, forKey: movieName as NSString)
                self.posterImage = image
                completion(true)
            } catch {
                // ...
            }
        case .failure(let error):
            // ...
        }
    }
}
```
- 실제 캐싱을 하는 위치는 `BoxOfficeManager`의 `fetchPosterImage`에서 이미지를 받아오기 전에 `movieName`을 `cacheKey`로 캐싱된 이미지가 있다면 `requestData`를 호출하지 않고 캐싱된 이미지를 사용합니다.
- 캐싱된 이미지가 없다면 `requestData`로 이미지를 받아와 캐싱하도록 구현했습니다.

### 5️⃣ 날짜선택
`UICalendarView`를 사용하여 날짜선택 뷰를 구현하였습니다.

```swift
private func setupCalendarView() {
    let fromDateComponents = DateComponents(calendar: Calendar(identifier: .gregorian), year: 2004, month: 1, day: 1)

    guard let fromDate = fromDateComponents.date else {
        return
    }

    let calendarViewDateRange = DateInterval(start: fromDate, end: Date.yesterday)
    calendarView.availableDateRange = calendarViewDateRange

    let dateSelection = UICalendarSelectionSingleDate(delegate: self)
    dateSelection.selectedDate = selectedDate
    calendarView.selectionBehavior = dateSelection
}
```
- `박스오피스 API`의 데이터가 `2003년 1월 1일`자는 가져오지 못하고 `2004년 1월 1일`자부터 가져오는 것을 확인하였습니다. 따라서 달력의 범위를 `2004년 1월 1일`부터 어제로 설정했습니다.
- `BoxOfficeViewController`에서 받아온 `selectedDate`를 선택된 날짜로 선택하도록 했습니다.
- `UICalendarSelectionSingleDate`로 단일 선택만 가능하도록 설정했습니다.

```swift
extension CalendarViewController: UICalendarSelectionSingleDateDelegate {
    func dateSelection(_ selection: UICalendarSelectionSingleDate, didSelectDate dateComponents: DateComponents?) {
        delegate?.selectedDate(date: dateComponents)
        dismiss(animated: true)
    }
}
```
- `UICalendarSelectionSingleDateDelegate`를 채택하여 날짜가 선택되었을 때 `Delegate` 패턴을 이용하여 `BoxOfficeViewController` 선택된 `DateComponents`를 넘겨주었습니다.

## 🙇‍♂️ 조언을 얻고싶은 점
### 1️⃣ AutoLayout
AutoLayout에 대한 Constant를 줄때 상수로 주는 것이 맞을 지 비율로 주는 것이 맞는 지, 현업에서는 어떤식으로 layout을 잡아 나가는지 궁금합니다🙏🏻
🔻 첫번째 경우
```swift
NSLayoutConstraint.activate([
    rankStackView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 32),
    rankStackView.centerYAnchor.constraint(equalTo: contentView.centerYAnchor),
    rankStackView.widthAnchor.constraint(equalToConstant: 40)
])
```
🔻 두번째 경우
```swift
NSLayoutConstraint.activate([
    rankStackView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, self.frame.width * 0.03),
    rankStackView.centerYAnchor.constraint(equalTo: contentView.centerYAnchor),
    rankStackView.widthAnchor.constraint(equalToConstant: self.frame.width * 0.1)
])
```
---
### 📚 참고 링크
- [🍎Apple: UICollectionViewDiffableDataSource](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource)
- [🍎Apple: NSDiffableDataSourceSnapshot](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot)
- [🍎Apple: Hashable](https://developer.apple.com/documentation/swift/hashable)
- [🍎Apple: UICalendarView](https://developer.apple.com/documentation/uikit/uicalendarview#3992448)

2023-08-09 07:38 UTC, July911 requested changes

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        boxOfficeManager.fetchBoxOffice { result in
weak self가 사라진 배경은 어떻게 되나요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let section = NSCollectionLayoutSection(group: group)
orthogonalScrollingBehavior 
decorationItems
visibleItemsInvalidationHandler

각각이 뭔지 언제 쓰이는지 설명해주세요.

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Controller/CalendarViewController.swift
> +    func selectedDate(date: DateComponents?)
네이밍 수정부탁드립니다.  어떻게 하면 조금 더 delegate패턴 답게 바꿀 수 있을까요 ?  
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) { 
를 보고 각 인자가 왜 들어가는지 이름이 왜 이런식인지 설명해주세요.

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Controller/CalendarViewController.swift
> +    weak var delegate: CalendarViewControllerDelegate?
weak var를 해주신 이유는 무엇인가요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/CacheManager.swift
> +
이름에 맞게 무언가 더 필요하지않을까요 ? 
저장한다거나, 불러온다거나, 있는지 확인한다거나 ..

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/DTO/Entity/DailyBoxOffice.swift
> +struct DailyBoxOffice: Hashable {
CollectionView에서 쓰는 데이터를 모든곳에서 쓸 수 있네요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/View/MovieDetailView.swift
> +    private let scrollView: UIScrollView = {
뷰를 정의하는 부분과 이름에서 스크롤뷰에 어떠한 부분도 정의되지않네요.

2023-08-09 07:38 UTC, July911 commented on BoxOffice/View/MovieDetailView.swift
> +    private let contentView: UIView = {
contentView 는 무엇인가요 ? 
셀에서 이미 쓰고있는 이름인데 여기서도 같은 이름과 용도로 사용되고 있는 것 같은데 의도하신건가요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/View/MovieDetailView.swift
> +        let stackView = UIStackView()
이건 따로 빼주셨네요 ~ 의도는 무엇인가요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/View/MovieDetailViewController.swift
> +        super.loadView()
You can override this method in order to create your views manually. If you choose to do so, assign the root view of your view hierarchy to the [view](doc://com.apple.documentation/documentation/uikit/uiviewcontroller/1621460-view?language=swift) property. The views you create should be unique instances and should not be shared with any other view controller object. Your custom implementation of this method should not call super.

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        boxOfficeManager.fetchBoxOffice { result in
https://velog.io/@haanwave/Article-You-dont-always-need-weak-self 
한번 읽어보세요 !

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/DTO/Entity/DailyBoxOffice.swift
> +//  DailyBoxOffice.swift
BoxOffice/Model/DTO/Entity/DailyBoxOffice.swift 
파일 뎁스가 의도하신바가 맞나요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/DTO/PosterImageInformation.swift
> +    enum CodingKeys: String, CodingKey {
외부에서 필요할까요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/BoxOfficeManager.swift
>      private let kobisKey = Bundle.main.object(forInfoDictionaryKey: NameSpace.kobisKey) as? String
BoxOfficeManager 의 프로퍼티로 있을 필요가 있나요 ?

2023-08-09 07:38 UTC, July911 commented on BoxOffice/Model/BoxOfficeManager.swift
> +        networkManager.requestData(from: urlRequest) { [weak self] result in
fetchPosterImage메서드의 79 ~ 94부분이 여기 있어도되는지에 대한 생각이 조금 드네요.

2023-08-11 01:43 UTC, YaRkyungmin commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        boxOfficeManager.fetchBoxOffice { result in
`GCD` 호출을 바로 해주고 있고, 애니메이션 호출도 바로 실행해주고있기때문에 순환참조가 일어나지 않는다는것을 학습했습니다🙏🏻

2023-08-11 02:00 UTC, YaRkyungmin commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let section = NSCollectionLayoutSection(group: group)
1️⃣`orthogonalScrollingBehavior`
: 특정 `Section`에 대해 스크롤 방향을 반대로 설정할 수 있게해주는 `Section`의 `property`입니다
2️⃣`decorationItems`
: 
3️⃣`visibleItemsInvalidationHandler`
:

2023-08-11 02:26 UTC, h-suo commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        let section = NSCollectionLayoutSection(group: group)
1️⃣ `orthogonalScrollingBehavior`
: 특정 `Section`에 대해 스크롤 방향을 반대로 설정할 수 있게해주는 `Section`의 `property`입니다
2️⃣ `decorationItems`
: `NSCollectionLayoutDecorationItem`의 배열로 `UICollectionReusableView`를 `layout`에 등록하여 `Section`의 배경으로 설정할 수 있습니다.
3️⃣ `visibleItemsInvalidationHandler`
: `Section`의 항목이 표시되기 전에 클로져가 실행되어 항목을 수정할 수 있도록 합니다.

2023-08-11 02:41 UTC, h-suo commented on BoxOffice/Controller/CalendarViewController.swift
> +    func selectedDate(date: DateComponents?)
`UICollectionViewDelegate`는 `UICollectionView`의 동작을 대신 구현해주는 것이기 때문에 메서드의 이름이 그 주체인 `collectionView`인 것 같습니다.
그리고 파라미터로는 선택된 주체인 `collectionView`, 몇번째 아이템이 선택되었는지 알 수 있도록 `indexPath`가 들어간 것 같습니다.
따라서 `calendarViewController(_ calendarViewController: UIViewController, didSelectDate dateComponents: DateComponents?)`로 리네임 하였습니다.

2023-08-11 03:12 UTC, h-suo commented on BoxOffice/Controller/CalendarViewController.swift
> +    weak var delegate: CalendarViewControllerDelegate?
특정 객체가 `CalendarViewController `를 프로퍼티로 가지고 있고 `CalendarViewController. delegate = self`로 `delegate`가 `CalendarViewController`를 가지고 있는 객체를 가리키게 될 경우 `RC`가 증가하여 순환 참조가 발생할 수 있으므로 예방을 위해 `delegate` 프로퍼티를 `weak var`로 선언하였습니다.

2023-08-11 03:25 UTC, YaRkyungmin commented on BoxOffice/Model/CacheManager.swift
> +
`shared CacheManager`의 `imageCache`프로퍼티에 `setCacheImage`, `cacheImage` 메서드를 통해 `Cache`를 저장하고 반환 할 수 있게 했습니다☺️

2023-08-11 04:04 UTC, YaRkyungmin commented on BoxOffice/Model/DTO/Entity/DailyBoxOffice.swift
> +struct DailyBoxOffice: Hashable {
`MovieDetailScrollView`로 네이밍을 변경해줬습니다☺️

2023-08-11 04:04 UTC, YaRkyungmin commented on BoxOffice/View/MovieDetailView.swift
> +    private let scrollView: UIScrollView = {
`MovieDetailScrollView`로 네이밍을 변경해줬습니다☺️

2023-08-11 04:07 UTC, YaRkyungmin commented on BoxOffice/View/MovieDetailView.swift
> +    private let contentView: UIView = {
[Auto Layout Guide](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithScrollViews.html#//apple_ref/doc/uid/TP40010853-CH24-SW1)
문서를 참고하여 `content`가 들어가는 `View`를 `contentView`라고 했습니다☺️

2023-08-11 04:08 UTC, YaRkyungmin commented on BoxOffice/View/MovieDetailViewController.swift
> +        super.loadView()
삭제해줬습니다! 감사합니다:)

2023-08-11 04:10 UTC, YaRkyungmin commented on BoxOffice/Model/DTO/Entity/DailyBoxOffice.swift
> +//  DailyBoxOffice.swift
`DTO`를 정제한 타입이 `Entity`라고 생각하여 의도한 부분은 맞지만 분리해줬습니다☺️

2023-08-11 04:15 UTC, h-suo commented on BoxOffice/Model/BoxOfficeManager.swift
>      private let kobisKey = Bundle.main.object(forInfoDictionaryKey: NameSpace.kobisKey) as? String
`ViewController`에서 받아온 데이터를 프로퍼티로 가지고 있는 상태로 사용하는 것보단 `BoxOfficeManager`가 데이터를 프로퍼티로 가지고 있는 상태로 `ViewController`는 `BoxOfficeManager`의 프로퍼티로 접근하여 데이터를 사용하는 방식으로 구현하기 위해 프로퍼티를 생성해주었습니다.

2023-08-11 04:35 UTC, h-suo commented on BoxOffice/Model/BoxOfficeManager.swift
> +        networkManager.requestData(from: urlRequest) { [weak self] result in
`CacheManager`의 캐싱된 이미지가 있다면 `completion`을 호출하는 로직은 네트워킹 작업을 하는 메서드에 있어야 된다고 생각하여 `URLRequest`를 만드는 로직만 분리해주었습니다.

2023-08-11 04:50 UTC, h-suo commented on BoxOffice/View/MovieDetailView.swift
> +        let stackView = UIStackView()
반복적인 `UIStackView`를 쉽게 추가하기 위해서 스택뷰를 만드는 메서드를 추가하였습니다.

2023-08-14 00:44 UTC, merged