박스오피스 [Step4] Minsup, Etial Moon
yagom-academy/ios-box-office pull request #99
Opened 2023-08-10 12:39 UTC by agilestarskim

@havilog 안녕하세요 havi!! Moon, minsup조 입니다.
코드를 짧게 줄이기 위해 신경을 많이 썼습니다.
이번 스탭 잘 부탁드립니다.🙂

## 고민한점

### 🤯 문제상황
네트워크 매니저에서 박스오피스 정보만 불러올 때는 API key를 URL에 포함하여 URL만 사용했습니다. 하지만 영화 포스터 이미지를 불러오기 위해 필요한 URL 형식이 다르기 때문에 API별로 분리가 필요했습니다.
| 영화진흥위원회 | 다음 이미지 검색 |
|:-:|:-:|
|API key가 URL 쿼리에 포함|API key가 헤더에 포함|

### 🔥 해결방법

URLRequest를 만드는 메소드를 분리하며 URLQueryItem과 헤더를 만들게 되었습니다.
```swift
static private func createRequest(fetchType: FetchType) -> URLRequest? {
    guard var urlComponents = URLComponents(string: fetchType.url) else {
        return nil
    }
    
    switch fetchType {
    case .boxOffice(let date):
        urlComponents.queryItems = [
            URLQueryItem(name: "key", value: Bundle.main.kobisAPIKey),
            URLQueryItem(name: "targetDt", value: date)
        ]
        
        guard let url = urlComponents.url else {
            return nil
        }
        
        return URLRequest(url: url)
        ...
    }
}
```
아울러 API key를 숨기기 위해 plist에 키를 저장하고 gitignore를 활용하는 방법을 찾았습니다.
```swift
extension Bundle {
    var kakaoAPIKey: String {
        return fetchPropertyList(domain: "KAKAO")
    }
    
    var kobisAPIKey: String {
        return fetchPropertyList(domain: "KOBIS")
    }
    
    private func fetchPropertyList(domain: String) -> String {
        guard let file = self.path(forResource: "APIKey", ofType: "plist") else { return "" }
        
        guard let resource = NSDictionary(contentsOfFile: file) else { return "" }
        guard let key = resource[domain] as? String else { fatalError("APIKey.plist에 \(domain) API키를 등록하세요")}
        
        return key
    }
}
```

---

### 🤯 문제상황
이미지를 불러왔을 때 이미지 크기와 다르게 공백이 생기는 문제가 있었습니다.
<img src="https://hackmd.io/_uploads/ByRPbKgnn.png" width=300>

### 🔥 해결방법
이미지 뷰의 가로와 원본 이미지의 가로를 통해 비율을 구한 후, 이 비율을 통해 높이를 구하여 이미지 뷰의 높이를 고정했습니다.

```swift
func injectMovieInformation(_ movieInformation: MovieInformation?, image: UIImage?) {
    posterImageView.image = image
    updatePosterImageViewConstraints()
   ...
}

private func updatePosterImageViewConstraints() {
    guard let imageWidth = posterImageView.image?.size.width,
          let imageHeight = posterImageView.image?.size.height else { return }
    let ratio = posterImageView.frame.width / imageWidth
    let height = ratio * imageHeight
    posterImageView.heightAnchor.constraint(equalToConstant: height).isActive = true
}
```

---

### 🤯 문제상황

DetailView에 UILabel이 많이 필요하여 코드가 복잡하고 길어졌습니다.
스택에 들어가는 요소들은 스택에 넣기만하면 굳이 전역으로 들고있을 필요가 없다고 판단하여
레이블을 생성하고 스택에 넣는 함수를 만들었습니다.
하지만 함수 내부에서도 스택을 만들고 레이블들을 만들어줘야하기 때문에 코드가 길어졌습니다.

### 🔥 해결방법

이 문제를 해결하기 위해 UILabel을 extension하여 레이블을 만드는 함수를 만들었습니다.
```swift
extension UILabel {
    static func key(text: String) -> UILabel {
        let label = UILabel()
        label.text = text
        label.font = UIFont.preferredFont(for: .body, weight: .bold)
        label.numberOfLines = 0
        label.textAlignment = .center
        label.adjustsFontForContentSizeCategory = true
        return label
    }
    
    static func value(text: String?) -> UILabel {
        let label = UILabel()
        label.text = text
        label.font = UIFont.preferredFont(forTextStyle: .body)
        label.numberOfLines = 0
        label.adjustsFontForContentSizeCategory = true
        return label
    }
}
```

이렇게 함으로 사용하는 곳에서 UILabel.key(text: String) 한줄로 UILabel을 만들 수 있게 되었습니다.

---

### 🤯 문제상황

현재 코드에선 데이터를 불러오는 방식으로 async/await을 사용중입니다.

```swift
let movie = await fetchMovie()
let poster = await fetchPoster()
detailView.injectMovieInformation(movie, poster)
```

해당 코드는 순차적으로 실행되기 때문에 movie의 값을 받을 때 까지 기다린 후 movie 데이터를 다 받으면 poster를 받기 시작합니다.

두 개는 서로 전혀 관계가 없고 오래 걸리는 작업이기 때문에 순차적으로 실행하며 기다리는 것은 손해라고 판단하였습니다.

### 🔥 해결방법
async let을 이용하여 문제를 해결하였습니다.
```swift
async let movie = fetchMovie()
async let poster = fetchPoster()

detailView.injectMovieInformation(await movie, await poster)
```

async let을 사용해서 비동기적으로 movie와 poster를 fetch할 수 있다는 사실을 배웠습니다. 

---
## 조언을 얻고싶은 점

UIActivityIndicatorView처럼 여러 뷰에서 사용하는 view를 싱글턴패턴으로 사용하면 어떤 문제가 생길까요? 저희의 생각으로는 뷰가 보여지기도 전에 메모리에 올라오므로 사용하지 않아도 메모리를 차지한다는 단점이 있지만, 장점은 뷰컨에서 전역변수로 indicator를 가지고 있지 않아도 된다는 장점이 있다고 생각합니다. 또한 재사용될 때 이미 메모리에 올라와있으므로 메모리에 올리는 과정이 필요없을 것이라고 생각합니다.

또한 이처럼 재활용해야하는 뷰들은 어떻게 관리하면 좋을까요?

```swift
final class Indicator {
    static let shared = UIActivityIndicatorView()
    private init() {}
}

// indicator를 사용하는 뷰
private func configureIndicator() {
    self.view.addSubview(Indicator.shared)
        
    Indicator.shared.translatesAutoresizingMaskIntoConstraints = false
    NSLayoutConstraint.activate([
        Indicator.shared.centerXAnchor.constraint(equalTo: view.centerXAnchor),
        Indicator.shared.centerYAnchor.constraint(equalTo: view.centerYAnchor),
    ])
}
```

2023-08-11 02:45 UTC, havilog requested changes
전체적으로 짧게 쓰려고 노력하시는 부분은 보기 좋습니다!
다만 걱정되는 부분은 extention들이 많아지는데 이는 레거시가 될 확률이 높아요.
팀에 20명의 개발자가 있으면, 그 20명의 개발자가 모두 그 extension을 알기란 어려운 일이라서요.

이 외 부분 코멘트 읽어보시면 될 듯 합니다 수고하셨어요~

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +final class BoxOfficeCollectionViewController: UICollectionViewController {
ViewController가 아닌 UICollectionViewController를 상속 받으신 이유가 있으실까요??

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
저도.. 왜 인지는 잘 모르겠는데
iOS 진영에서는 줄임말을 지양하는거 같아요.
보통 configuration으로 풀어쓰더라구요!

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let indicator = Indicator.shared
> 뷰컨에서 전역변수로 indicator를 가지고 있지 않아도 된다는 장점이 있다고 생각합니다.

요 부분에서 은 저와 의견이 조금 다른데요,
모든 뷰에서 공통적으로 사용하는 인디케이터라 할지라도,
어떤 뷰에서는 인디케이터를 사용하지만, 어떤 뷰에서는 사용하지 않을 수도 있을 것 같아요.

근데 shared가 된다면, 인디케이터를 사용하지 않는 뷰들만 메모리에 올라가있더라도 인디케이터는 계속 메모리에 불필요하게 살아있게 돼요.

또한 특정 뷰에서 인디케이터를 커스텀하게 사용하고 싶을 때에도 제약이 생기게 되는 거 같습니다!

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +    }
1. fetchData에서는 weak self를 잡아주셨는데, 여기서는 안해주신 이유가 있을까요?
2. refresh를 빠른 시간에 여러 번 실행시키면 어떤 결과가 나올지 테스트해보셨을까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            guard let self else { return }
guard를 해주신 이유가 무엇일지 궁금해요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        Task { [weak self] in
아래서도 비슷한 질문이 있긴 하지만, weak를 잡아줬을 때와 아닐 때 동작 차이에 대해 설명해주시면 좋을 것 같습니다

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            let boxOffice: BoxOffice = try await NetworkManager.fetchData(fetchType: .boxOffice(date: Date.yesterday.networkFormat))
NetworkManager를 enum으로 사용하는건 제가 안좋아하긴 하지만..
해당 스탭은 네트워크 구현 스탭이 아니니 패스할게여 ㅎㅎ..

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            collectionView.reloadData()
reloadData를 하면 모든 데이터가 바뀔거 같은데,
특정 데이터만 바꾸는 방법도 생각해보셨을까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BoxOfficeCollectionViewCell.identifier, for: indexPath) as! BoxOfficeCollectionViewCell
요 부분은 guard 쳐주는게 안전할 것 같아요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let boxOfficeItem = boxOfficeItems[indexPath.row]
index로 접근할때에도 safe하게 접근하면 좋을 것 같아요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +final class BoxOfficeCollectionViewCell: UICollectionViewListCell, Reusable {
Resusable이라는 프로토콜은, UICollectionViewCell, UITableViewCell에 준수시켜 놓아도 될 거 같아요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        label.numberOfLines = 0
```suggestion
        label.numberOfLines = .zero
```

취향 강요입니다 ㅎㅎ

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        }
권장하지는 모르겠지만.. 정말 짧게 쓰려면 이렇게도 돼요 ㅎ
```suggestion
        [rankLabel, rankVariationLabel, movieNameLabel, audienceNumberLabel].forEach(addSubview)
```

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        rankLabel.translatesAutoresizingMaskIntoConstraints = false
translatesAutoresizingMaskIntoConstraints는 선언 시점에 다뤄도 괜찮을 것 같아요! <개인 취향>

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        }
기왕 enum 만드신거 이아이도 이넘의 프로퍼티로 들어가는 것도 괜찮을 것 같아요!

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        case 하락
앵간하면.. 영어로 ㅎㅎ..

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Model/Extension/JSONDecoder+.swift
> +}
모든 JSONDecoder가 특정 도메인 에러에 의존하는것은 위험할 수도 있어요
다만 현 시점에서 이해하기엔 쉽지 않아 보이긴 하네요 ㅎㅎ..

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Model/Extension/Date+.swift
> +        }
이러면 어제임이 보장이 안되지 않을까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Model/Extension/Bundle+.swift
> +    }
fatalError가 아니라 error를 throw해서 핸들링해줘야하지 않을까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
convenience init과 required init을 나누신 이유가 궁금해요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    let movieDetailView = MovieDetailView()
외부에서 접근하는 프로퍼티일까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
loadView 시점에 self의 view를 바꿔줌으로써 얻는 이득이 무엇인지 설명해주세요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
여기서도 에러를 throw하고 fetchData에서 에러핸들링 하는 상상은 해보셨을까요?!

2023-08-11 02:45 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    var boxOfficeItem: BoxOfficeItem?
요 아이가 optional인 이유가 뭘까요?

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/MovieDetailView.swift
> +        let directors = movieInformation.directors.map { $0.peopleName }.joined(separator: ", ")
```suggestion
        let directors = movieInformation.directors.map(\.peopleName).joined(separator: ", ")
```
키패스로 꺼내오면 더 이쁠거 같아요

2023-08-11 02:45 UTC, havilog commented on BoxOffice/View/MovieDetailView.swift
> +        ]
따로 함수나 프로퍼티나 extension으로 빠져도 괜찮을거 같아요

2023-08-11 03:05 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +final class BoxOfficeCollectionViewController: UICollectionViewController {
메인 화면은 별다른 UI없이 컬랙션뷰만 사용하기 때문에 CollectionViewController를 직접 상속받아 사용하였습니다. 이렇게 직접 상속받아 사용하면 델리게이트나 데이터소스 프로토콜을 채택할 필요가 없어집니다.

2023-08-11 03:07 UTC, hojun-jo commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
함수이기 때문에 configure라는 동사로 사용해야 한다고 생각했습니다.
이 경우에는 보통 configurationCompositionalLayout이라는 이름으로 사용하게 되는 걸까요?

2023-08-11 03:09 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let indicator = Indicator.shared
다시 생각해보니 사용하지 않는 뷰일 때도 메모리에 남아있다는게 매우 비효율적이라고 생각합니다.👍
혹시 현재 저희가 View와 VC를 분리했는데 Indicator는 VC에서 configure하지 않는 방법이 있을까요..?
일단 indicator를 뷰로 옮기는 작업을 해보겠습니다. 감사합니다.

2023-08-11 03:35 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +    }
1. 실수했습니다. 다시 [weak self] 를 추가했습니다.
2. 빠르게 여러 번 실행시켰는데 앱이 종료되거나 그러진 않았습니다. 제 생각에는 async 코드이다보니 여러 스레드가 생길 것이라고 추측합니다. 뿐만 아니라 fetch 메소드를 계속 부르기 때문에 많은 부하를 일으킬 것 같습니다. 실제로 여러 스레드가 생성되는 것을 확인했습니다.

2023-08-11 03:36 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            guard let self else { return }
self가 옵셔널이다 보니 guard를 해주었지만, 생각해보니 Indicator가 start되고 guard문을 통해 조기 종료되어 indicator가 무한히 돌 수도 있기 때문에 self를 옵셔널 체이닝으로 사용하는 것이 적절하다고 생각해서 수정했습니다.

2023-08-11 03:40 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BoxOfficeCollectionViewCell.identifier, for: indexPath) as! BoxOfficeCollectionViewCell
guard 문을 써야했는데 실수했습니다. 다시 수정했습니다~

2023-08-11 04:09 UTC, hojun-jo commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        Task { [weak self] in
weak를 사용하지 않을 경우 강한 참조이기 때문에 순환 참조 문제가 있습니다. 
저희의 경우에는 Task의 실행이 끝나면 참조가 해제되기 때문에 순환 참조 문제는 없는 것같습니다. 이러한 경우는 [weak self]를 사용하지 않는 것이 좋을까요? 혹은 문제 상황이 아니더라도 [weak self]를 사용하는 습관을 들이는 것이 좋을까요?

2023-08-11 04:56 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            collectionView.reloadData()
https://github.com/yagom-academy/ios-box-office/pull/99/commits/92a09c0894cf8acc5f3cc81d2e5364005f117a1e
현재 데이터와 새로 받아온 데이터를 비교한 뒤 달라진 인덱스만 새로고침하는 기능을 추가하였습니다.
찾아보니 reloadItems라는 메소드가 있어서 그것을 사용해보았습니다.

하지만 해당 기능은 사용자가 밤 11:59분에서 12:00 사이에만 적용되는 기능이라 매번 앱을 켯다 끄는 상황에서는 메모리가 날라가기 때문에 적용되지 않는 것 같습니다. 시간이 남으면 디스크 캐시도 적용하여 더 효율적으로 만들어보겠습니다. 감사합니다.

2023-08-11 05:12 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let boxOfficeItem = boxOfficeItems[indexPath.row]
subscript를 만들어 해결하였습니다.

2023-08-11 05:20 UTC, hojun-jo commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +final class BoxOfficeCollectionViewCell: UICollectionViewListCell, Reusable {
https://github.com/yagom-academy/ios-box-office/pull/99/commits/554b494feac971e2f8c879e235f70360f01a61ce
커스텀 셀이 많아질 경우 하나하나 준수시키지 않아도 되어 좋은 방법인 것같습니다!

2023-08-11 05:23 UTC, agilestarskim commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        label.numberOfLines = 0
수정했습니다. 훨씬 보기 좋은 것 같습니다.

2023-08-11 05:29 UTC, agilestarskim commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        }
좋은 방법 알려주셔서 감사합니다.😊
forEach가 매개변수 하나인 클로저를 파라미터로 받기 때문에 가능한 것이었군요!
파라미터 두 개를 받는 클로저를 만들어 실행해보니 실패한 것을 확인했습니다.
사소하지만 중요한 사실을 상기하고 갑니다 😊

2023-08-11 05:32 UTC, hojun-jo commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        rankLabel.translatesAutoresizingMaskIntoConstraints = false
constraints를 잡을 경우에만 translatesAutoresizingMaskIntoConstraints = false로 하기 때문에 constraints를 설정하는 부분에서 하고 있습니다! 선언부에서 다룰 경우 헷갈릴 수 있을 것같아 이렇게 사용하게 되었습니다.
좋은 의견 감사합니다😄

2023-08-11 06:10 UTC, hojun-jo commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        }
https://github.com/yagom-academy/ios-box-office/pull/99/commits/e50ffeba5193e346d419844b885b1b33abf197a9
생각 못했던 부분이네요! 조언 감사합니다~😄

2023-08-11 06:10 UTC, hojun-jo commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +        case 하락
https://github.com/yagom-academy/ios-box-office/pull/99/commits/e50ffeba5193e346d419844b885b1b33abf197a9
영어로 수정했습니다!

2023-08-11 06:18 UTC, agilestarskim commented on BoxOffice/Model/Extension/JSONDecoder+.swift
> +}
https://github.com/yagom-academy/ios-box-office/pull/99/commits/03aa34b5dfadf1860d38e83c964a2c8c4271f2a3
JSONDecoder를 extension하지 않고 커스텀 클래스로 수정하였습니다!!

2023-08-11 06:19 UTC, agilestarskim commented on BoxOffice/Model/Extension/Date+.swift
> +        }
else로 넘어가는 상황때문에 그런것일 까요?

2023-08-11 06:38 UTC, agilestarskim commented on BoxOffice/Model/Extension/Bundle+.swift
> +    }
https://github.com/yagom-academy/ios-box-office/pull/99/commits/af24414cf56176344afe352412dc25085f6ff081
처음에는 api키가 없으면 권한이 없으므로 강제 종료를 해야한다고 생각했습니다. 
하지만 애플에서 fatalError를 좋아하지 않기 때문에 notFoundAPIKey라는 커스텀 에러를 만들고 반환하는 식으로 변경했습니다.

2023-08-11 06:43 UTC, agilestarskim commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    let movieDetailView = MovieDetailView()
https://github.com/yagom-academy/ios-box-office/pull/99/commits/e3ba5e39c419da3aa81e6005fc29c599ff0c3f39
private으로 변경했습니다.!! MainVC에서도 은닉화를 하지못해서 그것도 포함해서 수정했습니다.

2023-08-11 07:00 UTC, agilestarskim commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
호출되는 과정
1. 뷰를 로드하는 시점에서 뷰가 없으면 loadView를 실행합니다.
2. loadView가 오버라이드 되어있으면 해당 코드를 실행하고 오버라이드가 안되어있다면 nib파일을 찾는 것을 시도합니다.
3. nib파일이 없으면 빈 UIView()를 생성해서 넣어줍니다.

만약 loadView에서 View를 갈아끼우지 않고 실행하면 nib파일을 뒤지는 과정이 필요할 것이고 이것은 비용낭비로 이어집니다.

2023-08-11 07:02 UTC, hojun-jo commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
인스턴스를 생성하며 BoxOfficeItem을 받기 위해 convenience init을 사용했습니다.

required는 모든 하위 클래스가 해당 init을 구현해야 함을 나타냅니다.
init을 정의하지 않을 경우 상위 클래스의 init을 모두 상속받은 상태이기 때문에 required init을 구현할 필요가 없지만 init을 정의하게 될 경우 required init을 구현해야 합니다.

2023-08-11 07:33 UTC, agilestarskim commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
넵 이때 fetchData가 Indicator와 Task 때문에 안그래도 복잡한데 에러핸들링까지하면 너무 복잡할 것 같아서 에러핸들링은 하위 메소드에서 실행하는것이 좋다고 판단했습니다.
하지만 다시 생각해보니 중복되는 코드가 있는 것이 매우 불편하여 fetchData에서 하는 것으로 수정하였습니다😊

2023-08-11 07:43 UTC, agilestarskim commented on BoxOffice/View/MovieDetailView.swift
> +        let directors = movieInformation.directors.map { $0.peopleName }.joined(separator: ", ")
https://github.com/yagom-academy/ios-box-office/pull/99/commits/cf29b65beacfc6f7ea0b69569a127c853b950767
키패스는 잘 사용하지 않아서 잊고있었습니다. loop를 돌 때 자주 사용해보겠습니다. 감사합니다.

2023-08-11 07:44 UTC, hojun-jo commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    var boxOfficeItem: BoxOfficeItem?
boxOfficeItem이 옵셔널이 아닌 경우
```swift
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
}
```
위 코드의 super.init 부분에서 `Property 'self.boxOfficeItem' not initialized at super.init call` 이러한 에러가 발생했기 때문에 옵셔널로 두고 사용했었습니다. 현재는 init을 수정했기 때문에 옵셔널을 뺀 상태입니다. https://github.com/yagom-academy/ios-box-office/pull/99/commits/b1d0ad87aa261cd8e9437b5342f2cdeb0f4980e1

위 에러가 발생한 이유는 찾지 못 하였는데 알 수 있는 방법이 있을까요?

2023-08-11 07:45 UTC, hojun-jo commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
https://github.com/yagom-academy/ios-box-office/pull/99/commits/6f39324c50e9290c758aaf7b97126286b7ad5896
fetchData에서 에러를 핸들링하고 얼럿에서 재시도를 할 수 있도록 추가했습니다!

2023-08-11 08:08 UTC, agilestarskim commented on BoxOffice/View/MovieDetailView.swift
> +        ]
https://github.com/yagom-academy/ios-box-office/pull/99/commits/4ed77660de7b472d598d02763f08c4abf0124fe8

함수로 분리했습니다. 더 좋은 방법이 있으면 말씀해주세요. ☺️

2023-08-12 04:50 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +final class BoxOfficeCollectionViewController: UICollectionViewController {
현재 요구사항에서는 괜찮을거 같긴 한데, 이러면 뷰가 바꼈을 때 대응하기 힘들어질것 같아요!
뷰컨을 상속받는게 유지보수가 용이할 것 같습니다 ㅎㅎ

2023-08-12 04:51 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
함수 이름이 아니라 변수 명을 말한거에요 ㅎㅎ let config -> let congifuration

2023-08-12 04:55 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let indicator = Indicator.shared
인디케이터는 `뷰`이고, 뷰 컨트롤러가 뷰를 관리하는게 이상하지 않다고 생각되는데,
뷰컨이랑 분리하려고 하는 이유가 뭘까요?

2023-08-12 05:29 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +    }
1. 제가 알기로 Task는 릭이 나진 않아요. 다만 delay deallocation이 일어나, 예측하지 못한 현상이 발생할 수 있습니다.
2. 빠르게 두 번 리프레쉬 했을 때 이전 Task가 살아있을거 같아요. self에서 task를 가지고 있고 cancel시키는 로직이 필요할 것 같습니다.

2023-08-12 05:32 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            guard let self else { return }
오히려 self가 없을 경우 실행이 안될거라 생각되어서요!

2023-08-12 05:32 UTC, havilog commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        Task { [weak self] in
적절하게 선택해서 사용하는게 좋긴한데,
weak 잡아주는게 나쁜 선택은 아닌거 같아요
안붙이는거보단 애매하면 붙이는게 낫다 정도일듯 싶습니다!

2023-08-13 02:02 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
loadview가 어떻게 동작하는지가 아닌, 이렇게 self의 뷰를 갈아끼면, 개발적으로 유지보수나 역할분리에 어떤 이득이 있나에 대한 질문이었어요.

2023-08-13 02:04 UTC, havilog commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    var boxOfficeItem: BoxOfficeItem?
위에 말한 convenience init과 연관이 있는데요,
optional이 아닌 boxofficeitem타입을 받아주는 initializer를 구현해 주면 될거 같아요.
override하지 않고, convenience가 아닌

2023-08-13 11:31 UTC, hojun-jo commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    var boxOfficeItem: BoxOfficeItem?
https://github.com/yagom-academy/ios-box-office/pull/99/commits/b1d0ad87aa261cd8e9437b5342f2cdeb0f4980e1
override하지 않고, convenience가 아닌 initializer로 구현했습니다! 감사합니다~

2023-08-13 12:00 UTC, agilestarskim commented on BoxOffice/Controller/MovieDetailViewController.swift
> +    }
1. VC와 view의 역할분리를 할 수 있습니다. VC가 View의 생성과 레이아웃까지 담당하게되면 본인의 역할인 Model과 데이터 주고받기, View에게 이벤트 받기 등 너무 많은 역할을 부여받기 때문에 부하가 생길 수 있습니다 . 따라서 VC는 자신의 self.view만 가지고 관리하는 것이 자신의 역할에 충실할 수 있게 만들어줍니다. (역할 분리 측면)
2. View만 따로 관리하게되면 View를 수정하기 위해 VC를 뒤지지 않아도 됩니다. (유지보수 측면)
3. View만 따로 관리하게되면 View를 재사용할 수 있게됩니다. (유지보수 측면)

라고 정리를 해봤습니다.

2023-08-13 13:11 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +    }
1. 예측하지 못한 현상이라 하면 Task에서 UI update를 하는 상황을 생각해볼 수 있을 것 같습니다. 하지만 현재 저희 앱에서는 그런 상황이 일어날 것 같진 않아서 refresh하는 곳에서만 cancel을 호출했습니다. 다음에는 Task를 쓸 때 그런 상황을 대비하여 필요한 상황에 cancel을 고려해보겠습니다.

2. 로직을 추가했습니다. https://github.com/yagom-academy/ios-box-office/pull/99/commits/527d08c4088fd50d273b073029c48c1df4a5ac47

2023-08-13 13:20 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
https://github.com/yagom-academy/ios-box-office/pull/99/commits/4b387ad989168bc402193a2fd6fd9fdbce9b6d0f
수정하였습니다.!!

2023-08-13 14:14 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +final class BoxOfficeCollectionViewController: UICollectionViewController {
https://github.com/yagom-academy/ios-box-office/pull/99/commits/354301648eecbfda43657bc8c42da27f5595fb36
바뀔 수 있다는 상황을 생각을 못했네요!! UIViewController를 상속받는 것으로 수정하였습니다.!

2023-08-13 14:21 UTC, agilestarskim commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +        let indicator = Indicator.shared
현재 저희는 ViewController가 비대해지는 것을 막기 위해 뷰의 생성과 레이아웃은 View를 따로 만들고 VC의 view를 교체하는 방법을 사용하고 있습니다. 하지만 Indicator의 경우는 VC에서 control 해줘야하기때문에 VC에서 생성하고 관리하고 있습니다. 이 부분에서 저희는 일관성이 깨진다고 생각했습니다. (일관성의 문제)

하지만 그냥 indicator를 view에서 관리하고 애니메이션을 VC에서 control해주면 해결되는 문제였습니다. 
[3543016](https://github.com/yagom-academy/ios-box-office/pull/99/commits/354301648eecbfda43657bc8c42da27f5595fb36)

2023-08-14 04:44 UTC, hojun-jo commented on BoxOffice/Controller/BoxOfficeCollectionViewController.swift
> +            guard let self else { return }
[weak self]를 사용해도 guard 다음의 클로저로 넘어가면 strong reference가 되는 줄은 몰랐습니다! 감사합니다~

2023-10-09 10:59 UTC, closed without merging